### ISSUE TITLE
Error Attempted to load class "LexikJWTAuthenticationBundle" from namespace

### ISSUE THREAD

**Issue by jarenal** [lexik/LexikJWTAuthenticationBundle#1003]
Hi guys,

I just installed **LexikJWTAuthenticationBundle** in a clean **Symfony 5.4** and I followed all the steps from LexikJWTAuthenticationBundle documentation, but when I load any endpoint of my API I got the next error:

`Attempted to load class "LexikJWTAuthenticationBundle" from namespace "Lexik\Bundle\JWTAuthenticationBundle".
Did you forget a "use" statement for another namespace?`

I've tried to solve the issue doing these steps but the error persist:

1. remove and install again LexikJWTAuthenticationBundle
2. clear cache on Symfony
3. execute composer dump-autoload

Is this bundle compatible with Symfony 5.4?

In my composer.json appear that I'm using this version of LexikJWTAuthenticationBundle:

`"lexik/jwt-authentication-bundle": "^2.15"`

I will appreciate any help, thank you!

**Comment by fd6130** [comment]
Hi, can you check at your `config/bundles.php` contain the following line of code or not?

```php
Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true]
```

**Comment by jarenal** [comment]
Hi @fd6130 

yes, I got it, is the last one.

    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    FOS\RestBundle\FOSRestBundle::class => ['all' => true],
    SymfonyBundles\JsonRequestBundle\JsonRequestBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],

**Comment by fd6130** [comment]
Mine have no problem in a clean Symfony 5.4 new project. How is your configuration and also your endpoint api? Perhaps something not right there.

**Comment by jarenal** [comment]
Hi @fd6130 

I've created a new fresh Symfony 5.4 install, and everything is working fine there.

But in my real project no works and I don't know why, it's strange...

**Comment by jarenal** [comment]
Hi guys,

finally I solved the issue removing vendor folder and executing 

`composer install`

to install all the dependencies again.

Thanks so much @fd6130 for trying to help me.
