### ISSUE TITLE
Get token payload in AuthenticationSuccessListener

### ISSUE THREAD

**Issue by geoffroyp** [lexik/LexikJWTAuthenticationBundle#1010]
Hi people!

I have an authenticationSuccesListener file bound to `lexik_jwt_authentication.on_authentication_success`, like this:

```    app.event.authentication_success_listener:
        class: App\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
```

But I would like to access token payload in this listener. So I have found in your documentation [here](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/9-access-authenticated-jwt-token.rst) that I could use the following code to get it:

```
$decodedJwtToken = $this->jwtManager->decode($this->tokenStorageInterface->getToken());
```

Problem: when I do, I get the following error:
`Uncaught Error: Call to undefined method Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken::getCredentials()`

stack:
```
[/var/www/api/vendor/lexik/jwt-authentication-bundle/Services/JWTManager.php:106]
    [Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager->decode(TokenInterface $token)]
    › {
    › [    if (!($payload = $this->jwtEncoder->decode($token->getCredentials()))) {]
    ›         return false;
  }
```

Is it a bug? or is it simple impossible to get payload data at this stage?

**Comment by fd6130** [comment]
Since you are doing something after authentication is success, what you will obtain is the raw token and not user object. Thus,
in your `App\EventListener\AuthenticationSuccessListener` you can use `parse()` from `JWTTokenManagerInterface`:

```php

    public function __construct(private JWTTokenManagerInterface $jwtManager)
    {

    }

    public function onAuthenticationSuccessResponse(AuthenticationSuccessEvent $event)
    {
        $data = $event->getData();
        $user = $event->getUser();

        $payload = $this->jwtManager->parse($data['token']);
        // ... do other stuff
    }
```

I guess the `$decodedJwtToken = $this->jwtManager->decode($this->tokenStorageInterface->getToken());` is use when you have `Bearer <token>`  in the request header so you can decode and get payload in controllers or services.

**Comment by fd6130** [comment]
@geoffroyp How about this issue? Has it been solved?

**Comment by geoffroyp** [comment]
Yes, it's working perfectly

Thanks a lot!
