### ISSUE TITLE
<!-- Unable to find the controller for path /api/login_check. The route is wrongly configured. (404 Not Found)

### ISSUE THREAD

**Issue by LucasPickersgill** [lexik/LexikJWTAuthenticationBundle#1014]
Unable to find the controller for path &quot;/api/login_check&quot;. The route is wrongly configured. (404 Not Found)

Hey guys, i have this error when i try test the jwt implementation. I followed exactly the getting start from documentation and i have it as result.

Symfony 6.
And it's not the content type, I've tested it.

Someone have the same problem? 
![Captura de ecrã 2022-04-25, às 11 05 33](https://user-images.githubusercontent.com/57354531/165106212-ca03fa3a-84b9-43c9-b1ef-157fbe14112c.png)
![Captura de ecrã 2022-04-25, às 11 05 50](https://user-images.githubusercontent.com/57354531/165106220-adcec8b6-64dc-4811-9ae1-c07b416a15a4.png)
![Captura de ecrã 2022-04-25, às 11 07 50](https://user-images.githubusercontent.com/57354531/165106231-27f3c3d1-af68-4b3f-8ed2-dcf1448bc571.png)
![Captura de ecrã 2022-04-25, às 11 08 19](https://user-images.githubusercontent.com/57354531/165106234-da8aa6a9-c214-4dc5-85a9-f7803e771df4.png)

**Comment by fd6130** [comment]
Remove the `~` in front of your api in `security.yaml` and try again.

**Comment by LucasPickersgill** [comment]
Thanks a lot!! Thats it!.
