### ISSUE TITLE
Phpstan last version cannot assert that JWTAuthenticationFailureResponse extends from Response

### ISSUE THREAD

**Issue by GErpeldinger** [lexik/LexikJWTAuthenticationBundle#1017]
Hello since last version of phpstan (1.6), i have an error with the class JWTAuthenticationFailureResponse.

I have the impression that phpstan cannot determine that JWTAuthenticationFailureResponse extends from JsonResponse and therefore from Response, can that be because of the compatibility layer?

Exemple in test:

```php
        $this->client->request(
            method: Request::METHOD_POST,
            uri: '/api/login_check',
            server: ['CONTENT_TYPE' => 'application/json'],
            content: json_encode($credentials, JSON_THROW_ON_ERROR)
        );

        self::assertInstanceOf(JWTAuthenticationFailureResponse::class, $this->client->getResponse());
        self::assertSame('{"code":401,"message":"Invalid credentials."}', $this->client->getResponse()->getContent());
```

```
  80     Call to static method PHPUnit\Framework\Assert::assertInstanceOf() with 'Lexik\\Bundle\\JWTAuthenticationBundle\\Response\\JWTAuthenticationFailureResponse' and Symfony\Component\HttpFoundation\Response will always evaluate to false.  
```

Exemple in code:
```php
class Authenticator extends AbstractAuthenticator
{
   // ...

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): Response {
        return $this->failureHandler->onAuthenticationFailure($request, $exception);
    }
}
```

```
  88     Return type (Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationFailureResponse) of method App\Security\Handler\AuthenticationFailureHandler::onAuthenticationFailure() should be compatible with return type  
         (Symfony\Component\HttpFoundation\Response) of method Symfony\Component\Security\Http\Authentication\AuthenticationFailureHandlerInterface::onAuthenticationFailure() 
```

Thank for your work.

**Comment by GErpeldinger** [comment]
Update: I only have the problem when I activate the bleeding edge fonctionnalities to have the new phpstan option to reduce memory consumption, maybe this is an issue to report to their repository rather than here.

Maybe the "Fully static reflection engine"

Update: I have open a new issue on phpstan https://github.com/phpstan/phpstan/issues/7157

**Comment by ondrejmirtes** [comment]
The problem isn't in `eval` - the problem is that `Lexik\Bundle\JWTAuthenticationBundle\Response\JWTCompatAuthenticationFailureResponse` isn't defined acording to PSR-4 rules configured in that package's composer.json. If you put it to a separate file with the right filename, it's going to work.
