### ISSUE TITLE
AuthenticationSuccessEvent not dispatched when programmatically creating token 

### ISSUE THREAD

**Issue by geoffroyp** [lexik/LexikJWTAuthenticationBundle#1018]
Greetings,

Every I generate a token, I need to add in the response additional information which need to be sent to the frontend client. To achieve this, and according to your documentation, I add the additional response keys by creating a listener based on `AuthenticationSuccessEvent` (these info get passed through the `$event->setData()` )

Problem: If this works perfectly during a "normal" authentication, it does not get called when creating token programmatically (by using `$JWTManager->create($this->getUser())`  as stated in the documentation).
Thus, this does not allow me to add the necessary information I need.

Could this be changed? Or Is there another place/event to do this, that would work everytime we generate a token?

**Comment by fd6130** [comment]
The `AuthenticationSuccessEvent` if i'm not mistaken is for when the authenticator successfully authenticate your credentials. If you manually create a token without authenticator, that event might not work.

How about try using `JWT_CREATED` instead? Or you can dispatch your own event after you manually created the token too.

**Comment by geoffroyp** [comment]
ok, but how can I add data in the response? because I already have a listener on `JWTCreatedEvent` and if I add data to the event, it will end up in the JWT token payload, but not in the response (along with the JWT token, like it would if I was adding it to `AuthenticationSuccessEvent` ).

is there any way to add these data in the response from a listener which listen to `JWTCreatedEvent` ?

**Comment by chalasr** [comment]
Since you are creating tokens programatically using the JWTManager service directly, you are creating the response on your own as well, isn't it? Showing some code should help understanding better where you are coming from :)

**Comment by fd6130** [comment]
> ok, but how can I add data in the response? because I already have a listener on `JWTCreatedEvent` and if I add data to the event, it will end up in the JWT token payload, but not in the response (along with the JWT token, like it would if I was adding it to `AuthenticationSuccessEvent` ).
> 
> is there any way to add these data in the response from a listener which listen to `JWTCreatedEvent` ?

Have you refer from this one? https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/7-manual-token-creation.rst

If you create the token manually in a controller, you can return your own json response from it.

```php
class ApiController extends AbstractController
{
    #[Route(...)]
    public function login(Request $request, JWTTokenManagerInterface $JWTManager)
    {
        // do some validation and successfully obtain $user from database

        return $this->json(['token' => $JWTManager->create($user) , 'success' => true]); // return your custom json response
    }
}

//The response will be
{
   "token" => ".....",
   "success" => true
}
```

Or try using `AuthenticationSuccessHandler` service:  `$authenticationSuccessHandler->handleAuthenticationSuccess($user)`, maybe this will trigger the `AuthenticationSuccessEvent` ?

**Comment by geoffroyp** [comment]
Oh yeah, sorry for the inconvenience guys. I've been stupid on this one.

Thanks a lot for your time and answer!

**Comment by chalasr** [comment]
No worry, thanks for the feedback!
