### ISSUE TITLE
Wrong response format after authentication success

### ISSUE THREAD

**Issue by ydem83** [lexik/LexikJWTAuthenticationBundle#1028]
Hello,
I have a problem on authentication, during a curl on the /login route, I sometimes get a response in text/html format, which also contains the credentials transmitted in json body...

For example : 

`curl --request POST \
  --url http://xxxxxx/api/auth/credentials_login \
  --header 'Content-Type: application/json' \
  --data '{
	"username": "test",
	"password": "test"
}'`

response : 

HTTP/1.1 200 OK
Server: nginx/1.20.2
Date: Tue, 24 May 2022 12:31:21 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/8.1.5

`{
	"username": "test",
	"password": "test"
}{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTMzOTU0ODEsImV4cCI6MTY1MzM5OTA4MSwicm9sZXMiOlsiUk9MRV9JVEVNU19BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6IllERU0ifQ.KFOOHlGl98EUxJOQq5r5uJKejFrrN_CJVF0p1_JjTz0N3r823Y8bXekz-j7li-f9Fe5u-ii8TdYeXqPW-NKKW32qaBJgrDcupLeqLoWggERiMdp02VOYUZHR51lu5IM7ByieAsMVOj9TTiHt59jVl0fjdZQzBClBwSWvz9t3wwp7y_PDMmQ6vcJl88qLFnkfANkR1NFxy1EWHjlxZV2DAcPoG59t_LAbS6uDRMXjM6tBm-4K3fp-GJK1lLdeeaeXRi6c8IzZkWgY83S8kS1w-UzysKcQl-pnJDL4JoiFEGoYCzeck3lHGsdvD0sC4KCTZP0pCkzHWV01NEcdldnJrA","refresh_token":"92f1e6991537cc50411ead18f12e0c4c5021bf699d5f9c41d8310b3cd7b4ea9dd402a7a97bc8fc7f112201b60f818c877be0c0a4c150f3e7e16f1d7ff53b8fd1"}`

I can't find anything in the logs, does anyone have an idea for a solution? thank you

**Comment by fd6130** [comment]
Are you using the latest version of this bundle? I can't reproduce the error you mention above.

This is my terminal output
```
❯ curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8003/api/login_check -d '{"username":"test1","password":"123456"}'
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTM0NDI2NTUsImV4cCI6MTY1MzQ0NjI1NSwicm9sZXMiOltdLCJ1c2VybmFtZSI6InRlc3QxIn0.K0IVHuTN34sEy7sv3-sDgLV6KK-QzPG0uYA57am7VC-NPUknJIGQILq_kPYf1D54Q10Uce2pRQmGpL5JLPlJS_PiLJmc4ljko_wQ437t--3GeKFcaHdPfGpna7Z9ettLS035T_PqMmkd03NPYmi6uoBYWqVBNVwGOY-yb3hvM-pLCt6BlfDcscnzjOysWy1seUXSbUtofcl6Wh8-_rx83awWWQj4DaPhSOXKxfwcVmLfFutu2wxoQtDk3goS-NdbjzFtQGtwUNZ9DjzTv6wgy97ngmImBggOGkvQQM7M_cZtFZEAFQhU1cAr0ti8PM5Vig9bgi1qF_u1GNDiHBIsAA"}%          
```

**Comment by ydem83** [comment]
Yes, I am using the latest version.
I also receive a normal response half the time..

First response in json : 
`{
	"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTM0NTc0ODIsImV4cCI6MTY1MzQ2MTA4Miwicm9sZXMiOlsiUk9MRV9JVEVNU19BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6IllERU0ifQ.ZgDSC-mZ37MiUgioUkDHKaU1efIiXUchc6kUkyCgWdtruZsUF9kqor6zC3wCWD54RRFY-kOMmoqvHLlZYaEu9yJUrRL1LaNfxunu75ZOWawQDhnsWSNP51Ny0jJfkDmefkMJ1TGMAmIZM3Gvc-sdZ9ic0X-oG3RbRH0mU8ntNmz3Hi1uvtjxRsoft3Za-vrQLFlBAS-hYS30NBwNZDY2rFVbsIEfsJiETpDfewG0G7teXxyx6foAVr6MPtqtptR6IP_jt8oDhv2-0zPZocDEozz_Am1VlLtzOFGZ4vs9RJEq_7EQGbx-g6SXcMG3AIcKpWlE89WmoBg_ffwsp3DBlQ",
	"refresh_token": "55955d3f0aa8dd4b2b4a43a23a1180814e0b9dd9943ce647c58944811a531df4df4c59b1789925b1a8d30bc78c860bd0eab3a6ca68131aae5f69db5f7c5a490f"
}`

After x attempts in text/html : 

`{ "username": "test", "password": "test" }{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTM0NTc3MzcsImV4cCI6MTY1MzQ2MTMzNywicm9sZXMiOlsiUk9MRV9JVEVNU19BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6IllERU0ifQ.Q7BBOcnZ2apRuSa3B9X-3IwVtu4X5JDFDVM4L1pxVLY9plNSTWmbl889oCGcUUEwacYmBxvOrcP7gVxFJ9OUeK_7gqLGHmaTFle8feWw2U-VS12mDoWQz6eZSYpTfyULzFNlT7_lw-Uf1dawkUamV7n2BLDlE9osTmuIyRjww_FMW26AH2V4jmHYec8Ng9dUYih8Akg-fflLashPambv_hUSIOKsvu5eLbiHfDTA75VAHGnEcKb9gaQFq5lk92dxb0E-p-gy5fOyPflBe4un7ySpXlO8vYkqKgCOJeLWklv9BoK0P_A-r4RSgud5oycqqZMAJuoo8OASS_8Iv9bNHg","refresh_token":"356abfcaafb6a9e4afb5932ff39f2cfbeb30fbb47c05d0636bc95dd523959d6162ff63f36c9efa6f227ffba69043641bae9569ee01dc1f026ac2b683c5a93f64"}`

I don't understand .. :(

**Comment by fd6130** [comment]
> Yes, I am using the latest version. I also receive a normal response half the time..
> 
> First response in json : `{ "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTM0NTc0ODIsImV4cCI6MTY1MzQ2MTA4Miwicm9sZXMiOlsiUk9MRV9JVEVNU19BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6IllERU0ifQ.ZgDSC-mZ37MiUgioUkDHKaU1efIiXUchc6kUkyCgWdtruZsUF9kqor6zC3wCWD54RRFY-kOMmoqvHLlZYaEu9yJUrRL1LaNfxunu75ZOWawQDhnsWSNP51Ny0jJfkDmefkMJ1TGMAmIZM3Gvc-sdZ9ic0X-oG3RbRH0mU8ntNmz3Hi1uvtjxRsoft3Za-vrQLFlBAS-hYS30NBwNZDY2rFVbsIEfsJiETpDfewG0G7teXxyx6foAVr6MPtqtptR6IP_jt8oDhv2-0zPZocDEozz_Am1VlLtzOFGZ4vs9RJEq_7EQGbx-g6SXcMG3AIcKpWlE89WmoBg_ffwsp3DBlQ", "refresh_token": "55955d3f0aa8dd4b2b4a43a23a1180814e0b9dd9943ce647c58944811a531df4df4c59b1789925b1a8d30bc78c860bd0eab3a6ca68131aae5f69db5f7c5a490f" }`
> 
> After x attempts in text/html :
> 
> `{ "username": "test", "password": "test" }{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTM0NTc3MzcsImV4cCI6MTY1MzQ2MTMzNywicm9sZXMiOlsiUk9MRV9JVEVNU19BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6IllERU0ifQ.Q7BBOcnZ2apRuSa3B9X-3IwVtu4X5JDFDVM4L1pxVLY9plNSTWmbl889oCGcUUEwacYmBxvOrcP7gVxFJ9OUeK_7gqLGHmaTFle8feWw2U-VS12mDoWQz6eZSYpTfyULzFNlT7_lw-Uf1dawkUamV7n2BLDlE9osTmuIyRjww_FMW26AH2V4jmHYec8Ng9dUYih8Akg-fflLashPambv_hUSIOKsvu5eLbiHfDTA75VAHGnEcKb9gaQFq5lk92dxb0E-p-gy5fOyPflBe4un7ySpXlO8vYkqKgCOJeLWklv9BoK0P_A-r4RSgud5oycqqZMAJuoo8OASS_8Iv9bNHg","refresh_token":"356abfcaafb6a9e4afb5932ff39f2cfbeb30fbb47c05d0636bc95dd523959d6162ff63f36c9efa6f227ffba69043641bae9569ee01dc1f026ac2b683c5a93f64"}`
> 
> I don't understand .. :(

Can you try use Rest api tools like postman or insomnia and test your api there?

**Comment by ydem83** [comment]
> 

Yes, I use insomnia.
I tried with Curl, postman, insomnia and swagger ui

**Comment by fd6130** [comment]
> > 
> 
> Yes, I use insomnia. I tried with Curl, postman, insomnia and swagger ui

Alright, is it possible for you to create a new repository and push your current project to there so we can clone and test it?

**Comment by ydem83** [comment]
> > > 
> > 
> > 
> > Yes, I use insomnia. I tried with Curl, postman, insomnia and swagger ui
> 
> Alright, is it possible for you to create a new repository and push your current project to there so we can clone and test it?

Ok, I just invited you on the repo, thank you in advance

**Comment by fd6130** [comment]
Still can't reproduce the issue from curl and insomnia using your repository, can you provide some screenshot here for reference the issue?

And the response you provide from above is an invalid json, this bundle will never return invalid json like that.

> Yes, I am using the latest version. I also receive a normal response half the time..
>
> After x attempts in text/html :
> 
> `{ "username": "test", "password": "test" }{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NTM0NTc3MzcsImV4cCI6MTY1MzQ2MTMzNywicm9sZXMiOlsiUk9MRV9JVEVNU19BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6IllERU0ifQ.Q7BBOcnZ2apRuSa3B9X-3IwVtu4X5JDFDVM4L1pxVLY9plNSTWmbl889oCGcUUEwacYmBxvOrcP7gVxFJ9OUeK_7gqLGHmaTFle8feWw2U-VS12mDoWQz6eZSYpTfyULzFNlT7_lw-Uf1dawkUamV7n2BLDlE9osTmuIyRjww_FMW26AH2V4jmHYec8Ng9dUYih8Akg-fflLashPambv_hUSIOKsvu5eLbiHfDTA75VAHGnEcKb9gaQFq5lk92dxb0E-p-gy5fOyPflBe4un7ySpXlO8vYkqKgCOJeLWklv9BoK0P_A-r4RSgud5oycqqZMAJuoo8OASS_8Iv9bNHg","refresh_token":"356abfcaafb6a9e4afb5932ff39f2cfbeb30fbb47c05d0636bc95dd523959d6162ff63f36c9efa6f227ffba69043641bae9569ee01dc1f026ac2b683c5a93f64"}`
> 
> I don't understand .. :(

**Comment by ydem83** [comment]
I just realized that if I restart my docker container, it works for several hours, this problem appears after an unknown period..

**Comment by fd6130** [comment]
> I just realized that if I restart my docker container, it works for several hours, this problem appears after an unknown period..

Then maybe it is docker issue. You can try non-docker approach like install apache2, php, mysql in your computer and test it without docker.

But I'm sure that this issue is somehow not really cause by the bundle.

**Comment by ydem83** [comment]
Hello,
Indeed this problem is not caused by this bundle.
It was a port listening problem with docker.
Thanks for your help.

**Comment by JustDylan23** [comment]
@ydem83 what did you change in your docker config?

**Comment by ikyoh** [comment]
Hello,

Same issue, sometimes the response is good 
{token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2N…ayS5Is8XR_XpxCUuX4xHKLA7TpDbpLQGAdhCyZwPl3eRwdSdw}
sometimes the response looks like
 { "username": "username", "password": "password" }
{token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2N…ayS5Is8XR_XpxCUuX4xHKLA7TpDbpLQGAdhCyZwPl3eRwdSdw}

I know it's a docker problem but don't know how to resolve  it.....

**Comment by JustDylan23** [comment]
@ikyoh I managed to fix the issue. When running docker on production and having port 9000 (the PHP-FPM container) exposed, some nasty things could happen. In my VPS a crypto miner installed itself by hooking into the PHP-FPM process, completely bypassing the web server. I discovered it was at 100% usage all the time via a monitoring tool. This was the miner making the VPS work hard. PHP-FPM started giving back these malformed responses because of this.

The reason why after restarting docker, it doesn't break for a while is because the miner doesn't start running instantly when you start up the docker containers.

I'd recommend building the images again after using docker-compose's networking feature to only expose the port to docker and not to the outside world.

```yaml
version: '3.7'
services:
    db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=docker
            - MYSQL_DATABASE=my_db
            - MYSQL_USER=symfony
            - MYSQL_PASSWORD=docker
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - my_network
    php:
        build: ./docker/php
        volumes:
            - './:/var/www/symfony:cached'
        networks:
            - my_network
    nginx:
        build: ./docker/nginx
        ports:
            - '80:80'
        volumes:
            - './:/var/www/symfony:cached'
        networks:
            - my_network
networks:
    my_network:
```
