### ISSUE TITLE
Do not provide a token when the account is locked

### ISSUE THREAD

**Issue by itokia** [lexik/LexikJWTAuthenticationBundle#1030]
Hello
I have a field in my database that allows me to block the user if he has reached a certain number of connections. How can I incorporate it into the authentication system?
thank you

**Comment by mbabker** [comment]
You can use [user checkers](https://symfony.com/doc/current/security/user_checkers.html) to take care of this.  There isn't any extra config specific to this bundle to use this Symfony feature.

**Comment by chalasr** [comment]
Closing as explained.

**Comment by itokia** [comment]
Thank you mbabker
