### ISSUE TITLE
How to make logout?

### ISSUE THREAD

**Issue by AlessandroBakh** [lexik/LexikJWTAuthenticationBundle#1031]
Hi, I installed this plugin, made register and used auto login from this bundle.
Please, say how to make logout (delete jwt token of authorized user)

**Comment by fd6130** [comment]
Case 1:
Just simply remove any jwt token record at frontend side when user press logout button (if you have save any jwt token to local storage, cookie etc).


Case 2:
Or if you worry about the token itself, you can save the jwt token to database everytime user login to your system. When a user logout, remove the record from the database.

So you will need to check the database for existing jwt token, throw exception if jwt token not found in database.
