### ISSUE TITLE
symfony 6 and missing interface

### ISSUE THREAD

**Issue by adeptofvoltron** [lexik/LexikJWTAuthenticationBundle#1044]
Maybe I am doing something wrong
but all versions above 11.3 in class: ```https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Security/Guard/JWTTokenAuthenticator.php```
implements that interface:
```use Symfony\Component\Security\Guard\AuthenticatorInterface;```

however that Interface was removed in symfony 6.* https://github.com/symfony/symfony/tree/v6.1.2/src/Symfony/Component/Security

**Comment by adeptofvoltron** [comment]
here is [commit](https://github.com/lexik/LexikJWTAuthenticationBundle/commit/c503ce9afddb85b928d6c58266076da9bd91f92b#diff-a3100332743ec72ba165875e59b8aac71ee5dec970ec384dc2ef4e220dad1cc0) where it was changed to implement that deprecated interface 

and here is [commit](https://github.com/lexik/LexikJWTAuthenticationBundle/commit/ab1f5af0956ebfbf09c7ac78755d1fc4a94b82d7#diff-a3100332743ec72ba165875e59b8aac71ee5dec970ec384dc2ef4e220dad1cc0) before, when it was removed

**Comment by fd6130** [comment]
I recall that Guard is deprecated and removed in Symfony 6? You should use the new authenticator instead of guard from now on.

**Comment by adeptofvoltron** [comment]
exactly. that why it schouldn't implement interface from guard namespace.

https://symfony.com/doc/current/security/custom_authenticator.html

and someone already changed it in project https://github.com/lexik/LexikJWTAuthenticationBundle/commit/ab1f5af0956ebfbf09c7ac78755d1fc4a94b82d7

but than it was returned to the "old ways" - not functioning with symfony 6.

**Comment by fd6130** [comment]
Sorry maybe I misunderstood your question. Now I'm wondering why the error will occurs when you are not using guard in Symfony 6?

**Comment by adeptofvoltron** [comment]
I believe I schould use:

            `custom_authenticators:
                - lexik_jwt_authentication.security.jwt_authenticator`

however service is marked as abstract:
```<service id="lexik_jwt_authentication.security.jwt_authenticator" class="Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JWTAuthenticator" abstract="true">```

**Comment by fd6130** [comment]
> I believe I schould use:
> 
> ```
>         `custom_authenticators:
>             - lexik_jwt_authentication.security.jwt_authenticator`
> ```
> 
> however service is marked as abstract: `<service id="lexik_jwt_authentication.security.jwt_authenticator" class="Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JWTAuthenticator" abstract="true">`

Isn't it the error won't occur if you are not using guard in symfony 6? Just use new authenticator for the case.

**Comment by adeptofvoltron** [comment]
let me dig in

**Comment by fd6130** [comment]
> I believe I schould use:
> 
> ```
>         `custom_authenticators:
>             - lexik_jwt_authentication.security.jwt_authenticator`
> ```
> 
> however service is marked as abstract: `<service id="lexik_jwt_authentication.security.jwt_authenticator" class="Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JWTAuthenticator" abstract="true">`

Please check and compare your configuration with this https://symfony.com/bundles/LexikJWTAuthenticationBundle/current/index.html#configuration

**Comment by adeptofvoltron** [comment]
yes, you are correct. thank you
