### ISSUE TITLE
Can't mock createFromPayload method

### ISSUE THREAD

**Issue by altesack** [lexik/LexikJWTAuthenticationBundle#1064]
Hi!
I'm writing a test of my app and trying to mock TokenManager and createFromPayload method

But this doesn't work, because of `createFromPayload` is desclibed as magic in JWTTokenManagerInterface
```
        $JWTTokenManager = $this->createMock(JWTTokenManagerInterface::class);
        $JWTTokenManager->method('createFromPayload')->willReturn(self::GOOD_JWT_TOKEN);
// Trying to configure method "createFromPayload" which cannot be configured because it does not exist, has not been specified, is final, or is static
```

This code doesn't work too, because of `createFromPayload` is not magic in JWTTokenManager
```
        $JWTTokenManager = $this->createMock(JWTTokenManagerInterface::class);
        $JWTTokenManager
            ->method('__call')
            ->with('createFromPayload')
            ->willReturn(self::GOOD_JWT_TOKEN);
// Trying to configure method "__call" which cannot be configured because it does not exist, has not been specified, is final, or is static

```

It works only if I use JWTManager instead of JWTManagerInterface
```
        $JWTTokenManager = $this->createMock(JWTManager::class);
        $JWTTokenManager->method('createFromPayload')->willReturn(self::GOOD_JWT_TOKEN);
// This works fine
```
Could you make it magic in the class or make it not magic in the interface?

**Comment by Spomky** [comment]
Why are you trying to mock this method when you can directly forge a valid (or invalid) access token with e.g. `none` algorithm?

**Comment by chalasr** [comment]
Hi,
This method is virtual for backward-compatibility reasons. As suggested by @Spomky, you should rather use a dummy/stub than mocking something you don't own. See e.g. https://blog.frankdejonge.nl/testing-without-mocking-frameworks/.
Thank you

**Comment by altesack** [comment]
Thank you. Backward-compatibility reasons are important  indeed.
No more questions
