### ISSUE TITLE
What's the length of the JWT token?

### ISSUE THREAD

**Issue by gremo** [lexik/LexikJWTAuthenticationBundle#1107]
I can't find the information anywhere. I need to store the token in the database (for blacklisting logic)... what's the maximum length?

**Comment by Spomky** [comment]
Tokens often have an unpredictable size.
If you want to have a blacklist, you should only store the token ID (https://www.rfc-editor.org/rfc/rfc7519#section-4.1.7) and not the token itself.

**Comment by gremo** [comment]
Thanks. You mean I need to decode the JWT token server-side and use the ID in my custom logic?
