### ISSUE TITLE
Deactivate API Platform automatic integration

### ISSUE THREAD

**Issue by jonag** [lexik/LexikJWTAuthenticationBundle#1118]
Hello,

Since the version [2.18.0](https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v2.18.0) the API Platform integration is automatically enabled if the bundle detects that API Platform is installed.

This is a great addition and should work for most projects, but can also cause some issue is some specific case. For example I'm using split cookies and have handcrafted my own definition for the API login operation. So after the update, I now have in the documentation page two definitions for the login route: mine and the one autogenerated (with a wrong definition).

Is there a way to deactive the automatic integration (I didn't find any) or would you consider a PR to allow that? If so, what whould be the best approach? Adding a new parameter under `lexik_jwt_authentication.api_platform` or something else?

Thank you!

**Comment by chalasr** [comment]
Looks like we totally forgot to care about BC here, sorry for this! It should definitely be fixed
