### ISSUE TITLE
Trying to instanciate an interface in LcobucciJWSProvider

### ISSUE THREAD

**Issue by Kern046** [lexik/LexikJWTAuthenticationBundle#1123]
In [`LcobucciJWSProvider.l105`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Services/JWSProvider/LcobucciJWSProvider.php#L105), there is a new instanciation of [`Lcobucci\JWT\Builder`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Services/JWSProvider/LcobucciJWSProvider.php#L7). But `Builder` is [an interface](https://github.com/lcobucci/jwt/blob/4.0.x/src/Builder.php). So this line would trigger an error if `Lcobucci\JWT\Token\Builder` [were to be unavailable](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Services/JWSProvider/LcobucciJWSProvider.php#L102).

Is it still relevant to control the existence of `Lcobucci\JWT\Token\Builder` ? If yes, what would be the alternative for `Lcobucci\JWT\Builder` instanciation ?

I'm ready to make a PR about it either to remove this condition or change the `else` statement :).

**Comment by chalasr** [comment]
Do you actually face a bug in this code? IIRC, Builder is instantiable when the JWTBuilder class does not exist (= old version where it was still a class)

**Comment by chalasr** [comment]
Of course it might be broken :) we would need a failing test case

**Comment by Kern046** [comment]
> Do you actually face a bug in this code? IIRC, Builder is instantiable when the JWTBuilder class does not exist (= old version where it was still a class)

I don't ! I was just visiting the code and saw this :). If it's for compatibility with older versions then it's legit I guess, as long as the change for `Builder` becoming an interface is in the same version as `JWTBuilder`creation.

**Comment by chalasr** [comment]
That’s the case, all good then. Thanks!

**Comment by chalasr** [comment]
(Don't feel embarrassed, these changes on the underlying lib are very hard to keep up with)
