### ISSUE TITLE
Unable to locate  "AuthenticatorInterface" 

### ISSUE THREAD

**Issue by joedoe20322** [lexik/LexikJWTAuthenticationBundle#1129]
I am on Symfony 6.0 after upgrade from 5.3 and i wanna keep the old jwt system ( based on JWTTokenAuthenticator) 
when calling the endpoint i receive this error : 
```
Attempted to load interface "AuthenticatorInterface" from namespace "Symfony\Component\Security\Guard".
Did you forget a "use" statement for e.g. "Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface" or "Symfony\Component\Mailer\Transport\Smtp\Auth\AuthenticatorInterface"?
```

**Comment by gordinskiy** [comment]
Security-guard component was deprecated since Symfony 5.3, and was removed in 6.0. 
Are you sure you no forgot to update all components, including LexikJWTAuthenticationBundle?
