### ISSUE TITLE
v2.18.1 Incompatible with lcobucci/jwt 5.0.0

### ISSUE THREAD

**Issue by test789t** [lexik/LexikJWTAuthenticationBundle#1138]
`composer require lexik/jwt-authentication-bundle`

Problem 1
    - Root composer.json requires lexik/jwt-authentication-bundle ^2.18 -> satisfiable by lexik/jwt-authentication-bundle[v2.18.0, v2.18.1].
    - lexik/jwt-authentication-bundle[v2.18.0, ..., v2.18.1] require lcobucci/jwt ^3.4|^4.0 -> found lcobucci/jwt[3.4.0, ..., 3.4.6, 4.0.0, ..., 4.3.0] but the package is fixed to 5.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by chalasr** [comment]
fixed in v1.19.0
