### ISSUE TITLE
Error on symfony 2.8.* upgrade

### ISSUE THREAD

**Issue by welcoMattic** [lexik/LexikJWTAuthenticationBundle#114]
Hi! I just try to upgrade my project with symfony 2.8.*, here is my composer.json piece:

```
"require": {
    "symfony/symfony": "2.8.*",
    [...]
    "lexik/jwt-authentication-bundle": "~1.3.1",
}
```

And the error of `composer update` command : 

```
lexik/jwt-authentication-bundle v1.3.1 requires symfony/symfony ~2.3 -> no matching package found.
```

May the problem comes from a mistake on your composer.json?

Thanks

**Comment by slashfan** [comment]
Hi,

I just checked on a fresh Symfony 2.8 installation and there is no problem installing the bundle. The last tag of the 1.x branch is 1.3.1 and is compatible Symfony ~2.3. You could try to replace the constraint in your composer.json by 1.3.* instead of ~1.3.1.

Let me know if you solved this.

**Comment by welcoMattic** [comment]
It works! My bad ... 

Thanks for your help
