### ISSUE TITLE
Login api route not showing in swagger api platform 3

### ISSUE THREAD

**Issue by RachidTMT** [lexik/LexikJWTAuthenticationBundle#1142]
I have a project with theses config versions : 
`"lexik/jwt-authentication-bundle": "^2.19",`

`"api-platform/core": "3.1.12",`

Can't the api for generating a token in swagger docs ?
I follow the docs for api platform : https://api-platform.com/docs/core/jwt/
Best regards.

**Comment by divine** [comment]
Hello,

I had the same issue and modified the documentation https://github.com/api-platform/docs/pull/1763

It's not enabled automatically anymore, the logic was changed in PR https://github.com/lexik/LexikJWTAuthenticationBundle/pull/1119

Thanks!

**Comment by chalasr** [comment]
Thanks @divine
