### ISSUE TITLE
Random 401 invalid JWT token on requests

### ISSUE THREAD

**Issue by ChristianVermeulen** [lexik/LexikJWTAuthenticationBundle#1145]
We are seeing an issue I can not explain and I have no idea how or where to debug it. When our mobile app is called, sometimes one of the requests will randomly fail authentication. This triggers our login, which will get a proper 200 and redirect back. This results in a n XHR redirection loop.

As you can see in the GIF below, we start out with 200's. Then when `preferences-hash` is called, all of a sudden we get a 401 with `invalid JWT token` even though the exact same bearer is used (as you can see when switching to successful requests.

![Screenshot 2023-06-07 at 11 51 02](https://github.com/lexik/LexikJWTAuthenticationBundle/assets/1062751/f52d8332-9834-4906-ade0-d5516be969d1)

The more requests are fired, the more are suddenly getting 401's back. And then eventually, after a couple of cycles everything will get 200 and all is fine.

**Comment by chalasr** [comment]
It is not possible to fix a bug without reproducing it first. Please comment/reopen if you can provide such reproducer.
