### ISSUE TITLE
LexikJWTAuth unexpected identifier Encoder expecting variable (500 Internal Server Error)

### ISSUE THREAD

**Issue by vincegio91** [lexik/LexikJWTAuthenticationBundle#1150]
This is my security.yaml:
security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        #name
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                username_path: email  
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/
            stateless: true
            jwt: ~
        dev:
            #bereich
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
    #    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #    - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #    - { path: ^/login, roles: PUBLIC_ACCESS }
    #    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
    
    
    lexik_jwt_authentication.yaml:
    ```
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    user_identity_field: email
```
MY REQUEST: 
{
    "email": "email",
    "password": "Hallo"
}

Can anyone help me why i recieved this syntax error?

**Comment by chalasr** [comment]
Please provide the the full stack trace of your error.
