### ISSUE TITLE
symfony 7

### ISSUE THREAD

**Issue by lxregistry** [lexik/LexikJWTAuthenticationBundle#1171]
- Root composer.json requires lexik/jwt-authentication-bundle ^2.19 -> satisfiable by lexik/jwt-authentication-bundle[v2.19.0, v2.19.1].
    - lexik/jwt-authentication-bundle[v2.19.0, ..., v2.19.1] require symfony/config ^4.4|^5.3|^6.0 -> found symfony/config[v4.4.0, ..., v4.4.44, v5.3.0, ..., v5.4.31, v6.0.0, ..., v6.4.0] but these were not loaded, likely because it conflicts with another require.

**Comment by KDederichs** [comment]
It's already merged even, just needs a release
