### ISSUE TITLE
Version 2.20+ requiring php 7.1 >= but using arrow functions

### ISSUE THREAD

**Issue by cirovargas** [lexik/LexikJWTAuthenticationBundle#1182]
In the EnableEncryptionConfigCommand command you are using arrow functions (php 7.4 feature) and in composer are requiring PHP version >= 7.1

This is throwing an exception when installing the package on a PHP 7.2 environment

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/3df8317555ea899a81b5c6b7558e421838f2f926/composer.json#L40C15-L40C15

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/v2.20.2/Command/EnableEncryptionConfigCommand.php#L89

![image](https://github.com/lexik/LexikJWTAuthenticationBundle/assets/1972562/a2dae6b2-1136-46d9-b40b-24db7764e534)

**Comment by aandriano931** [comment]
I agree. Same error here on a PHP 7.3 environment, lexik/jwt-authentication-bundle:v2.20.2

![image](https://github.com/lexik/LexikJWTAuthenticationBundle/assets/49196540/9533b49d-62d5-4c5d-8bbb-d464044298bc)

**Comment by chalasr** [comment]
Will be fixed by #1183. Turns out we have a CI job giving false positives...
