### ISSUE TITLE
Not compatible with PHP 8.2

### ISSUE THREAD

**Issue by abdousadik** [lexik/LexikJWTAuthenticationBundle#1186]
Hello,

i'm working on a Symfony 7 project, which works with at least PHP 8.2

i tried to install LexikJWTAuthenticationBundle but met with compatiblity issues:

![lexik](https://github.com/lexik/LexikJWTAuthenticationBundle/assets/73437552/a466ba38-5211-4ee2-ae4f-1b8301bf4bff)

please help,
thank you

**Comment by theofidry** [comment]
It is compatible with PHP 8.2, the issue, as per the problem listed, is that the package `lcobucci/jwt` requires `ext-sodium` which you do not have installed or enabled.

**Comment by chalasr** [comment]
Closing as explained.

**Comment by kapcus** [comment]
sodium is not available on RHEL v PHP 8.2 or newer - is it possible to have it without sodium? Is sodium core requirement for this extension? e.g. maybe it can be replaced by bcrypt etc and this extension will still work?

thx for any suggestion
