### ISSUE TITLE
Can we tell this bundle not to use Redis?

### ISSUE THREAD

**Issue by aruku** [lexik/LexikJWTAuthenticationBundle#1197]
I added the command to generate the keys to the Google Cloud build steps for my app and it fails because in the environment there is no Redis. (I'm guessing that PHP instance doesn't have it).
`Cannot find the "redis" extension nor the "predis/predis" package`

Is there a way to tell the bundle not to use it? Or to not to load it, as I assume there is not much of a need for it at that point)?

**Comment by theofidry** [comment]
From where this dependency comes from exactly? (You can use `composer why`)

**Comment by aruku** [comment]
I don't know, since the error is that it is not present. Your question makes me assume LexikJWT doesn't know anything about this, so it should be coming from some other dependency and it just happens to be initialized when running the command for the keys.

The thing is that I stopped the Redis container on my local Docker and the command finished ok, so I don't know what to try next.

EDIT: Well, this seems to be coming from Symfony's cache mechanism; I rebuild my PHP container without enabling the Redis extension and I got the same error, so I searched for the usage of that trait and found its only two usages in the entire vendor directory.

I don't know if this something you would like to take another look at or not. In the meantime, I can update this thread if I found a solution other than enabling Redis just for this in the Google Cloud project.

**Comment by mbabker** [comment]
Run the command with the `-vvv` flag, you should get a stack trace that gives you an idea what's trying to boot up a cache service.  Nothing in this bundle directly relies on `symfony/cache`, so maybe some other service getting booted up during the console lifecycle (i.e. an event listener) does?

**Comment by aruku** [comment]
> Run the command with the `-vvv` flag, you should get a stack trace that gives you an idea what's trying to boot up a cache service. Nothing in this bundle directly relies on `symfony/cache`, so maybe some other service getting booted up during the console lifecycle (i.e. an event listener) does?

No stack trace:
```
I have no name!@258375bc1f18:/workspace$ bin/console lexik:jwt:generate-keypair -vvv --overwrite
Xdebug: [Step Debug] Time-out connecting to debugging client, waited: 200 ms. Tried: host.docker.internal:9000 (fallback through xdebug.client_host/xdebug.client_port) :-(

 You are about to replace your existing keys. Are you sure you wish to continue? (yes/no) [yes]:
 > yes

                                                                                                                        
 [OK] Done!                                                                                                             
                                                                                                                        
```

**Comment by aruku** [comment]
`-vvv` didn't get me the stack trace; I ended up creating a simple PHP Docker image with Redis enabled and was able to run the command.
Thank you both for your time.
