### ISSUE TITLE
Release with "namshi/jose": "~6.0"

### ISSUE THREAD

**Issue by jblanchon** [lexik/LexikJWTAuthenticationBundle#121]
Hi,

Is it possible to have a new release with `"namshi/jose": "~6.0"` ?

Thank you,

**Comment by slashfan** [comment]
Hi, this has been done, it just isn't tagged at the moment, see https://github.com/lexik/LexikJWTAuthenticationBundle/issues/112

**Comment by jblanchon** [comment]
Hi, thank you, i will wait for the tag
