### ISSUE TITLE
Protect my API responses

### ISSUE THREAD

**Issue by 3KyNoX** [lexik/LexikJWTAuthenticationBundle#122]
Hello everyones,

I just finished install Lexik JWT Auth Bundle but the requested behavior is not met.

My problem is probably related to my misunderstanding and here the questions : 

Since Lexik Bundle is installed, if I try to go to my api request page, it redirects to FOSUser login, asks for user credentials and then redirect to a generated token page.

That's ok for this part, but if I try to go to my api with the token set to URL or using POSTMAN to put the Bearer token on headers, it still continue infinitly redirecting me to login page and token generation.

If I remove from my security.yml the stateless true option, I can access my api page (as the api only required to be logged in to display responses).

So now, if I can get some help, why the api page is not protected correctly if no token given (and I have redirect to login) and why when I set the token, it still doesn't display my api jsons ?

[Here is my code](https://gist.github.com/3KyNoX/3c7b4930c1d619fa2a6d)

Thanks for help.

**Comment by slashfan** [comment]
Hi, you should place your api firewall before the main firewall. The api firewall is never reached as the main firewall pattern and position makes it take over the api section.

**Comment by 3KyNoX** [comment]
You did it slashfan, it works now with header and query now, 2 days blocked with this issue.

Thanks a lot !

**Comment by 3KyNoX** [comment]
Another question if possible, when I call : 

 > curl -X POST -d  _username="johndoe" -d _password="test" http://courtier-web-api-platform/app_dev.php/login_check

A token is returned correctly, but I need to pass user credentials with json, to get it with angular $http object method. Unfortunately, using : 

> curl -X POST -d '{"username": "johndoe", "password": "test"}' -H "Content-Type:application/json" http://courtier-web-api-platform/app_dev.php/login_check

 returns  53{"code":401,"message":"Bad credentials"}

Because I pass user credentials from angular as a json object, I'll need this second method.

Any idea to correct this ?

**Comment by slashfan** [comment]
If you want to send the user credentials as a JSON request you need to decode it before it reaches the login_check action. You could implement a request event listener to decode it or use FOSRestBundle for that.

**Comment by 3KyNoX** [comment]
Anyway, I managed it fro the  angular client : 

```js
$scope.user = {username: 'johndoe', password: 'test'};
...
$http({
      method: 'POST',
      url: 'http://my-api-platform/login_check',
      headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
      },
      data: $.param($scope.user)
```
