### ISSUE TITLE
Issue with LMI HMC M3F3 EXTRACTION

### ISSUE THREAD

**Issue by GurramSireehsa98** [lexik/LexikJWTAuthenticationBundle#1220]
Hello Team,
Actually we have an issue with LMI HMC Mef3 extraction when they platform team is trying to run the mef3 data the extraction line was broken not present on the mef3 data and these scripts have to run on IBMi 7.3 QSH (K shell environment) and the last line is never produced and perl is not in the environment.
[HMC data.zip](https://github.com/lexik/LexikJWTAuthenticationBundle/files/15160864/HMC.data.zip)

Kindly help us to get this issue resolved as early as possible.
Please find the debug log and mef3 data for your reference.

**Comment by chalasr** [comment]
Hi, I don't understand what you're talking about so I think this is not the repository you're looking for :)

**Comment by GurramSireehsa98** [comment]
Hello Robin,
when we extract the mef3 data we will get the signature line in the last right but here we haven't received any signature line.

**Comment by GurramSireehsa98** [comment]
Hello Team,

Please close the ticket the issue is solved.
