### ISSUE TITLE
Allow credentials to be sent as JSON

### ISSUE THREAD

**Issue by Flo-Schield-Bobby** [lexik/LexikJWTAuthenticationBundle#123]
Hi,

Thanks for this bundle, it works great so far :)

I was just wondering, would it be possible to allow credentials to be sent both a a JSON object or `application/x-www-form-urlencoded` data?

It just makes more sense, as the response is sent in the JSON format anyway.
Basically, in addition to this request:

```
POST /api/login HTTP/1.1
Host: https://whatever.domain.org

_username="any-name"&_password="any-password"
```

Allow this one also:

```
POST /api/login HTTP/1.1
Host: https://whatever.domain.org
Content-Type: "application/json"

{
    "_username": "any-name",
    "_password": "any-password"
}
```

**Comment by slashfan** [comment]
Hi, 

I don't think that's the bundle's role to handle the request format. Currently all examples are based on the form_login provided by Symfony wich expects application/x-www-form-urlencoded, so if you want to keep using it you will have to implement a request listener which will convert your json payload to the appropriate format. FOSRestBundle provides such a listener. 

Hope it helps !

**Comment by Flo-Schield-Bobby** [comment]
Oh, okay, I just did not know it would work with a RequestListener!
Thanks, I'll carry it myself so :)

**Comment by dunglas** [comment]
See https://github.com/symfony/symfony/pull/18952
