### ISSUE TITLE
Got 401 Status with angular and 200 and the token with Postman or CURL X POST

### ISSUE THREAD

**Issue by MaLaSarr** [lexik/LexikJWTAuthenticationBundle#130]
When Tried the login with my Front (Angular) I Got 401 BAD Credential.
But When I use it with postman and got my token and status 200.
I got my token also when I use curl curl -X POST -d username="test2" -d password="test1" http://koober.dev/app_dev.php/api/login_check
Did someone already have this kind of error ? 
i did modify my VHOST on MAMP PRO
 RewriteEngine On
    RewriteCond %{HTTP:Authorization} ^(.*)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

Thank You

**Comment by slashfan** [comment]
Hi, could you check if angular sends the credentials request using application/x-www-form-urlencoded format and not as json payload ? See #123

**Comment by MaLaSarr** [comment]
Thank you a lot.
It was the problem. 
I found this solution: http://stackoverflow.com/questions/19254029/angularjs-http-post-does-not-send-data?answertab=active#tab-top
If you have an easier one, it'll helpful 
Thank

**Comment by slashfan** [comment]
Cool !
