### ISSUE TITLE
Expiration date in response?

### ISSUE THREAD

**Issue by Flo-Schield-Bobby** [lexik/LexikJWTAuthenticationBundle#131]
Just a question about how token expiration is handled, would it be possible (and is it a good idea?) to append the expiration date of the token in the response?

I know the TTL is configurable, which is good, but what if it is changed at any time on server-side, while clients are not aware of it?

Would there be any interest of having the token expiration date inside the response, to be stored client-side, in order to know when does this token actually expires ?

```
{
    token: "xxxxxxxx-yyyyy-zzzzzz",
    expires_at: "YYYY-MM-DDTHH:ii:ss"
}
```

**Comment by slashfan** [comment]
Hi, it is already possible using the events dispatched by the bundle, you can see an example here :   https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsauthentication_success---add-public-data-to-the-jwt-response.
