### ISSUE TITLE
Preflight Response Returns 404 (Regardless of firewall order)

### ISSUE THREAD

**Issue by jkosmetos** [lexik/LexikJWTAuthenticationBundle#135]
First off, apologies for posting this here, but I am at the end of my rope, I've been struggling for days on end, and I am no closer to finding a solution.

I've just implemented the bundle, but when I attempt to authenticate a user, I keep getting the following response, 

    XMLHttpRequest cannot load http://api.example.trunk/api/login_check. Response for preflight has invalid HTTP status code 404

What's weird, is that the request does work via Postman, and I get a token, so I'm thinking that this could have something to do with CORS?

**security.yml**

    security:
    
        encoders:
            User\UserBundle\Entity\User: sha512
    
        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
        providers:
    
            database_users:
                entity: { class: UserBundle:User }
    
            in_memory:
                memory:
                    users:
                        ryan:
                            password: ryanpass
                            roles: 'ROLE_USER'
                        admin:
                            password: kitten
                            roles: 'ROLE_ADMIN'
    
        firewalls:
            login:
                pattern:  ^/api/login
                stateless: true
                anonymous: true
                form_login:
                    check_path:               /api/login_check
                    success_handler:          lexik_jwt_authentication.handler.authentication_success
                    failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                    require_previous_session: false
    
            api:
                pattern:   ^/api
                stateless: true
                lexik_jwt: ~
    
            dev:
                pattern: ^/(_(profiler|wdt)|css|images|js)/
                security: false
    
        access_control:
            - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

**example.trunk.conf (Apache VHost)**

    <VirtualHost *:80>
      ServerName api.example.trunk
      DocumentRoot /Users/user/Sites/example/web
      UseCanonicalName Off
      ErrorLog "/Users/user/Sites/logs/example-error_log"
      CustomLog "/Users/user/Sites/logs/example-access_log" common
      DirectoryIndex app_dev.php
    
      Header always set Access-Control-Allow-Origin "*"
      Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
      Header always set Access-Control-Allow-Headers "x-requested-with, content-type, origin, authorization, accept, client-security-token"
      Header always set Access-Control-Max-Age "1000"
    
      RewriteEngine On
      RewriteCond %{HTTP:Authorization} ^(.*)
      RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
    
      <Directory "/Users/user/Sites/example/web">
        AllowOverride All
        Order allow,deny
        Allow from all
      </Directory>
    </VirtualHost>

**Request / Response Headers**

    General headers:
      Request URL:http://api.example.trunk/api/login_check
      Request Method:OPTIONS
      Status Code:404 Not Found
      Remote Address:127.0.0.1:80
    
    Response headers:
      HTTP/1.1 404 Not Found
      Access-Control-Allow-Origin: *
      Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT
      Access-Control-Allow-Headers: x-requested-with, content-type, origin,
      authorization, accept, client-security-token
      Access-Control-Max-Age: 1000
      Cache-Control: no-cache
      Keep-Alive: timeout=5, max=100
      Connection: Keep-Alive
      Transfer-Encoding: chunked
      Content-Type: text/html; charset=UTF-8
    
    Request headers:
      OPTIONS /api/login_check HTTP/1.1
      Host: api.example.trunk
      Connection: keep-alive
      Access-Control-Request-Method: POST
      Origin: http://localhost:3000
      Access-Control-Request-Headers: accept, content-type
      Accept: */*
      Referer: http://localhost:3000/

  [1]: https://github.com/lexik/LexikJWTAuthenticationBundle

**Comment by slashfan** [comment]
Hi, did you try using NelmioCorsBundle ? Hi had problems with server configuration alone, this bundle did the trick. See https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/4-cors-requests.md#working-with-cors-requests.

**Comment by jkosmetos** [comment]
I had tried it earlier, but it didn't seem to work. I've since started from scratch, and installing it this time around seems to have done the trick. It seems like the initial OPTIONS request was confusing things a bit, but the bundle definitely takes care of that issue. Thanks a lot @slashfan!

**Comment by cve** [comment]
Hi,

I'm developing Vue.js app with REST and CORS enabled with NelmioCorsBundle, but when I try to post /auth/login_check from my Vue.js app with proper payload of _username and _password then the server first call OPTIONS (without payload) which end's with status 200 and immediatly call second request POST to /auth/login but this time without my request payload {} so it response is 401 unathorized...

I'm fight with this problem since to 2 days... :/ can anyone help me?
