### ISSUE TITLE
Changing username cause Fatal error

### ISSUE THREAD

**Issue by Diwatt** [lexik/LexikJWTAuthenticationBundle#137]
Hi guys. First of all thanks for your work ! It helps us a lot !

We discover one case where the bundle will throw an error.
If we change the username in database the method JWTProvider::getUserFromPayload cannot retrieve anymore the user and we get this error:

`PHP Fatal error:  Call to a member function getRoles() on a non-object in /vendor/lexik/jwt-authentication-bundle/Lexik/Bundle/JWTAuthenticationBundle/Security/Authentication/Provider/JWTProvider.php on line 70`

We fix this with a simple rule in the JWTDecodedListener:
```
if ($user->getUsername() !== $payload['username']) {
    $this->logger->debug(sprintf('changing username force re-auth (new: "%s", old: "%s")', $user->getUsername(), $payload['username']));
    $event->markAsInvalid();
}
```

Then we get a "bad credentials" response.
Maybe this should be handled by the bundle rather than a listener ?

Another solution may be throw a bad credentials if the getUserFromPayload return null.
Because every times we have auth error we get this exact same error. "Call to member function getRoles()...."

**Comment by slashfan** [comment]
Hi, thanks for the heads up ! I never met this case before but you are right it should be handled by the bundle itself. I'll try to make a quick fix for this one.

**Comment by slashfan** [comment]
Just a question what is the UserProvider class used by your firewall ?

**Comment by Diwatt** [comment]
Atm it's ours own UserProvider then yes you're right on this. It should throw the UsernameNotFoundException and it does not do that. Then i don't know anymore if the bundle should handle that's or maybe the doc should provide info about this ?

**Comment by slashfan** [comment]
Hi, I don't think it's the job of the bundle after all. It's the job of the classes implementing UserProviderInterface to throw that exception. If it is correctly thrown then there won't be a problem anymore :)

**Comment by Diwatt** [comment]
I closes the issue then. The small problem is that except this page http://api.symfony.com/3.0/Symfony/Component/Security/Core/User/UserProviderInterface.html (and i look for it) there is no explicit doc telling that the interface have to throw this exception. I feel like you may be annoyed for the exact same problem.
