### ISSUE TITLE
How to add connection method to the api documentation?

### ISSUE THREAD

**Issue by Seb33300** [lexik/LexikJWTAuthenticationBundle#138]
Hello

I am creating a REST API with FOSRestBundle and your bundle to provide a JWT authentication.
I am using the NelmioApiDocBundle to generate a documentation of my API.

I would like to show login in the documentation as a method (with username / password as required params and the token as the outpout).

So I created my custom authentication controller containing the login method with proper annotations to make it appear in the documentation, but how to forward the call of this method to the login_check validation?

Thanks

**Comment by Seb33300** [comment]
Just found the solution here: https://github.com/nelmio/NelmioApiDocBundle/issues/340

Just have to create a "fake" controller method on which I can place ApiDoc annotations in your project with the same route as the login_check route.

In the app/config/route.yml, just set the login_check route before importing your bundle routes so it will have the priority.

If you use the NelmioApiDocBundle sandbox to test your REST API calls, depending on your config, it may add a ".json" at the end of the url, so you have to redefine the login_check route to:
```
api_login_check:
    path: /api/login_check{_format}
    defaults:  { _format: ".json" }
```

**Comment by wadjeroudi** [comment]
A more up to date solution : https://github.com/nelmio/NelmioApiDocBundle/issues/806#issuecomment-377928048
