### ISSUE TITLE
Never expires (as defined in config)

### ISSUE THREAD

**Issue by 3kynox** [lexik/LexikJWTAuthenticationBundle#140]
Hello,

I saw sometimes token is expiring with default 86400sc value, when it pass one day and I come back to  call a new request.

I now need to test and implements from my client the case when token expires to set a new one, or refresh existing (using gesdinet bundle).

But, I set token_ttl to 120sc and looks like the token still active. Doesn't matter cache is cleared and 2 minutes passed.

Any idea about this ?

**Comment by slashfan** [comment]
Hi, could you show us your config ? Which version of the bundle and the namshi/jose library do you use ?

**Comment by 3kynox** [comment]
JWTBundle 1.4.

I was doing some tests from angular, and it looks like to refresh, so ...
Tests I done before with postman let me uses token even it was expired.

Anyway, angular side is the important. Thanks for answer :)
