### ISSUE TITLE
Unable to find the controller for path "/login_check". The route is wrongly configured. 

### ISSUE THREAD

**Issue by sirjcbg1** [lexik/LexikJWTAuthenticationBundle#143]
Hi, I followed all the steps to create a custom form, but tells me not find the login_check
 
My security.yml 

security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        app_users:
            ldap:
                service: app.ldap
                base_dn: dc=bancoex,dc=corp
                search_dn: ******
                search_password: ******
                filter: "(&(msExchUserAccountControl=0)(name={username}))"
                default_roles: ROLE_USER
                
        my_chain_provider:
            chain:
                providers:  [ app_users ]       
    firewalls:
        api:
            provider:  app_users
            stateless: true
            pattern:   ^/pruebaldap1
            http_basic_ldap:
                service: app.ldap
                dn_string: "{username}@bancoex.corp"
        backend:
            provider: app_users
            pattern:  ^/pruebaldap
            logout:
                path:   logout
                target: login
            form_login_ldap:
                service: app.ldap
                always_use_default_target_path: true
                default_target_path:            ^/pruebaldap 
                dn_string: **************
                check_path: login_check
                login_path: login

my rounting.yml

prueba:
    resource: "@PruebaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login_check:
    path: /login_check
    

my controller

namespace PruebaBundle\Controller;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class SecurityController extends Controller
{
    /**
     * @Route("/login", name="login")
    */
    public function loginAction(Request $request)
    {
        $authenticationUtils = $this->get('security.authentication_utils');

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render(
            'PruebaBundle:Login/login.html.twig',
            array(
                // last username entered by the user
                'last_username' => $lastUsername,
                'error'         => $error,
            )
        );
    }
   
}         

my twig:

{% extends '::base.html.twig' %}
{% block body -%}
    {% if error %}
        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    <form action="{{ path('login_check') }}" method="post">
        <label for="username">Username:</label>
        <input type="text" id="username" name="_username" value="{{ last_username }}" />

        <label for="password">Password:</label>
        <input type="password" id="password" name="_password" />
        <input type="hidden" name="_target_path" value="/admin" />

        {#
            If you want to control the URL the user
            is redirected to on success (more details below)
            <input type="hidden" name="_target_path" value="/account" />
        #}

        <button type="submit">login</button>
    </form>
{% endblock body -%}

**Comment by AntonioCS** [comment]
Did you add login_check in routes.yml?

**Comment by slashfan** [comment]
@sirjcbg1 any progress on this ?
