### ISSUE TITLE
Openssl command requires pass phase

### ISSUE THREAD

**Issue by AntonioCS** [lexik/LexikJWTAuthenticationBundle#146]
Hey,

The command:

`openssl genrsa -out app/var/jwt/private.pem -aes256 4096`

Requires a pass phrase. If I just click enter  I get this:

> 140149337790112:error:28069065:lib(40):UI_set_result:result too small:ui_lib.c:869:You must type in 4 to 8191 characters

Is there any way to bypass this?

**Comment by devantoine** [comment]
Why would you want to bypass it?
Simply set a passphrase, use it to generate the public key and configure the parameters.yml accordingly.

**Comment by AntonioCS** [comment]
In all the examples there is no passphrase so I assumed there was either an option or an older version of the command was used.

**Comment by devantoine** [comment]
Well, it's all in the documentation: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md

**Comment by AntonioCS** [comment]
The documentation example shows the as pass_phrase as empty. All I am saying is if it is mandatory the documentation should have something in the pass_phrase.

**Comment by slashfan** [comment]
@AntonioCS feel free to correct the documentation and make a PR

**Comment by AntonioCS** [comment]
@slashfan I think it would take me more time to fork the repo, do the change and then send a PR request, when you can just add some text in the passphrase and be done with it.

**Comment by rayenhidri27** [comment]
im using this library and this command, but when it asks me do enter the pass phrase, i cant type anything
i tried to type it in windows terminal, in VS Code terminal and even in git bash, it stills not working
is it a known issue ?
if so, is there a solution ?
