### ISSUE TITLE
trying to customize my user provider

### ISSUE THREAD

**Issue by stickyhands** [lexik/LexikJWTAuthenticationBundle#151]
Im trying to implement some custom logic into my user provider, 
to do so I created my own loadUserByUsername function into my repository class, but for some reason my loadUserByUsername function is ignored. 

Is that normal ?

My use case is to allow my JWT login only for few IPs (that can be sets by a back office)

**Comment by stickyhands** [comment]
for now I'm using a listener on the JWTCreatedEvent

**Comment by slashfan** [comment]
@stickyhands do you want to allow only certain IPs to obtain a token or use a generated token ?
