### ISSUE TITLE
Use JWTEntryPoint instead of OAuthEntryPoint

### ISSUE THREAD

**Issue by devantoine** [lexik/LexikJWTAuthenticationBundle#152]
Hi,

When a request is made to a secured route and the user is not authenticated the request is redirected to the login form because of OAuthEntryPoint. What I want is to throw a 401 like JWTEntryPoint does, but I don't know how to do it.

My bad solution would be add a new listener extending KernelException, catch the AccessDeniedHttpException and use the exact same code than the one in JWTEntryPoint::start() but that's not dry at all. I'm sure there's a better way to do this.

Here is my security.yml:

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lexik_jwt:
                create_entry_point: true
            pattern: ^/
            oauth:
                require_previous_session: false
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                check_path: /login/login_check
                resource_owners:
                    google: "/login/check-google"
                login_path:        /login
                oauth_user_provider:
                    service: api.user_provider
            logout:       true
            anonymous:    ~
            stateless: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: ROLE_USER }
```

**Comment by chalasr** [comment]
If I correctly understand, you configured HWIOAuthBundle + this bundle on the same firewall, right ?
How does that behave in case of successful authentication ?
Which one is used to authenticate users, the JWT response or the OAuth one ?

**Comment by slashfan** [comment]
What stack do you use for OAuth ? From what I understand your issue is not really related to this bundle.

**Comment by devantoine** [comment]
I'm using HWIOAuthBundle.

I've finally done it using FosRestBundle with the access_denied_listener parameter.
