### ISSUE TITLE
Functional test with authenticated client

### ISSUE THREAD

**Issue by devantoine** [lexik/LexikJWTAuthenticationBundle#155]
I'm not able to create an authenticated client to make my functional tests work.

I've seen [the documentation](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/3-functional-testing.md) about it but I don't understand to which controller /api/login_check should redirects.

I'm developing a rest api so I have no login form. Authentication is done with oauth, using HWIOAuthBundle.

**Comment by yanict** [comment]
hey,
i'm trying to implement it with HWIOAuthBundle and i'm not sure 100% sure about the way i should take to do it.
Could you explain how you did it and/or share code ? It would be very helpful !!
thanks

**Comment by devantoine** [comment]
@yanict Are you talking about the testing part or the configuration between HWIOAuthBundle and LexikJWTAuthenticationBundle for the firewall?

**Comment by yanict** [comment]
about the configuration between HWIOAuthBundle and LexikJWTAuthenticationBundle.

**Comment by devantoine** [comment]
@yanict Open anew issue then and I'll try to answer it, but I'd like to keep this issue focused on my case.

**Comment by yanict** [comment]
ok thanks, actually there already is an issue for that but it has been closed a year ago. https://github.com/lexik/LexikJWTAuthenticationBundle/issues/64

**Comment by devantoine** [comment]
@yanict I've answered in the corresponding issue.
