### ISSUE TITLE
bad cerdentials

### ISSUE THREAD

**Issue by khaledbouguerra** [lexik/LexikJWTAuthenticationBundle#158]
hi ! I couldn't get this bundle to work , when i run the cmd curl -X POST http://localhost:8000/api/login_check -d _username=johndoe -d _password=test , i keep getting this json object :{"code":401,"message":"Bad credentials"}
i followed the doc you provided ! but nothing is working , i hope you can help  toget over this prblm beacuse i'm really stuck in it  , and thanks.

**Comment by khaledbouguerra** [comment]
hey guys is there any one can helps , doI need to make a custom provider or just use the configurations mentioned in the documentation , or use this bundle with FOSUSerbundle to make it work 
PS: I'm using this bundle to authentificate an angularjs app

**Comment by chalasr** [comment]
@khaledbouguerra  Please take a look at the sandbox, I answered you on [StackOverflow](http://stackoverflow.com/a/36463549/4363634).

**Comment by khaledbouguerra** [comment]
SO i need to create a user Entity and Create AuthentificationController with the function: setUp() ,testLoginFailure(),testLoginSuccess()...

**Comment by chalasr** [comment]
@khaledbouguerra That's (pretty much) it, this bundle requires to have a configured User Provider.

Look at [How create a custom user provider](http://symfony.com/doc/current/cookbook/security/custom_provider.html) or use the [FOSUserBundle](https://symfony.com/doc/master/bundles/FOSUserBundle/index.html) (ready to use).
I agree with you on the fact that this prerequisite could be present in the documentation.

Can we close this issue ?

**Comment by khaledbouguerra** [comment]
thanks alot man ! this is all i need to know  :+1:
