### ISSUE TITLE
PR #157 ignores security.yml anonymous path

### ISSUE THREAD

**Issue by maciejmiara** [lexik/LexikJWTAuthenticationBundle#160]
Merged PR #157 commit 3051ad5912327 (Add Events::JWT_INVALID and Events::AUTHENTICATION_FAILURE listening) causes an error.

Now, even though I have following setting in security.yml:

> access_control:
>         - { path: ^/api/v1/sign_in$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
>         - { path: ^/api/v1/client/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
>         - { path: ^/api/v1/employee/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }

I receive 401 response for "api/v1/employee/register" with information that no JWT token has been provided, but I don't want to provide it, because it is route with anonymous access.

**Comment by chalasr** [comment]
@maciejmiara Thank you for the report.
I already submitted a PR #159 that fixes the bug, it will be merged as soon as possible (hope tomorrow).
Sorry for the inconvenience.

**Comment by slashfan** [comment]
Fixed in 1.5.1 tag
