### ISSUE TITLE
Bad credentials with good information

### ISSUE THREAD

**Issue by Quovandius** [lexik/LexikJWTAuthenticationBundle#163]
Hello everyone,

I have seen many post on this subject, but i can't make a correct request, regardless all of my tests.
I hope anyone could help me on this.

My current configuration : 
I work with wamp - apache 2.4.9 -- php 5.5.12
I work with symfony3

i add all rewrite rules in my vhost : 

```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.)
RewriteRule . - [e=HTTP_AUTHORIZATION:%1]
```

On backend, my security.yml is : 

```
firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern: ^/api/doc
            anonymous: true

        api_login:
            pattern:  ^/api/login
            provider: fos_userbundle
            stateless: true
            anonymous: true
            form_login:
                check_path:     /api/login_check
                require_previous_session: false
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            provider: fos_userbundle
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    Bearer
                throw_exceptions:        true
                create_entry_point:      true
```

Configuration  of fosuserbundle : 
```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    group:
        group_class: UserBundle\Entity\Group
        form:
            type: UserBundle\Form\Type\GroupFormType
    profile:
        form:
            type: UserBundle\Form\Type\ProfileFormType
```

And side of client, i use ionic with angular js, and i try to get the token with : 
```
 var loginData = {
                username: this.login.username,
                password: this.login.password
            };

            console.debug(loginData);

            $http({
                url: 'http://app.local/app_dev.php/api/login_check',
                method: 'POST',
                data: loginData,
                headers: {'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'},
                ignoreAuthModule: true
            })
                .success(function (data) {
                    console.log("Success -- login ok with ".data);
                    $scope.token = data;
                })
                .error(function (data) {
                    console.log("ERROR -- login fail with ", data);
                    $scope.token = data;
                });
```

that's always return me 'bad credentials'

But my test with curl send me a token
`curl -X POST http://app.local/api/login_check -d _username=username -d _password=pass`

If anyone have an idea ??

**Comment by slashfan** [comment]
Hi, try to prefix username and password with an `_` in your angular code

**Comment by chalasr** [comment]
BTW, [stackoverflow](http://stackoverflow.com) is the offical platform for [Symfony support](http://symfony.com/doc/current/contributing/code/bugs.html) (and community bundles). There is a _lexikjwtauthbundle_ tag that you can use for tag your question and, if nobody can help, open an issue here.

@slashfan What do you think? It could preserve this repository from issues that are not related to the bundle itself / not relevant.

**Comment by Quovandius** [comment]
@slashfan Thx for your answer, i try this trick but nothing has changed.

@chalasr sorry, but this question concern this bundle so i think its logic to post here. I have found many issues on same problem, but for now i can't get  my token.

**Comment by chalasr** [comment]
@Quovandius What I mean is that, as you pointed, there is many posts on this subject and in fact the problem doesn't come from the bundle itself, but from your implementation (environment, configuration), So, asking on stackoverflow will give you more chances to have an answer from someone that have the same environment and already solved the same problem, and you'll be answered quicker than here because of the lots of people watching on.

If I can give an advice, try to clone the [sandbox](https://github.com/slashfan/LexikJWTAuthenticationBundleSandbox) that have an implementation of the bundle very close to yours. If it works, look for any different configurations, if it doesn't, it's pretty much sure that the problem come from your environment.

**Comment by Quovandius** [comment]
@chalasr i follow your advice, and post my problem on stackoverflow

Thanks for your help, it's a very nice bundle.

**Comment by chalasr** [comment]
You're welcome, don't hesitate to re-open the issue if the problem persist!

**Comment by slashfan** [comment]
@chalasr I agree 100%

**Comment by Quovandius** [comment]
Hello
sorry for disturbing, but i can't find any solution for my problem :s

I have opened 2 stackoverflow, ask on nelmiocors github (0answer) and even on fosrest github...

1) http://stackoverflow.com/questions/36933801/lexikjwtauthenticationbundle-with-ionic-app

2) http://stackoverflow.com/questions/37227328/cors-request-with-symfony-angular/37282619

My symfony server return me this request :
```
Request URL:http://sub.domain.com/app_dev.php/api/login_check
Request Method:OPTIONS
Status Code:200 OK
Remote Address:x.x.x.x:80
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Headers:origin, content-type, x-requested-with, accept
Access-Control-Allow-Methods:POST, PUT, GET, DELETE, OPTIONS
Access-Control-Allow-Origin:http://localhost:8100
Access-Control-Allow-Origin:*
Access-Control-Max-Age:3600
```

I can't understand why 'Access-Control-Allow-Headers' and 'Access-Control-Allow-Origin' are duplicated. 

One guy tell me its maybe nginx configuration which add on header. I have try many configuration, but that's not solved my problem

Sorry for this trouble :s

**Comment by chalasr** [comment]
It seems you have a problem with your web server configuration, sorry but I can't do anything more than what you are able to do, as your issue is totally specific to your environment.

IMHO, try to do the same with the built-in php web server (`php app/console server:run`), if there is no problem, this issue must be closed because totally unrelated to this bundle.

@slashfan I let you see if you can help or if this should be closed.

**Comment by Quovandius** [comment]
Ok thx for this quick answer, i reclose this issue, and try again your advice.

If this does not work, i must be change solution
