### ISSUE TITLE
Adding other data to JWT Token

### ISSUE THREAD

**Issue by snaquaye** [lexik/LexikJWTAuthenticationBundle#185]
Hello,

I think it would be nice to be able to add other user related fields to the generated token, like user's full name or data developpers would like to send to the client.

Thanks

**Comment by snaquaye** [comment]
Sorry, my bad, I think i can use the listener.

**Comment by chalasr** [comment]
Sure, see [data customization](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md).
