### ISSUE TITLE
lexik_jwt_authentication.on_jwt_invalid fired only for valid JWTS

### ISSUE THREAD

**Issue by skiner68** [lexik/LexikJWTAuthenticationBundle#187]
Hello,
I want to log all invalid requests to my API so registered a listener: **lexik_jwt_authentication.on_jwt_invalid**

I have made some tests:  **lexik_jwt_authentication.on_jwt_invalid** is not fired when token does not meet JWT syntax requirements or is not defined in http header. Only **AuthenticationCredentialsNotFoundException** exception is logged in profiler:

`
Context: { "exception": "Object(Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException)" } `

Is there any way to solve this in some easy way? Thank you for your time!

**Comment by chalasr** [comment]
Hi @skiner68,

> when token does not meet JWT syntax requirements

Can you precise what you mean here?

Actually, if you are passing a wrong token (via a Authorization header for instance) e.g:

`Bearer xxx`, the `lexik_jwt_authentication.on_jwt_invalid` is fired, you can override the response as documented [here](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md).

But in case of you don't pass the token we currently don't dispatch any event.
You are the first to exprim the need of this bug fix so I take it as reminder and will propose a `lexik_jwt_authentication.on_jwt_not_found` event on the master branch, we should quickly add a release for.

Keep you informed soon.

**Comment by skiner68** [comment]
Hello @chalasr, thanks for your reply!

As far as I remember, I have prepended a valid JWT with some random letters, I think I have used some czech ones ("řčšřčřřž"). But I am not sure at the moment. 
Unfortunately I am out of office today and for the whole next week so I can not make some other tests and provide specific examples. But I will take a look at it when I come back.

Yes, on_jwt_not_found event would be great!

**Comment by chalasr** [comment]
@skiner68 BTW, be sure to use the last stable release (`v1.5.1`) if you make some tests on the `on_jwt_invalid` event, it's a recent addition.

**Comment by chalasr** [comment]
@skiner68 see #188 for the fix

**Comment by skiner68** [comment]
this is great, thank you!

**Comment by chalasr** [comment]
It has been released, you can use by updating your dependency to `v6.0.
You're welcome!
