### ISSUE TITLE
Entity Provider not working by default

### ISSUE THREAD

**Issue by xavierfaucon** [lexik/LexikJWTAuthenticationBundle#212]
Hello,

I am using LewikJwtBundle with Symfony 2.8.*.

I have implemented a custom User Entity (not FOSUserBundle) (following this:
http://symfony.com/doc/current/security/entity_provider.html) with username OR email login. It works correctly without LexikJwtBundle as per the official doc. However with LexikJwt it returned 401 everytime. The solution was to create a custom user provider. It could be worth mentionning in the doc?

Default test which wasn't working:
```
// src/AppBundle/Entity/UserRepository.php
namespace AppBundle\Entity;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;

class UserRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.username = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
```
and

```
# app/config/security.yml
security:
    # ...

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
```

Then afterjust creating a custom user provider in the same fashion as the one FOSUserBundle: (http://symfony.com/doc/current/security/custom_provider.html) it worked properly.

```
<?php


namespace UserBundle\Security\User;

use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;

class EmailUserProvider implements UserProviderInterface
{
    protected $userManager;

    public function __construct($userManager)
    {
        $this->userManager = $userManager;
    }

    public function loadUserByUsername($username)
    {
        $user = $this->userManager->getUserByUsernameOrEmail($username);

        if (!$user) {
            throw new UsernameNotFoundException(sprintf('Username "%s" does not exist.', $username));
        }
        
        return $user;
    }

    public function refreshUser(UserInterface $user)
    {
        if (!$user instanceof User) {
            throw new UnsupportedUserException(
                sprintf('Instances of "%s" are not supported.', get_class($user))
            );
        }

        return $this->loadUserByUsername($user->getUsername());
    }

    public function supportsClass($class)
    {
       return $class === 'UserBundle\Entity\User';
    }
}
```

**Comment by chalasr** [comment]
Hi @xavierfaucon,

Thank you for reporting that!
We'll investigate and, if the bug is confirmed, we'll try to fix it.
If it can't be fixed, then it should indeed be mentioned in in the documentation.

Keep you informed here.

**Comment by yoannfleurydev** [comment]
Hi guys,

I got the same issue as @xavierfaucon today when I implemented the security with users from my database (it was from `in_memory` provider until today). 

Well, I fixed that issue by creating my own User Provider as @xavierfaucon did.

Hope we'll find a solution soon for future users.

**Comment by chalasr** [comment]
Hi,

It was a good surprise to see that this bundle works as expected with this database user loading system.

I created a sample project to let you see it in action and maybe fix the problem in your code by picking the sample's one: [chalasr/lexik-jwt-authentication-sandbox](https://github.com/chalasr/lexik-jwt-authentication-sandbox).
It is a strict implementation of http://symfony.com/doc/current/security/entity_provider.html.

To try it yourself, just follow the README file distributed in the repository.
I close the issue, do not hesitate to ping me for questions or details.

Cheers
