### ISSUE TITLE
login_check 

### ISSUE THREAD

**Issue by foolskill** [lexik/LexikJWTAuthenticationBundle#213]
Hi,
I have install the LexikJWT this morning and i have some problem width my api.

when I run a query on "login_check" I get a 404 error.
I configured my security file as you ask me in the documentation but when I run a "debug: router --show-controllers" I get the road well "login_check" but it does not match with any controller.

Someone could help me please.

PS: sorry for my english i am in france.
![jwt](https://cloud.githubusercontent.com/assets/6184877/17290205/9e52101e-57dd-11e6-9a17-01abeaf8fae7.PNG)

**Comment by chalasr** [comment]
Hi @foolskill,

Opening an issue here means that you may find a bug in this bundle, or want to discuss about introducing a new feature or improving an existing one.

Could you please ask a question on StackOverflow using the [`lexikjwtauthbundle` tag](http://stackoverflow.com/questions/tagged/lexikjwtauthbundle)? Someone will help you for sure, or you could find the answer to your problem in an existing question, as it is a support related issue.

It's not mentioned in the documentation, sorry for that. It will be really soon.

Thank you in advance.

**Comment by foolskill** [comment]
ok thank you
