### ISSUE TITLE
How to get Token expiration date

### ISSUE THREAD

**Issue by ulilicht** [lexik/LexikJWTAuthenticationBundle#22]
Hi, 
I am setting the token expiration time in the config file. 
Is it possible to get the expiry date of a token, for example in an AuthenticationSuccessListener? I would like to attach this information to my token response. 

Thanks for your help, 
Uli

**Comment by hectorprats** [comment]
$jws = JWS::load($data['token']);
$data['expires'] =$jws->getPayload()['exp'];
