### ISSUE TITLE
Symfony 3.1 support

### ISSUE THREAD

**Issue by chriscollinsboxuk** [lexik/LexikJWTAuthenticationBundle#220]
I'm starting a new Symfony project for an API application and I'd love to use this bundle for JWT authentication. However, my Symfony project is currently on v3.1: this bundle only supports 3.0.

I've not looked into what's involved in adding 3.1 support myself - are there plans for this to be done? This bundle looks great, so I may end up downgrading to 3.0 temporarily, but if 3.1 support is imminent I can wait.

**Comment by chalasr** [comment]
Hi @chriscollinsboxuk 

This bundle works well on Symfony 3.1, you can use it right now.
The only thing is that we don't test the bundle on Symfony > 3.0.
To give you an explanation, we are currently working on a 2.0 version which should be released very soon and is especially suited for Symfony 3+, supporting until 2.8+.

You can get in touch when 2.0 comes to be released by watching this repository, this one gives a lots of improvements and some nice new features.

Let me know if this solved your question or directly close this issue.
I hope this bundle fits your needs.

**Comment by chriscollinsboxuk** [comment]
Hi @chalasr 

You're quite right, I made a silly mistake - I was having trouble installing it because I'd forgotten that we mirror our dependencies using Satis and I'd not yet made the dependency available to our mirror. Composer's error messages are sometimes a little vague :)

Thanks for your help.
