### ISSUE TITLE
JWT token not expiring

### ISSUE THREAD

**Issue by kimigxfoxy** [lexik/LexikJWTAuthenticationBundle#234]
Hi its me again, So I was testing the library POST Man RestClient in Chrome navigator but somehow my token was not expiring,here is my parameterrs.yml

*****************************************************************************
    jwt_private_key_path: '%kernel.root_dir%\var\jwt\private.pem'   # ssh private key path
    jwt_public_key_path:  '%kernel.root_dir%\var\jwt\public.pem'    # ssh public key path
    jwt_key_pass_phrase:  'happyapi'                           # ssh key pass phrase if present
    jwt_token_ttl:        10
*****************************************************************************

here is my config.yml

*******************************************************************************
#lexik_jwt_authentication
lexik_jwt_authentication:
     private_key_path: %jwt_private_key_path%
     public_key_path:  %jwt_public_key_path%
     pass_phrase:      %jwt_key_pass_phrase%
     token_ttl:        %jwt_token_ttl%
********************************************************************************
And here is my JwtAuthenticator.php

***********************************************************************************
use Doctrine\ORM\EntityManager;
use Lexik\Bundle\JWTAuthenticationBundle\Encoder\JWTEncoder;
use Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\AuthorizationHeaderTokenExtractor;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Guard\AbstractGuardAuthenticator;

class JwtAuthenticator extends AbstractGuardAuthenticator
{
    private $em;
    private $jwtEncoder;

    public function __construct(EntityManager $em, JWTEncoder  $jwtEncoder)
    {
        $this->em = $em;
        $this->jwtEncoder = $jwtEncoder;
    }

    public function start(Request $request, AuthenticationException $authException = null)
    {
        return new JsonResponse('Auth header required', 401);
    }

    public function getCredentials(Request $request)
    {

        if(!$request->headers->has('Authorization')) {
            return;
        }

        $extractor = new AuthorizationHeaderTokenExtractor(
            'Bearer',
            'Authorization'
        );

        $token = $extractor->extract($request);

        if(!$token) {
            return;
        }

        return $token;
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $data = $this->jwtEncoder->decode($credentials);

        if(!$data){
            return;
        }

        $email = $data['email'];

        $user = $this->em->getRepository('KasualJobsBundle:User')
            ->findOneBy(['email' => $email]);

        if(!$user){
            return;
        }

        return $user;
    }

    public function checkCredentials($credentials, UserInterface $user)
    {

        return true;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        die;
        return new JsonResponse([
            'message' => $exception->getMessage()
        ], 401);
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return;
    }

    public function supportsRememberMe()
    {
        return false;
    }

}
********************************************************************************************

**Comment by chalasr** [comment]
The way you are encoding/decoding tokens (as shown in the link you given in #232) is not the right way. Using the encoder directly means you get rid of all that is done in the `JWTManager`, which is the service that should be used to create and decode a JWT, through the symfony security system (not programmatically from a controller, except for very specific needs where you may only create the token from an existing user).

The `JWTManager` is actually responsible of creating the token using the encoder, passing it a payload containing the `exp` claim used to determine if the token is expired or not, based on the ttl you configured (the encoder itself is not aware of the ttl).

Also I guess this can be the thing that make you unable to decode the token in #232, a token with a payload that doesn't contain an `exp` claim may be rejected (I did not verify by looking deeper into the JOSE library we use for that, but there is good chances). 

I still need to determine if this should be corrected (move the [payload intitialization](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Services/JWTManager.php#L72) logic from the manager to the encoder as it is a public service) or if the encoder should be private and the `JWTManager` the only way to create/decode a token.

For now, please follow the [documentation](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md) for using this bundle (you just need configuration, nothing more). 
You can also take example of how use the jwt manager from #184, but imho it doesn't worth it as we will provide a Guard Authenticator built on top of this bundle in `2.0` (see #184).

**Comment by kimigxfoxy** [comment]
Thanks a lot I tried the configuration way as suggested by you and it worked,the tokens expire, guess the next challenge is to refresh them using gesdinet/JWTRefreshTokenBundle.

**Comment by chalasr** [comment]
You're welcome @kimigxfoxy 

> refresh them using gesdinet/JWTRefreshTokenBundle.

Yes if it fits your needs of course, we suggest it. I hope you will easily be able to use it, it works well from my side. 

Thank you for opening this issue, I'm going to close it as solved, do not hesitate to open a new one in case of problem, we'll be our best to help.

**Comment by m0onspell** [comment]
@chalasr thanks, that fixed the issue for me as well. So I am assuming this guide with custom Authenticator and direct usage of encoder is incorrect if we want our tokens to be expired:
https://kolabdigital.com/lab-time/symfony-json-web-tokens-authentication-guard

**Comment by chalasr** [comment]
@m0onspell  You're welcome. However, as of the 2.0 version of this bundle (current is 2.4 this issue should not occur anymore, the encoder is now responsible for setting claims in the token payload. (see https://github.com/lexik/LexikJWTAuthenticationBundle/pull/249).

> So I am assuming this guide with custom Authenticator and direct usage of encoder is incorrect if we want our tokens to be expired:
https://kolabdigital.com/lab-time/symfony-json-web-tokens-authentication-guard

As of 2.0 it should be correct, but we also switched to providing an extensible authenticator in the same version, so there should be no need for writing your own from scratch.

**Comment by Suhailattatras** [comment]
Maybe at the time of encoding, you are not passing 'exp' key to the array. 

Like this,

$token = $this->get('lexik_jwt_authentication.encoder')
                                ->encode([
                                    'username' => $user->getUsername(),
                                    'exp' => time() + $this->getParameter('jwt_timeout')
                                ]);
