### ISSUE TITLE
Is there a way to know if token is expired

### ISSUE THREAD

**Issue by kimigxfoxy** [lexik/LexikJWTAuthenticationBundle#235]
Hello, its me again, i was wondering if there is a method that I can call from a controller to know if a token has expired so that I can refresh it.

**Comment by chalasr** [comment]
Refresh a JWT token programmatically is not a good idea, it needs to be done via a reel refresh system based on refresh tokens transmitted in the same time as the original token. Then you can use this second token to get a new one when the original expires. This is what JWTRefreshTokenBundle does, and it does it well :)

To give you a simple example where do this would be a security hole, let's say an user login for the first time to your application, and you have a controller action that renew a token every time the given one is expired. If an user comex back on your api two years later with its very first token, it will just work. We can't provide this kind of features or whatever solutions to come to this behavior without introducing bad practices and usages. Let's use JWT as JWT, namely a self-auto-invalidated token.

I hope you can understand this and find what you need in the mentioned bundle

**Comment by chalasr** [comment]
For support questions, please use our [`lexikjwtauthbundle` tag on stackoverflow](http://stackoverflow.com/questions/tagged/lexikjwtauthbundle). 

Thank you
