### ISSUE TITLE
Flexibility to use other secret tokens instead of private key

### ISSUE THREAD

**Issue by joostfarla** [lexik/LexikJWTAuthenticationBundle#24]
First of all, thanx for the awesome bundle! One thing I noticed is that tokens can only be signed by using a private key statically stored in a file. I think it would be nice to make this more flexible and allow other types of "secret tokens" to be passed to the encoder. 

When using JWT authentication for an API-driven CMS, it would be nice to gain some more control on the generation and invalidation of tokens, on a per-user level. If I want some user's token to become invalid (and force the user to login again) for some reason, I could simply regenerate its "secret token", if it was stored in the database.

This could be solved simply by creating an interface for the encoder and make the encoder configurable.

Please let me know your thoughts on this subject. If you have some other ways of handling this, that's fine also. If you agree with my feedback, I would be happy to contribute. :)

**Comment by ypereirareis** [comment]
HI @andreaslarssen !

Do you have an example on how to implement the standard Symfony2 API keys authentication alongside this bundle ?

Thanks

**Comment by andreaslarssen** [comment]
Hi @ypereirareis.

I haven't got the time right now, but give me a week or three, and I'll do a write up.

**Comment by ypereirareis** [comment]
Oh ok thanks but it will be too late... not important ! :smile:
