### ISSUE TITLE
[DX] Better apache authorization header "bug" handling

### ISSUE THREAD

**Issue by slashfan** [lexik/LexikJWTAuthenticationBundle#25]
As mentionned by @arendjantetteroo in a precedent issue https://github.com/lexik/LexikJWTAuthenticationBundle/issues/23, Apache server will strip any `Authorization header` not in a valid HTTP BASIC AUTH format, causing the bundle to be useless in "header mode".

To work around the problem, 3 main approches exists :
- [ ] Add rewrite rules to the VirtualHost ([description here](http://stackoverflow.com/questions/11990388/request-headers-bag-is-missing-authorization-header-in-symfony-2/17175260#17175260)) : simple but needs server side intervention
- [ ] Use the `apache_request_headers` php function to retrieve the original header ([description here](http://stackoverflow.com/questions/11990388/request-headers-bag-is-missing-authorization-header-in-symfony-2/14656291#14656291))
  - [ ] Inside a listener on the kernel.request event : fix the header bag but will be called on each request
  - [ ] Inside the [AuthorizationHeaderTokenExtractor](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/TokenExtractor/AuthorizationHeaderTokenExtractor.php)

For now I have documented the first solution, but it might not be the most DX-friendly. Adding the logic to extract the original header inside the AuthorizationHeaderTokenExtractor might be simpler for newcomers. 

Does anybody have an opinion on this one ? Thanks !

**Comment by RoxKilly** [comment]
Another, even easier solution in many cases is to simply add `CGIPassAuth on` to .htaccess.  See [Apache docs](https://httpd.apache.org/docs/2.4/en/mod/core.html#cgipassauth) and [StackOverflow](http://stackoverflow.com/questions/26549250/apache-strips-down-authorization-header/33809524#33809524).  Worked for me, although I'm not using this bundle so your mileage may vary
