### ISSUE TITLE
how do you deploy to Heroku?

### ISSUE THREAD

**Issue by tartarsaucemedia** [lexik/LexikJWTAuthenticationBundle#253]
I cannot seem to figure out how to configure the private/public key paths in Heroku. Can anyone please point me into the right direction? 😄

**Comment by chalasr** [comment]
Hi @tartarsaucemedia,

Your public/privates keys should have been generated in your projects, you should include them in your heroku deployment just like you would do locally (except if locally, you generate the keys outside of your project).

**Comment by tartarsaucemedia** [comment]
That was the problem! Heroku could not read them outside of the project, so I moved them inside the config folder and it works!
