### ISSUE TITLE
Response for preflight has invalid HTTP status code 401

### ISSUE THREAD

**Issue by luniiix** [lexik/LexikJWTAuthenticationBundle#266]
Hello,

I try to send my token but i can't modify my header, i work on it from yesterday. Can u help me please ?

![1](https://cloud.githubusercontent.com/assets/6369410/19998739/d1e50b12-a26e-11e6-8084-97936a546ffb.png)
![2](https://cloud.githubusercontent.com/assets/6369410/19998740/d41e87dc-a26e-11e6-93d8-fef4658f5d65.png)
![3](https://cloud.githubusercontent.com/assets/6369410/19998741/d904c0a4-a26e-11e6-8b66-a1e7bdbbad46.png)
![4](https://cloud.githubusercontent.com/assets/6369410/19998772/00e2e948-a26f-11e6-89aa-197a18557b82.png)

And i modify my htpd-vhosts.conf to allow authorization but i dont understand. )=

Sorry for the incovenance...

**Comment by chalasr** [comment]
Hi @luniiix , sorry for the long delay.

I think your issue come from your web server and it will be hard to help you as you seem to be aware of the common issue about the `Authorization` header not properly transmitted when using apache. 

Could you paste your `vhost` here? I can't guarantee anything but I can try to see if something is wrong, at least.

**Comment by sirjcbg1** [comment]
Hi @chalasr, I have the same issue, this is my vhost

DocumentRoot /var/www/html/backend/web
    <Directory /var/www/html/backend/web>
        AllowOverride None
        Order Allow,Deny
        Allow from All

        <IfModule mod_rewrite.c>
            Options -MultiViews
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{HTTP:Authorization} ^(.*)
            RewriteRule ^(.*)$ app_dev.php [QSA,L] .* - [e=HTTP_AUTHORIZATION:%$
        </IfModule>
    </Directory>

Regards,

**Comment by chalasr** [comment]
Hi @sirjcbg1 

I'm really sorry about that but unfortunately I can't see any issue in the vhost you given, it's pretty sure that the problem comes from your webserver, an httaccess overidding this config, `mod_rewrite` not enabled (you should really check that) and so on. 

A quick alternative is to use a different name for your header, it can be achieved using the bundle configuration. For example, if you want to send a `JWT` header with `Bearer` prefix, use the following:

```yaml
# app/config/config.yml
#....
lexik_jwt_authentication:
    # ...
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    JWT
 ```

Hope this solution can work for you.
/cc @luniiix

**Comment by sirjcbg1** [comment]
Thanks @chalasr  for answer soon,

 1. I tried using JWT as prefix and not working.

 2. this is part of my .httaccess and can see the mod_rewrite is on!.

RewriteEngine On

    # Determine the RewriteBase automatically and set it as environment variabl$
    # If you are using Apache aliases to do mass virtual hosting or installed t$
    # project in a subdirectory, the base path will be prepended to allow proper
    # resolution of the app.php file and to redirect to the correct URI. It will
    # work in environments without path prefix as well, providing a safe, one-s$
    # fits all solution. But as you do not need it in this case, you can comment
    # the following 2 lines to eliminate the overhead.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

    # Sets the HTTP_AUTHORIZATION header removed by Apache
    RewriteCond %{HTTP:Authorization} .
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

and this is my config.yml 

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%
    
    
    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  Bearer
            name:    JWT
        cookie:                    # check token in a cookie
            enabled: false
            name:    BEARER
        query_parameter:           # check token in query string parameter
            enabled: true
            name:    bearer

my security.yml is 

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        
        app_users:
            ldap:
                service: ldap
                base_dn: OU=##
                search_dn: CN=##
                search_password: ##
                filter: "(&(msExchUserAccountControl=0)(name={username}))"
                default_roles: ROLE_USER
                
        my_chain_provider:
            chain:
                providers:  [ app_users ]       
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            provider: app_users
            form_login_ldap:
                service: ldap
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                dn_string: '{username}@bancoexcorp'

        api: 
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                throw_exceptions:        false     # When an authentication failure occurs, return a 401 response immediately
                create_entry_point:      true      # When no authentication details are provided, create a default entry point that returns a 401 response
                authentication_provider: lexik_jwt_authentication.security.authentication.provider

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

I'm trying with a pluggin DHC by Restlet of Google Chrone and i get the token  fine, but i send the token and I get from server code": 401, "message": "Bad credentials".

These are the parameters of the request:

Host: mivirtualhost
JWT: Bearer JhbGciOiJSUzI1NiJ9.eyJ1c2VybmF...... (My Token)
Content-Type: application/x-www-form-urlencoded
Content-Length: 0

**Comment by sirjcbg1** [comment]
In my dev.log, i can see

An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /var/www/html/backend/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:53

**Comment by chalasr** [comment]
@sirjcbg1 Which version of this bundle are you using?

**Comment by sirjcbg1** [comment]
name": "lexik/jwt-authentication-bundle",
        "version": "v2.0.2",
        "version_normalized": "2.0.2.0",

**Comment by chalasr** [comment]
could you run the `lexik:jwt:check-config` command and confirm me it succeeds?

**Comment by sirjcbg1** [comment]
jblanco@A000695972-L:/var/www/html/backend$ php bin/console lexik:jwt:check-config
The configuration seems correct.

**Comment by sirjcbg1** [comment]
The token is not being saved, so it is not comparing it with the one that I then send

**Comment by sirjcbg1** [comment]
I have to go, but I will return. please help @chalasr

**Comment by chalasr** [comment]
> The token is not being saved, so it is not comparing it with the one that I then send

I think the issue come from the fact you're using ldap. I'll look deeper at it tomorrow and keep you informed here.

**Comment by sirjcbg1** [comment]
Hi  @chalasr,
          
         Can you see something?

**Comment by chalasr** [comment]
Hi @sirjcbg1, sorry for the delay.

I'm sorry but I will need to do some live debugging with you, since I don't have any ldap server at hand.

Could you please set the `throw_exceptions` option to `true` in your `api` firewall and retry? I would like to get more in the trace, in order to know which exception has been thrown by the bundle and which message it contains.

**Comment by sirjcbg1** [comment]
thanks for your answer,

I did a test with providers in memory, and also get 401 bad credentials, 

POST /sandbox/web/app_dev.php/home HTTP/1.1
Host: localhost
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.e .......
Content-Type: application/x-www-form-urlencoded
Content-Length: 0

this is my security.yml 

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: password, roles: [ 'ROLE_USER' ] }
                    admin: { password: password, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/api/(_(profiler|wdt|doc))/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/home
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }


I'm going to prove what you told me, enable throw_exceptions

**Comment by sirjcbg1** [comment]
Am I sending the token correctly?

**Comment by chalasr** [comment]
> I'm going to prove what you told me, enable throw_exceptions

It's not worth it, I think your issue is about how you send the token. 
Do you still get the same error message with the last configuration you pasted (`form_login` and `in_memory` users)?

Anyway, could you please try through your cli using cURL:

```
curl -H "Authorization: Bearer TOKENHERE" 127.0.0.1:8000/home
```

Replacing `TOKENHERE` by the token and `127.0.0.1:8000` by your hostname?

**Comment by sirjcbg1** [comment]
If you also provide it a moment ago, I will download your sanbbox to prove it

**Comment by sirjcbg1** [comment]
if  also provide it a moment ago, I will download your sanbbox to prove it

**Comment by chalasr** [comment]
@sirjcbg1 There's nothing to proof since there's no bug to fix here. I'm just trying to help you understanding what you're doing wrong. Please consider trying to run the curl command I given you in https://github.com/lexik/LexikJWTAuthenticationBundle/issues/266#issuecomment-263374770

**Comment by sirjcbg1** [comment]
I run the command curl and get the same issue "401 bad credentials"

**Comment by chalasr** [comment]
Well, sorry but I don't know what to say. 
You should try to clone https://github.com/chalasr/lexik-jwt-authentication-sandbox , follow the README and if it doesn't work for you, the issue comes from either the way you're sending the token or your webserver.

**Comment by sirjcbg1** [comment]
Hi @chalasr,
Finally worked with parameter query parameter, using an LDAP provider, there should definitely be some configuration in apache and the headers

thanks

**Comment by chalasr** [comment]
@sirjcbg1 Glad to read that. Indeed, I would be curious to see what `$_SERVER` returns from your side using the buggy configuration.
