### ISSUE TITLE
Document how to manually generate a token for a given User

### ISSUE THREAD

**Issue by chalasr** [lexik/LexikJWTAuthenticationBundle#273]
As pointed out in [this stackoverflow question](http://stackoverflow.com/questions/29764275/symfony-2-manual-login-and-json-web-token/34320849), it may be helpful in some cases to generate a token programatically. As simple as:

```php
$this->container->get('lexik_jwt_authentication.jwt_manager')->create($user);
```

**Comment by scaytrase** [comment]
Also either unmark the `JWTAuthenticationSuccessResponse` as internal or document a way how to refresh the token using the token only (by hitting DB here now). 

Currently I've end up with

```
/**
 * @Route("/api/auth")
 */
final class AuthController extends Controller
{
    /**
     * @Route("/refresh", name="api_refresh_token")
     * @Security("is_granted('IS_AUTHENTICATED_FULLY')")
     */
    public function refreshAction()
    {
        $user = $this->getUser();

        $jwt      = $this->get('lexik_jwt_authentication.jwt_manager')->create($user);
        $response = new JWTAuthenticationSuccessResponse($jwt);

        $event = new AuthenticationSuccessEvent(['token' => $jwt], $user, $response);
        $this->get('event_dispatcher')->dispatch(Events::AUTHENTICATION_SUCCESS, $event);
        $response->setData($event->getData());

        return $response;
    }
}
```

Which looks weirds as it mostly a copy-paste, so I think it could be improved

**Comment by chalasr** [comment]
@scaytrase Thanks for your feedback , I fully agree. I'll look at making the copy-pasted part reusable

**Comment by DhiaDjobbi** [comment]
If u are inside a a Service or Event Subscriber you can do :
```
use Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface;

    private $jwtManager;

    public function __construct(JWTTokenManagerInterface $jwtManager)
    {
        $this->jwtManager = $jwtManager;
    }
```

and then inside ur function use 
`$token=$this->jwtManager->create($user);`
