### ISSUE TITLE
Can't manage to trigger AuthenticationSuccessListener

### ISSUE THREAD

**Issue by hiromik** [lexik/LexikJWTAuthenticationBundle#274]
Hi, using Symfony 2.8 with MongoDB I can't manage to trigger the listener, the response always stays the same (the token) when I do a POST through /login.

![jwt2](https://cloud.githubusercontent.com/assets/9575928/20457943/7570bf04-ae97-11e6-8a99-1c118837c313.PNG)
![jwt1](https://cloud.githubusercontent.com/assets/9575928/20457944/75708ea8-ae97-11e6-921b-8e0983b53925.PNG)
![jwt3](https://cloud.githubusercontent.com/assets/9575928/20457954/b3125e26-ae97-11e6-880f-9e8a4eca6c19.PNG)

The die() doesn't work.

Thanks for your help.

**Comment by hiromik** [comment]
After hours of research... I finally found the problem, it was missing an UserInterface in the AuthenticationSucessListener (which is highlighted in the screen), the worst part of it is... it kept sending the  token like no problem and there wasn't any error message about it !
![jwt](https://cloud.githubusercontent.com/assets/9575928/20459504/f2137a02-aec3-11e6-80eb-8de34039cde6.PNG)

**Comment by chalasr** [comment]
> it kept sending the token like no problem and there wasn't any error message about it !

Yeah, since you're calling `return` in your listener, the event lifecycle just continue and our `AuthenticationSuccessHandler` returns the original response containing the original data, as it is already set before your listener intercept the event.

Unfortunately, event listeners might be painful to debug...

**Comment by hiromik** [comment]
Yeah, thanks to your sandbox and the listener in it I managed to find the problem =)
