### ISSUE TITLE
Path validation does not work with StreamWrappers

### ISSUE THREAD

**Issue by cevou** [lexik/LexikJWTAuthenticationBundle#284]
Since version 2 there is a check n the configuration if the paths for private and public key are valid. This is a good thing, because you can show an error message to the user already while the container is being compiled. However, it doesn't work if you use stream wrappers. I use a stream wrapper (AWS S3) in my production environment, so that all nodes can access the same key pair. These wrappers are only initialized after the container is compiled. Because of that the check in the configuration fails and I cannot clean and warmup the cache during composer install in my production environment.
Is there a way to fix this?

Best,
Chris

**Comment by chalasr** [comment]
Hi @cevou,

It's indeed a common use case that I didn't think about when adding this validation. Right now the only way to fix it I see is to remove this validation from the configuration, and do it on login as in 1.x. I'll quickly make a fix and keep you informed here, a patch release will be drafted after merging it. 

Thank you for reporting this bug

**Comment by chalasr** [comment]
@cevou The validation has been removed in #285 you can upgrade the bundle to v2.0.3 in order to get the fix

**Comment by cevou** [comment]
Thanks for the quick fix!
