### ISSUE TITLE
Checking if a user is registred with his token

### ISSUE THREAD

**Issue by AienTech** [lexik/LexikJWTAuthenticationBundle#288]
Hi,
sorry that I'm posting this question here (as an issue), I've post it some time ago in stackoverflow but no one did answer.

I just wanted to check the token and see if the user on it is registered and if true, then return the user, else I would liked to return a 403 error.

but I'm using this code for now as a workaround, its working good but will not return the error code I wanted, instead, it redirects to login route

```
$user = $this->container->get('sonata.user.user_manager')->findUserByUsernameOrEmail(
            $this->container->get('lexik_jwt_authentication.jwt_token_authenticator')->getCredentials($request)->getPayload()['username']
        );

        if ($user)
        {
            return $user;
        } else {
            return null;
        }
```

tnx again for you help.

**Comment by scaytrase** [comment]
The general way for symfony is to check `is_granted('IS_AUTHENTICATED_FULLY')`

**Comment by AienTech** [comment]
@scaytrase Thanks for the answer, but its not what I wanted. I mean I need to decode the Payload and extract the username, then check if this username exists.

if true then it will return the user object. else it should throw a 403 (or 401) error, without redirecting to login page. similar question have been asked in #122 but the solution is not working for me

**Comment by scaytrase** [comment]
You should not do this manually for sure. If you have configured firewall with `access_control` section (which triggers firewall) then you will should have this functionality by default. Looks like that you have some kind of firewall misconfiguration, as redirection is performed with `form_login` only (or custom authenticators). You can post more of your config (i.e firewall and access_control) so we can help you

**Comment by chalasr** [comment]
@AienTech Hi, sorry for being late.
@scaytrase is right. You should take a look at the README, this bundle provides an authentication mechanism that makes use of the symfony security system. You have to configure the guard authenticator on your firewall to do things right, not fetching it from the container for authenticating users manually. Like that you're sure to don't create security issues in your app.

I should have made the authenticator service private to avoid such usages, it may well be deprecated in the next minor release and no longer possible in the next major. 

If you face issues at following the README, please follow this advice:
> You can post more of your config (i.e firewall and access_control) so we can help you

If you're good, please close this :)

@scaytrase Thanks a lot for helping

**Comment by AienTech** [comment]
dear @scaytrase and @chalasr thanks for your helps. just to make sure, I'll send my security configs. maybe there is something that I didn't see.

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    acl:
        connection: default

    access_decision_manager:
        strategy: affirmative

    role_hierarchy:
        ROLE_SALES_NOTIFICATIONS: [ ROLE_SALES_NOTIFICATIONS ]
        # FULL CONTROL
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
                success_handler: admin_success_handler
            logout:
                path:           /admin/logout
            anonymous:          true

        # Custom firewall for api area
        api_login:
            pattern:  ^/api/user
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path:               /api/user/check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api/
            methods: [ POST, PUT ]
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        api_doc:
            pattern: ^/api/doc
            stateless: true
            anonymous: true
        # -> end custom configuration

        # default login area for standard users

        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:
            pattern:             .*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     /login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true

    access_control:
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/assets/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/uploads/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/user/, role: [ROLE_USER] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY, methods: [POST, PUT] }
        - { path: ^/api/user, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/efconnect, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/elfinder, role: IS_AUTHENTICATED_FULLY }
```

the thing is, I've secured all of my `POST` and `PUT` methods, and not all of `GET` methods are secured, since they can be accessed publicly, but there are some other `GET` methods which needs the user to be logged in. as an example,
`GET /api/blog/posts` will return the blog posts as expected, it doesn't need and security but
`GET /api/user/profile'` must be protected and must return the users profile with token.

I'm thinking that maybe I'm misusing the api...

**Comment by scaytrase** [comment]
> `-  { path: ^/api/user, roles: IS_AUTHENTICATED_ANONYMOUSLY }`

Could this be an issue? You have the WHOLE path /api/user/ being accessed anonymously, not only `/api/user/check` here

try something like `^/api/user/check$

**Comment by chalasr** [comment]
@AienTech What's the status of this issue?

**Comment by AienTech** [comment]
@chalasr I'll check very soon

**Comment by chalasr** [comment]
I'm closing here due to the lack of feedback, feel free to reopen.
