### ISSUE TITLE
Persist token in database

### ISSUE THREAD

**Issue by crash21** [lexik/LexikJWTAuthenticationBundle#289]
Hello,

Currently if you have ttl 3600 and go to login_check you will get  token valid for 1 hour. If you go again to login_check you will get another key valid for 1 hour. Every time you do it one more key will be valid for 1 hour. But I would prefer only 1 key be valid (the last one created).

How to do this easily? I am thinking of just persisting key in db and check login against it.

Is this good approach? What exactly need to override?

Thanks a lot!

**Comment by carlcraig** [comment]
The default setup is completely stateless, and tokens cannot be `revoked` without some custom validation. In the documentation there is an example on how to lock a JWT to the IP address which created it. https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md

---

You could potentially do the following:

Add a `datetime` field called `tokenLastIssued` to your user entity.

Create a [`onJWTCreated`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsjwt_created---adding-data-to-the-jwt-payload) listener, which updates your users `tokenLastIssued` to **now**. Set a custom property on the JWT payload of `tokenLastIssued` to match your users new `tokenLastIssued` value.

Create a [`onJWTDecoded`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsjwt_decoded---validating-data-in-the-jwt-payload) listener to verify the `tokenLastIssued` value in decoded JWT matches your users `tokenLastIssued` value.

Essentially, every time a new token is created, the `tokenLastIssued` will be updated and all previous tokens will become invalid.

**Comment by crash21** [comment]
Excellent something like that was expecting! Thanks a lot!!!!!

**Comment by chalasr** [comment]
Hi @crash21, Thank you for opening this issue.
@carlcraig Thanks a lot for helping , that's how a great community works. 

Closing this issue as solved!
