### ISSUE TITLE
401 bad credentials on frontend

### ISSUE THREAD

**Issue by leevanhe** [lexik/LexikJWTAuthenticationBundle#291]
I am making a app with back- and frontend, for my frontend i use ionic 2, for the back symfony 3.2.
When i try to login in the front i get following error.

"EXCEPTION: Response with status: 401 Unauthorized for URL: http://pomodoro.local/api/login_check"

but when i try the curl command in the CLI in the symfony part i see my token so that works.

![schermafbeelding 2016-12-20 om 20 01 52](https://cloud.githubusercontent.com/assets/14766149/21363985/3589fb4c-c6ef-11e6-8299-8e53ecd864c1.png)

this is my: security.yml

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header: # check token in Authorization Header
                    enabled: true
                    prefix:  Bearer
                query_parameter:      # check token in query string parameter
                    enabled: true
                    name:    bearer
                throw_exceptions:        false     # When an authentication failure occurs, return a 401 response immediately
                create_entry_point:      true      # When no authentication details are provided, create a default entry point that returns a 401 response
                authentication_provider: lexik_jwt_authentication.security.authentication.provider

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/api/doc             , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login           , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login_check     , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/v1              , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$              , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register            , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting           , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin               , roles: ROLE_ADMIN }

and my auth.service for the front:

    constructor(private http: Http) {
        // set token if saved in local storage
        var currentUser = JSON.parse(localStorage.getItem('currentUser'));
        this.token = currentUser && currentUser.token;
    }

    login(username: string, password: string): Observable<boolean> {
        return this.http.post('http://pomodoro.local/api/login_check', JSON.stringify({ username: username, password: password }))
            .map((response: Response) => {

                // login successful if there's a jwt token in the response
                let token = response.json() && response.json().token;
                if (token) {
                    // set token property
                    this.token = token;

                    // store username and jwt token in local storage to keep user logged in between page refreshes
                    localStorage.setItem('currentUser', JSON.stringify({ username: username, token: token }));

                    // return true to indicate successful login
                    return true;
                } else {
                    // return false to indicate failed login
                    return false;
                }
            });
    }

    logout(): void {
        // clear token remove user from local storage to log user out
        this.token = null;
        localStorage.removeItem('currentUser');
    }

**Comment by chalasr** [comment]
Hi,

Since you are correctly getting the token when running the request through cURL, there's nothing to fix here. I would look at the request headers from the symfony side, I fear you'll not find the authorization header and that the issue is just about sending it properly from your frontend service.

I suggest you to open a question on stackoverflow (see the support section of our readme) without tagging this bundle, only asking how to deal with authorization headers using the your frontend language.

I'm closing this issue
