### ISSUE TITLE
LoggedIn Action in Controller

### ISSUE THREAD

**Issue by Aylarius** [lexik/LexikJWTAuthenticationBundle#293]
Hi!
I'm using this bundle with Symfony 2.8 and Angular 1.5. I created different actions in my UserController (login, register, getall, getone, edit, delete) but I need to create a LoggedIn action to check if the user is logged and if the token is a valid one. This action will be called on client-side through the URL : api/loggedin.
All the solutions I found online were through eventlisteners, which is not helpful to me.

Do you have any idea how this could be done?

Thanks in advance!

**Comment by chalasr** [comment]
Hi @Aylarius,

We use github issues for bug reports and feature requests, all support questions should be asked on  [stackoverflow](https://github.com/lexik/LexikJWTAuthenticationBundle#support) (please consider it for your next needs).

If I understand correctly, what you are trying to achieve is quite simple. 
- Create the route sort as it is covered by your jwt-protected firewall (for a firewall covering `^/api`, `/api/loggedin` will automatically require JWT authentication).
- Create the corresponding controller action:
  ```php
  use Symfony\Component\HttpFoundation\Response;

  public function loggedInAction()
  {
      return new Response();
  }
  ```

Like this when hitting `/api/loggedin` from your angular app, if you are passing a valid token (thus the user is correctly logged in), the response status code will be `200`. If the token is invalid (thus the user is not logged in), the status code will be `401`. 

Just check the value of the status code and you're good :)

**Comment by Aylarius** [comment]
It works perfectly!!
Thanks a lot for your fast reply and sorry I didn't know!
