### ISSUE TITLE
JWT Token not found

### ISSUE THREAD

**Issue by Adraesh** [lexik/LexikJWTAuthenticationBundle#300]
Hi,

As the title says I have a 401 when trying to contact my API. I can get the token of User without any problem but when I try to use it it's not working properly.

I am using SF 2.8 + lexik/jwt-authentication-bundle v2.1.0.

Thank you in advance.

My VHOST includes:

RewriteEngine On
            RewriteCond %{HTTP:Authorization} ^(.*)
            RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

The curl command line:

curl -H "Authorization: Bearer my_token" http://localhost/api/user/some-user-request

Config:

lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization

Security:
login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/(api)(?!/doc)
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

Thank you in advance.

**Comment by Adraesh** [comment]
Just a quick note, I tested by enabling the token through parameter and it's working.

**Comment by spike31** [comment]
Hi, I think you can found an answer to that common error on search on the issues or stackoverflow :)

**Comment by Adraesh** [comment]
Hello

Sorry I totally forgot to come back to close the issue, and yes I found the answer through google etc ...

Thanks !

**Comment by sergiosanabria** [comment]
I have the same problem. What was the answer?

**Comment by RecanN** [comment]
@Adraesh Can you share with us the solution

**Comment by Adraesh** [comment]
Well it's been a long time but still I can share with you some config which is actually working:

Vhost:
```
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Methods "OPTIONS, GET, PUT, POST, DELETE, PATCH"
```

web/.htaccess must includes (newer SF version include it by default):
```
RewriteCond %{HTTP:Authorization} .
RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

config.yml
```
# LexikJWTAuthenticationBundle
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
    #user_identity_field: [username, email]
    token_extractors:
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
```

security.yml (Adapt your patterns based on your needs. In my case the api is not under mydomain.com/api but directly callable from mydomain.com):
```
login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path:               /login_check
                success_handler:       lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

api:
            pattern:   ^(?!.*(\/test|\/security\/login))
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```

Hope it helps.

**Comment by blaszku** [comment]
I faced the same issue, so you should check if it is not due to redirection, because by default Alamofire doesn't pass authorization field in header to another request ( this seems to be reasonable behavior in such case).

So to make authorization transmissible you can do it like:

```swift
Alamofire.SessionManager.default.delegate.taskWillPerformHTTPRedirection = { session, task, response, request in
    var redirectedRequest = request
    
    if let originalRequest = task.originalRequest,
        let headers = originalRequest.allHTTPHeaderFields,
        let authorizationHeaderValue = headers["Authorization"]
    {
        var mutableRequest = request
        mutableRequest.setValue(authorizationHeaderValue, forHTTPHeaderField: "Authorization")
        redirectedRequest = mutableRequest
    }
    
    return redirectedRequest
}

//now use your requests  i.e:
Alamofire.request(url, method: .post, parameters: params, encoding: JSONEncoding.default, headers: header)
    .validate()
    .responseJSON(completionHandler: { (response) in
        switch response.result {
        case .success:
            //success
            break
        case .failure(let error):
            //fail
            break
        }
    })
```

If you want to return to default behavior just simply:
```swift
Alamofire.SessionManager.default.delegate.taskWillPerformHTTPRedirection = nil
```
