### ISSUE TITLE
Access public key string programmaticaly

### ISSUE THREAD

**Issue by scaytrase** [lexik/LexikJWTAuthenticationBundle#305]
In order to build extensible communications I want to publish my public key from signing key-pair as a separate controller file.

If I try to use the following code

```php
    public function pubkeyAction()
    {
        $key = $this->get('lexik_jwt_authentication.key_loader')->loadKey('public');
        dump($key);

        return new Response(
            stream_get_contents($key),
            200,
            ['Content-Type' => 'text/plain']
        );
    }
```

it shows me 

```
Warning: stream_get_contents(): supplied resource is not a valid stream resource
```

Is there any convenient way to export public key without knowing the nature of underlying library that reads the key from the filesystem?

I have an option to manually fetch the key from the container parameters, but I think this is not a good choice

**Comment by chalasr** [comment]
Sounds legit to me. 
What do you think about adding an interface like e.g. `KeyReaderInterface::readKey()` and make the existing key loaders implement it? 
Would you mind submit a PR?

**Comment by scaytrase** [comment]
Interface idea looks OK, maybe `KeyDumper` ? `current Loader` actually `Read`s keys already
not sure if I'm fully familiar with openssl and other libs to implement it properly

**Comment by chalasr** [comment]
No problem, I'll do.

>  maybe KeyDumper ?

👍
