### ISSUE TITLE
Sign with HMAC algo is keypair bound

### ISSUE THREAD

**Issue by Algatux** [lexik/LexikJWTAuthenticationBundle#307]
I'm using the bundle with lcobucci provider, his library offers an HMAC sign feature using only a secret, the bundle instead seems to not support it requiring a private/public certificate.

in \Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\LcobucciJWSProvider::create:66
```
new Key($this->keyLoader->loadKey('private'), $this->keyLoader->getPassphrase());

// can be too

new Key('secret')
```

and in \Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\LcobucciJWSProvider:91
```
$jws->verify($this->signer, $this->keyLoader->loadKey('public')) && $jws->validate(new ValidationData());

// can be too

$jws->verify($this->signer, '--> secret <--') && $jws->validate(new ValidationData());
```

do you plan to support it ? I can try to prepare a pr if it's ok for you

**Comment by chalasr** [comment]
The support for different algorithms with different JOSE libraries is indeed something that needs to be enhanced. I would be pleased to see a PR, especially for the lcobucci provider which could very well become our default one in the next major. I'm ready to help this way if needed.

**Comment by MisterGlass** [comment]
Any word on this? I wanted to try switching from RS256 to HS256 & see if there was a big speed difference, but I can't get HS256 working. I changed the signature_algorithm & made sure I had a passphrase set, but I keep getting errors that my JWT is invalid.

**Comment by chalasr** [comment]
This will be truly supported soon.

**Comment by JarJak** [comment]
Any news on supporting HS256?

**Comment by chalasr** [comment]
In progress in #369
