### ISSUE TITLE
Unable to find the controller for path /v1/login_check

### ISSUE THREAD

**Issue by adetwiler** [lexik/LexikJWTAuthenticationBundle#31]
Hello!

I was following the security.yml in the sandbox application and this bundle. However, I cannot seem to get past this firewall issue.

Symfony version: 2.5.5

security.yml

```
security:
    encoders:
        Acme\UserBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        acme_userbundle:
            id: acme_user.provider

    firewalls:

        login:
            pattern:  ^/v1/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /v1/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/v1
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1, roles: IS_AUTHENTICATED_FULLY }
```

app/routing.yml

```
acme_api:
    resource: "@AcmeAPIBundle/Resources/config/routing.yml"
    prefix:   /v1
```

src/AcmeAPIBundle/Resources/config/routing.yml

```
login_check:
    path: /login_check

acme_api_v1:
    type:     rest
    resource: "Acme\APIBundle\Controller\UserController"
    defaults: {_format: json}
    prefix:   /
```

Thanks!

**Comment by johnpancoast** [comment]
@adetwiler what was the solution? I have similar configuration with a similar error.

**Comment by adetwiler** [comment]
@johnpancoast I can't remember specifically, but here is my new config that works. I separated the routes to where /api is accessible to anyone and use /sapi for authenticated api requests.

`      
 
        api:
            pattern:   ^/api
            stateless: true
            anonymous: true

        sapi:
            pattern:   ^/sapi
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                throw_exceptions:        false
                create_entry_point:      true
                authentication_provider: lexik_jwt_authentication.security.authentication.provider

        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true

    access_control:
        - { path: ^/api/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sapi,         roles: IS_AUTHENTICATED_FULLY }`

**Comment by johnpancoast** [comment]
I actually found my problem which was just a misconfiguration of the login route. Thanks, @adetwiler.

**Comment by EvKoh** [comment]
Try to change order of your firewalls, example :
1 - dev
2 - login
3 - api
4 - main
