### ISSUE TITLE
Question: Encrypting contents of the JWT

### ISSUE THREAD

**Issue by schodemeiss** [lexik/LexikJWTAuthenticationBundle#329]
Hello,

My system requires the use of a users email fairly frequently, and I'd like to include that in the JWT if I can so I don't have to hydrate my user from my DB on every request to my API, but I'm aware that anyone that could get hold of this token, could then see another users email address or other sensitive information in the token.

**Is there a way to encrypt the contents of the token?** I hear JWE is a thing, but I don't know if this bundle provides something like this out of the box?

From here: https://stormpath.com/blog/jwt-the-right-way#how-to-secure-jwt

> Do not contain any sensitive data in a JWT. These tokens are usually signed to protect against manipulation (not encrypted) so the data in the claims can be easily decoded and read. For example, you wouldn’t want to include a user’s address in a JWT; you would want to store a link to the user’s record or another identifier that is opaque and have your application look up the information. If you do need to store sensitive information in a JWT, check out JSON Web Encryption (JWE).

Thanks in advance for the help!

**Comment by chalasr** [comment]
Hi @schodemeiss,

This bundle doesn't provide encryption out of the box due to the fact we depend on JOSE libraries which do not provide it. I suggest you to have a look at https://github.com/Spomky-Labs/lexik-jose-bridge which provides encryption support for this bundle through a custom encoder service.

Let me know if it helps.

**Comment by Spomky** [comment]
Hi @schodemeiss, 

I will be happy to help you to use the https://github.com/Spomky-Labs/lexik-jose-bridge

Feel free to contact me if you need help or information.

**Comment by schodemeiss** [comment]
Perfect, thank-you!
