### ISSUE TITLE
Unable to verify the given JWT through the given configuration.

### ISSUE THREAD

**Issue by Webonaute** [lexik/LexikJWTAuthenticationBundle#331]
since I updated to symfony3 I have this error message :
Unable to verify the given JWT through the given configuration. If the "lexik_jwt_authentication.encoder" encryption options have been changed since your last authentication, please renew the token. If the problem persists, verify that the configured keys/passphrase are valid.

My config :

```
lexik_jwt_authentication:
    private_key_path: "%kernel.root_dir%/config/jwt/private.pem"   # ssh private key path
    public_key_path:  "%kernel.root_dir%/config/jwt/public.pem"    # ssh public key path
    pass_phrase:      'somethingyouhavenoidea'                                      # ssh key pass phrase
    token_ttl:        86400
    user_identity_field: id
````

it seem that when Namshi/Jose package verify the input, it's always return 0.

vendor/namshi/jose/src/Namshi/JOSE/Signer/OpenSSL/PublicKey.php
`$result = openssl_verify($input, $signature, $keyResource, $this->getHashingAlgorithm());` 

I am on php 7.1

**Comment by chalasr** [comment]
I'm unable to reproduce. Is your public key still present and readable in the configured path? Did you regenerate them? Forking the symfony standard edition with the minimal configuration required to reproduce your bug would help.

**Comment by Webonaute** [comment]
I regenerated the key twice.

I will try to fork the symfony standard edition to reproduce.

**Comment by chalasr** [comment]
Which version of this bundle are you using ? Is it the same as before upgrading?
Thanks

**Comment by chalasr** [comment]
Closing here due to the lack of feedback. Feel free to comment or reopen.
