### ISSUE TITLE
How can I verify that user_id in request body belongs to current user?

### ISSUE THREAD

**Issue by m0onspell** [lexik/LexikJWTAuthenticationBundle#336]
Let's say I am sending a form which have `user_id` field in it, which must be equal to ID of current user.
```javascript
{
    "user_id": 1,
    // ...
}
```
And a token in header, of course.

But doesn't that mean that anybody who have authenticated token can now submit a form with whatever `user_id` they want? So we need a way to verify somehow on the server that `user_id` from the form belongs to token owner. How can I achieve that?
Shoul I just add `user_id` to my token payload when it's generated, and then always retreive `user_id` only from there?
Thanks.

**Comment by chalasr** [comment]
If your user is _authenticated_ (through the current firewall, meaning that a valid token has been passed by header/query param/cookie in the current request), you can just get the current user via the `security.token_storage` service as usual:

`$form['user_id'] === $tokenStorage->getToken()->getUser()->getId()`

No need for passing the token as a form field. 
If you don't want to use the symfony built-in authentication mechanism (which we highly encourage to use), put your `user_id` in the token itself (see https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsauthentication_success---adding-public-data-to-the-jwt-response) and compare it when needed using the `lexik_jwt_authentication.jwt_manager` service: 

`$form['user_id'] === $jwtManager->decode($token)['user_id']`

**Comment by m0onspell** [comment]
Cool, the first method works! Thanks!
