### ISSUE TITLE
Integrating with FOSUser and HWIOAuth

### ISSUE THREAD

**Issue by antonmedv** [lexik/LexikJWTAuthenticationBundle#347]
Hi,

I have an app configured with FOSUser and HWIOAuth, now i'm creating an SPA and want to use jwt tokens. Do you have some guides about integrating all things together? Or maybe some articles? 

Also what is better way of integrating oauth for SPA? For form with login/password you can send request to backend api and get jwt token back. But whsat to do with oauth services like google/github/etc? I can redirect user to oauth page, then redirect to third party oauth server, then back to oauth "callback" page, but how and when to obtain jwt token then? 

BTW, thanks for a great bundle.

**Comment by chalasr** [comment]
Hello @antonmedv,

Outside of the fact you're using FOSUser and HWIOAuth bundles, this is an interesting question. 
We don't have any docs about integrating this bundle for SSO, OAuth or any third-party authentication. I plan to work on providing examples in our sandbox asap.
In the meantime, could you provide more info about your exact workflow? Is your SPA a standalone application (maybe front-end only?) which hits your oauth server, itself redirecting from your SPA to the targeted third party application (e.g. github), then redirecting back to your SPA once authentication succeeded/failed? I will try to give you some hints.

**Comment by antonmedv** [comment]
@chalasr yes, SPA is a standalone app front-end only. Now you login with github, user needs to go to special route, that route will redirect him to github and back to callback route, there HWIOAuth exchange access_tokens and load user data.

I think it will be cool to integrate LexikJWTAuthenticationBundle here, and get API token in callback route of HWIOAuth.

**Comment by chalasr** [comment]
Sorry for the delay!

Based on what a colleague did at work (no FOSUser, no HWIOAuth, only a custom guard authenticator which makes use of [league/oauth2-github](https://github.com/thephpleague/oauth2-github), and this bundle) I would recommend the following workflow: 

- Once your user has been redirected from e.g. github to your server-side callback url, forge a JWT in the callback controller action (or any event subscriber you can hook into for accessing the logged-in user and set the success/failure response for your SPA)  using the `lexik_jwt_authentication.jwt_manager` service: 
`$token = $this->jwtManager->create($authenticatedUser);` 
and return this token in the response (usually JSON formatted)
- Configure our `lexik_jwt_authentication.jwt_token_authenticator` guard authenticator on the firewall(s) which is behind your protected resources (see the README for setting it up), and make your SPA passes the token to each request targeting a protected resource.

Is that doable with your current setup? In case you have a doubt in one of the given steps or you need some code, just ask me. On my side I'll use this to provide some docs on the subject

**Comment by antonmedv** [comment]
Ok, thanks. But working example with HWIOauth will be more awesome)

**Comment by LilianaFuentes0717** [comment]
Buenas tardes, estoy tratando de integrar Lexik JWT con HWIOAuthl, pero aún no he podido realizarlo correctamente, ya que necesito en lugar de realizar un callback, autenticar al usuario y generar el JWT, alguien tiene una duda de como realizarlo
