### ISSUE TITLE
Overriding JWTProvider

### ISSUE THREAD

**Issue by epicwhale** [lexik/LexikJWTAuthenticationBundle#35]
I need to override the JWTProvider class' authenticate function (https://github.com/lexik/LexikJWTAuthenticationBundle/blob/118758ed7ea2e8b2cc36360c47069bac009088d9/Security/Authentication/Provider/JWTProvider.php#L42) to modify the logic as follows:
1. My user id is stored in a payload field called 'uid' and NOT username.
2. I need a different function called to load the user, instead of the $this->userProvider->loadUserByUsername  (since I am using the uid and some other constraint for finding the user).

The first approach that comes to my mind to achieve the above is creating a new class that extends the JWTProvider and rewriting the class definition for the lexik_jwt_authentication.security.authentication.provider to my own class.

This approach will seem to solve my problem, but the bundle makes such implementation unfriendly as the member variables inside the JWTProvider class are declared as private.

```
    /**
     * @var UserProviderInterface
     */
    private $userProvider;

    /**
     * @var JWTManager
     */
    private $jwtManager;
```

Wouldn't it better to declare all such variables across this class and other classes as protected so they are well-extendable? It looks right now I will have to copy paste the entire class logic or at least the constructor and assigning of these member variables.

What's your thoughts on the above?

**Comment by VanVan** [comment]
There is a new methode setUserIdentityField() on JWTProvider
