### ISSUE TITLE
Symfony 3.3

### ISSUE THREAD

**Issue by wimpog** [lexik/LexikJWTAuthenticationBundle#350]
When will this be ready for Symfony 3.3?
Thank you!

**Comment by chalasr** [comment]
It is alread. Ate you experiencing any issue ?
Or is it becauuse the readme has not been updated (I just realize)?

**Comment by wimpog** [comment]
Yeah, the README. I ain't experiencing no issues, but want to make sure it is all set for that version. 
Thank you!

**Comment by chalasr** [comment]
You're welcome, sorry about the README, I'm going to fix that except if you wish to do it. Keeping this open until it's fixed

**Comment by wimpog** [comment]
Thank you!
