### ISSUE TITLE
How to add a HEADER parameter?

### ISSUE THREAD

**Issue by wimpog** [lexik/LexikJWTAuthenticationBundle#351]
Say I want to add a `"typ": "JWT"` to the header. How do I accomplish it?
Thank you!

**Comment by chalasr** [comment]
See https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsjwt_created---adding-data-to-the-jwt-payload for adding data to the payload.

Note that standard claims such as `typ`  will soon be part of the payload by default, some other might be configurable.

**Comment by chalasr** [comment]
Closing as answered :)

**Comment by Spomky** [comment]
Hi @chalasr 

In fact `typ` is not part of the payload, but the header (see [rfc7519#section-5.1](https://tools.ietf.org/html/rfc7519#section-5.1)).

At the moment the bundle allows developers to alter the claims in the payload, but AFAIK there is not way to modify the header.
It would be achievable by extending the `JWTCreatedEvent` and adding `getHeader()`/`setHeader()` methods.

**Comment by chalasr** [comment]
Fixed by @Spomky in #352, will be part of the next minor
