### ISSUE TITLE
digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

### ISSUE THREAD

**Issue by antonmedv** [lexik/LexikJWTAuthenticationBundle#355]
Hi,

After creating pub/priv pub files with command from README.md and running chekc command got this:

```
$ bin/console lexik:jwt:check-config
Failed to load private key "/Users/anton/Projects/pro/back/app/../var/jwt/private.pem":
 0906D06C:PEM routines:PEM_read_bio:no start line
 06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
 0906A065:PEM routines:PEM_do_header:bad decrypt
```

**Comment by antonmedv** [comment]
What am I going wrong? :)

**Comment by Spomky** [comment]
It looks like your private key is encrypted. [Save it unencrypted](https://techjourney.net/how-to-decrypt-an-enrypted-ssl-rsa-private-key-pem-key/) and try again

**Comment by chalasr** [comment]
Closing as solved, that's a key generation issue. Thanks @Spomky for helping out.

**Comment by soromamadou** [comment]
If someone have the same problem, make sure that the pass use to generate the private is the same in the config files

**Comment by willchr** [comment]
> If someone have the same problem, make sure that the pass use to generate the private is the same in the config files

I have the same problem and wondering which config files you are talking about. Could u give me a hint?
