### ISSUE TITLE
curl gets 404 error

### ISSUE THREAD

**Issue by wraycode** [lexik/LexikJWTAuthenticationBundle#359]
where do I specify the port? I can't test with php server because curl and guzzle timeout and under apache I get a 404 not found when trying to access the routes?

**Comment by chalasr** [comment]
The uri on which your symfony application is served doesn't concern this bundle at all, same for your webserver configuration.

**Comment by wraycode** [comment]
it does not make sense that
curl -X POST http://localhost:8000/api/login_check  works
but 
curl -X POST http://localhost/api/login_check returns 404

also just ran compser update got this 

  - Updating lexik/jwt-authentication-bundle (v2.4.0 => v2.4.1):     Update failed (Could not delete /var/www/html/cg-open-api/vendor/lexik/jwt-authentication-bundle/UPGRADE.md: )
    Would you like to try reinstalling the package instead [yes]? yes
  - Removing lexik/jwt-authentication-bundle (v2.4.0)

                                                                                                  
  [RuntimeException]                                                                              
  Could not delete /var/www/html/cg-open-api/vendor/lexik/jwt-authentication-bundle/UPGRADE.md:

**Comment by wraycode** [comment]
maybe a permissions issue

**Comment by wraycode** [comment]
fixed permission on cache but still curl get 404 not found

**Comment by wraycode** [comment]
my route is
 api_login_check:
    path: /api/login_check 

works fine under php server but not apache

**Comment by chalasr** [comment]
Then your webserver is misconfigured or you have a cache issue. You will find all you need on the internet (e.g. http://symfony.com/doc/current/setup/web_server_configuration.html, http://stackoverflow.com), this is totally unrelated to this bundle, we can't help on that.
Thanks for your understanding

**Comment by wraycode** [comment]
why does you example only show curling to the php server?

**Comment by wraycode** [comment]
no response on stack 
https://stackoverflow.com/questions/44831379/sending-jwt-authorization-guzzle

**Comment by chalasr** [comment]
That's an example which makes use of the PHP built-in server, which runs it on the port 8000 using `bin/console server:run` on a symfony standard edition, you should have a look at the command itself (which is a symfony one, not provided by this bundle). If `/login_check` returns 404, I guess any all other urls of your application won't work, hence closing this issue as unrelated. Again, this bundle is not responsible for your webserver configuration.
