### ISSUE TITLE
Anonymous Token?

### ISSUE THREAD

**Issue by epicwhale** [lexik/LexikJWTAuthenticationBundle#36]
I am using the JWT token (via data modifiers) to pass additional data like say a unique traceable session id to maintain state across a guest checkout. In this case, authentication is optional and the login token will not have the 'username' field set.

How do I go about achieving the above?
1.  Is there an anonymous token implementation in this bundle?
2.  If I override the JWTProvider's authenticate(..) function, would that suffice? I was thinking of removing the AuthenticationException which is thrown when !isset($payload['username')) and instead doing something here that treats this request as anonymous.

What are your thoughts on this?

**Comment by lopsided** [comment]
I am looking to do a very similar thing. @epicwhale did you get this working in the end?

**Comment by epicwhale** [comment]
@lopsided excuse my delayed reply. Yes, I did via writing complete custom code and overriding some handles and registering events listeners.

There isn't a simple recipe. But the trick for me was to decode the token before this bundle does it and if its a guest, don't pass it on to JWT, so the user field is never checked. You can store the session id in some other field in the token.
