### ISSUE TITLE
Catchable Fatal Error: Argument 1 passed to Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager::create() 

### ISSUE THREAD

**Issue by med004** [lexik/LexikJWTAuthenticationBundle#365]
Hello,
I have this error when I use JWTAuthenticationBundle for generate token:

> Catchable Fatal Error: Argument 1 passed to Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager::create() must be an instance of Symfony\Component\Security\Core\User\UserInterface, instance of MedBundle\Entity\Med given, called in /var/www/html/authenti/src/MedBundle/Controller/ApiController.php on line 51 and defined

code controller:

`<?php

	namespace MedBundle\Controller;

	use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
	use Symfony\Component\HttpFoundation\Request;
	use Symfony\Bundle\FrameworkBundle\Controller\Controller;
	use FOS\RestBundle\Controller\Annotations\RouteResource;
	use Symfony\Component\HttpFoundation\JsonResponse;
	use FOS\RestBundle\View\ViewHandler;
	use FOS\RestBundle\View\View;
	use MedBundle\Entity\Med;
	use Symfony\Component\Security\Core\User\UserInterface;

	 Class ApiController extends Controller {

	 	public function getAction() {

	 		$em = $this->getDoctrine()->getManager();
	        $test = $em->getRepository('MedBundle:Med')->findAll();
	        $viewHandler = $this->get('fos_rest.view_handler');

	        // Création d'une vue FOSRestBundle
	        $view = View::create($test);
	        $view->setFormat('json');

	        // Gestion de la réponse
	        return $viewHandler->handle($view);
	        //return array('test'=>$test);

	 	}

	 	public function loginAction() {

	 		$em = $this->getDoctrine()->getManager();
	 		$request = $this->getRequest();
	 		if ($request->getMethod() == 'POST') {
		 		$username = $request->request->get('username');
		    	$password = $request->request->get('password');

		     $test = $em->getRepository('MedBundle:Med')->findOneBy(array('username' => $username));

		        if (!($test)) { var_dump('error'); } else{ 
		        	$salt= $test->getSalt();
		        	$pass = crypt($password,$salt);
		        	if ( $pass === $test->getPassword() ) {
		        	var_dump('success'); } 
		        }

		        $x = $this->get('lexik_jwt_authentication.jwt_manager')->create($test);
		        var_dump($x);
	 }	   
		 		return $this->render('default/login.html.twig');

	 	}

	 	public function logoutAction() {

	 		
	 	}

	 }`

help me please for resolve this bug and thanks

**Comment by norkunas** [comment]
As errors says it expects instanceof `Symfony\Component\Security\Core\User\UserInterface` so your `MedBundle:Med` entity must implement that interface.

**Comment by med004** [comment]
with this code : 

`<?php

namespace MedBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use FOS\RestBundle\Controller\Annotations\RouteResource;
use Symfony\Component\HttpFoundation\JsonResponse;
use FOS\RestBundle\View\ViewHandler;
use FOS\RestBundle\View\View;
use MedBundle\Entity\Med;
use Symfony\Component\Security\Core\User\UserInterface;

 Class ApiController extends Controller implements UserInterface {

 	public function getAction() {

 		$em = $this->getDoctrine()->getManager();
        $test = $em->getRepository('MedBundle:Med')->findAll();
        $viewHandler = $this->get('fos_rest.view_handler');

        // Création d'une vue FOSRestBundle
        $view = View::create($test);
        $view->setFormat('json');

        // Gestion de la réponse
        return $viewHandler->handle($view);
        //return array('test'=>$test);

 	}


 	public function loginAction() {

 		$em = $this->getDoctrine()->getManager();
 		$request = $this->getRequest();
 		if ($request->getMethod() == 'POST') {
	 		$username = $request->request->get('username');
	    	$password = $request->request->get('password');

	     $test = $em->getRepository('MedBundle:Med')->findOneBy(array('username' => $username));

	        if (!($test)) { var_dump('error'); } else{ 
	        	$salt= $test->getSalt();
	        	$pass = crypt($password,$salt);
	        	if ( $pass === $test->getPassword() ) {
	        	var_dump('success'); } 
	        }

	        $x = $this->get('lexik_jwt_authentication.jwt_manager')->create($test);
	        var_dump($x);
 }	   
	 		return $this->render('default/login.html.twig');

 	}



 	public function logoutAction() {


 		
 	}

 }`


I have this error:

> Error: Class MedBundle\Controller\ApiController contains 5 abstract methods and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Security\Core\User\UserInterface::getRoles, Symfony\Component\Security\Core\User\UserInterface::getPassword, Symfony\Component\Security\Core\User\UserInterface::getSalt, ...)

**Comment by norkunas** [comment]
I said that your entity `MedBundle:Med` must implement `Symfony\Component\Security\Core\User\UserInterface` not the `ApiController` :)

**Comment by med004** [comment]
now when I implement interface in entity:

code entity:

`<?php

        namespace MedBundle\Entity;

        use Doctrine\ORM\Mapping as ORM;
        use Symfony\Component\Security\Core\User\UserInterface;

        /**
         * Med
         *
         * @ORM\Table(name="med")
         * @ORM\Entity(repositoryClass="MedBundle\Repository\MedRepository")
         */
        class Med implements UserInterface
        {
            /**
             * @var int
             *
             * @ORM\Column(name="id", type="integer")
             * @ORM\Id
             * @ORM\GeneratedValue(strategy="AUTO")
             */
            private $id;

            /**
             * @var string
             *
             * @ORM\Column(name="username", type="string", length=255)
             */
            private $username;

            /**
             * @var string
             *
             * @ORM\Column(name="email", type="string", length=255)
             */
            private $email;

            /**
             * @var string
             *
             * @ORM\Column(name="password", type="string", length=255)
             */
            private $password;

             /**
             * @var string
             *
             * @ORM\Column(name="salt", type="string", length=255)
             */
            private $salt;

            /**
             * Get id
             *
             * @return int
             */
            public function getId()
            {
                return $this->id;
            }

            /**
             * Set username
             *
             * @param string $username
             *
             * @return Med
             */
            public function setUsername($username)
            {
                $this->username = $username;

                return $this;
            }

            /**
             * Get username
             *
             * @return string
             */
            public function getUsername()
            {
                return $this->username;
            }

            /**
             * Set email
             *
             * @param string $email
             *
             * @return Med
             */
            public function setEmail($email)
            {
                $this->email = $email;

                return $this;
            }

            /**
             * Get email
             *
             * @return string
             */
            public function getEmail()
            {
                return $this->email;
            }

            /**
             * Set password
             *
             * @param string $password
             *
             * @return Med
             */
            public function setPassword($password)
            {
                $this->password = $password;

                return $this;
            }

            /**
             * Get password
             *
             * @return string
             */
            public function getPassword()
            {
                return $this->password;
            }

            /**
             * Set salt
             *
             * @param string $salt
             *
             * @return Med
             */
            public function setSalt($salt)
            {
                $this->salt = $salt;

                return $this;
            }

            /**
             * Get salt
             *
             * @return string
             */
            public function getSalt()
            {
                return $this->salt;
            }
        }
`

I have this errror:

> Error: Class MedBundle\Entity\Med contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Symfony\Component\Security\Core\User\UserInterface::getRoles, Symfony\Component\Security\Core\User\UserInterface::eraseCredentials)

**Comment by norkunas** [comment]
So implement the remaining methods :)

**Comment by chalasr** [comment]
Closing as this is a Symfony support issue, should be asked on a Symfony [support platform](https://symfony.com/support) instead. Thanks for your understanding.

**Comment by med004** [comment]
thanks for help
