### ISSUE TITLE
Sensio Insights Recommendations

### ISSUE THREAD

**Issue by RenierLewis** [lexik/LexikJWTAuthenticationBundle#371]
Hi Team

I did a Sensio Insights code scan on the code.

It recommended the following recommendations:

1. Unused method, property, variable or parameter
MinorDeadcode
in Response/JWTAuthenticationSuccessResponse.php, line 23
    private $token;
This token attribute is declared but never used. You should remove it.

2. Deprecated class usage found 
in DependencyInjection/Security/Factory/JWTFactory.php, line 171
    {
        if (class_exists('Symfony\Component\DependencyInjection\ChildDefinition')) {
            return new ChildDefinition($parent);
        }
        return new DefinitionDecorator($parent);
The Symfony\Component\DependencyInjection\DefinitionDecorator class has been deprecated in Symfony 3.3. Use the Symfony\Component\DependencyInjection\ChildDefinition class instead.

in DependencyInjection/Security/Factory/JWTUserFactory.php, line 23
 */
final class JWTUserFactory implements UserProviderFactoryInterface
{
    public function create(ContainerBuilder $container, $id, $config)
    {
        $definition = $container->setDefinition($id, new DefinitionDecorator('lexik_jwt_authentication.security.jwt_user_provider'));
The Symfony\Component\DependencyInjection\DefinitionDecorator class has been deprecated in Symfony 3.3. Use the Symfony\Component\DependencyInjection\ChildDefinition class instead.

Perhaps you want to consider fixing these issue if possible.
Alternatively I can ask my team to fix these.

Let me know how to proceed.

Regards
Renier Lewis

**Comment by chalasr** [comment]
Hello @RenierLewis, thanks for taking care of opening this issue.

> Unused method, property, variable or parameter

👍  for removing that unused property.

> Deprecated class usage found

It is used as fallback when the replacement does not exist yet, which can happen because this bundle supports several symfony versions. So we must keep this one as is.

PR is welcome :)

**Comment by chalasr** [comment]
Fixed in #405

**Comment by RenierLewis** [comment]
Thanks for fixing this guys!
