### ISSUE TITLE
let token to expire after midnight

### ISSUE THREAD

**Issue by sensorario** [lexik/LexikJWTAuthenticationBundle#375]
Is there a configuration that force jwt token expiration after midnight?

**Comment by akomm** [comment]
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#example-override-token-expiration-date-calculation-to-be-more-flexible

**Comment by sensorario** [comment]
Uh sorry, fixed. I forgot to close the issue.
