### ISSUE TITLE
It is possible to use with ODM? 

### ISSUE THREAD

**Issue by korsmakolnikov** [lexik/LexikJWTAuthenticationBundle#386]
I'm trying to use the bundle directly passing doctrine_odm, 
but got an AuthenticationFailureEvent with this error `Doctrine ORM Manager named "doctrine_mongodb" does not exist`. 

Actually it is possible to use it with odm?

**Comment by chalasr** [comment]
This bundle does not depend on doctrine, so if you did configure an user provider able to load the user through the ODM, it should work. I think you are trying to use an `entity` provider while you should use a `mongodb` one (see http://symfony.com/doc/3.1/bundles/DoctrineMongoDBBundle/index.html#securitybundle-integration).

**Comment by chalasr** [comment]
Closing as explained.
