### ISSUE TITLE
/api/login_check is not working from browser

### ISSUE THREAD

**Issue by habibun** [lexik/LexikJWTAuthenticationBundle#387]
/api/login_check is not working in browser, but it works in postman and cli.

**Comment by chalasr** [comment]
Postman/CLI and your browser are just using different HTTP clients. This does not make sense.
Search what's change between the requests sent from your browser and the ones from your cli/postman, any difference would be the bottleneck.
Please do not reopen, this does not make sense. Use stackoverflow for such issues.
