### ISSUE TITLE
Send Token Headless

### ISSUE THREAD

**Issue by juliusstoerrle** [lexik/LexikJWTAuthenticationBundle#388]
Hey,

is there a config option allowing to send (and validate) a headless token?

Maybe i just didn't look hard enough in the docs, but even the search could find something.
Thanks for your reply in advance!

**Comment by chalasr** [comment]
Hey, can you explain me what you mean by headless? Thanks

**Comment by juliusstoerrle** [comment]
Hey, i mean removing the header so that only the payload and signature parts are send. 

I read on various pages that that would improve security, as a server would than only accept one algorithm for validation.

**Comment by chalasr** [comment]
Sorry for the delay.
Actually this bundle (and the JOSE libraries it is based on) don't consider the `alg` header value for validating tokens. It always relies on the `lexik_jwt_authentication.encoder.signature_algorithm` config option, putting its value as `alg` value. I may be wrong but I think it's enough.

@Spomky could you confirm or give your opinion here?

**Comment by Spomky** [comment]
Well... it deviates from the JWT specification.

@juliusstoerrle I am curious. Where have you seen that it improves the security.

The algorithm used on server side can be guessed using the signature (e.g. a 256 bits signatures generated by the HS256 algorithm).
A better way to improve the security would be to have good keys (e.g. at least 2048 bits RSA keys) and to rotate them.

**Comment by juliusstoerrle** [comment]
I'm not to sure where i have read it but following article explains the underlying vulnerability.
(https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/ 

But if this library is not using the header to check a token, this does not apply anyway, so it would only be less data to be send down the wire, but those few bytes do not matter in my opinion.

**Comment by Spomky** [comment]
This bundle relies on third party libraries (namshi/jose, lcobucci/jwt or custom implementations).
It is up to these implementations to perform all cryptographic operations and header verification.

As far as I know, the security issue you mentioned is fixed for all libraries officially supported by the bundle.

**Comment by chalasr** [comment]
Closing then :)
