### ISSUE TITLE
Abandon namshi/jose

### ISSUE THREAD

**Issue by chalasr** [lexik/LexikJWTAuthenticationBundle#389]
Library is [not maintained anymore](https://github.com/namshi/jose#deprecation-notice).
Initial plan: replace it by lcobucci/jwt integration, and go with custom encoders for complex needs (pushing towards `SpomkyLabs/jose`).

**Comment by Taluu** [comment]
How about using the suggested replacement (`firebase/php-jwt`) instead, or the continuation of spomky which is `web-token/jwt-framework` ?

**Comment by chalasr** [comment]
@Taluu lcobucci/jwt is already implemented so the switch is easy, and `spomky-labs` has its own bridge + flex recipe for this bundle. A firebase/php-jwt integration would be good to have though.

**Comment by Taluu** [comment]
The thing is, `spomky-labs` is deprecated in favor of the `web-token`, as stated on the README :

> We highly recommend you to use the new [JWT Framework project](https://github.com/web-token/jwt-framework) instead of this library.
> 
> * Active support of this library is provided until **end of 2018**.
> * Security support will be provided **from 2019 and up to end of 2020**.
> 
> A migration guide will be/is available in [the documentation of the new project](https://web-token.spomky-labs.com/migration/spomky-labs-jose/).

**Comment by chalasr** [comment]
The bridge has been updated accordingly, it relies on `web-token` https://github.com/Spomky-Labs/lexik-jose-bridge/blob/v2.0/composer.json

**Comment by gmponos** [comment]
Any progress on this. Since PHP 7.2 is out the package is not updated to support PHP 7.2.

I hope [this](https://github.com/namshi/jose/pull/120) get merged.

**Comment by Oliboy50** [comment]
@gmponos it just has been merged, so it looks like namshi/jose supports php7.2
