### ISSUE TITLE
"Bad credentials" translation

### ISSUE THREAD

**Issue by lpichoud** [lexik/LexikJWTAuthenticationBundle#390]
Hello,

I try to translate the message "Bad credentials" returned when wrong credentials are provided : 

```
{
    "code": 401,
    "message": "Bad credentials"
}
```

I tried to put translation in security.fr.yml, messages.fr.yml and LexikJWTAuthenticationBundle.fr.yml but none of theses worked.

I found the message in JWTAuthenticationFailureResponse but it doesn't look like it's translated.

Is there a way to do it ?
Thanks in advance.

**Comment by lashae** [comment]
We made the translation in our JWTListener class as follows:

```
    public function onAuthenticationFailureResponse(AuthenticationFailureEvent $event)
    {
        $data = 'Giriş yapılamadı, bilgilerinizi kontrol ederek yeniden deneyiniz.';
        $response = new JWTAuthenticationFailureResponse($data);
        $event->setResponse($response);
    }
```

**Comment by lpichoud** [comment]
Thanks for your answer. I handled it manually in client side, but it may help someone.
