### ISSUE TITLE
cannot call doctrine with JWTTokenAuthenticator extends BaseAuthenticator with app.php

### ISSUE THREAD

**Issue by maximebourdel** [lexik/LexikJWTAuthenticationBundle#391]
Hi,

i have a problem when i switch between app_dev.php and app.php

here is the error in my prod.log

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Call to a member function getRepository() on null" at /var/www/html/carPool/api/src/MainBundle/Security/Guard/JWTTokenAuthenticator.php line 73

the precise line is 
$admin = $this->doctrine->getRepository('MainBundle:Admin')
                    ->findOneByEmail($user->getUsername());

The problem is that $this->doctrine becomes null when I set app.php instead of app_dev.php

I wanted to include @doctrine.orm.entity_manager into JWTTokenAuthenticator so i decided to set my services.yml

    app.jwt_token_authenticator:
        class: MainBundle\Security\Guard\JWTTokenAuthenticator
        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
        calls:
            - [setDoctrine, ["@doctrine.orm.entity_manager"]]

so i set up setDoctrine method.

Here is my class JWTTokenAuthenticator.

``

	<?php

	namespace MainBundle\Security\Guard;

	use MainBundle\Entity\Admin;

	use Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator as BaseAuthenticator;
	use Symfony\Component\Security\Core\User\UserInterface;
	use Symfony\Component\Security\Core\User\UserProviderInterface;
	use Symfony\Component\HttpFoundation\Request;
	use Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken;
	use Symfony\Component\Security\Core\Exception\BadCredentialsException;

	class JWTTokenAuthenticator extends BaseAuthenticator
	{
		private $doctrine;
		
		/**
		 * Injecte doctrine via les services
		 * @param type $doctrine
		 */
		public function setDoctrine($doctrine){
		    $this->doctrine = $doctrine;
		}

		/**
		 * {@inheritdoc}
		 */
		public function checkCredentials($credentials, UserInterface $user)
		{
		   
		  .....  
		            
		    $admin = $this->doctrine->getRepository('MainBundle:Admin')
		                ->findOneByEmail($user->getUsername());
		    
		    ....
		    
		}
		
	}
``
Do you know with i got the error when i switch with prod mode ?

Thank you in advance.

Cordially,
Maxime Bourdel

**Comment by chalasr** [comment]
This looks like a cache issue. If you get a different behavior between dev and prod environments for a service that does not differ, it's likely you need to remove the production cache (fastest: `rm -rf var/cache/*`).

**Comment by maximebourdel** [comment]
Works like a charm after cleaning cache sorry i did not think about it.
