### ISSUE TITLE
How I set jwt_token_ttl before I generate a token?

### ISSUE THREAD

**Issue by lvillarino** [lexik/LexikJWTAuthenticationBundle#394]
Hi:

How I set _jwt_token_ttl_ before I call _$this->get( 'lexik_jwt_authentication.encoder' )
		              ->encode_ ?

Thanks

**Comment by chalasr** [comment]
Hi, that's not possible AFAIK. Can you explain your use case?

**Comment by lvillarino** [comment]
I want to generate 2 tokens with different ttl, and I want to use the second token as a refresh_token.

I don't to use the https://github.com/gesdinet/JWTRefreshTokenBundle 

Thanks

**Comment by lvillarino** [comment]
I think that I can resolved my problem with this https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#example-override-token-expiration-date-calculation-to-be-more-flexible
