### ISSUE TITLE
Getting token payload into custom user provider

### ISSUE THREAD

**Issue by ahtsei** [lexik/LexikJWTAuthenticationBundle#396]
Hi there, 

Firstly, thanks for this useful bundle.

My question is essentially about getting the token payload passed into my custom user provider, more specifically the loadUserByUsername method. I'm using a custom provider as I'm fetching a user that's uniquely defined by two fields ie. username + company.

My issue is that one of those fields is getting passed in the token payload, so ideally i could extract it from the passed in payload. I can see that the JWTUserProvider accepts something like this, but as far as I can see there's currently no way to work this logic into a custom provider.

Would you have any advice or suggestions?

Thanks,
Aleks

**Comment by chalasr** [comment]
Hey,

Fortunately, this should be unlocked in the next minor version thanks to #344.
I would like to release it by the end of this month.

Maybe could you try it and confirm it fits your need? 
Checking out the master branch of this bundle and maving your custom user provider implements `UserProviderWithPayloadSupportsInterface` should do the job (btw, I plan to rename it to something like `PayloadAwareUserProviderInterface` in the meantime).

Anyway, I'll keep you informed here when it's released.

**Comment by ahtsei** [comment]
Awesome, thanks for that @chalasr (and also big thanks to @sroze for implementing).

**Comment by chalasr** [comment]
Closing then :)

**Comment by sroze** [comment]
@chalasr speaking about it... it might be time for a minor? 😉

**Comment by mrfijas** [comment]
@chalasr is there any chance of releasing this feature? this would allow us to remove custom `JWTTokenAuthenticator` and have custom `UserProvider` only.

great bundle btw, keep up the good work!
