### ISSUE TITLE
login_check with Content-Type application/json not working

### ISSUE THREAD

**Issue by henry-geronimo** [lexik/LexikJWTAuthenticationBundle#397]
Hi guys,

When i send a post request on login_check with application/json content-type, it keeps returning me a 401 "Bad credentials", whereas if i use application/x-www-form-urlencoded everything is working perfectly.

I can see with logs that when using application/json it acts like there was no username provided : 
`doctrine.DEBUG: SELECT t0.username AS username_1, [...] WHERE t0.username_canonical = ? LIMIT 1 ["none_provided"] []`

Any idea ? Did i miss something ?

**Comment by chalasr** [comment]
The symfony `form_login` listener is not meant to handle JSON encoded requests. You should have a look at `json_login` (introduced in symfony 3.3, see http://symfony.com/doc/current/security/json_login_setup.html).
