### ISSUE TITLE
I can't generate public en private key automatically

### ISSUE THREAD

**Issue by Mestoph** [lexik/LexikJWTAuthenticationBundle#400]
Hello,

If i run this command : 
`bin/console debug:container jwt`
and i select
`lexik_jwt_authentication.encoder.default`

I have this response : 
`Information for Service "lexik_jwt_authentication.encoder.default"
==================================================================

 ---------------- ------------------------------------------------------------- 
  Option           Value                                                        
 ---------------- ------------------------------------------------------------- 
  Service ID       lexik_jwt_authentication.encoder.default                     
  Class            Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder  
  Tags             -                                                            
  Public           yes                                                          
  Synthetic        no                                                           
  Lazy             no                                                           
  Shared           yes                                                          
  Abstract         no                                                           
  Autowired        no                                                           
  Autoconfigured   no                                                           
 ---------------- ------------------------------------------------------------- 

`

And i have nothing generated.

So my config it is 

config.yml : `lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'`

parameters.yml: `    jwt_private_key_path: %kernel.root_dir%/../var/jwt/private.pem # ssh private key path
    jwt_public_key_path:  %kernel.root_dir%/../var/jwt/public.pem  # ssh public key path
    jwt_key_pass_phrase:  toto                                     # ssh key pass phrase
    jwt_token_ttl:        3600`

So, my probleme it's i can't generate private/public key automatically, but i can generate this manually with the command openssl for generate rsa private and public key.

What's wrong with my scenario ?

**Comment by chalasr** [comment]
Hello,

The `debug:container` command is not meant to generate keys for you, but give you information about the services available to your application. 
The bundle doesn't provide a command for generating keys, we decided to not make it responsible for this task, you have to run the commands given [there](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#installation) to generate keys.
