### ISSUE TITLE
Unable to use token after generating it. JWTDecodeFailureException

### ISSUE THREAD

**Issue by sephilink** [lexik/LexikJWTAuthenticationBundle#401]
Hi, 

I'm in a bad situation for about 3 days, I'm trying to make a simple auth & register app, but I'm always getting this 500 error when using the token I'm generating : 

> Unable to verify the given JWT through the given configuration. If the "lexik_jwt_authentication.encoder" encryption options have been changed since your last authentication, please renew the token. If the problem persists, verify that the configured keys/passphrase are valid.

I was wondering what couldn't be good actually, here's my config : 
In parameters.yml
```
jwt_public_key_path: '%kernel.root_dir%/../var/jwt/public.pem'
jwt_private_key_path: '%kernel.root_dir%/../var/jwt/private.pem'
jwt_key_pass_phrase: pass
jwt_token_ttl: 3600
```

The head of the RSA private : 
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-256-CBC,5C160F2F53CC8B80C24A66955A6B4E24
```

The config.yml
```
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      'pass'
    token_ttl:        '36000'
    token_extractors:
            authorization_header:      # look for a token as Authorization Header
                enabled: true
                prefix:  Bearer
                name:    Authorization
            cookie:                    # check token in a cookie
                enabled: false
                name:    BEARER
            query_parameter:           # check token in query string parameter
                enabled: false
                name:    bearer
```

The security.yml
```
    firewalls:
        main:
            pattern: ^/
            anonymous: true
            stateless: true

            logout:       true
            anonymous:    true
            guard:
                authenticators:
                    - 'token_authenticator'

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_parameter: username
                password_parameter: password

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```

I'm on v2.4 /w SF 3.3@dev, and it seems that somewhere between the versions something crashed. Still, even after renewing the keys/regenerating a token, nothing is good for the moment and I've always this error.

**Comment by timneill** [comment]
I am getting the same issue. The exception being returned is the generic "Invalid JWT Token" exception message coming rom a re-thrown exception inside JWTTokenAuthenticator. [Source](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Guard/JWTTokenAuthenticator.php#L104). The decode is failing, even though the token can seems fine (i.e. parseable on e.g. jwt.io).

Everything was working a couple of versions ago. My config is basically the same as @SephiL1nk

**Comment by chalasr** [comment]
I'll have a look today.

**Comment by chalasr** [comment]
I'm unable to reproduce locally. Could one of you guys fork https://github.com/chalasr/lexik-jwt-authentication-sandbox, reproduce the issue and give me the branch here?

**Comment by SephiL1nk** [comment]
I'll try that today yeah, keeping you updated

**Comment by SephiL1nk** [comment]
I tried and reproduced the error here : https://github.com/SephiL1nk/issueLexitJWTToken/tree/issue-loginJWTToken
I sent you a link, I'm not that accustomed to Github :)

**Comment by chalasr** [comment]
@SephiL1nk Thanks! Can you give the steps needed to reproduce the bug? I guess I need to hit `/login` to get a token, then `/api` should fail when using the token?

**Comment by SephiL1nk** [comment]
Yep exactly! That's the only steps I did

**Comment by chalasr** [comment]
Despite the reproducer, there is no issue on my side. Here is what I do:

```sh
git clone https://github.com/SephiL1nk/issueLexitJWTToken
cd issueLexitJWTToken
git checkout issue-loginJWTToken
composer install
./bin/console doctrine:database:create
./bin/console doctrine:schema:update --force
./bin/console server:start
curl -X POST http://localhost:8000/register -d _username=foo -d _password=bar
curl -X POST http://localhost:8000/login -H "PHP_AUTH_USER: foo" -H "PHP_AUTH_PW: bar"
# Replace $TOKEN below by the token returned by the previous call
curl -H "Authorization: Bearer $TOKEN"  http://localhost:8000/api
# Logged in as foo
```

**Comment by fd6130** [comment]
This become really old, perhaps the issue is fixed long time ago?
