### ISSUE TITLE
Lcobucci relies on `alg` header for parsing

### ISSUE THREAD

**Issue by chalasr** [lexik/LexikJWTAuthenticationBundle#402]
As described in https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/, the algorithm used to decode the token should always be the one used to sign it, which might not be the case using the lcobucci provider. We should prevent that.

**Comment by Spomky** [comment]
Hi @chalasr,

It should be fixed sinc [v3.0.0](https://github.com/lcobucci/jwt/releases/tag/3.0.0).
A test could confirm it.

**Comment by chalasr** [comment]
For now it's only a soft dependency required as `~3.2` in dev, so there's no issue. 
Thanks @Spomky
