### ISSUE TITLE
401 credentials with entity User

### ISSUE THREAD

**Issue by thanhhuy12th** [lexik/LexikJWTAuthenticationBundle#406]
I create my web service with symfony and JWT, and get an issue, it return 401. And here code, please check my wrong, thank you.

**Security**:

`security:
    encoders:
          AppBundle\Entity\User:
              algorithm: bcrypt

    providers:
          entity_provider:
              entity:
                  class: AppBundle\Entity\User
                  property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter:       _username
                password_parameter:       _password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        register:
            pattern:  ^/api/register
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: ~
    access_control:
            - { path: ^/api/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/register,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api,        roles: IS_AUTHENTICATED_FULLY }`

And User class

`            <?php
            
            namespace AppBundle\Entity;
            
            use Doctrine\ORM\Mapping as ORM;
            use Symfony\Component\Security\Core\User\UserInterface;
            use Symfony\Component\Validator\Constraints as Assert;
            
            /**
             * User
             *
             * @ORM\Table(name="user")
             * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
             */
            class User implements UserInterface
            {
                /**
                 * @var int
                 *
                 * @ORM\Column(name="id", type="integer")
                 * @ORM\Id
                 * @ORM\GeneratedValue(strategy="AUTO")
                 */
                private $id;
            
                /**
                 * @var string
                 * @Assert\NotBlank(message="Please enter your username")
                 * @Assert\Regex("/\S+/",message="add some characters")
                 * @ORM\Column(name="username", type="string", length=255, unique=true)
                 */
                private $username;
            
                /**
                 * @var string
                 * @Assert\NotBlank(message="Please enter your password")
                 * @Assert\Regex("/\S+/",message="add some characters")
                 * @ORM\Column(name="password", type="string", length=255)
                 */
                private $password;
            
                /**
                 * @var boolean
                 * @ORM\Column(name="is_active", type="boolean")
                 */
                private $isActive;
            
                public function __construct($username)
                {
                    $this->isActive = true;
                    $this->username = $username;
                }
                /**
                 * Get id
                 *
                 * @return int
                 */
                public function getId()
                {
                    return $this->id;
                }
            
            
            
                /**
                 * Get username
                 *
                 * @return string
                 */
                public function getUsername()
                {
                    return $this->username;
                }
            
                /**
                 * Set password
                 *
                 * @param string $password
                 *
                 * @return User
                 */
                public function setPassword($password)
                {
                    $this->password = $password;
            
                    return $this;
                }
            
                /**
                 * Get password
                 *
                 * @return string
                 */
                public function getPassword()
                {
                    return $this->password;
                }
            
                public function getSalt()
                {
                    return null;
                }
            
                public function getRoles()
                {
                    return array('ROLE_USER');
                }
                public function eraseCredentials()
                {
                }
            }
            
`
![r](https://user-images.githubusercontent.com/27939341/32343863-8f889904-c037-11e7-85f5-f6e9aae0ee40.PNG)

**Comment by thanhhuy12th** [comment]
Ok, i did it. Just add 
`security:
          encoders:
              AppBundle\Entity\User:
                  algorithm: md5
                  encode_as_base64: false
                  iterations: 0`

And it's work!

**Comment by norkunas** [comment]
Please don't store passwords as md5, use stronger encoders like bcrypt or argon2i

**Comment by thanhhuy12th** [comment]
Yes, thank you. I see!
