### ISSUE TITLE
JWTAuthenticationFailureResponse shouldn't be tagged with @internal

### ISSUE THREAD

**Issue by lashae** [lexik/LexikJWTAuthenticationBundle#407]
We need to translate the "Bad credentials" message which is displayed when a user tries to login with bad credentials.

To fulfill this requirement, we implemented a listener on the `lexik_jwt_authentication.on_jwt_invalid` event with the following code:

```
<?php

namespace MasterBundle\EventListener;

use Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationFailureResponse;
use Lexik\Bundle\JWTAuthenticationBundle\Event\JWTInvalidEvent;

class JwtListener
{
  // ...
    public function onJWTInvalid(JWTInvalidEvent $event)
    {
        $response = new JWTAuthenticationFailureResponse('Oturumunuz geçerli değil, lütfen yeniden giriş yapınız.');

        $event->setResponse($response);
    }
}
```

However, `JWTAuthenticationFailureResponse` class has the `@internal` phpDoc tag, which causes a warning on our IDE PhpStorm:

`Class JWTAuthenticationFailureResponse is @internal`

I don't know the point why this class is an "internal" one, however since we can listen the `lexik_jwt_authentication.on_jwt_invalid` event and listener has to use JWTAuthenticationFailureResponse I propose to remove the `@internal` tag from the `JWTAuthenticationFailureResponse` class.

**Comment by chalasr** [comment]
👍  Can you submit a PR?

**Comment by lashae** [comment]
@chalasr Sure. Same is true for `JWTAuthenticationSuccessResponse`. Would you like me to remove its `@internal` tag as well?

**Comment by chalasr** [comment]
👍  again :)

**Comment by lashae** [comment]
Here it is @chalasr #408

**Comment by lashae** [comment]
@chalasr When do you plan to release 2.4.3?

**Comment by chalasr** [comment]
@lashae released, thanks for the reminder

**Comment by lashae** [comment]
You're welcome :-)
