### ISSUE TITLE
HOW TO unit testing for extending JWTTokenAuthenticator and JWTCreatedListener 

### ISSUE THREAD

**Issue by maximebourdel** [lexik/LexikJWTAuthenticationBundle#414]
Hi, 

I would like to create Unit testings with phpunit for 

- `JWTTokenAuthenticator`

- `JWTCreatedListener` classes I have extended in my own bundle,

But i don't know how to do so...

I tried to take a look at :
`Lexik\Bundle\JWTAuthenticationBundle\Tests\Security\Guard\JWTTokenAuthenticatorTest` 

but as far as i can see, it extends` \PHPUnit_Framework_TestCase`
And when i try to use that class or even trying `PHPUnit\Framework\TestCase`, it fails.
I tried looking on google it said to set my phpunit version tu 5.7 but in vain.

So i am a bit lost. :/
Do you have any link, or solution about my `JWTTokenAuthenticatorTest` reuse problem ?

Thank you in advance

**Comment by chalasr** [comment]
Hey,

The `PHPUnit/Framework/TestCase` class is a PSR-4 alias of the `\PHPUnit_Framework_TestCase` class, this alias is provided by the [symfony/phpunit-bridge](https://github.com/symfony/phpunit-bridge) package. 
You can either look at using this package (it's a dev requirement for this bundle, that's why you won't get it installed when requiring this bundle), or use the original `\PHPUnit_Framework_TestCase` class, it makes no difference on this point, the bridge just provides extra features and btw a namespaced phpunit API. 

Please don't hesitate to share your test once written, I would be glad to provide some base test case(s) in this bundle if needed.

**Comment by chalasr** [comment]
Closing due to the lack of feedbacks as it does not report a bug nor ask for a precise feature. Please feel free to reopen

**Comment by maximebourdel** [comment]
Sorry, i tried with \PHPUnit_Framework_TestCase but i did not managed to.

I only managed to PHPunit my controllers

`use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class WhatYouWantControllerTest extends WebTestCase
{
    private $client;
    private $em;
    
    protected function setUp() {
        $this->client = static::createClient();
        $this->client->enableProfiler();
        $this->em = $this->client->getContainer()
                                ->get('doctrine.orm.entity_manager');
        //Annule le commit
        $this->em->getConnection()->beginTransaction();
        $this->em->getConnection()->setAutoCommit(false);
    }
    
    public function testGetAllReservationAction()
    {
        //Création de l'utilisateur
        $token = $this->createUser('ROLE_ADMIN');
        
        //On appelle la route
        $this->client->request('GET', '/your/route/path'
            , array() , array() 
            , array('HTTP_AUTHORIZATION' => 'Bearer '. $token)
        );
        
        //On vérifie que le code de retour est bien 200
        $this->assertEquals(200 , $this->client->getResponse()->getStatusCode());
    }
    
    /**
     * Crée un utilisateur fictif et retourne son token
     * @param string $role role de l'utilisateur ('ROLE_ADMIN', 'ROLE_USER')
     * @return type token de l'utilisateur
     */
    private function createUser($role) {
        $data = array('username' => 'test','roles' => [$role]);
        
        return $this->client->getContainer()
                ->get('lexik_jwt_authentication.encoder')
                ->encode($data);
    }
}
`
