### ISSUE TITLE
Symfony Flex and JWT configuration

### ISSUE THREAD

**Issue by nicraMarcin** [lexik/LexikJWTAuthenticationBundle#415]
Hi, 
How about configuration jwt with symfony flex? 
After install via composer, generate keys, jwt doesn't emit any events :/
```
bin/console debug:event-dispatcher lexik_jwt                                                                                                             
 [WARNING] The event "lexik_jwt" does not have any registered listeners.                                                
````

**Comment by chalasr** [comment]
Hi,

It does _emit_ events, but does not listen on. This bundle dispatches a bunch of events you can hook into (https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md) but does not register any listener itself because there is no need to do so.

**Comment by nicraMarcin** [comment]
Yes, but profiler shows all dispatched events even without listeners. In standard symfony profiler shows all jwt events but not in flex version.

**Comment by nicraMarcin** [comment]
Ok,
but after install jwt via composer `composer req jwt-auth` and configure providers and firewall in config/services.yaml I have that error
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                                  
  The service "security.authentication.provider.guard.api" has a dependency on a non-existent service "security.user.provider.concrete.jwt". 
```

**Comment by nicraMarcin** [comment]
Ok,
my mistake.
Thanks
