### ISSUE TITLE
Symfony 4

### ISSUE THREAD

**Issue by evaldoprestes** [lexik/LexikJWTAuthenticationBundle#416]
Please, update to Symfony 4.

**Comment by chalasr** [comment]
What do you mean? This bundle is compatible and tested on Symfony 4, installable using `composer req jwt-auth` on flex.

**Comment by BunnyHolder** [comment]
It can be closed. I have problem with JWT token not found, but only in test cases

**Comment by FabulousCo** [comment]
@BunnyHolder so how did you fix it ? I've get the same error since my upgrade to symfony 4 flex
