### ISSUE TITLE
Weird user mismatch issue

### ISSUE THREAD

**Issue by chteuchteu** [lexik/LexikJWTAuthenticationBundle#418]
We've implemented this bundle into our project for a while now (several months). Since the beginning, we're experiencing weird un-reproducible issues that drives us crazy.
Since the beginning, some users gets logged in as others. Nothing links one user (the "stealer" that gets logged in as the "victim") to another (the "victim").

The issue appears randomly, without any pattern

Our app is an API that gets consumed by a React application. We double-checked - the generated tokens are valid, and tokens payload contains an information (user's email) that's unique.

I know that without any code or configuration or steps to reproduce this issue (which we don't even have) you cannot help me further - I wanted to know if anyone already experienced something similar

Thank you!

**Comment by chalasr** [comment]
@chteuchteu strange story, any news about the cause or do you still suffer from this? It feels like Given the lack of feedback I guess the culprit is on your side :/

**Comment by chteuchteu** [comment]
Nope, nothing new on our side. We added some checks on the consuming client to ensure that the token we're getting matches the expected identity, but it just feels weird.

Closing this, I'll post updates when/if we get some. Thank you for your attention!
