### ISSUE TITLE
Hash password alternative ?

### ISSUE THREAD

**Issue by pesseyjulien** [lexik/LexikJWTAuthenticationBundle#419]
Hi,

Thanks for this great bundle !

I have a little concern though, regarding the authentification process. Is it mandatory to send the password in clear ? Could we send the hash version ?

Best,
Julien

**Comment by fesor** [comment]
> Could we send the hash version ?

this will make hash of your password just "plain password" from server point of view. If I catch your hash, I sill could use it to authenticate.

Anyway, SSL basically solves most of the problems.

**Comment by chalasr** [comment]
The `form_login` is part of Symfony, not this bundle. Anyways, sending plain passwords in the request body is common as said above. Closing here, thanks
