### ISSUE TITLE
Token expired even if I use it in every REST API request

### ISSUE THREAD

**Issue by ducho** [lexik/LexikJWTAuthenticationBundle#421]
Hi.
I need to have the JWT token expire when no request is call in my REST API. I need TTL 1800 but let the token expire when application is not used for 30 minutes. 

Is it possible with this bundle ? Or any recommended solution ?
Thanks.

**Comment by GianniObiglio** [comment]
Do you refer to a refresh token system ?
- First, you log, and the server gives you a 30 min lifetime token.
- Each time you do a request, and the token is valid, the server returns you the data you need + a new token available for 30 min.
- Client side, you have to replace the previous token by the new one.
- So when you dont do request (when application is not used for 30 minutes), the token you have on client side will expire, cause he last 30 min.

You got the idea ?

**Comment by chalasr** [comment]
JWT tokens are self-contained, they cannot be invalidated. You'll need some additional datastore hits for implementing this, @GianniObiglio's suggestion is fine, any kind of blacklist would do the job as well (e.g. adding a unique identifier to the token and keep a cache of `token id => last_used_at` and rejecting any token when the value is more than 30minutes ago, or a `lastAuthenticatedAt` at the user level and making authentication fails if more than 30minutes ago). Closing as resolved
