### ISSUE TITLE
Private key does not exist or is not readable

### ISSUE THREAD

**Issue by pesseyjulien** [lexik/LexikJWTAuthenticationBundle#426]
Hi,

I'm having some trouble to make the token creation work on Heroku. I have followed the doc to generate the keys, they exist, 777 rights, but I'm getting the error every time i'm trying to login.

`Private key "/app/app/../var/jwt/private.pem" does not exist or is not readable`

Any thoughts ?

Thanks in advance,
Julien

**Comment by brunoreis** [comment]
Hey @pesseyjulien, please, how did you do your deploy to heroku?

**Comment by pesseyjulien** [comment]
HI,

You need to use env variables.

So in your parameters, you have `env(jwt_path): '%kernel.root_dir%/../var/jwt'`
config : `private_key_path: '%env(jwt_path)%/private.pem'
                public_key_path:  '%env(jwt_path)%/public.pem'`

and your heroku dashboard, define a Config Variables. 
<img width="726" alt="capture d ecran 2018-01-24 a 11 17 01" src="https://user-images.githubusercontent.com/10850944/35326806-1d7b46d4-00f8-11e8-8ad3-6eee8b150436.png">

Then you need to access your Dyno with bash (heroku run bash), and execute the commands to generate the keys.

Cheers,
Julien
