### ISSUE TITLE
Attempted to load class "LexikJWTAuthenticationBundle" from namespace "Lexik\Bundle\JWTAuthenticationBundle". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by rmartinezoliva** [lexik/LexikJWTAuthenticationBundle#427]
Symfony 3.1.3

**Comment by zorn-v** [comment]
My computer did not work, can you do anything with this, guys ?

**Comment by rmartinezoliva** [comment]
When I try to install jwt-authentication-bundle
  php composer.phar require "lexik/jwt-authentication-bundle"
  Update  AppKernel
  new Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle(),

 and test only this
http://localhost:8082/html/web/app_dev.php

and show the error 


"Attempted to load class "LexikJWTAuthenticationBundle" from namespace "Lexik\Bundle\JWTAuthenticationBundle". Did you forget a "use" statement for another namespace? "

**Comment by rmartinezoliva** [comment]
Update to Symfony 3.3 and solved the problem.
