### ISSUE TITLE
'openssl' is not recognized as an internal command

### ISSUE THREAD

**Issue by abdelhafiddahhani** [lexik/LexikJWTAuthenticationBundle#428]
when i exc this command  openssl genrsa -out var/jwt/private.pem -aes256 4096 i get error ==> 'openssl' is not recognized as an internal command
or external, an executable program or a batch file.

How i can fix this issus plz

**Comment by zorn-v** [comment]
If you have Win10 (apparently you try to do it on windows) you can install Linux subsystem. Find "Ubuntu" in windows market and install it. Then you can run `bash` in cmd and go on.
