### ISSUE TITLE
Question about KeyDumperInterface

### ISSUE THREAD

**Issue by lashae** [lexik/LexikJWTAuthenticationBundle#430]
While trying to implement #429 I came across with the KeyDumperInterface:

```
interface KeyDumperInterface
{
    /**
     * Dumps a key to be shared between parties.
     *
     * @return resource|string
     */
    public function dumpKey();
}
```

All of the KeyLoaders included within the bundle implements this interface.

I searched the bundle for the usage of `dumpKey()` method however it seems that it isn't used anywhere. What is the purpose of this interface and required `dumpKey` method?

**Comment by chalasr** [comment]
It has been added to ease sharing a public/shared key, see https://github.com/lexik/LexikJWTAuthenticationBundle/issues/305 for discussion.

**Comment by lashae** [comment]
Thank you for clarification.
