### ISSUE TITLE
Should JWTEncoderInterface implementing class return false or throw an exception on error?

### ISSUE THREAD

**Issue by chteuchteu** [lexik/LexikJWTAuthenticationBundle#431]
According to documentation ([Creating your own encoder](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/5-encoder-service.md#create-the-encoder-class)), a class implementing the `JWTEncoderInterface` should return `false` when something goes wrong in the `decode` method.

In the other hand, the [`DefaultEncoder`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Encoder/DefaultEncoder.php#L52) seems to always return an array and throw an exception if an error occurs.

Also, [`JWTEncoderInterface::decode`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Encoder/JWTEncoderInterface.php)'s PHPDoc states that it returns an array (no boolean):

```php
    /**
     * @param string $token
     *
     * @return array
     *
     * @throws JWTDecodeFailureException If an error occurred while trying to load the token
     *                                   (invalid signature, invalid crypto key, expired token...)
     */
    public function decode($token);
```

What should we do?

**Comment by chalasr** [comment]
The documentation is wrong, it should throw an exception to be handled by the consumer. Would you mind creating a PR for fixing it? Thanks for the report

**Comment by chteuchteu** [comment]
@chalasr Here it is! :-)
