### ISSUE TITLE
Question: firewall-specific token_extractors still possible with v2?

### ISSUE THREAD

**Issue by BlueM** [lexik/LexikJWTAuthenticationBundle#432]
Hi,

thanks for your work on this bundle – JWT as easy as it can get :-)

In the preparation of the migration of an existing Sf application to v4, I upgraded LexikJWTAuthenticationBundle from v1 to v2. The application uses JWTs via “Authorization“ header, but for one part of the application (i.e.: one route prefix) it must be possible to pass the token via query string.

With v1 of the bundle, I could do this in `security.yml`:

    myfirewall_which_should_allow_query_parameter:
      # ...
      lexik_jwt:
        query_parameter:
          enabled: true
          name:    token

However, with the Guard-based approach I don’t see how I can configure this. For the moment, I therefore have globally enabled `query_parameter` support in `config.yml`:

    lexik_jwt_authentication:
      # ...
      token_extractors:
        authorization_header: ~
        cookie: ~
        query_parameter:
          enabled: true
          name: token

This works, but I would prefer being able to configure this per firewall would be preferable. Is this still possible with version 2?

Thanks in advance.

**Comment by mnavarrocarter** [comment]
I'm not the maintainer of this repo, but as far as I can see in the code, the Guard Authenticator receives a ChainTokenExtractor service, that has different types of extractors that are run one by one. In those the QueryParam one is included. In theory, you could send the token via query param in every protected route on the firewall and it will work anyways.

If you don't want that functionality, you can probably take [this](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/6-extending-jwt-authenticator.md) aproach and create your own authenticator extending the JWT one and overriding the `getTokenExtractor` method.

**Comment by BlueM** [comment]
Thanks for answering. After the migration to Sf4 and bundle version 2 everything works fine with the globally available query-string based token. I would have preferred to restrict the query string approach only to the one functionality where I can’t avoid it, but (as you point out) it is no longer simply a configuration option, I think I’ll just leave it like it is. But anyway, thanks for the hint to the docs – maybe this will come in handy in another project.
