### ISSUE TITLE
Question: Is it possible to login using custom field?

### ISSUE THREAD

**Issue by kregielpl** [lexik/LexikJWTAuthenticationBundle#434]
Hi,
I want to login and generate token using only barcode which is assigned to user.
I've read a bit about custom user authentication in SF2 but that way require a lot of work.
What do you think if exist a simpler way? 
Thanks for advice.

**Comment by mnavarrocarter** [comment]
Yes, you can.

You can define your `user_identity_field` as show in [here](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md). Then you need to make sure your user provider answers to the field where you have the barcode.

Also, you will probably need to Hook to some events if you have a service that sorts of reads or decodes the barcode you have. But maybe not.

**Comment by kregielpl** [comment]
But If it works without password field?

**Comment by mnavarrocarter** [comment]
In the `UserInterface` in Symfony you have a method called `getPassword` if I recall correctly. That is what the symfony auth system checks for as a "password", but you can put whatever you want in there. So you make that field return the barcode value, or you can put some custom logic in there to return one or the other. But also you will have to hook into the Auth System to perform some extra validation of that I suppose.

**Comment by chalasr** [comment]
I would suggest to write a guard authenticator that replaces the `form_login` used to get a token. The authenticator would load your user by barcode and, for its `onAuthenticationSuccess/Failure()`  methods, use the authentication failure+success handlers provided by this bundle. That would require one class and the corresponding service definition, see https://symfony.com/doc/current/security/guard_authentication.html

**Comment by chalasr** [comment]
Closing due to the lack of feedback, feel free to reopen.
