### ISSUE TITLE
Symfony 4 Documentation

### ISSUE THREAD

**Issue by AlexDupreWeb** [lexik/LexikJWTAuthenticationBundle#439]
I have some problems with JWT Token integration in Symfony 4. Your documentation is available for Symfony 3.2 or less. Can you update with Symfony 4 integration please? 😃

**Comment by chalasr** [comment]
Sure, it needs some updates. Could you detail the problems you face and how you solved them if you did? That would help for sure. Thanks1

**Comment by chalasr** [comment]
Here is a working example under symfony flex: https://github.com/chalasr/lexik-jwt-authentication-sandbox/tree/flex.
Feedback welcomed, I'll soon take time to update the bundle documentation accordingly.

**Comment by nicraMarcin** [comment]
I've simmilar issue but I get 401 Bad Credentias :/

**Comment by lfridael** [comment]
FYI: I've been able to get up-and-running in a local Symfony 4 dev environment, by following the installation instructions as-is. 

The only thing I did differently is fix the config path for the key file. See changes in this PR:
https://github.com/lexik/LexikJWTAuthenticationBundle/pull/490
