### ISSUE TITLE
Symfony 4 + json_login exemple

### ISSUE THREAD

**Issue by christophe-mailfert** [lexik/LexikJWTAuthenticationBundle#440]
Hi there,

Thx a lot for your bundle.

I'm trying to transform form_login to a json_login for an api. With form_login everything works, but when i'm trying to have a json_login got this error:

[warning] Unable to look for the controller as the "_controller" parameter is missing.

```
security:
    firewalls:
        login:
            pattern:  ^/user/login
            stateless: true
            anonymous: true
            provider: user_provider
            json_login:
                check_path:               user.login
                username_path:            email
                password_path:            password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
```

It's like symfony system authentication does not work with json_form.

Any idea ?

Thx for advance;

**Comment by kavw** [comment]
Hello @christophe-mailfert, please try to follow examples in this article http://symfony.com/doc/current/security/json_login_setup.html

**Comment by chalasr** [comment]
Here is a working example using `json_login` under symfony 4 (flex): https://github.com/chalasr/lexik-jwt-authentication-sandbox/tree/flex.
Feedback welcomed, I'll soon take time to update the bundle documentation accordingly.

**Comment by kavw** [comment]
Hello @chalasr! Could you please give an answer, is there a way to return a token after the registration or it's bad practice. Thank you.

**Comment by christophe-mailfert** [comment]
Thx all for your return.

Seems work when i'm in production mode, but fail and i launch my unit test. I will try to provide an example asap :)

**Comment by chalasr** [comment]
@kavw fine for me.

I'm closing here due to the lack of feedback, feel free to reopen.
