### ISSUE TITLE
Accept connection with only one ROLE

### ISSUE THREAD

**Issue by imajim** [lexik/LexikJWTAuthenticationBundle#446]
Hello !

I have a ROLE_API (and other ROLES) but i would like that only users with this role, could connect to my API.
It's possible ?

Thanks ^^

**Comment by imajim** [comment]
In addition i do 
 
in services.yml : 
`api.event.jwt_decoded_listener:
        class: ApiBundle\EventListener\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }`

JWTCreatedListener.php :  
`
namespace ApiBundle\EventListener;

use Lexik\Bundle\JWTAuthenticationBundle\Event\JWTCreatedEvent;
use Symfony\Component\HttpFoundation\RequestStack;

class JWTCreatedListener
{

    /**
     * @param RequestStack $requestStack
     */
    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }


    /**
     * @param JWTCreatedEvent $event
     *
     * @return void
     */
    public function onJWTCreated(JWTCreatedEvent $event)
    {


        if(!in_array('ROLE_API',$event->getData())){
            // todo : send exception ??
        }

    }
}`

**Comment by imajim** [comment]
Waiting for a better answer here is what I did : 
services.yml : 
`
api.event.authentication_success_listener:
        class: ApiBundle\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
`
In ApiBundle/EventListener/AuthenticationSuccessListener.php
`
class AuthenticationSuccessListener
{
    /**
     * @param AuthenticationSuccessEvent $event
     */
    public function onAuthenticationSuccessResponse(AuthenticationSuccessEvent $event)
    {
        $data = $event->getData();
        $user = $event->getUser();

        if (!$user instanceof UserInterface) {
            return;
        }
        if (!in_array('ROLE_API', $user->getRoles())) {
            $data = [
                'code' => 400,
                'message' => 'Vous n\'avez pas accès à l\'API'
            ];
            $event->setData($data);
        }
    }
}
`

In security.yml : 
`
access_control:
    - { path: ^/api, roles: ROLE_API, requires_channel: '%httpProtocol%' }
`

**Comment by chalasr** [comment]
Personally I would users a token and reject it using the `access_control` rule only, but I understand the motivation for not giving a token at all. Your last implementation is the way to go.

**Comment by nasrithamer** [comment]
Hello @chalasr ,
please i have a question;
 i am working with **lexik and nelmio api doc** and i want when user connect and i let him navigate without putting in every route token parameters like **POSTMAN**. i hope its clear with the IMG

![image](https://user-images.githubusercontent.com/13709609/60591097-92cb5d80-9d95-11e9-9006-bfe2cf80dea5.png)

thank you
