### ISSUE TITLE
The "lexik_jwt_authentication.jwt_manager" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

### ISSUE THREAD

**Issue by TheKassaK** [lexik/LexikJWTAuthenticationBundle#450]
Hello,

We are working on a Symfony 4 Flex project with my team (first time we use this version), and we have an error with this bundle :

In a controller, we retrieve a jwt_token like : `$token = $this->container->get('lexik_jwt_authentication.jwt_manager')->create($user);`

This work in a previous version of Symfony (3.4).

But now we have an error : 

> The "lexik_jwt_authentication.jwt_manager" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

Do you have an idea ? Thanks !

**Comment by norbert-yoimo** [comment]
As a workaround in the meantime, you can use:

```yaml
    jwt_manager:
        public: true
        alias: lexik_jwt_authentication.jwt_manager
```
And then fetch `jwt_manager` from the container.

**Comment by chalasr** [comment]
Fixed in #466

**Comment by gustawdaniel** [comment]
@norbert-yoimo where paste this code in Symfony 4?

**Comment by norbert-yoimo** [comment]
Into services.yml
