### ISSUE TITLE
Getting " Invalid JWT Token " when I test my API

### ISSUE THREAD

**Issue by RecanN** [lexik/LexikJWTAuthenticationBundle#455]
Hi all, for information I'm a Noob in the unit Test.
So, LexikJWTAuthenticationBundle works fine when I try /login_check and the CRUL command line.
But when I try to do the TestCase I get this error : 

_1) Tests\AppBundle\Controller\StoreControllerTest::testPOSTRate
GuzzleHttp\Exception\ClientException: Client error: `GET http://localhost:8000/api/stores` resulted in a `401 Unauthorized` response:
{"code":401,"message":"Invalid JWT Token"}_

My testPOST function :

```
public function testPOSTRate(){
    $data = array(
      'rate' => 1,
      'store' => 1
    );
    // I'm not sure if it's the right way to get Token
    $token = $this->getService('lexik_jwt_authentication.encoder')->encode([
      'username' => 'Nacer',
      ]);

    $this->client->get('http://localhost:8000/api/stores', [
      'body' => json_encode($data),
      'headers' => [
        'Authorization' => 'Bearer '.$token
      ]
    ]);
  }
```

**Comment by chalasr** [comment]
Hey, better hit your login endpoint for getting a token, or use the `lexik_jwt_authentication.jwt_manager` service
