### ISSUE TITLE
Symfony 3.4 JWTFactory and JWTUserFactory are depricated.

### ISSUE THREAD

**Issue by deniskhmel** [lexik/LexikJWTAuthenticationBundle#456]
In LexikJWTAuthenticationBundle  classes JWTFactory and JWTUserFactory are depricated.
And also how can i use $jwtManager = $this->get('lexik_jwt_authentication.jwt_manager'); via dependency injection in my custom controller? thanks)

**Comment by chalasr** [comment]
Yes, they are deprecated on purpose, configuring the bundle as documented avoids the need for using them. About the `jwt_manager` service, it has been made public in #466.
