### ISSUE TITLE
Invalidate token

### ISSUE THREAD

**Issue by tahina4** [lexik/LexikJWTAuthenticationBundle#46]
Is there a way to invalidate the token from a controller ???

**Comment by benjaminrau** [comment]
@slashfan I got here while searching for the same thing. Thanks for the shared link - it was very useful.

As i implemented one of the suggestions there with Lexik id like to share it for others. Sure one could discuss now if this is still stateless now - anyway i think that the db query is fine as Symfony is doing so anyway and there are hardly no solutions without beeing kind of stateful.

Here is what i did:
1. i added a property tokenValidAfter which is a date on the User entity
2. i update this date to the current one whenever i want to invalidate previous issued tokens for the user (change password, reset password, logout from all devices action)
3. i listen the JWTDecodedEvent to mark the token as invalid if the token is older than that date

Gist: https://gist.github.com/benjaminrau/865f94d142605eb72a23a34ccdd0617a

**Comment by waspinator** [comment]
@benjaminrau with your solution if a sure is logged into two different computers, logging out on one logs out on all, right?

**Comment by benjaminrau** [comment]
@waspinator Yes, if intended. A "logout from all" would change the tokenValidAfter date and thus logout from all computers / invalidate all tokens. Regular logout would not change tokenValidAfter and user can logout from just one place.
