### ISSUE TITLE
userIdentityField is hard coded in the JWTManager

### ISSUE THREAD

**Issue by WitteStier** [lexik/LexikJWTAuthenticationBundle#460]
Hi,
Is there a reason why the `userIdentityField` property is hard coded or is this a bug?

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/49f1ba49bab08a0632b275373748445b89de84fd/Services/JWTManager.php#L47

**Comment by norkunas** [comment]
It is just a default value. You can see in [manager configuration](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/96b99310a5ac3a6f32a455b731fa2de44109d0c3/Resources/config/jwt_manager.xml) that service sets identity field with the value you configure

**Comment by WitteStier** [comment]
Thanks for your reply. Following this [documentation](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/49f1ba49bab08a0632b275373748445b89de84fd/Resources/doc/7-manual-token-creation.md) i can use the JWT manager to manual create tokens. But when i inject the JWTManager into my class and use `$jwtManager->create($user);`, then the token will contain a `username` property while i configured another property. 

I expected that the configuration also affected the JWT Manager. So from my POV its a bug.

**Comment by chalasr** [comment]
Hi,

The service is configured with a [method call](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/config/jwt_manager.xml#L12) to `setUserIdentityField` from the value given to the bundle configuration , this is just a default value. I agree it's weird to set it in the constructor, it should be on the property directly, I'll change that asap, but the config does work.
