### ISSUE TITLE
How to know if the token is almost valid

### ISSUE THREAD

**Issue by MustaphaGhlissi** [lexik/LexikJWTAuthenticationBundle#461]
Hi 

I am working with lexikauthentication 

I want to know if there is any way to know if the token is expired or not 

Regards,

**Comment by Bonfante** [comment]
for example
`eyJhbGciOiJSUzI1NiJ9.eyJ1c2VybmFtZSI6IjFhcGl1c2VyQGRpbmFtaWNhIiwiaWF0IjoxNTE5NjEwNTE4LCJleHAiOjE1MTk2MTQxMTh9.N57BYhDzC0uTaBzGkBLbs2wIbr3tQOz3KTkmUaCzIDGgBCe7hVXa8XjRZkxrFSdfRtheSzUwMH6ZyErC8rF3VPTG26yKhQ8nExmkCzggPRi-KXNB_E9qrwdlVFweJaYPaZklXHzzZOe0ueRmg6W686qdnZtne7spYm_xRhKF1RLahuPk8iL4ZX3IxD-jjj7iHAn5ZUWEou7bTp_hjsf5Nf2uidBFL937WqeOcCpRIARfryRIOLfOgDruV2MPb5RNojibVCNpvzE-a2RrKDOkLIqWm8o565EFmcl5UU_2wn2aYEfR_xF5MmkJOXXN7UaUuZo1E4pbmhs_a39d3SEgbeGSm1r4_h3sxFE3iPsJ5oj1SU4-TOg-V8txyecaAeVeGptpeSAREI_J2e5Dyjv_h1DSjjJ0MNVL2LZ_xRGb9EwdpPnLVznjAq8ud3SfzWfl79PEoV026LcONzxsiGc6CV6ModbMSXHPiBAm11k33F8FZmo_y2hLT1vI_pQOZrZkPsWUXcj9Qj_8MfAS5zn-OPM3qNNavyifK-r6CaC87e7l9FQ5hfv8xaLol5Cm0LhAc1iEB4CV9edEOB6eqyrDPBytb8QeVVSCAFWBVDfd1hK5KOdKvDjC9zFS0dX8M7JE-_ulZ-_FVh8YTLSNAP5M13xymFcTpip6WsbUgNNnWMk`

on https://jwt.io/ debugger
the payload is 

   {
     "username": "1apiuser@dinamica",
     "iat":   1519610518,
     "exp": 1519614118
   }

For client side, just look in exp

and for server side has a event.
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsjwt_expired---customizing-the-response-message-on-expired-token

**Comment by chalasr** [comment]
As @Bonfante said, you can listen on the events dispatched during the token verification process to check the value of any claim.
