### ISSUE TITLE
AuthenticationSuccessHandler issues

### ISSUE THREAD

**Issue by aequasi** [lexik/LexikJWTAuthenticationBundle#464]
I'm trying to inject this class into my Symfony 4.0 Service using autowiring, but the class isn't in the container this way.

Would be awesome if this class was made public! I think the failure one needs to be as well.

**Comment by chalasr** [comment]
Hey,

proper dependency-injection must work with private services using both explicit or auto wiring.
Are you sure that you're not trying to `get()` the success handler from a container?

**Comment by chalasr** [comment]
Fixed by #465
