### ISSUE TITLE
Exception message not returned when using onAuthenticationFailure

### ISSUE THREAD

**Issue by Walkoss** [lexik/LexikJWTAuthenticationBundle#470]
Hi,

I implemented a Guard Authenticator as @chalasr  recommended #468 to do and first I want to thank him.

I also extended my User entity to handle `isEnabled()` functionality https://symfony.com/doc/current/security/entity_provider.html#forbid-inactive-users-advanceduserinterface

But now when I try to get a token (login) from a non-active user I get the following response :
```json
{
	"code": 401,
	"message": "Bad credentials"
}
```

Here is my `onAuthenticationFailure` method on my guard authenticator:
```php
public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
{
    // Here $exception->getMessage() = "User account is disabled."

    return $this->failureHandler->onAuthenticationFailure($request, $exception);
}
```

Maybe `onAuthenticationFailure` function have to passed this exception message as the first parameter of `JWTAuthenticationFailureResponse`

```php
public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
{
    $event = new AuthenticationFailureEvent($exception, new JWTAuthenticationFailureResponse());

    $this->dispatcher->dispatch(Events::AUTHENTICATION_FAILURE, $event);

    return $event->getResponse();
}
```

But when I'm using a JWT token from a non-active user, I get the correct response:
```json
{
	"code": 401,
	"message": "Account is disabled."
}
```

**Comment by chalasr** [comment]
👍 Good catch, can you submit a PR? It should target the 2.4 branch
