### ISSUE TITLE
Symfony4 + jwt-auth rescipe always return {“code”:401,“message”:“Bad credentials”}

### ISSUE THREAD

**Issue by sensorario** [lexik/LexikJWTAuthenticationBundle#480]
I've no troubles with Symfony3. With Symfony4 is not working. I always get Bad Credentials.

https://stackoverflow.com/questions/49592019/userproviderloaduserbyusername-and-i-always-get-code401-messagebad-c

**Comment by sensorario** [comment]
Solved here https://github.com/sensorario/sf4-jwt-example

**Comment by Casporro** [comment]
How did you resolve the problem?

**Comment by sensorario** [comment]
pem keys if I remember correctly
