### ISSUE TITLE
Symfony 3.4 + FOSUserBundle + LexikJWTAuthenticationBundle

### ISSUE THREAD

**Issue by ocdevops** [lexik/LexikJWTAuthenticationBundle#486]
Could you update the documentation to be compatible with Symfony 3.4 version?
I used LexikJWTAuthenticationBundle with Symfony 2.8 without any issue, but after I started to use it on Symfony 3.4 I'm getting errors:

- route 'api_login_check' not found
- route '/api/login_check' -> return 404 error

**Comment by webdevilopers** [comment]
Have you added your routing?

`api_login_check:
    path: /api/login_check
`

* https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#configuration

This should be same in all Symfony versions. Symfony Flex will use XML instead of YAML.
