### ISSUE TITLE
no controller found for /api/login_check

### ISSUE THREAD

**Issue by MatSkor** [lexik/LexikJWTAuthenticationBundle#488]
Hi,

I'm new to Symfony and tried this bundle with his documentation but I only get the error: 
"no controller found for /api/login_check". I don't understand where it comes from. I already googling but I did not find a solution for my error. If someone can help, thank a lot.

Here is my code : 
` security.yml : 

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:    ^/api
            stateless:  true
            lexik_jwt:  ~

        main:
            pattern: ^/
            form_login:
                provider:               fos_userbundle
                csrf_token_generator:   security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }`

 `
config.yml:

    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
   
    parameters:
        locale: en

    framework:
        secret: '%secret%'
        router:
            resource:               '%kernel.project_dir%/app/config/routing.yml'
            strict_requirements:    ~
        form:               ~
        csrf_protection:    ~
        validation:         { enable_annotations: true }
        templating:
            engines: ['twig']
        default_locale:     '%locale%'
        trusted_hosts:      ~
        session:
            handler_id: session.handler.native_file
            save_path:  '%kernel.project_dir%/var/sessions/%kernel.environment%'
        fragments: ~
        http_method_override: true
        assets: ~
        php_errors:
            log: true
    twig:
        debug:              '%kernel.debug%'
        strict_variables:   '%kernel.debug%'

    doctrine:
        dbal:
            driver:     pdo_mysql
            host:       '%database_host%'
            port:       '%database_port%'
            dbname:     '%database_name%'
            user:       '%database_user%'
            password:   '%database_password%'
            charset:    UTF8

    orm:
        auto_generate_proxy_classes:    '%kernel.debug%'
        naming_strategy:                doctrine.orm.naming_strategy.underscore
        auto_mapping: true

    swiftmailer:
        transport:  '%mailer_transport%'
        host:       '%mailer_host%'
        username:   '%mailer_user%'
        password:   '%mailer_password%'
        spool:      { type: memory }

    fos_user:
        db_driver:      orm
        firewall_name:  main
        user_class:     AppBundle\Entity\User
        from_email:
            address:        "%mailer_user%"
            sender_name:    "%mailer_user%"
        registration:
            form:
                type: AppBundle\Form\RegistrationType

    lexik_jwt_authentication:
        private_key_path: %jwt_private_key_path%
        public_key_path:  %jwt_public_key_path%
        pass_phrase:      %jwt_key_pass_phrase%
        token_ttl:        %jwt_token_ttl%
`
`routing.yml:

    app:
        resource: '@AppBundle/Controller/'
        type: annotation

    fos_user_security:
        resource: "@FOSUserBundle/Resources/config/routing/security.xml"

    fos_user_profile:
        resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
        prefix: /profile

    fos_user_register:
        resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
        prefix: /register

    fos_user_resetting:
        resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
        prefix: /resetting

    fos_user_change_password:
        resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
        prefix: /profile

    fos_user:
        resource: "@FOSUserBundle/Resources/config/routing/all.xml"

    api_login_check:
        path: /api/login_check
`

**Comment by zim32** [comment]
What was the solution?
