### ISSUE TITLE
Request with token returns 401 Unauthorized

### ISSUE THREAD

**Issue by xavierfaucon** [lexik/LexikJWTAuthenticationBundle#49]
Hello,

Sorry to paste this here, but I don't find any answers on SO: http://stackoverflow.com/questions/27961635/lexik-jwt-returns-401-unauthorized

I have not hint where to start debugging this ?

Would you have any idea :-) ?

**Comment by xavierfaucon** [comment]
Hello,

In the end, the solution was to add the "fos_userbundle" provider to both "api_login" and "api" firewalls.

**Comment by slashfan** [comment]
Hi,

Sorry I didn't have the time to check it out. Thanks for the heads up ! I'll add it to the documentation :)
