### ISSUE TITLE
EventListener not fire

### ISSUE THREAD

**Issue by Ogek** [lexik/LexikJWTAuthenticationBundle#494]
![image](https://user-images.githubusercontent.com/25302511/40112724-472e6f4e-5907-11e8-8dc7-c0ca11cc2b18.png)

![image](https://user-images.githubusercontent.com/25302511/40112783-76a40f0e-5907-11e8-8312-8d05e03cd70c.png)

the event listener seem not firing. Any suggestions?

**Comment by Rebolon** [comment]
@Ogek what was the mistake and how did you fix it ?
