### ISSUE TITLE
 Symfony 4 + json_login with Legacy PHP application?

### ISSUE THREAD

**Issue by jry25** [lexik/LexikJWTAuthenticationBundle#496]
Hi there,

I'm using this great bundle along with api-platform to turn a legacy application into a better SPA.

The problem is when I use json_login, no cookie is set to authenticate the user. So on the first request when the legacy application boots the Symfony 4 Kernel the user is authenticated within the legacy application (through the legacy cookie) but not within the Symfony 4 application.

How can I achieve to keep the user authenticated within both applications ?
Should I set the cookie manually within the Symfony 4 application ? If it's the case, which event should I listen to in order to do so ?

Or is the best way to do it is to authenticate the user on the Symfony 4 application using the legacy cookie?

Thanks for helping me, any idea is welcome!

**Comment by chalasr** [comment]
Hey, this bundle is not in charge of `json_login`, that's a Symfony thing. 
Moreover, `json_login` is stateless by default.
We use github Issues to track bugs and feature requests, please use Symfony [support platfoms](https://symfony.com/support), you may find help there.
Thanks for your understanding.
