### ISSUE TITLE
Public/Private key as a string

### ISSUE THREAD

**Issue by aurimasniekis** [lexik/LexikJWTAuthenticationBundle#497]
Hey, I couldn't find anything related to use string (ENV variable) as private/public keys values.

Is there something already done or needs to be implemented?

**Comment by chalasr** [comment]
Hey, 

Already asked in https://github.com/lexik/LexikJWTAuthenticationBundle/issues/340 :)
Implementation in progress in #369, should be soon released.

Glad to see you're interested in this feature :)
Closing as duplicate !

**Comment by aurimasniekis** [comment]
Thanks somehow GitHub search didn't returned nothing on issues :)
