### ISSUE TITLE
Case insensitive login with Postgre not working ?

### ISSUE THREAD

**Issue by pesseyjulien** [lexik/LexikJWTAuthenticationBundle#498]
Hi, 

I setup fos_user + jwt on my symfony project and evertyhing is working fine except for a weird case.

On my dev env, if I try to login with different variation (with all lowercase, all upercase, one upercase, etc.) of one user email address, it works fine. 

But on my integration/prod envs, it's giving me 'Bad credentials' if I do not provide the email address with the exact case.

The only difference between the envs is the database. I'm running mysql on local, and postgre on integration/prod.

Could it be the problem ?

Thanks in advance for your help,
Julien

**Comment by chalasr** [comment]
Hey, the issue indeed comes from the different RDBMS used across your environments.
https://wiki.postgresql.org/wiki/Things_to_find_out_about_when_moving_from_MySQL_to_PostgreSQL says:

> PostgreSQL is case-sensitive for string comparisons. The field "Smith" is not the same as the field "smith". This is a big change for many users from MySQL [...]

This difference between your environments does not seem sane, I'd suggest to choose one that you can use in all environments.
