### ISSUE TITLE
Wrong section config in the doc

### ISSUE THREAD

**Issue by ameur-frikha** [lexik/LexikJWTAuthenticationBundle#506]
to configure lexik_jwt_authentication:
please change keys  **secret_key, public_key** to **private_key_path** and  **public_key_path**

**Comment by chalasr** [comment]
Master needs to be released, please refer to the 2.4 branch meanwhile. Keeping this open until released.

**Comment by chalasr** [comment]
v2.5 has been released, closing as resolved :)
