### ISSUE TITLE
{"code":401,"message":"JWT Token not found"}

### ISSUE THREAD

**Issue by Ezar101** [lexik/LexikJWTAuthenticationBundle#520]
Hello
I need help please.
I installed and configured api platform and wanted to implement FosUser and LexikJWTAuthentication in my API.
When I go to the url /login_check with the good login I get the token, but when I try to access the API I get displayed {"code":401,"message":"JWT Token not found"}
Thank you

**Comment by chalasr** [comment]
Duplicate of #300? See https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#important-note-for-apache-users
