### ISSUE TITLE
Bad credentials bcrypt

### ISSUE THREAD

**Issue by T-Nagui** [lexik/LexikJWTAuthenticationBundle#527]
hi, i find a problème with authentification with JWT: 

i'm using guard and encoder is made with bcrypt. when i regester new user and try to login him i get always  
`{"code":401,"message":"Bad credentials"}`

Security.yml : 
`
security:
    encoders:
        Prototype\ConfigBundle\Entity\AppUser:
            algorithm: bcrypt
            cost: 16
    role_hierarchy:
        ROLE_SUPER_USER: ROLE_SUPER_USER
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_OPERATOR: ROLE_OPERATOR
        ROLE_TECHNICIAN: ROLE_TECHNICIAN
        ROLE_SUPERVISOR: ROLE_SUPERVISOR
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: Prototype\ConfigBundle\Entity\AppUser
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_docs:
            pattern: ^/api/doc
            anonymous: true
        login:
            pattern:  ^/api/user/auth/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/user/auth/login_check
                username_parameter: username
                password_parameter: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            logout: true
        api:
            pattern:  ^/api
            stateless: true
            anonymous: true
            provider: db_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/auth/login_check , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user/auth/register , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }`

**Comment by MehdyDriouech** [comment]
hello, why did you close the issue ? Did you find a fix ? Could you share it ?
