### ISSUE TITLE
Login using /api/login

### ISSUE THREAD

**Issue by TheFlow95** [lexik/LexikJWTAuthenticationBundle#53]
Hello,
I want to use your bundle to create a secure API for my iOS app but I don't understand how to get the token using the URL. I configured the bundle as you said but now I don't know what to do...
Can you help me ?
Thanks

PS: I think you are french but I'm not sure

**Comment by slashfan** [comment]
Hi,

Yes we are french :) But as the issue might be interesting to other people let's continue in english. 

The workflow is described here https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#usage.
But to sum up the first thing you need to do is obtain a token by sending the user credentials from your iOS app to your symfony2 application. 

If you followed the method described in the documentation, just send them through a POST request to the /api/login_check uri. Just like you would do with a classic HTML form. 
If the authentication is successful, you'll obtain a reusable token.

Let me know if you still have the problem.

**Comment by TheFlow95** [comment]
Hi,
I think my config isn't good because I get a "no route found" when I call /api/login_check in my navigator

**Comment by slashfan** [comment]
Try the sandbox : https://github.com/slashfan/LexikJWTAuthenticationBundleSandbox
Everything is configured and working, and there's a sample application to demonstrate usage with a javascript client (angularjs).

**Comment by slashfan** [comment]
Hi, did you manage to manage to make it work ?

**Comment by TheFlow95** [comment]
Hello,

I followed all the steps, I even used the same code as the sandbox and my /api/login_check uri give me that error:
> Unable to find the controller for path "/api/login_check". Maybe you forgot to add the matching route in your routing configuration? 

I don't know what is the problem...
Can you help me please ?

**Comment by tbachir** [comment]
It's for sure too late for you, but it may help other people. 

This error is caused because you are trying to access to "/api/login_check" with a GET request, but only POST requests are allowed.

**Comment by eissasoubhi** [comment]
You need to make sure that you are sending a **POST** request with **HEADER** `'content-type': 'application/json'` and the data must be in **JSON**
