### ISSUE TITLE
Error 500 in Login

### ISSUE THREAD

**Issue by Lory1990** [lexik/LexikJWTAuthenticationBundle#531]
I am new to LexikJWTAuthenticationBundle and I am facing a 500 Internal server error like this:

```
    {
        "error": {
            "code": 500,
            "message": "Internal Server Error"
        }
    }
```

when I pass a form-data to `localhost:8000/api/v1/authorize` like this:

```
    _username: user
    _password: password
```

I ran also the command `php bin/console lexik:jwt:check-config` and the result is `The configuration seems correct.`

This is my `Securty.yml` file

```
    firewalls:        
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_login:
            pattern:  ^/api/v1/authorize
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/v1/authorize
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false           
        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

```

What is the problem? May I debug the LexikJWTAuthenticationBundle?

Thanks

**Comment by flohw** [comment]
Hello,

I think you can get more information on the profiler. You have to reach the page manually at http://localhost/_profiler and find the request you want to debug.

**Comment by fd6130** [comment]
Error 500 mean server-side error. You can check your log file in `/var/log/dev.log` or check your profiler.
