### ISSUE TITLE
Unable to create a signed JWT from the given configuration "HEROKU"

### ISSUE THREAD

**Issue by FA-TECHNOLOGIE** [lexik/LexikJWTAuthenticationBundle#538]
request.CRITICAL: Uncaught PHP Exception Lexik\Bundle\JWTAuthenticationBundle\Exception\JWTEncodeFailureException: "Unable to create a signed JWT from the given configuration." at /app/vendor/lexik/jwt-authentication-bundle/Encoder/LcobucciJWTEncoder.php line 41 {"exception":"[object] (Lexik\\Bundle\\JWTAuthenticationBundle\\Exception\\JWTEncodeFailureException(code: 0): Unable to create a signed JWT from the given configuration. at /app/vendor/lexik/jwt-authentication-bundle/Encoder/LcobucciJWTEncoder.php:41)"} []

Thanks,

**Comment by FA-TECHNOLOGIE** [comment]
> ok résolu 
-> Il me manquait les fichiers .pem car ignorés lors du push (git)
        -> à enlever du .gitignore (solution temporaire) à deplacer dans exemple --> var/jwt/private.pem  
            ###> lexik/jwt-authentication-bundle ###
            /config/jwt/*.pem
            ###< lexik/jwt-authentication-bundle ###
-> Renseigner dans l'interface Heroku les const. JWT 

Bonne journée !

**Comment by chalasr** [comment]
Good to know :)
