### ISSUE TITLE
Too many user roles within the token payloads crashes the server

### ISSUE THREAD

**Issue by kanonhian** [lexik/LexikJWTAuthenticationBundle#550]
While working with 70-80 roles in the system there was no problem, but when the number raised to 130 then the server threw a bad request error like [this](https://support.mozilla.org/en-US/questions/1201869).

In my case, because  I had to previously  override the **loadUser** method of the **JWTTokenAuthenticator** and as result I  don't need the payload's roles anymore, what I did  was to exclude the user roles from the payload before building the token( which means override the **create** method of the **jwtManager**), this way the size of the token remains constant.

Is there any way to solve this issue without touching the web server configuration?

**Comment by chalasr** [comment]
Perhaps you need to shorten your user roles names (and use some kind of role map to convert them to their full names?). Sorry, I have no clue for this issue as it's web-server related, you'll need to workaround it on your side. Thank you
