### ISSUE TITLE
How to create a translation for my own bundle?

### ISSUE THREAD

**Issue by devkbsc** [lexik/LexikJWTAuthenticationBundle#551]
Hello, 
Thanks for giving some more detailled information about creating a new translation for all my bundles. 

How to add a new domaine?

**Comment by chalasr** [comment]
We use github issues for tracking bugs and feature requests, and translations are not part of the bundle scope at all. Please use [Symfony official support platforms](https://symfony.com/support) instead.
Thanks for your understanding.
