### ISSUE TITLE
Authorization in an already existing JWT protected API with a secret key

### ISSUE THREAD

**Issue by enekochan** [lexik/LexikJWTAuthenticationBundle#552]
I've been looking for info regarding this but haven't found any so I open this "issue" which is more a "question". I have an API in Symfony 3.4 working with LexikJWTAuthenticationBundle. We use Angular 2+ to work with it and everything is fine. Now we want to create a WordPress plug-in that will communicate with this existing API (not with Angular 2+ but that's not the problem). We don't want to ask for or store (in the WordPress space) the user and password of our users so I would like to use a pre-generated secret string given from our application to the user and then the user should paste that secret in the configuration of our plug-in in WordPress. That secret should be used to generate a JWT token.

Is there a way I can get a valid JWT token from this secret string with an already existing secure approach? Or should I just create an end-point to exchange the secret for a JWT token? I'm not sure how to deal with the secure exchange of the secret and the JWT token. Does anybody know a better approach for this?

Thanks.

**Comment by enekochan** [comment]
The solution to this was to create a [custom authenticator class](https://symfony.com/doc/3.4/security/guard_authentication.html#step-1-create-the-authenticator-class) and use [multiple guard authenticators](https://symfony.com/doc/3.4/security/multiple_guard_authenticators.html) in the same path.

**Comment by chalasr** [comment]
Sorry for the lack of feedback though! And thank you for sharing your solution
