### ISSUE TITLE
Change Entry Point ?

### ISSUE THREAD

**Issue by vincentdieltiens** [lexik/LexikJWTAuthenticationBundle#56]
Hi,

I would change the body of entry point when the user tries to use a protected API without being authenticated.
The default body is :
```json
{
    "code": 401,
    "message": "Invalid Credentials"
}
```

To be consistent with other message errors, I would like to have :
```json
{
    "error": {
        "code": 401,
        "message": "Invalid Credentials"
    }
}
```

Is there a way to do that ?

Thanks,

Vincent

**Comment by slashfan** [comment]
Hi,

There is no way to do that right now, so your best option might be to replace the [JWTEntryPoint](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Http/EntryPoint/JWTEntryPoint.php) class by your own, and then override the `lexik_jwt_authentication.security.authentication.entry_point.class` parameter to make use of it.

Let me know it it helps :)

**Comment by vincentdieltiens** [comment]
Hi,

Mmmh, I was aware of this solution but I don't like to override parameters that I'm not the "owner".

An other solution is to fork this and let the possibility to set the entry point class as a parameter. What do you think ?

**Comment by slashfan** [comment]
There is no problem in overriding class parameters of a bundle, that's what they are for. 

But I'll try to dispatch an event so the response can be modified like in the [AuthenticationFailureHandler](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Http/Authentication/AuthenticationFailureHandler.php).
