### ISSUE TITLE
"Invalid JWT Token" sometimes in tests

### ISSUE THREAD

**Issue by pcholewa** [lexik/LexikJWTAuthenticationBundle#561]
Hi,

I got sometimes "Invalid JWT Token" in functional tests (phpunit). When i run tests again, fail tests are fixed, but got same error in other tests. Sometimes tests are all passed.
Someone can help?

**Comment by chalasr** [comment]
could it be due to expiration? You can set the `token_ttl` config option to `null` for the test env in order to get rid of timing issues.

**Comment by DavG** [comment]
Can be the iat too. If you have a small difference of time between your apps.

**Comment by pcholewa** [comment]
solved, thx for help!

**Comment by david-vde** [comment]
> solved, thx for help!

Hello How did you solved your issue ? I'm going crazy with invalid_token issue in env test.
Thank you

**Comment by ivandziub** [comment]
Hey guys. I'm getting the same problem :(
