### ISSUE TITLE
Shouldn't you switch to alternative signing library

### ISSUE THREAD

**Issue by pmouawad** [lexik/LexikJWTAuthenticationBundle#562]
Hello,
AFAIU you use:

- "namshi/jose":"^7.2"

Looking at the github of namshi/jose you have a deprecation notice saying:

`
    Hi there,
    as much as we'd like to be able to work on all of the OSS in the world, we don't actively use this library anymore This means that new features / bugfixes / etc will only be merged based on pull requests from external contributors, and we strongly recommend you look for a long-term alternative.

    If you're looking for an actively maintained library check firebase/php-jwt out!
`

This library is not mentioned in JWT.IO as library for PHP:

- https://jwt.io/

Isn't it dangerous in terms of security to rely on a deprecated library ? 
AFAIK, there is no current known CVE for version 7.2 but there was one for example for 5.0.

Regards

**Comment by chalasr** [comment]
Hey, we already switched to [lcobucci/jwt](https://github.com/lcobucci/jwt) which is the one used by default. 
The `namshi/jose` requirement is for backward compat only, you get deprecation notices with proper warnings if you use it.
We will drop the requirement in 3.0 with all the `namshi/jose` integration.
See https://github.com/lexik/LexikJWTAuthenticationBundle/issues/389 and related PR for details

**Comment by pmouawad** [comment]
@chalasr , Thanks a lot for your rapid feedback.
Sorry for the noise.
