### ISSUE TITLE
The login_check example curl does not work on Windows 10

### ISSUE THREAD

**Issue by mortenhartvig** [lexik/LexikJWTAuthenticationBundle#565]
The following (in the example code) does not work (it returns invalid JSON format).

`curl -X POST -H "Content-Type: application/json" http://localhost:8000/api/login_check -d '{"username":"johndoe","password":"test"}'`

When debugging the code (Windows 10, php bin/console server:run) i see, that i have to change the POST paramaters, to double quotes (else json_decode returns NULL, thus not logging in - using PHP 7.2)

The following works for me on Windows (Windows command prompt and PHPstorm console/GIT bash tested)

`curl -X POST -H "Content-Type: application/json" http://localhost:8000/login_check -d "{\"username\":\"johndoe\",\"password\":\"test\"}"`

**Comment by mortenhartvig** [comment]
(please disregard the different use of URI path (/api/login_check vs /login_check). I was simply playing around, look at the -d paramater :) Maybe it works just fine on linux/unix based systems. I only tested on Windows 10.

**Comment by chalasr** [comment]
PR welcome to improve the doc in that regard.
