### ISSUE TITLE
symfony/security-bundle v3.4.0 conflicts with symfony/symfony[v3.2.14].

### ISSUE THREAD

**Issue by JonnyD** [lexik/LexikJWTAuthenticationBundle#566]
Problem 1
    - Conclusion: don't install lexik/jwt-authentication-bundle v2.5.4
    - Conclusion: don't install lexik/jwt-authentication-bundle v2.5.3
    - Conclusion: don't install lexik/jwt-authentication-bundle v2.5.2
    - Conclusion: don't install lexik/jwt-authentication-bundle v2.5.1
    - Conclusion: remove symfony/symfony v3.2.14
    - Installation request for lexik/jwt-authentication-bundle ^2.5 -> satisfiable by lexik/jwt-authentication-bundle[v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.4].
    - Conclusion: don't install symfony/symfony v3.2.14
    - lexik/jwt-authentication-bundle v2.5.0 requires symfony/security-bundle ^3.4|^4.0 -> satisfiable by symfony/security-bundle[v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6].
    - symfony/security-bundle v3.4.0 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.1 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.10 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.11 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.12 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.13 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.14 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.15 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.16 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.17 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.2 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.3 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.4 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.5 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.6 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.7 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.8 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v3.4.9 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.0 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.1 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.10 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.11 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.12 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.13 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.14 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.2 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.3 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.4 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.5 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.6 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.7 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.8 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.0.9 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.1.0 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.1.1 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.1.2 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.1.3 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.1.4 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.1.5 conflicts with symfony/symfony[v3.2.14].
    - symfony/security-bundle v4.1.6 conflicts with symfony/symfony[v3.2.14].
    - Installation request for symfony/symfony (locked at v3.2.14) -> satisfiable by symfony/symfony[v3.2.14].

**Comment by Spomky** [comment]
The error description is quite clear: your application is based on Symfony 3.2 and you try to install the bundle that requires at least Symfony 3.4.

To solve that, you should first update your Symfony dependency to 3.4.
