### ISSUE TITLE
[QUESTION] Get images from server

### ISSUE THREAD

**Issue by JuanWilde** [lexik/LexikJWTAuthenticationBundle#575]
Hi. Since I implemented this library I have an issue when trying to show images from server in my application (like profile picture).

I'm storing them in a server folder and I have a path to retrieve them. But now I get an error because I supposed to send the token in the header to perform the GET from my Angular Frontend...

I saw I can include the token within the URL, but I think it is not secure since that token will be stored in the logs files.

And also I can't remove that URL from the security because anyone could access to that images.

Any clue about how to solve it?

Thanks in advance

**Comment by mu4ddi3** [comment]
You should send token in request header for example: "Authorization: Bearer JWT_TOKEN"

If you use JS framewowrk as frontend app, you could use for example *axios* to send some requests therefore  you need to configure it to send that header. 

I think it has nothing  to do with lexik/LexikJWTAuthenticationBundle

**Comment by JuanWilde** [comment]
Yes, this is what I did at the end. I was wondering if there was an easier solution, but I did it in the way you mention. Thanks :)

**Comment by chalasr** [comment]
Sending the token via `Authorization` header is the best way to achieve this to me
