### ISSUE TITLE
Type error: Argument 3 passed , when in login_check 

### ISSUE THREAD

**Issue by abdallahmaali** [lexik/LexikJWTAuthenticationBundle#587]
i have this prblem i made reinstall  for the bundle and i checked the configuration i can't solve this problem, i also delete all cache files but same problem , anybody could help me plz 

`Type error: Argument 3 passed to Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Provider\JWTProvider::__construct() must implement interface Symfony\Component\EventDispatcher\EventDispatcherInterface, string given, called in /Applications/XAMPP/xamppfiles/htdocs/daman/var/cache/dev/ContainerPknmejc/getSecurity_Authentication_Provider_Jwt_ApiService.php on line 10
`--

**Comment by chalasr** [comment]
Just released v2.6.1 which includes the fix for this regression, upgrading should solve the issue.
Thanks for reporting.

**Comment by abdallahmaali** [comment]
thanks for your quick response , it's working
