### ISSUE TITLE
Cannot autowire service "Lexik\Bundle\JWTAuthenticationBundle\Services\JWT Manager": argument "$userIdClaim" of method "__construct()" has no type-hint , you should configure its value explicitly.

### ISSUE THREAD

**Issue by aayaresko** [lexik/LexikJWTAuthenticationBundle#590]
Cannot autowire service "Lexik\Bundle\JWTAuthenticationBundle\Services\JWT Manager": argument "$userIdClaim" of method "__construct()" has no type-hint , you should configure its value explicitly.

symfony 4 symfony/lts dev-master

lexik version v2.6.1

**Comment by aayaresko** [comment]
the issue appears after composer update is executed.

**Comment by aayaresko** [comment]
PHP 7.1.23-1+ubuntu16.04.1+deb.sury.org+1

**Comment by aayaresko** [comment]
symfony/framework-bundle - v4.1.8

**Comment by chalasr** [comment]
Can you confirm that #593 fixes your issue?

**Comment by aayaresko** [comment]
@chalasr , hello, of course.
tried with "lexik/jwt-authentication-bundle": "dev-master" - the issue persists.

**Comment by aayaresko** [comment]
oh durn, that was silly... one sec...

**Comment by aayaresko** [comment]
@chalasr , yeap, I confirm that it fixes the issue.

**Comment by aayaresko** [comment]
closing the issue.
