### ISSUE TITLE
Symfony 3.4.18 + FosUserBundle 2.0 + LexikJWT

### ISSUE THREAD

**Issue by nasrithamer** [lexik/LexikJWTAuthenticationBundle#594]
Hi,
I want to to configure LexikJWT with fosuserbunle 2.0 but i receive with postman this always 
![bug_username](https://user-images.githubusercontent.com/13709609/49244486-345d8b80-f410-11e8-9f4c-a06893cd4534.png)

my security.yaml:

`
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                username_parameter: _username
                password_parameter: _password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            provider: fos_userbundle
            stateless: true
            lexik_jwt: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
        

        

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
`

**Comment by chalasr** [comment]
Hey,
The error gives a good hint about what happens: a `_username` key is expected, while your request seems to contain a `username` key instead, changing the key should fix the issue.
Also note that your security configuration uses `lexik_jwt: ~` which is deprecated, only the `guard` key is necessary.

**Comment by chalasr** [comment]
Other alternative: change the `username_parameter` and `password_parameter` values to `username` and `password` respectively (no leading underscore).

**Comment by nasrithamer** [comment]
thank you @chalasr , i have changed what you said but i have an other BUG
![image](https://user-images.githubusercontent.com/13709609/49285144-f8213e00-f496-11e8-83da-e5b3e27b68d7.png)

`
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                username: username
                password: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            provider: fos_userbundle
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true
        

        


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
`

**Comment by chalasr** [comment]
it should be
```
username_parameter: username
password_parameter: password
```

**Comment by nasrithamer** [comment]
the returns my friend when i change to
username_parameter: username
password_parameter: password
 maybe the problm in my request in POSTMAN 
key and value ?
![image](https://user-images.githubusercontent.com/13709609/49291197-c4034880-f4a9-11e8-8c92-a90e9b601e7e.png)

**Comment by chalasr** [comment]
Request parameters need to be `form-data`, not query params:

![screen shot 2018-11-30 at 15 59 43](https://user-images.githubusercontent.com/7502063/49699299-9d42c180-fbcf-11e8-944b-008059bdea73.png)

We use github issues to track bugs and feature requests only. For questions, please continue on [Symfony support platforms](https://symfony.com/support). Thanks for your understanding.
