### ISSUE TITLE
No Route found for POST /login With Api Platform SF4

### ISSUE THREAD

**Issue by tmorea05** [lexik/LexikJWTAuthenticationBundle#596]
Hello Everybody, 

This is the first time that it happens to me and i cannot understand why ?
I try to authenticated my users to my api through LexikJWTAuthenticationBundle, but it doesn't generate the route /login ?

Here this is my security.yaml

`
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]

    encoders:
        App\Entity\Actor\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        main:
            provider: entity_provider
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
`

And when i check my routes no /login route appears and when i try to call it with Postman obviously i got a 404 HTTP status code.

Can someone help me with that i don't want to make a custom controller for that i really want to use this.

Thank you a lot for your time,
This is such an enigma for me.

Thomas.

**Comment by longnd** [comment]
@tmorea05 how did you fix that issue?
