### ISSUE TITLE
login_check Invalid JSON Bad Request

### ISSUE THREAD

**Issue by vincauddu29** [lexik/LexikJWTAuthenticationBundle#598]
Hello I have a problem with login_check. When I go to the api/login_check POST with Postman, I obtain an error 400 Bad Request and the message error is Invalid JSON.

My security.yml :

`jwt:
            lexik_jwt:
                class: App\Entity\Utilisateur

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
                pattern: ^/api/login
                stateless: true
                anonymous: true
                json_login:
                        check_path:             /api/login_check
                        success_handler:        lexik_jwt_authentication.handler.authentication_success
                        failure_handler:        lexik_jwt_authentication.handler.authentication_failure

        api:
                pattern: ^/api
                stateless: true
                provider: jwt
                guard:
                        authenticators:
                               - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: true

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
`

My routes.yml :
`
api_login_check:
    path: /api/login_check
`

Can you help me ?

Sorry for my english, I'm french

**Comment by chalasr** [comment]
Hello, if the error says invalid json, that's probably because you are sending invalid json, thus I need to see the JSON you are sending in order to help :)

**Comment by vincauddu29** [comment]
![postman_001](https://user-images.githubusercontent.com/18056722/50172454-6ec29600-02f5-11e9-9cb0-49305af12202.png)

**Comment by Livda** [comment]
That's not a JSON you send. If you pay attention to your URL, your parameters are in the URL, but you want them in the body of your request.
So instead of putting them in the "Params" tab, go to the "Body" tab, select "raw", then click sur "Text" on the right, select "JSON (application/json)" and in the text area bellow you can entrer your parameters in JSON like that
```json
{
  "username": "donvalvi",
  "password": "password"
}
```

**Comment by chalasr** [comment]
Closing as explained.
