### ISSUE TITLE
Config variables in the .env.local file problem

### ISSUE THREAD

**Issue by zahardev** [lexik/LexikJWTAuthenticationBundle#605]
I try to move JWT_PASSPHRASE variable to the .env.local file and it fails with error: 
"Environment variable not found: "JWT_PASSPHRASE".". 
If I setup JWT_PASSPHRASE in the .env file, it works perfectly. 
It looks like for now bundle doesn't support this feature. But what if I don't want to store this variable in the version control system?

**Comment by mu4ddi3** [comment]
I use jwt with new env structure without problem.

**Comment by Najki** [comment]
I have a similar issue.

```
# .env
APP_SECRET=ThisTokenIsNotSoSecretChangeIt
# ...
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=secret
```

```
#.env.test
APP_SECRET=testSecret
JWT_SECRET_KEY='%kernel.project_dir%/config/jwt/test-private-nopass.pem'
JWT_PUBLIC_KEY='%kernel.project_dir%/config/jwt/test-public.pem'
JWT_PASSPHRASE=
```

I've placed a simple debug in my test:

```php
var_dump('JWT_SECRET_KEY', $_ENV['JWT_SECRET_KEY']);
var_dump('JWT_PUBLIC_KEY', $_ENV['JWT_PUBLIC_KEY']);
var_dump('JWT_PASSPHRASE', $_ENV['JWT_PASSPHRASE']);
```

You'll never guess what the output is. Seems like all environment variables besides `JWT_*` env's are read from `.env.test`, but `JWT_*` env's are read from `.env` file... It doesn't make much sense and I'm not sure if it's a problem with your bundle or Symfony itself.

```
string(10) "APP_SECRET"
string(13) "s$cretf0rt3st"
string(14) "JWT_SECRET_KEY"
string(43) "%kernel.project_dir%/config/jwt/private.pem"
string(14) "JWT_PUBLIC_KEY"
string(42) "%kernel.project_dir%/config/jwt/public.pem"
string(14) "JWT_PASSPHRASE"
string(6) "secret"
```

Using Symfony 4.2.9 (with Dotenv 4.2.9) and Lexik 2.6.3.

**Comment by fd6130** [comment]
Having no problem here since `.env.local` or `.env.local.php` will overwrite the `.env`.

Using Symfony 4.4 and 5.3.

**Comment by chalasr** [comment]
I'm going to assume this was more a symfony/dotenv issue and close the ticket. If you still run into this, please comment so we can consider to reopen.
Thanks.
