### ISSUE TITLE
Session data destruction on server

### ISSUE THREAD

**Issue by med-seif** [lexik/LexikJWTAuthenticationBundle#607]
Hello,

When activating The bundle on our distant server, $_SESSION data becomes empty in some responses.

I have a page that loads 6 simultaneous ajax requests from my API where the bundle is installed.

in my app.php I added these lines to test

    var_dump(session_id()); // returns always the some session ID and that's what I'm looking for
    var_dump($_SESSION); // in the 5th request, prints that this is an empty array

Disabling the bundle will not produce that strange behaviour.

Any Idea?

Thank you

**Comment by Med-Seif** [comment]
The changing of the Session ID is occuring when Kernel has handled the request
    var_dump(session_id());
    $response = $kernel->handle($request);
    var_dump(session_id()); // not the same value as the previous var_dump

**Comment by chalasr** [comment]
I have no idea how the bundle can be the cause of this behavior. I would need a small app with enough code to reproduce the bug, forking https://github.com/chalasr/lexik-jwt-authentication-sandbox might help.
