### ISSUE TITLE
How execute login after register user?

### ISSUE THREAD

**Issue by JellyBellyDev** [lexik/LexikJWTAuthenticationBundle#61]
Hi,
after registration user i would autenticate the user.

In my controller after registration i tried this:

    $response = $this->forward(
        'AppBundle:Rest\V1\Security:check',
        array(
            'email' => $user->getEmail(),
            'password' => $user->getPlainPassword(),
        )
    );

but i receive this error message: 

    {
        "code": 500,
        "message": "You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.",
        "errors": null
     }

I think that this isn't the right way to do this. 
how can i do? 
Thank you so much!

**Comment by slashfan** [comment]
Hi,

You can use the [JWTManager::create($user) method](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Services/JWTManager.php)  (`lexik_jwt_authentication.jwt_manager` service) to generate a token for any given user object. Then you can pass it along a response like in the [AuthenticationSuccessHandler](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Http/Authentication/AuthenticationSuccessHandler.php) class.

Regards.

**Comment by JellyBellyDev** [comment]
I edit my code in this way:

```php
   //stuff
   if ($user) {
       /** @var JWTManager $jwtManager */
       $jwtManager = $this->get('lexik_jwt_authentication.jwt_manager');
       $jwt = $jwtManager->create($user);
       $response = new JsonResponse();
       $event = new AuthenticationSuccessEvent(array('token' => $jwt), $user, $request);
       $event->setResponse($response);
       $response->setData($event->getData());
       return $response;
   }
```

and work!! thank you so much!

I remove only call to dispatch event. I thought that was not needed. I was wrong?
Thanks a lot again

**Comment by slashfan** [comment]
You should dispatch the event, unless you are absolutely sure there is no listener registered for it.

If you choose not to dispatch it, then there is no need to create it. Just use `$response->setData(array('token' => $jwt))` and you should be good to go.

**Comment by JellyBellyDev** [comment]
i edit my code with dispatch use:

```php
            if ($user) {
                /** @var JWTManager $jwtManager */
                $jwtManager = $this->get('lexik_jwt_authentication.jwt_manager');
                /** @var EventDispatcher $dispatcher */
                $dispatcher = $this->get('event_dispatcher');

                $jwt = $jwtManager->create($user);
                $response = new JsonResponse();
                $event = new AuthenticationSuccessEvent(array('token' => $jwt), $user, $request);
                $event->setResponse($response);
                $dispatcher->dispatch(Events::AUTHENTICATION_SUCCESS, $event);
                $response->setData($event->getData());

                return $response;
            }
```

sounds good! ;)
