### ISSUE TITLE
Token validation service

### ISSUE THREAD

**Issue by BentCoder** [lexik/LexikJWTAuthenticationBundle#614]
Hi,

Is there an existing service that we can call to verify if the token is valid/expired or not?

Thanks

e.g.
```php
class MyTokenService
{
   public function verify(Request $request)
   {
      $token = $request->header->get('authorization');
      $isValid = $this->someLexikService->isTokenValid($token); // Something like this
      ....
   }
}
```

**Comment by nipeharefa** [comment]
@BentCoder 
actually by default all request with bearer authentication will validate automatically, if you have configured this library. But you can see more detail on [code](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Authentication/Provider/JWTProvider.php#L76-L95)

**Comment by ashish-russmediatech** [comment]
Hello @nipeharefa ,
I want to check if the Token is valid/expired before creating a new token. If my client sending me a token which is expired, I want to create a new one without making him to send a new api call to create a token. So how can I check if the token which my client has sent me in a api call is valid or not?
Or what if client want to check if the token id valid or not with an api call?

Thank You,
Ashish Shah

**Comment by ashish8488** [comment]
Hello @nipeharefa ,
I want to check if the Token is valid/expired before creating a new token. If my client sending me a token which is expired, I want to create a new one without making him to send a new api call to create a token. So how can I check if the token which my client has sent me in a api call is valid or not?
Or what if client want to check if the token id valid or not with an api call?

Thank You,
Ashish Shah

**Comment by nipeharefa** [comment]
@ashish8488 You can decoded token, look at `exp` or `expired`. 
But i recomended to use refresh token flow, please look at [https://github.com/gesdinet/JWTRefreshTokenBundle](https://github.com/gesdinet/JWTRefreshTokenBundle)

**Comment by ashish-russmediatech** [comment]
@nipeharefa ,
Thank you.

**Comment by chalasr** [comment]
Closing as explained, thanks @nipeharefa
