### ISSUE TITLE
How Can I Place The JWT Token In A Cookie Instead Of The Body?

### ISSUE THREAD

**Issue by piperRyan** [lexik/LexikJWTAuthenticationBundle#616]
Haven't found any relevant docs on how to do this. It would be more preferable to doing this as suppose storing it in memory or local storage.

**Comment by stipic** [comment]
Check token extractors: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#full-default-configuration

**Comment by chalasr** [comment]
Thanks @stipic.
Closing here.

**Comment by piperRyan** [comment]
@stipic or @chalasr I don't think that is what I want at all as far as I can tell? If I am understanding correctly the token extractor is just looking for the token after authentication. Where I am trying get the initial response after authenication to be a cookie instead of a json response.  I have in my `lexik_jwt_authentication.yaml` 

```
    token_extractors:
            # check token in a cookie
            cookie:
                enabled: true
                name:    BEARER
```

But this still sends the token in the body of the response.

**Comment by piperRyan** [comment]
Or maybe I got this figured out? I need to extend the JWTTokenAuthenticator and follow the same idea as found in [!76](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/76)? Could either one of you confirm this is the right track?
