### ISSUE TITLE
? Does the client need to send also the session id with the jwt token 

### ISSUE THREAD

**Issue by AbdessamadElouarti** [lexik/LexikJWTAuthenticationBundle#619]
The android client needs to send the jwt token as well as the sessionID in the request header in order to get the 200 token validation response. if it sends only the token the api returns invalid jwt token message.

**Comment by chalasr** [comment]
Hi,

This bundle is responsible for delivering and verifying tokens server-side, but not for the client-side usage. If you need to perform extra checks on extra data depending on your client (being android here), you may want to have a look at [the relevant part of the documentation](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md).

If you need more support, please checkout stackoverflow or the symfony-devs slack. We use Github issues for bug reports and feature requests.
Thanks for your understanding.
