### ISSUE TITLE
Retrieve User from given Token, from an unsecured path

### ISSUE THREAD

**Issue by Ph3nol** [lexik/LexikJWTAuthenticationBundle#62]
Hi,

First congrats for this awesome and amazing bundle that I'm currently using for all my WebServices projects.

My little question:
What is the best way to retrieve a user from an unsecured path?

My context: 
I have a `/api/1/example/{id}.json` endpoint, to access an element informations.
This path is unsecured.
I'd like to use an optional token, and retrieve matching user if passed through the Request headers.
The problem is that without passing through the firewall (and so the bundle security listener), my token-user association is not handled.

Any idea about this?

Thank you so much.

**Comment by slashfan** [comment]
Hi,

I think  you could use the [JWTManager::decode(TokenInterface $token)](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Services/JWTManager.php#L79) method. 
Unfortunately it only accepts a TokenInterface so you would have to first create a new [JWTUserToken](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Authentication/Token/JWTUserToken.php) and pass it your token in the [setRawToken($rawToken)](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Authentication/Token/JWTUserToken.php#L32) method.

If the token is successfully decoded it will return an array containing the user identity (by default the username). Then it's up to you to retrieve your user from it.

Of course, it's all theory ! Let me know if it works :)

**Comment by Ph3nol** [comment]
I was thinking about using this solution yesterday, but ignoring if a better practice was planned for an incoming release.

I'll test it today and keep you informed about it.
Thanks! :)

**Comment by Ph3nol** [comment]
I confirm this theory works perfectly! :)

**Comment by slashfan** [comment]
Great :)
