### ISSUE TITLE
Correction proposal for the readme

### ISSUE THREAD

**Issue by valentin-harrang** [lexik/LexikJWTAuthenticationBundle#623]
Hi,

In the "1. Obtain the token" section of the README.md, there is this line to test getting the token with a simple curl : `curl -X POST -H "Content-Type: application/json" http://localhost/api/login_check -d '{"username":"johndoe","password":"test"}'` .

I encountered the following problem on Windows 10 : https://stackoverflow.com/questions/54959497/invalid-json-message-while-using-lexikjwtauthenticationbundle and solved it by modifying the command line given in the documentation by this one: `curl -X POST -H "Content-Type: application/json" http://localhost/api/login_check --data {\"username\":\"johndoe\",\"password\":\"test\"}`

I don't think I'm the only one to have encountered this problem so I propose this small patch :)

**Comment by chalasr** [comment]
Can you open a pull request?

**Comment by fd6130** [comment]
Can close this since #924 already merged.
