### ISSUE TITLE
Update lcobucci/jwt dependency version to be compatible with php7.3

### ISSUE THREAD

**Issue by alx-web** [lexik/LexikJWTAuthenticationBundle#627]
Hi,

Actually, i have an error when i try with php 7.3. I think you have to use lcobucci/jwt in version 3.3 now compatible with php 7.3 : https://github.com/lcobucci/jwt/issues/282

Thanks,

Alex

**Comment by lbayerl** [comment]
for me it's working with PHP 7.3.3 and lcobucci/jwt 3.2.5?!

**Comment by alx-web** [comment]
I don't understand why but now it's working too. Thanks for your answer
