### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by dtfafard** [lexik/LexikJWTAuthenticationBundle#632]
In the "Getting Started", the script to generate the ssh key uses Linux/openssl. I wasn't able to make it work with Git Bash on Windows. Instead, I've used the code : 

`ssh-keygen -t rsa -b 4096 -f config/jwt/jwtkey`

It would be worth to add it in the documentation to help people with my configuration. 

Also, the pub file was generated under : 

`config/jwt/jwtkey.pub`

Maybe something to mention too.

**Comment by dtfafard** [comment]
Hi again, 

after some changes, it seems I couldn't make the JWT library work. This is because the LexikJWTAuthenticationBundle is dependent on the openssl library. I don't remember seeing that it was informed anywhere so I would recommend to either inform everyone about this or to fix this hard dependency. In the former, I would suggest to add a step by step tutorial on how to create openssl private keys from GitBash on Windows. This would greatly help.

Also, I've found in : CLASS : LcobucciJWSProvider LINE : 94 that the Exception was caught, but nothing was thrown. It would have greatly helped my investigation if it : 
- Had not been caught
- Logic had been in place to warn the programmer of the error.

**Comment by dtfafard** [comment]
I managed to make the openssl commands in the Get Started documentation work. Simply use : 
```
$ winpty openssl genrsa -out config/jwt/private.pem -aes256 4096
$ winpty openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
```
I hope this helps future developers like me. In any other case, I think it would be also nice to have the whole system not dependent on openssl, but to also allow ssh-keygen keys.

Good luck in your projects!

**Comment by fd6130** [comment]
Now you may use `php bin/console lexik:jwt:generate-keypair` to generate key without worrying anything.
