### ISSUE TITLE
Question : user security with jwt

### ISSUE THREAD

**Issue by younesdiouri** [lexik/LexikJWTAuthenticationBundle#633]
Hello,
first thank you for this amazing bundle, and the very well done doc ^^. I have a question about user verification, from the jwt : I am using the following code in a graphql mutation : 

    protected $em;
    protected $userRepository;
    protected $jwtManager;
    protected $tokenStorageInterface;
    protected $roomRepository;

    public function __construct(EntityManagerInterface $em, UserRepository $userRepository,RoomRepository $roomRepository,TokenStorageInterface $tokenStorageInterface, JWTTokenManagerInterface $jwtManager) {
        $this->em = $em;
        $this->userRepository = $userRepository;
        $this->jwtManager = $jwtManager;
        $this->tokenStorageInterface = $tokenStorageInterface;
        $this->roomRepository = $roomRepository;
    }

    public function create(string $content, string $room)
    {
        $decodedJwtToken = $this->jwtManager->decode($this->tokenStorageInterface->getToken());
        $user = $this->userRepository->find($decodedJwtToken["id"]);
        $post = new Post();
        $room = $this->roomRepository->findOneBy(["name" => $room]);
        $post->setContent($content);
        $post->setAuthor($user);
        $post->setRoom($room);
        $this->em->persist($post);
        $this->em->flush();

        return $post;
    }

But from what I learned in the doc, we shouldn't be getting the user from the database in this check. It could be done with a custom user provider, implementing the JWTUserInterface but I don't understand how to use it in the example above :/. 

Also does it affects alot performance to keep the userRepository->find() ? 

Thank you in advance for your help. 

Younes

**Comment by RikudouSage** [comment]
If I understand you correctly, you want to get the current user?

Then you can do this:

`$currentUser = $this->tokenStorageInterface->getToken()->getUser();`

Beware that `getToken()` can be null, so you should check for that unless you're sure that there always must be a user logged in.

**Comment by chalasr** [comment]
Using the token storage is indeed the way to go.
Closing as answered. Thanks @RikudouSage

**Comment by seddighi78** [comment]
> If I understand you correctly, you want to get the current user?
> 
> Then you can do this:
> 
> `$currentUser = $this->tokenStorageInterface->getToken()->getUser();`
> 
> Beware that `getToken()` can be null, so you should check for that unless you're sure that there always must be a user logged in.

Why the user is like a new user when I used `$this->getUser()`? I want to load it from database
