### ISSUE TITLE
Support for JSON Web Keys

### ISSUE THREAD

**Issue by lvillarino** [lexik/LexikJWTAuthenticationBundle#635]
Hi,

I want to know if this bundle provide support for **JSON Web Keys** for decode tokens.

Thanks

**Comment by Spomky** [comment]
The support for JWK depends on the encoder used by your application.
The default ones do not support such keys, but you can use the [spomky-Labs/lexik-jose-bridge](https://github.com/Spomky-Labs/lexik-jose-bridge) that fully supports JWK, JWKSet as well as encrypted tokens (JWE).
