### ISSUE TITLE
[2.6.2] NULL userIdClaim doesn't take value of user_identity_field

### ISSUE THREAD

**Issue by rsida** [lexik/LexikJWTAuthenticationBundle#638]
Hello,

I updraded your bundle to v2.6.2 and I don't want to overload userIdClaim so I keep it at NULL (no configuration has been defined for **user_id_claim**).
But in this file Services/JWTManager.php (in constructor or getUserIdClaim), there is no code like this:
```php
<?php
    /**
     * @param JWTEncoderInterface      $encoder
     * @param EventDispatcherInterface $dispatcher
     * @param string|null              $userIdClaim
     */
    public function __construct(JWTEncoderInterface $encoder, EventDispatcherInterface $dispatcher, $userIdClaim = null)
    {
        $this->jwtEncoder        = $encoder;
        $this->dispatcher        = $dispatcher;
        $this->userIdentityField = 'username';
        $this->userIdClaim       = $userIdClaim ?: $this->userIdentityField;
    }

    // OR

    /**
     * @return string
     */
    public function getUserIdClaim()
    {
        return $this->userIdClaim ?: $this->userIdentityField;
    }
```

So in this case, the code in file Security/Guard/JWTTokenAuthenticator.php:getUser() crashed cause he called `$idClaim = $this->jwtManager->getUserIdClaim();` that is actually NULL.

**Comment by chalasr** [comment]
Thanks for the report, I’m on it.
