### ISSUE TITLE
[2.6.2] EventDispatcher wrong order of arguments

### ISSUE THREAD

**Issue by mwoile** [lexik/LexikJWTAuthenticationBundle#639]
Hello,

I cannot use the current version in my project with Symfony 4.2. It is either working with Symfony 4.1 or with the version here of 2.6.1. Otherwise I get the following error:

`Argument 2 passed to Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher::dispatch() must be an instance of Symfony\\Component\\EventDispatcher\\Event or null, string given, called in /.../vendor/lexik/jwt-authentication-bundle/Services/JWTManager.php on line 68`

**Comment by chalasr** [comment]
Thanks for the report, I will give it a look today.

**Comment by chalasr** [comment]
I'm not able to reproduce. Would you mind forking https://chalasr/lexik-jwt-authentication-sandbox and do the minimal changes required to reproduce the bug?

**Comment by mwoile** [comment]
Thanks for looking into the issue. It turned out that composer installed the master branch of "symfony/contracts". With the current stable release, everything is working fine.

**Comment by chalasr** [comment]
Thanks for the confirmation, closing then :)

**Comment by avramcosmin** [comment]
After updating to Symfony 4.3 I started to receive the following error:

```
Argument 1 passed to "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" must be an instance of Symfony\Component\EventDispatcher\Event, Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationSuccessEvent given.
```

**Comment by chalasr** [comment]
@avramcosmin `EventDispatcherInterface::dispatch()` does not have any `Event` typehint in 4.3. Are you sure that `symfony/event-dispatcher` is installed in its `4.3` version?

**Comment by avramcosmin** [comment]
@chalasr From what I see, Symfony 4.3 introduces `ContractsEventDispatcherInterface` where the `dispatch()` method only receives an $event object. I updated the code and eliminated the error but now I no longer get the `refreshToken` (I'm taking this with `gesdinet/jwt-refresh-token-bundle`).

**Comment by chalasr** [comment]
@avramcosmin I guess some work needs to be done in https://github.com/gesdinet/JWTRefreshTokenBundle. Would you mind opening an issue there?

**Comment by avramcosmin** [comment]
@chalasr with pleasure. Give me a moment to track and find the source of the problem and right after I will open an issue.
