### ISSUE TITLE
How to change a token to be invalid status?

### ISSUE THREAD

**Issue by lichnow** [lexik/LexikJWTAuthenticationBundle#643]
If I  logout or after the password changed,I should let the token to be invalid status.Have any method like which in `onJWTDecoded` event's `$event->markAsInvalid()` method to be use in  controller or any other service?

**Comment by RikudouSage** [comment]
You need to store the invalid tokens somewhere and then check if the token does not exist in the stored database (I would recommend Redis for such tasks). When you encounter such invalidated token, you can use the `$event->markAsInvalid()` you mentioned.

**Comment by lichnow** [comment]
@RikudouSage If store the token to redis or database will make the jwt like session.so ,I may be found a better solution for it.I check if it in `logout` request and `$event->markAsInvalid()` to clear the token,last,I will send the successful message.
```php
public function onJWTDecoded(JWTDecodedEvent $event)
    {
        if($this->request->get('_route') !== 'api_users_logout_collection'){
            return;
        }
        if($this->tokenFactory->clearToken($event)){
            $response = new JsonResponse(['message' => 'Logout successfully.']);
            $response->headers->set('Access-Control-Allow-Origin', '*');
            $response->prepare($this->request);
            $response->send();
        }
    }
```
```php
public function clearToken(JWTDecodedEvent $event)
    {
        $result = false;
        $refreshQueryParams = [];
        $payload = $event->getPayload();
        if ($payload && isset($payload['username'])){
            $event->markAsInvalid();
            $refreshQueryParams['username'] = $payload['username'];
            $result = true;
        }
        $refreshToken = $this->getRefreshToken();
        if($refreshToken){
            $repo = $this->doctrine->getRepository(RefreshTokenEntity::class);
            $refreshQueryParams['refreshToken'] = $refreshToken;
            $RTObject = $repo->findOneBy($refreshQueryParams);
            if ($RTObject){
                $em = $this->doctrine->getManager();
                $em->remove($RTObject);
                $em->flush();
            }
        }
        return $result;
    }
```

**Comment by RikudouSage** [comment]
@lichnow 
Yeah, that doesn't work the way you probably think it does.

The `$event->markAsInvalid()` is used only to inform the security system that they should treat the token as invalid **for current request**. But it doesn't store the information anywhere. It's there so that you can decide whether the token is valid or not after you decoded the data.

In your code nothing happens. The token you "invalidated" can be used again with no problem. To actually invalidate it, you need to store the invalidated tokens somewhere then in an event listener check if the token you received is invalidated (e.g. is stored in database) and then use the `$event->markAsInvalid()` to inform the security system that it should treat the token as invalid, even though it's technically valid.

As I said, Redis is great for stuff like this for two reasons (and probably some others):

1. The check will happen on every request, Redis is quick
2. You can set ttl for the token, set the ttl to the time the token expires, that way you don't have to clean up the database, Redis will delete the rows on its own

**Comment by lichnow** [comment]
@RikudouSage 
thanks for you perfect answer.now I solve the problem by redis.it is like this:
```php
  public function onJWTDecoded(JWTDecodedEvent $event)
    {
        $payload = $event->getPayload();
        if (!$payload) return;
        if ($this->tokenFactory->isInvalidateToken()) {
            $event->markAsInvalid();
            return;
        }
        if ($this->request->get('_route') !== 'api_users_logout_collection') return;
        $this->tokenFactory->invalidateToken();
        $this->tokenFactory->clearRefreshToken($payload);
        $response = new JsonResponse(['message' => 'Logout successfully.']);
        $response->headers->set('Access-Control-Allow-Origin', '*');
        $response->prepare($this->request);
        $response->send();
    }
```
```php
    public function invalidateToken()
    {
        if (($token = $this->getToken()) !== null && !$this->isInvalidateToken()){
            $this->redis->sadd('token_blacklist',[$token]);
        }
    }

    public function isInvalidateToken()
    {
        if (null === ($token = $this->getToken())) return false;
        return $this->redis->sismember('token_blacklist',$token) === 1;
    }

    protected function getToken()
    {
        if(false === ($jsonWebToken = $this->tokenExtractor->extract($this->request))) return null;
        return $jsonWebToken;
    }
```
But now I have another question.As you said:
"You can set ttl for the token, set the ttl to the time the token expires, that way you don't have to clean up the database, Redis will delete the rows on its own".my question is:

First question,what expires I should set to redis for a token?Is the token expires time?In order to get expires time of token,I must set a value to `payload` which named `expired_time`  in `JWTCreate event` handler.`expired_time`  will be add TTL to the token creation time,like `Carbon::now()->addSeconds($this->container->getParameter('lexik_jwt_authentication.token_ttl'))`.
then I should set invalid token a  `expiredAt` time(get from payload) which will been added to redis 'token_blacklist' key in 
`JWTDecoded event` handler.like `$this->predis->expireat($expiredAt)`.Is my idea above correct?

Second,Which Type of redis data value should I use?The `set` type can not set expires for every token,So I should use `hash` Type?

Thank you again for your answer.

**Comment by chalasr** [comment]
Closing as solved, thanks for the help @RikudouSage
