### ISSUE TITLE
How to authenticate using phone Number instead of username & password ?

### ISSUE THREAD

**Issue by MustaphaGhlissi** [lexik/LexikJWTAuthenticationBundle#645]
Hi Lexik community ! 

I am working with API Platform with it I set up LexikBundle for auth process 

My need is to use phone number to authenticate instead of username & password (This feature looks like WhatsApp Auth)

Any help ?

**Comment by RikudouSage** [comment]
This is out of the scope of this bundle, you need to set up your security config. You can start reading about custom authentication at https://symfony.com/doc/current/security/guard_authentication.html.

**Comment by MustaphaGhlissi** [comment]
Thanks !
