### ISSUE TITLE
Compatibility error with EventDispatcher/Debug/TraceableEventDispatcher 4.3

### ISSUE THREAD

**Issue by yceruto** [lexik/LexikJWTAuthenticationBundle#647]
After this fix https://github.com/lexik/LexikJWTAuthenticationBundle/pull/644 I'm still facing a type error in `TraceableEventDispatcher::preDispatch($eventName, Event $event)` method:
> Type error: Argument 2 passed to Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher::preDispatch() must be an instance of Symfony\Component\EventDispatcher\Event, instance of Lexik\Bundle\JWTAuthenticationBundle\Event\JWTCreatedEvent given, called in /var/project/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php on line 299

I think the typehint can't be removed due BC:
https://github.com/symfony/symfony/blob/fba11b4dc34e7c589d8c30d5b6a090387d52e648/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php#L314

Should this be resolved here?

**Comment by chalasr** [comment]
Thanks, dunno yet, I’ll look into it before the weekend

**Comment by chalasr** [comment]
https://github.com/symfony/symfony/pull/31254 should fix it
