### ISSUE TITLE
An error occurred while trying to encode the JWT token

### ISSUE THREAD

**Issue by jbiddulph** [lexik/LexikJWTAuthenticationBundle#658]
Please help, I just implemented teh LexikJWTAuthenticationBundle and I get the error:

An error occurred while trying to encode the JWT token. Please verify your configuration (private key/passphrase)

**Comment by behrooz** [comment]
i have this issue , did you find any solution ?

**Comment by behrooz** [comment]
> Please help, I just implemented teh LexikJWTAuthenticationBundle and I get the error:
> 
> An error occurred while trying to encode the JWT token. Please verify your configuration (private key/passphrase)

i have this issue , did you find any solution ?

**Comment by turiaso** [comment]
Hi,

I have the same problem, but only when I create user by custom post method on api using usermanger service. The server throws Error 500 and traces not run.

I solve the problem that you have got using the next sentence into vhost on apache2:
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

And generate pem with 512 length:
openssl genrsa -out config/jwt/private.pem -aes256 512
openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem

All endpoints that need athorization or specific method (PUT, POST) run right, but POST api/user dont run properly usemanagerinterface:
UserController:
 public function __construct(LoggerInterface $logger, UserManagerInterface $service)
    {
        $this->logger = $logger;
        $this->service = $service;
    }

 public function createUsuario(Request $request): JsonResponse
    {
        $usuarioDTO = $this->container->get('serializer')->deserialize($request->getContent(), UsuarioDTO::class, 'json');

        $usuarioToCreate = new Usuario();
        $usuarioToCreate->setUsername($usuarioDTO ->getUserName())
            ->setPlainPassword($usuarioDTO ->getPassword())
            ->setEmail($usuarioDTO ->getEmail());
        $usuarioToCreate->setEnabled(true);
        $usuarioToCreate->getRoles() == null?$usuario->setRoles(['ROLE_USER']):null;
        $usuarioToCreate->getRoles() == null?$usuario->setSuperAdmin(false):null;

        $this->userManager->updateUser($usuarioToCreate);
        return new JsonResponse(
            json_decode($this->container->get('serializer')->serialize(
                new UsuarioDTO(
                    $usuarioToCreate->getId(),
                    $usuarioToCreate->getUserName(),
                    $usuarioToCreate->getEmail())
            , 'json')),
            JsonResponse::HTTP_CREATED
        );
    }

This problem only is reproduce on production environment using apache (with nginx I didnt test).

On local, with server-dev all fine.

Regards

**Comment by binou95diallo** [comment]
change the JWT_PASSPHRASE in .env with the passphrase you choose when configuring the private key

**Comment by marinsagovac** [comment]
Run from root path `openssl genrsa -out config/jwt/private.pem -aes256 512` and write any your private passphrase. That passphrase copy inside .env file:

`JWT_PASSPHRASE=passphrase`

**Comment by lionelkimbs** [comment]
This error can happens also if you have some special chars in your pass phrase. Remove them and it will works.

**Comment by IlyaSavich** [comment]
it looks like in you environment (container, vm, local machine) something goes wrong with environment, probably you've refreshed passphrase in env file, but it wasn't refreshed in machine. Faced with that problem. Didn't find out how to fix it, so just regenerated jwt certificates with old ones

**Comment by MarlonAEC** [comment]
> it looks like in you environment (container, vm, local machine) something goes wrong with environment, probably you've refreshed passphrase in env file, but it wasn't refreshed in machine. Faced with that problem. Didn't find out how to fix it, so just regenerated jwt certificates with old ones

thanks for the answer... I already fixed but... well, i didn't find where the problem was, I just regenerated the certificates like a million time ahah ... but well I'm happy it works :) ...

**Comment by fgrx** [comment]
Same problem here !
I solved it moving my "/config/jwt" to "/src/config/jwt".
You have to create your "jwt" folder inside "src" folder, not on the root directory.

**Comment by fd6130** [comment]
For anyone encounter this issue and you are using the latest version of the bundle, you can use command `php bin/console lexik:jwt:generate-keypair` to generate keys. 

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.md#prerequisites

> change the JWT_PASSPHRASE in .env with the passphrase you choose when configuring the private key

Seems like this is the solution for this issue.

**Comment by zazzou** [comment]
hi,
I'm facing the same issue, none of the solution above worked for me.

SF 5.4.9 using ApiPlatform.
(nginx server && PHP8.1)

I have same error :
`"hydra:description": "An error occurred while trying to encode the JWT token. Please verify your configuration (private key/passphrase)",`

I checked my passphrase multiple times, i tested with plain passphrase in the lexik_jwt_authentication.yaml file, i tried to move folder in src, an i used the command `php bin/console lexik:jwt:generate-keypair` to generate keys.

Nothing seems to work i'm stuck with this error for 2 days now.

Can someone help me ?

here is my lexik_jwt_authentication.yaml code:
`lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    token_ttl:   3600`

my .env : 
`JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=passphrase`

i tried this command on my terminal:

`sudo php bin/console lexik:jwt:generate-keypair --overwrite
`

Thank you.

**Comment by adorey** [comment]
> Hi,
> 
> I have the same problem, but only when I create user by custom post method on api using usermanger service. The server throws Error 500 and traces not run.
> 
> I solve the problem that you have got using the next sentence into vhost on apache2: SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
> 
> And generate pem with 512 length: openssl genrsa -out config/jwt/private.pem -aes256 512 openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem
> 
> All endpoints that need athorization or specific method (PUT, POST) run right, but POST api/user dont run properly usemanagerinterface:
> 
> UserController:
> 
> public function __construct(LoggerInterface $logger, UserManagerInterface $service) { $this->logger = $logger; $this->service = $service; } public function createUsuario(Request $request): JsonResponse { $usuarioDTO = $this->container->get('serializer')->deserialize($request->getContent(), UsuarioDTO::class, 'json'); $usuarioToCreate = new Usuario(); $usuarioToCreate->setUsername($usuarioDTO ->getUserName()) ->setPlainPassword($usuarioDTO ->getPassword()) ->setEmail($usuarioDTO ->getEmail()); $usuarioToCreate->setEnabled(true); $usuarioToCreate->getRoles() == null?$usuario->setRoles(['ROLE_USER']):null; $usuarioToCreate->getRoles() == null?$usuario->setSuperAdmin(false):null;
> 
> ```
>     $this->userManager->updateUser($usuarioToCreate);
>     return new JsonResponse(
>         json_decode($this->container->get('serializer')->serialize(
>             new UsuarioDTO(
>                 $usuarioToCreate->getId(),
>                 $usuarioToCreate->getUserName(),
>                 $usuarioToCreate->getEmail())
>         , 'json')),
>         JsonResponse::HTTP_CREATED
>     );
> }
> ```
> 
> This problem only is reproduce on production environment using apache (with nginx I didnt test).
> 
> On local, with server-dev all fine.
> 
> Regards

Thanks a lot @turiaso. I had the same issue and my problem was solved by adding the following to my apache configuration ! `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

You save my day and maybe more !

**Comment by lreqr** [comment]
> For anyone encounter this issue and you are using the latest version of the bundle, you can use command `php bin/console lexik:jwt:generate-keypair` to generate keys.
> 
> https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.md#prerequisites
> 
> > change the JWT_PASSPHRASE in .env with the passphrase you choose when configuring the private key
> 
> Seems like this is the solution for this issue.

Man you saved my life

**Comment by numediaweb** [comment]
Make sure the private keys are generated with a better standard and with a passkey instead of using the `bin/console lexik:jwt:generate-keypair` command as it doesn't give you a passphrase!:

```shell
openssl genrsa -out config/jwt-test/private.pem  -aes256 4096
```
And a public key:

```shell
openssl rsa -pubout -in config/jwt-test/private.pem  -out config/jwt-test/public.pem
```

**Comment by chalasr** [comment]
@numediaweb no, the `lexik:jwt:generate-keypair` does use the configured passphrase for generating the keypair.

**Comment by andrii-boiko** [comment]
> [@numediaweb](https://github.com/numediaweb) no, the `lexik:jwt:generate-keypair` does use the configured passphrase for generating the keypair.

Could you please tell how to specify the passphrase when generating keys? Because when I run l`exik:jwt:generate-keypair` command, it doesn't ask for a passphrase.

**Comment by lionelkimbs** [comment]
> > [@numediaweb](https://github.com/numediaweb) no, the `lexik:jwt:generate-keypair` does use the configured passphrase for generating the keypair.
> 
> Could you please tell how to specify the passphrase when generating keys? Because when I run l`exik:jwt:generate-keypair` command, it doesn't ask for a passphrase.

Hi, you have to do it by setting up the passphrase in your .`env` or `.env.local` file, through the parameter `JWT_PASSPHRASE`.
