### ISSUE TITLE
Dosen't get any error if not set authorization token.

### ISSUE THREAD

**Issue by mitesh-iod** [lexik/LexikJWTAuthenticationBundle#659]
I am using ```"lexik/jwt-authentication-bundle": "^2.6",```  with ```symfony 4.2``` . It was working if i m not set authorization token it gives the error ``` "JWT Token not found" ```. 
while, i 've upgraded version of symfony  ```4.2``` to  ```4.3```. i've notice that i can call any api without authorization token. It should be come error if i m not pass  authorization token.

I believe following method dosen't call after upgrading symfony version:
```
public function start(Request $request, AuthenticationException $authException = null)
    {
        $exception = new MissingTokenException('JWT Token not found', 0, $authException);
        $event     = new JWTNotFoundEvent($exception, new JWTAuthenticationFailureResponse($exception->getMessageKey()));
        
        $this->dispatcher->dispatch(Events::JWT_NOT_FOUND, $event);
        
        return $event->getResponse();
    }
```

**Comment by ankit-iod** [comment]
After Symfony 4.3 update the package needs to implement these changes after that this should work :
1. The ListenerInterface is deprecated, turn your listeners into callables instead.
2.The Firewall::handleRequest() method is deprecated, use Firewall::callListeners() instead.

**Comment by Spomky** [comment]
Minor releases should not modify the behavior of your application, even if deprecated classes/methods are used.

**Comment by mitesh-iod** [comment]
Issue solved!
I think issue was occurred due to somehow version was not updated properly.
