### ISSUE TITLE
Generate Database-less token with user roles

### ISSUE THREAD

**Issue by leroy0211** [lexik/LexikJWTAuthenticationBundle#674]
I'm using the database-less approach for one application, and in another application I'm generating the tokens. 

But for testing, I want to be able to create a token with user roles attached. But in the current command (`lexik:jwt:generate-token`) that is not possible. You can only specify a username. But in a database-less approach that user token will never have any roles assigned.

I think it would be great that for testing purposes the roles and maybe other information can be added to the JWT token when using the `lexik:jwt:generate-token` command.

**Comment by chalasr** [comment]
Should be the case now I believe.

**Comment by mergeMarc** [comment]
lexik/LexikJWTAuthenticationBundle,


Vielen Dank für Ihre EMail. Wir haben Ihre Anfrage erhalten und werden uns schnellstmöglich mit Ihnen in Verbindung setzen. Wir beantworten Ihre Anfrage in der Regel innert einem Arbeitstag. Wenn Sie Ergänzungen zu Ihrer Anfrage anbringen möchten, stellen Sie bitte sicher, dass Ihre Ticket-ID im Betreff enthalten ist.

Thank you for getting in touch with NetZone Support - we've received your message. One of our Support team members will get in touch with you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject line to ensure that your replies are tracked appropriately.

   Ticket ID: VVN-698-72450
   Subject: Re: [lexik/LexikJWTAuthenticationBundle] Generate Database-less token with user roles (#674)
   Department: Info

Freundliche Grüsse

NetZone AG

**Comment by mergeMarc** [comment]
lexik/LexikJWTAuthenticationBundle,


Vielen Dank für Ihre EMail. Wir haben Ihre Anfrage erhalten und werden uns schnellstmöglich mit Ihnen in Verbindung setzen. Wir beantworten Ihre Anfrage in der Regel innert einem Arbeitstag. Wenn Sie Ergänzungen zu Ihrer Anfrage anbringen möchten, stellen Sie bitte sicher, dass Ihre Ticket-ID im Betreff enthalten ist.

Thank you for getting in touch with NetZone Support - we've received your message. One of our Support team members will get in touch with you as soon as possible. When replying, please make sure that the ticket ID is kept in the subject line to ensure that your replies are tracked appropriately.

   Ticket ID: DLE-676-53945
   Subject: Re: [lexik/LexikJWTAuthenticationBundle] Generate Database-less token with user roles (#674)
   Department: Info

Freundliche Grüsse

NetZone AG
