### ISSUE TITLE
Make "token_ttl" a parameter during "create" new token

### ISSUE THREAD

**Issue by toxaco** [lexik/LexikJWTAuthenticationBundle#676]
I wonder if there is a way to change the token_ttl in a "per token" bases? 

For example, once you call "$jwt->create($user, $token_ttl)" to get a token based on the provided "token_ttl" and not in the global config (set in parameters.yml or .env).

If you provide your preferences/restrictions I can submit a request with these changes.

**Comment by franzwilding** [comment]
I'm also looking for exactly this feature. I want to create short and long loving tokens.

**Comment by franzwilding** [comment]
@toxaco I just figured out, that you can set the exp in an JWT_CREATED event subscriber: 

```
$data['exp'] = time() + 12334;
```

This is not exactly what I need, but with a little ugly hack you can use the user object to pass context information to the event and set the exp based on that information.

**Comment by pluk77** [comment]
You might be able to do this by setting the default ttl to null and passing the ttl in the payload when creating the token.

```yaml
lexik_jwt_authentication:
    token_ttl:   null
```

```php
$payload['exp'] = time() + 36000;
$JWTManager->createFromPayload($user,$payload);
```

This is possible because the create method of DefaultJWSProvider and LcobucciJWSProvider both only use ```$this->ttl``` if ```$payload['exp']``` is not set.

**Comment by pluk77** [comment]
I found an issue with my previous solution as setting the token_ttl to null will bypass the exp validation of the token completely. see #889

**Comment by jawira** [comment]
I'm also looking for this feature.
Related https://github.com/lexik/LexikJWTAuthenticationBundle/issues/682

**Comment by pluk77** [comment]
@jawira Perhaps you can assist with having a look at the [PR918](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/918). I can not seem to get those tests working, which prevents the PR from being actioned.
