### ISSUE TITLE
custom authentication failure response

### ISSUE THREAD

**Issue by jessequinn** [lexik/LexikJWTAuthenticationBundle#680]
Hi Guys,

Great work here.

I read some previously closed issues namely #16 however, i am having the same issue with the authentication failure response.

```
<?php

namespace App\EventListener;

use Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationFailureEvent;
use Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationFailureResponse;


class AuthenticationFailureListener
{
    /**
     * @param AuthenticationFailureEvent $event
     */
    public function onAuthenticationFailureResponse(AuthenticationFailureEvent $event)
    {
        $data = [
            'meta' => [
                'code' => 401,
                'status' => 'error',
                'message' => 'Bad credentials, please verify that your username/password are correctly set.',
            ]
        ];
        $response = new JWTAuthenticationFailureResponse($data);
        $event->setResponse($response);
    }
}
```
outputs
```
{"code":401,"message":{"meta":{"code":401,"status":"error","message":"Bad credentials, please verify that your username\/password are correctly set."}}}%
```
However, based on the class `JWTAuthenticationFailureResponse` i do not see a way to do this correctly. My work around is to use `$response = new JsonResponse($data);`

**Comment by fd6130** [comment]
> {"code":401,"message":{"meta":{"code":401,"status":"error","message":"Bad credentials, please verify that your username\/password are correctly set."}}}

Yea because `JWTAuthenticationFailureResponse` constructor first argument is `message` and it will replace the default message in that class. If you wish to insert some custom data while maintaining the output format from that response, simply use `$response->setData($data)` instead.

Else, use `$response = new JsonResponse($data);` for your own output format is better choice.

**Comment by chalasr** [comment]
Closing as explained. Thank you for the kind words and the discussion.
