### ISSUE TITLE
how does the lexik library generate the token 

### ISSUE THREAD

**Issue by MXP22** [lexik/LexikJWTAuthenticationBundle#681]
hello how does the lexik library generate the token i have not seen any method exactly that does generera

**Comment by fd6130** [comment]
> hello how does the lexik library generate the token i have not seen any method exactly that does generera

This is the one you are looking for: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Security/Http/Authentication/AuthenticationSuccessHandler.php

And also before that, you may read more about `JSON_LOGIN` at https://symfony.com/doc/4.4/security/json_login_setup.html (this issue 2019 so i guess you are using symfony 4.4)
