### ISSUE TITLE
How to test is account is enabled or not ? 

### ISSUE THREAD

**Issue by CedLP** [lexik/LexikJWTAuthenticationBundle#686]
Hello, Can i test if account is enabled or not with jwt tokien ? if yes what can i do to configure it please? 
Thanks

**Comment by EresDev** [comment]
If you do not want to allow the generation of JWT token when user's account is not enabled, use [UserChecker](https://symfony.com/doc/current/security/user_checkers.html)

If you want to allow the generation of JWT token but you only need information about user's account status, you can [add it to payload](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsjwt_created---adding-custom-data-or-headers-to-the-jwt).

**Comment by CedLP** [comment]
Thanks EresDev you help me, sorry for late.
