### ISSUE TITLE
Integrating with existing Symfony auth

### ISSUE THREAD

**Issue by mattdillon100** [lexik/LexikJWTAuthenticationBundle#693]
I have existing auth in my Symfony project that uses and external resource to authenticate users.

Is it possible to use this bundle to create a JWT token on authentication?

If so, how would this work with the `login_check` endpoint, since this does not exist in my current set up?

**Comment by jrbarros** [comment]
First deploy jwt after existing login. This can be done in many ways one of which is to return a 'handleAuthenticationSuccess' from the AuthenticationSuccessHandler class, a user implementing UserInterface is expected.

[example](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/7-manual-token-creation.md)

In authenticated requests it is possible to implement a custom decode:
[example](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/5-encoder-service.md)
