### ISSUE TITLE
JWTDecodedEvent doesn´t work

### ISSUE THREAD

**Issue by Julen10** [lexik/LexikJWTAuthenticationBundle#694]
Hi guys,

I´m following the examples defined on the guide, I have added some info to the payload on JWTCreatedEvent correctly. But, when I´m trying to get that payload information on the JWTDecodedEvent it doesn´t even print any var_dump information.

I´ve just copy pasted the guide example

**Comment by Julen10** [comment]
I´ve tried [this example](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsjwt_authenticated---customizing-your-security-token) too and i´m unable to dump or get anything

**Comment by Julen10** [comment]
Now the listener is on the Orphaned Events tab inside the profiler

**Comment by jeroen-hoekstra** [comment]
Did you ever got it working? 

I'm experiencing the same issue. I followed this example ([Using Events::JWT_CREATED](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/2-data-customization.md#adding-custom-data-or-headers-to-the-jwt)) and added a dump() inside the event listener and I see it appear but when doing the same using this example ([Using Events::JWT_AUTHENTICATED](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/2-data-customization.md#eventsjwt_authenticated---customizing-your-security-token)) I don't see the dump appear.

**Comment by fd6130** [comment]
> Did you ever got it working?
> 
> I'm experiencing the same issue. I followed this example ([Using Events::JWT_CREATED](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/2-data-customization.md#adding-custom-data-or-headers-to-the-jwt)) and added a dump() inside the event listener and I see it appear but when doing the same using this example ([Using Events::JWT_AUTHENTICATED](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/2-data-customization.md#eventsjwt_authenticated---customizing-your-security-token)) I don't see the dump appear.

Hi, is it possible for you to post your code here?

**Comment by yunmoxue** [comment]
@fd6130 
service.yaml
```
services:
    acme_api.event.jwt_created_listener:
        class: App\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
```
App\EventListener\JWTCreatedListener.php
```
namespace App\EventListener;

use Lexik\Bundle\JWTAuthenticationBundle\Event\JWTCreatedEvent;

class JWTCreatedListener
{
    /**
     * @param JWTCreatedEvent $event
     *
     * @return void
     */
    public function onJWTCreated(JWTCreatedEvent $event)
    {
        $user = $event->getUser();
        dd($event->getUser());

    }

}
```

**Comment by fd6130** [comment]
@jeroen-hoekstra @yunmoxue

Sorry for the late reply. The `JWT_AUTHENTICATED` event will work only when you call an api with `Bearer <token>` header. 

And the  `JWT_CREATED` event will trigger only when JWT is created after `username` and `password` are correct.

**Comment by fd6130** [comment]
> Hi guys,
> 
> I´m following the examples defined on the guide, I have added some info to the payload on JWTCreatedEvent correctly. But, when I´m trying to get that payload information on the JWTDecodedEvent it doesn´t even print any var_dump information.
> 
> I´ve just copy pasted the guide example

I guess your intention is to obtain the JWT payload right? Try see #1010, hope that will help you.

**Comment by yunmoxue** [comment]
@fd6130 thank you
