### ISSUE TITLE
Change from namshi/jose to firebase/php-jwt

### ISSUE THREAD

**Issue by 94noni** [lexik/LexikJWTAuthenticationBundle#699]
Hi,

first thank you for this bundle,
Cf the readme of the actual package `namshi/jose`, they recommand to use an other one `firebase/php-jwt`.

Do you plan to swap for next release? also where can i find a release map for this bundle?
I saw that the `DefaultEncoder.php` talk about it

Cheers,

**Comment by chalasr** [comment]
The namshi/jose integration has been deprecated in 2.x, we chosen to implement https://github.com/lcobucci/jwt. See #508
