### ISSUE TITLE
get keys programatically (from store)

### ISSUE THREAD

**Issue by xvilo** [lexik/LexikJWTAuthenticationBundle#700]
Hi all,

I was searching through the issues and documentation, but is it possible to let it get the secrets from a special store. So simply put, instead of setting a file path, setting a class/method name to get the keys and/or it's passphrase?

**Comment by MLDMoritz** [comment]
Use Environmental Variables. How you populate them is up to you.

**Comment by mcn-fredw** [comment]
Expecting the same issue deploying api platform using this bundle on multiple containers.
Want to bake the secrets in to the deployment environment, not the deployment image. Also don't want to write additional container startup code for dev/qa/production.
As far as I can tell, the packages yaml file expects a file path.
Should be able to use a service expression to grab and store the contents, then return the path.
https://symfony.com/doc/current/service_container/expression_language.html

**Comment by MLDMoritz** [comment]
Setting ENV variables works in the deployment environment. Building them doesn't bake them into code.

**Comment by mcn-fredw** [comment]
Ideally, only dev-ops should have access to production key material. Developers can be given/generate dev keys and mount volumes in the container for development/testing.
As far as I can tell, the ENV variables for the public/private keys are paths to files containing the key material. If you can put the key material in the ENV variables, then no problem. If the ENV values are just paths, then the key material has to come from somewhere besides the code repository. If that's done building the deployment image, then the key material is in the image repository. In the ideal environment, that means developers can't have access to the image repository.

**Comment by MLDMoritz** [comment]
Using env vars as config:

https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables

Using file as config:
```
# config/packages/framework.yaml
parameters:
    env(AUTH_FILE): '../config/auth.json'
google:
    auth: '%env(file:AUTH_FILE)%'
```

**Comment by mcn-fredw** [comment]
Won't is_file() fail for an https:// schema?
From your raw key reader:
```
        if (!$key || !is_file($key) || !is_readable($key)) {
            if ($isPublic) {
                return null;
            }

            throw new \RuntimeException(
                sprintf('Signature key "%s" does not exist or is not readable. Did you correctly set the "lexik_jwt_authentication.signature_key" configuration key?', $key, $type)
            );
        }
```

**Comment by dytyniuk** [comment]
@mcn-fredw could you so kind to explain your deployment strategy a bit? This will allow to address the issue properly.
Of course, if the question is still relevant :)

**Comment by mcn-fredw** [comment]
We use AWS ECS. Would be nice to be able to set the keys in the task definition "secrets" section, which would populate the keys as environment variables.
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_environment
I see how I can over-ride your raw key reader service with a custom reader to fetch the keys from the environment, so not an issue for us.

**Comment by dytyniuk** [comment]
@mcn-fredw to populate environment variable of your ECS task with a key payload, you should use Secrets Manager -- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data-secrets.html#secrets-envvar
