### ISSUE TITLE
Create a token that never expires

### ISSUE THREAD

**Issue by Acetyld** [lexik/LexikJWTAuthenticationBundle#704]
Hello!
I am loving the LexikJWT bundle
Every thing works, but i need to have a token, that never expires.

Does anyone have any clue how to do this?

**Comment by SmirnovW** [comment]
Hi, the same question :)

**Comment by fd6130** [comment]
Set the `token_ttl` to 0?

But why do you need a token that never expires? If a malicious user obtain that token... then he can do whatever he want with that token forever...

**Comment by aziizoon** [comment]
Hi, i have the same issue.
In other ways, I'm looking for a way to change token_ttl in every request .... I want to make token as invalid when the no request send in 15 minutes.

anyone here tried to make something like that ?

**Comment by fd6130** [comment]
> Hi, i have the same issue.
> In other ways, I'm looking for a way to change token_ttl in every request .... I want to make token as invalid when the no request send in 15 minutes.
> 
> anyone here tried to make something like that ?

It is very bad but you can persist the token to database.

When user send request to your server, check the expire time in token database if it exceed 15 minutes denied access. Otherwise update the expire time to new 15 minutes in database.

**Comment by chalasr** [comment]
You can use `null` for the `token_ttl` option in order to have an infinite lifetime. 
But, except for testing purposes, this should never be done in an authentication context as you have no way to revoke that token if you need to.
