### ISSUE TITLE
Bug: public_key and secret_key not defined as parameters

### ISSUE THREAD

**Issue by ghost** [lexik/LexikJWTAuthenticationBundle#706]
In the [extension configuration, lines 45-53](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/DependencyInjection/LexikJWTAuthenticationExtension.php#L45-L53) it's checked if `private_key_path` and `public_key_path` are set. If so they are added via `setParameter()` so they can be fetched from services and controllers.

This is all fine and dandy but the new `secret_key` and `public_key` are nowhere to be seen. In other words, inside a controller this words:

```
$this->getParameter('lexik_jwt_authentication.public_key_path')
```

but this does not:

```
$this->getParameter('lexik_jwt_authentication.public_key')
```

Can you add the new keys as parameters too?

**Comment by ajdinmore** [comment]
`lexik_jwt_authentication.public_key` is never set in the container. The `public_key` and `secret_key` are just set in the `$config` array and get used later in that method.

From what I can tell, this was done to support the`public_key` and `secret_key` config nodes on [lines 35-42 of the definition](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/a6a77189cd9400a4483129bf683955d67e8d8711/DependencyInjection/Configuration.php#L35). Which is something to do with supporting HMAC based signing, according to the commit.

**Comment by armin-crosslend** [comment]
If you look a few lines up in that commit it says that  `private_key_path` and `public_key_path` are deprecated. AFAIK they have been replaced by `public_key` and `secret_key`.

**Comment by ajdinmore** [comment]
Ah, good point; the new IDs are to replace the old ones, not supplement them. That'll teach me to comment on things just before bed.

Seems like a pretty straight-forward patch to support the new IDs as parameters. ;)
