### ISSUE TITLE
Verify if account is activated before generating JWT token

### ISSUE THREAD

**Issue by ziiko10** [lexik/LexikJWTAuthenticationBundle#710]
Hello everyone, i want to verify is user accountis activated before generating the JWT TOKEN, i'm currently using the **on_jwt_created** event and it is working but when i handle AccessDeniedException it returns me html reponse instead of Json.

This my code 

    class JwtCreatedSubscriber
     {
       public function updateJwtData(JWTCreatedEvent $event)
       {
         //Get the current User
          $user = $event->getUser();

          if (!$user instanceof UserInterface) {
            return;
          }
        
          if(!$user->getIsActivated())
            throw new AccessDeniedException('You need to activate your account');

           // Get the data generated in JWT
           $data = $event->getData();

           if(!$user->getUserRole()){
            $role = [];
            }
           else {
            $role =  [
                $user->getUserRole()->getName()
            ];
          }

          //Enrich the token with the user role
          $data['roles'] = $role;
          $data['id'] = $user->getId();

          $event->setData($data);
          }
       }

And this is the reponse : 

![response](https://user-images.githubusercontent.com/18125884/72224909-c3c7ee80-357f-11ea-9cde-b838bd6eb821.png)

But i want a Json reponse and when i return **newJsonReponse('Error')** it return the token

Thank you for any help.

**Comment by EresDev** [comment]
I have not looked into your code, so I am not sure what the problem is. What I am here to tell is, you write a [User Checker](https://symfony.com/doc/current/security/user_checkers.html) in Symfony Security to perform such checks. You don't need to write a listener or subscriber for it. 

And even if you want to go with your subscriber/listener, you should preview the html. Hopefully there will be a clear error message about it.

**Comment by fd6130** [comment]
I think you need a custom exception and  a custom exception listener to handle that exception.

So let's say you throw an exception class `UserNotActivated`, and use custom exception listener to handle that exception and return a json response.

```
class UserNotActivatedExceptionListener {
    //...
   public function onKernelException(ExceptionEvent $event) { 
           if($exception instanceof UserNotActivated) {
                    // return json response
           }
          // ...
      }
}

```

**Comment by fd6130** [comment]
> I have not looked into your code, so I am not sure what the problem is. What I am here to tell is, you write a [User Checker](https://symfony.com/doc/current/security/user_checkers.html) in Symfony Security to perform such checks. You don't need to write a listener or subscriber for it.
> 
> And even if you want to go with your subscriber/listener, you should preview the html. Hopefully there will be a clear error message about it.

Thanks for the info. User Check very useful.
