### ISSUE TITLE
Getting user by JWT token

### ISSUE THREAD

**Issue by Cypaubr** [lexik/LexikJWTAuthenticationBundle#712]
I wondered if there is a way to get an User (implementing UserInterface) by its JWT token?

**Comment by Vandetho** [comment]
what you need to do is to use the function getUser() in controller.

**Comment by Cypaubr** [comment]
It's not in a controller but in a Ratchet WS server (acting like a service). The user is sending a WS message for authentication containing a token field. With this token I need to get the user object.

**Comment by fd6130** [comment]
If you want to get User object in a service, just inject `Security` class from `Symfony\Component\Security\Core\Security` and use getUser() to obtain User object.

**Comment by Cypaubr** [comment]
The thing is (as I said before), I am running a Websocket server using Ratchet (this server is always running in the background with a supervisor, and this is a separate part of my main app). The server is started using a Symfony command.
To authenticate, the user sends a WS message with a JWT token field. I need in my server to get this token, and I a service (for example UserService) to get the user authenticated with this JWT token and store it in memory with its connection ID.

**Comment by RikudouSage** [comment]
@Cypaubr If you have access to Symfony services from the server, you can just inject `TokenStorageInterface` or the `Security` service and get user from there.

If you don't have access to the Symfony services, you have to parse the data manually, see https://jwt.io for the description of the structure.

**Comment by Schneider95** [comment]
Exact same case here. My Ratchet server receive a JWT token in WebSocket, and I would like to know which user sent this token.

**Comment by watlf** [comment]
I faced with exactly the same issue when worked with sending WS messages. There is only one way I found to manage it:
<pre>
    public function __construct(ManagerRegistry $managerRegistry, JWTTokenManagerInterface $jwtManager)
    {
        $this->jwtManager = $jwtManager;
        $this->managerRegistry = $managerRegistry;
    }
    
    $usrToken = new JWTUserToken([], null, $jwtTokenString);
    $payload = $this->jwtManager->decode($usrToken);
    $user = $this->managerRegistry->getManager()->getRepository(User::class->loadUserByUsername($payload['username']);
</pre>

**Comment by russelRajitha** [comment]
How to get the user in symfony controller or repository? 

> If you want to get User object in a service, just inject `Security` class from `Symfony\Component\Security\Core\Security` and use getUser() to obtain User object.
> 
> Documentation: https://symfony.com/doc/current/security.html#b-fetching-the-user-from-a-service

this is also not worked for me.

**Comment by fd6130** [comment]
Huh? It should have no problem if you use `getUser()` in a symfony controller. Any error or unexpected output?

**Comment by fd6130** [comment]
> How to get the user in symfony controller or repository?
> 
> > If you want to get User object in a service, just inject `Security` class from `Symfony\Component\Security\Core\Security` and use getUser() to obtain User object.
> > Documentation: https://symfony.com/doc/current/security.html#b-fetching-the-user-from-a-service
> 
> this is also not worked for me.

Huh? It should have no problem if you use getUser() in a symfony controller. Did it return any error or unexpected output?

**Comment by russelRajitha** [comment]
No, it didn't work at all. I checked by enabling guard from security.yml for the protected route. and it also failed with unauthorized even Authorization header is present. here is my `api/config/packages/security.yaml`. here `api/user `cannot access. even if remove validation, in the controller cannot extract the user.

```

security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator



            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user, roles: IS_AUTHENTICATED_FULLY }

```

**Comment by fd6130** [comment]
@russelRajitha 

Put main firewall below api:

```yaml
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            lazy: true
            provider: app_user_provider
```

**Comment by russelRajitha** [comment]
Thanks Now It's working. It's all about The order, If First Authenticator Failed Second one not executed. 

> @russelRajitha
> 
> Put main firewall below api:
> 
> ```yaml
> firewalls:
>         dev:
>             pattern: ^/(_(profiler|wdt)|css|images|js)/
>             security: false
> 
>         api:
>             pattern:  ^/api
>             stateless: true
>             anonymous: false
>             provider: app_user_provider
>             guard:
>                 authenticators:
>                     - lexik_jwt_authentication.jwt_token_authenticator
>         main:
>             lazy: true
> ```

**Comment by fd6130** [comment]
> Exact same case here. My Ratchet server receive a JWT token in WebSocket, and I would like to know which user sent this token.
> 
> I manage to get it with the method `decode` from `Lexik\Bundle\JWTAuthenticationBundle\Encoder\LcobucciJWTEncoder`

So i think this is the right answer for this issue?

**Comment by chalasr** [comment]
Agree, this looks resolved. Closing then, thanks.
