### ISSUE TITLE
Unable to Manually Authenticating a User

### ISSUE THREAD

**Issue by oleg-andreyev** [lexik/LexikJWTAuthenticationBundle#713]
In Symfony Docs it's stated that I can simply authenticate a User by using GuardAuthenticatorHandler

But it seems that it's not the case with JWT Bundle due to exception:
```
Unable to return an authenticated token since there is no pre authentication token.
```

But manually Authenticate User is really simple with JWT, just call `JWTManager::create($user)`, so probably it should be reflected in documentation somehow.

Ref.: 
https://symfony.com/doc/4.2/security/guard_authentication.html#guard-manual-auth

**Comment by chalasr** [comment]
Seems like a unnecessary limitation 👍Would you mind opening a PR?

**Comment by douglasjam** [comment]
up

**Comment by fd6130** [comment]
Have we solved this issue?

**Comment by fd6130** [comment]
Do we still need this since we can create JWT manually by injecting `JWTTokenManagerInterface` as service?

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/7-manual-token-creation.md

**Comment by chalasr** [comment]
Seems like we can close here.
