### ISSUE TITLE
Extending JWTTokenAuthenticator not working as parent supports-function returns false

### ISSUE THREAD

**Issue by dennobaby** [lexik/LexikJWTAuthenticationBundle#714]
Hi,

i am trying to modify some aspects of this bundle by extending the JWTTokenAuthenticator. 
How i understand the thing is, that if i change not one thing, writing all methods and call in every method the parent-function it should work as normal but with the extended class. 
This is not happening as the parent-call in the supports-method returns false everytime so my extended Guard-Authenticator is never used. 
Configuration is like in the documentation so i don't know that to post else as my experience. 

Hope someone could check this.

**Comment by rapliandras** [comment]
Have you implemented `JWTUserInterface` by the child class?

**Comment by dennobaby** [comment]
You mean like using the JWTUserProvider instead of my own? No, why would this be necessary?

**Comment by rapliandras** [comment]
JWTTokenAuthenticator explicitly checks for the implementation of JWTUserInterface in the sublass in its `supportsClass()` method. You have to implement it to get `true`

**Comment by dennobaby** [comment]
I think you don't see the thing i want to do. 
I am extending JWTTokenAuthenticator, not JWTUser. This should work without using the JWTUserProvider.
Neither it makes sense to implement JWTUserInterface in a class extentind JWTTokenAuthenticator.

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/6-extending-jwt-authenticator.md

**Comment by fd6130** [comment]
Can you post your configuration and how you extend the JWTTokenAuthenticator?

**Comment by fd6130** [comment]
@dennobaby Friendly ping. Do you manage to find a solution for your case?
