### ISSUE TITLE
How can I add custom data to the payload body when manually creating?

### ISSUE THREAD

**Issue by beejaz** [lexik/LexikJWTAuthenticationBundle#719]
Hi,

Following this https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/7-manual-token-creation.md for  SF 4 for manually creating a token, how can I add custom data to the payload when its manually created? Like $JWTManager->create($user, ['extra' => 'fields']); ?

As I understand from https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsjwt_created---adding-custom-data-or-headers-to-the-jwt I am not able to add extra parameters if its not from a request, eg when its created manually.

Is this correct or am I missing something?

If its not possible, I guess one uggly hack is to add a dummy property to the User entity like public $data; and then use grab it with $event->getUser()->data from JWTCreatedEvent?

**Comment by beejaz** [comment]
I ended up just assigning the variable i wanted on the $user object like $user->whatever and it was included when doing $JWTManager->create($user) when checking out $event later..

**Comment by chalasr** [comment]
> As I understand from https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsjwt_created---adding-custom-data-or-headers-to-the-jwt I am not able to add extra parameters if its not from a request, eg when its created manually.

Not true :) The example adds extra fields from the current request information, but it could be any other info, just inject the services you need in your event listener and fill your payload using them. 
Listening on events that are listed in this documentation area is the way to for customizing the payload.

**Comment by beejaz** [comment]
Hi @chalasr , thanks for the answer. I understand that case you describe and injecting the service i need but I was wondering if I have just a (dynamic) text string I want to add, not a service, that I know during manual creation only
