### ISSUE TITLE
Can LexikJWTAuthenticationBundle will support Symfony 4.2 and above?

### ISSUE THREAD

**Issue by elangovanshanthi** [lexik/LexikJWTAuthenticationBundle#728]
My application is working on `symfony 4.2` and  we will upgrade to `symfony V4.4` and `symfony V5.0`. So Lexik JWT bundle will support `symfony V4.4 and V5.0`?
If yes means, could you please share some snippets and how to use this package in Symfony V5.0.

**Note:** I have tried the JWT bundle with **Symfony V4.3** and it is not working and unable to create the token.

**Comment by chalasr** [comment]
Symfony 4/5 is supported, the bundle is tested under these versions. 
Please share a stack trace or reproducer demonstrating the issue you are facing.

**Comment by elangovanshanthi** [comment]
It works as expected. thanks.
