### ISSUE TITLE
How to customize the exception message?

### ISSUE THREAD

**Issue by fd6130** [lexik/LexikJWTAuthenticationBundle#729]
Hi, when i throw exception in my extended JWTTokenAuthenticator and set a custom message, the json response won't print out the custom messsage but the default one.

For example:

`throw new InvalidTokenException('This token is invalid, please try again');` 
the json response will give the default one which is:

```
{
  "code": 401,
  "message": "Invalid JWT Token"
}
```

How can we make it print out the custom message? Thanks.

**Comment by chalasr** [comment]
Please see https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#eventsauthentication_failure---customizing-the-failure-response-body
