### ISSUE TITLE
not working on  AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by BernardA** [lexik/LexikJWTAuthenticationBundle#730]
I have an app with Symfony API-Platform which I am deploying to AWS Elastic Beanstalk.

When attempting to login  an user on AWS I am getting error "Invalid credentials" ( works fine locally ).

The public and private keys are available at `/config/jwt/` on the bundle uploaded to EB.

In EB's configuration tab I have added on `Environmental properties`:

`JWT_PASSPHRASE`  -> 'my_passphrase'
`JWT_PUBLIC_KEY` -> `%kernel.project_dir%/config/jwt/public.pem`
`JWT_SECRET_KEY` -> `%kernel.project_dir%/config/jwt/private.pem`

A dump of $_SERVER('JWT_PUBLIC_KEY') will output the correct string 
`string(42) "%kernel.project_dir%/config/jwt/public.pem"`  

Any ideas

**Comment by BernardA** [comment]
Further findings: I found out that on AWS the `$request` does not include the `bearerToken` even though it is part of the headers seen on dev tools. 

A dump of `var_dump($request->headers->all());` on the `supports` method of class 
`/lexik/jwt-authentication-bundle/Security/Guard/JWTTokenAuthenticator` 
will include the bearerToken on `localhost`, but not so AWS.

So the `supports` method returns `false` and access is, of course, denied. 

Any ideas on why Symfony would drop the `token` from the request?

**Comment by chalasr** [comment]
Are you using Apache as web server? You might need to have a look at https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#important-note-for-apache-users?

**Comment by BernardA** [comment]
Thanks @chalasr . That was it. I added the recommended change to .htaccess as below:
 
      SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
