### ISSUE TITLE
Roles in JWTUserToken not populated using database-less approach

### ISSUE THREAD

**Issue by webdevilopers** [lexik/LexikJWTAuthenticationBundle#735]
We recently switched to a database-less approach. The authorization with our custom `User` class works fine.
Before switching we were used to inject the Symfony `tokenStorage` and use `getUser()`. Now it will return null.

This was our first workaround:

```php
        $jwtToken = $this->jwtManager->decode($this->tokenStorage->getToken());

        $user = User::fromToken($jwtToken); // Take the token array data and populate our custom class
```

Is there a single-step approach to either get the User directly from somewhere. Or should we use an event listener to inject `tokenStorage` and call `$tokenStorage->setUser(...)`?

Related:
* https://github.com/lexik/LexikJWTAuthenticationBundle/issues/357
* https://github.com/lexik/LexikJWTAuthenticationBundle/issues/322
* https://github.com/lexik/LexikJWTAuthenticationBundle/issues/116

**Comment by webdevilopers** [comment]
In addition the "isGranted" methods don't seem to work with the database-less approach.

What you can do is this:

```php
$jwtToken = $this->jwtManager->decode($this->tokenStorage->getToken());
$user = User::fromToken($jwtToken); // Take the token array data and populate our custom class

$token = new JWTUserToken($user->getRoles(), $user);

$authToken = $this->authenticationManager->authenticate($token);
$this->tokenStorage->setToken($authToken);

$this->authorizationChecker->isGranted('ROLE_USER');
```

But I guess there is a smarter way to populate the authentication manager with the JWT User Token?

**Comment by webdevilopers** [comment]
I've recognized that the `JWTUserToken` already exists inside the `tokenStorage`.
Though authenticated it looks like the `roles` are missing that are required for the `isGranted` checks via authorization manager:

```
JWTUserToken {#211 ▼
  #rawToken: "..."
  #providerKey: null
  -user: null
  -roles: []
  -authenticated: true
  -attributes: []
}
```

**Comment by webdevilopers** [comment]
I found the solution. Our config still had some old keys:

```yaml
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
```

After completely(!!!) removing the `lexik_jwt` key everything works as expected.

Is there a reason the `key` is still supported? It looks like a legacy config for older symfony version?

**Comment by chalasr** [comment]
See https://github.com/lexik/LexikJWTAuthenticationBundle/pull/738 :) Thanks for investigating @webdevilopers!
