### ISSUE TITLE
(1/1) NotFoundHttpException Unable to find the controller for path "/api/login_check". The route is wrongly configured.

### ISSUE THREAD

**Issue by sterichards** [lexik/LexikJWTAuthenticationBundle#740]
I am using "lexik/jwt-authentication-bundle": "^2.6" with "symfony/framework-bundle": "4.2.*",

This is a new project without any other changes from the symfony repo

I have applied all changes in the installation instruction buts I get the following error when making a POST to api/login_check:

(1/1) NotFoundHttpExceptionUnable to find the controller for path "/api/login_check". The route is wrongly configured.
--
in HttpKernel.php line 134
at HttpKernel->handleRaw(object(Request), 1)in HttpKernel.php line 67
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 198
at Kernel->handle(object(Request))in index.php line 25

**Comment by sterichards** [comment]
I removed default  security.yaml entries and this now works for me

**Comment by lefuturiste** [comment]
> I removed default security.yaml entries and this now works for me

I have the same problem but I can't find what are the "default entries" ?

**Comment by sterichards** [comment]
> > I removed default security.yaml entries and this now works for me
> 
> I have the same problem but I can't find what are the "default entries" to remove?

This was too long about for me to remember the exact details of the default entries

Here is a snippet of my firewalls and access_control entry. Hope it helps:

`firewalls:
        reset_password:
            pattern: ^/reset-password
            stateless: true
            security: false
            anonymous: true

        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/
            stateless: true
            jwt: ~
            
            
access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }            `

**Comment by lefuturiste** [comment]
Yes I solved it just after I posted here. It was a issue with the orders of the firewalls. But thanks you anyways It could have solve this issue too.

**Comment by sterichards** [comment]
> Yes I solved it just after I posted here. It was a issue with the orders of the firewalls. But thanks you anyways It could have solve this issue too.

Ahhh yes, firewall order issue. It's a classic :)
