### ISSUE TITLE
getUser from REST API

### ISSUE THREAD

**Issue by ewertoncode** [lexik/LexikJWTAuthenticationBundle#742]
hi all!

I'm want auth my user from REST API. I created a Custom Guard (App\Secutiry\JWTTokenAuthenticator) where I get the credetials posted from the user (json_login):

```
public function getCredentials(Request $request)
    {
        return [
            'username' => $request->request->get('username'),
            'password' => $request->request->get('password')
        ];
    }
```

And in my getUser method I try get user from the database or REST API:

```
public function getUser($credentials, UserProviderInterface $userProvider)
    {

        if (null === $credentials) {
            // The token header was empty, authentication fails with HTTP Status
            // Code 401 "Unauthorized"
            return null;
        }

        $user = $this->entityManager->getRepository(User::class)->findOneBy(['username' => $credentials['username']]);

        if (!$user) {
              // MAKE REQUEST TO API
            // FILL my user entity and persist
        }
    return $user;
}
```

I get token whit sucess, but in dev.log I saw that a query in database to verify the user. I undertood when set stateless:true in firewall this should not happen (maybe I got it wrong).

There is a way that I don't need persist in database my user and generate token e validate that same way?

Thanks a lot!

**Comment by fd6130** [comment]
For what i know, stateless doesn't mean that it won't persist in database nor it won't query from database.  Stateless simply mean that it is session-less.

For database-less, perhaps you mean this one https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/8-jwt-user-provider.md

**Comment by ewertoncode** [comment]
Thanks
