### ISSUE TITLE
Activation token by email

### ISSUE THREAD

**Issue by Sftaita** [lexik/LexikJWTAuthenticationBundle#751]
Hello community.

I am taking the liberty of asking for your help because I am a novice. I have created a functional site, using JWT authentication. 

I have created in my USER entity an "activation_token", which receives a random token when a USER is created.

What I've already done: A link is created and sent by email. When the USER clicks on the link, the activation token entity becomes NULL.

What I'm trying to do: When a user logs in, if activation_token is not NULL, the account does not log in.

My problem: I have no idea where to write this condition with LExikJWTBundle...

If someone can help me it would be great!!!!

**Comment by norkunas** [comment]
Hi,
You should create a custom user checker (https://symfony.com/doc/current/security/user_checkers.html) which would throw exception if activation token is not null.

**Comment by Sftaita** [comment]
dear Thomas,   


Thank you for your answer. I've already tried it, but it's not working.

First of all in the documentation it explains to use:

use App\Security\User as AppUser;

but I can't find this address.

My user entity is called User patient butApp\Security\UserPatient does not exist either.

**Comment by norkunas** [comment]
So you should use namespace where your UserPatient entity is stored :)

**Comment by Sftaita** [comment]
Good morning,,

It would actually work better :).

I followed the documentation but the file never seems to be read.

For the moment my UserChecker is in my controllers because there is already a UserChecker in App/security.

Here is my code

`
src/Controller/UserChecker

namespace App\Controller;                           //I used this namepace because there was already a UserChecker in security

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\User as UserPatient;
use Symfony\Component\Security\Core\User\UserCheckerInterface;
use Symfony\Component\Security\Core\Exception\InvalidValidationException;

class UserChecker implements UserCheckerInterface
{
    // Personnal function for check the activation token
    /*
    public static function fetchEmail($email)
    {
        $request = $this->repo->fetchByEmail($email);
        $transit = $request[0];
        return  $transit["activation_token"];
    }
    */
    
    
    public function checkPreAuth(UserInterface $user)
    {
        if (!$user instanceof UserPatient) {
            return;
        }
        
        $x=1;
        
        if ($x === 1) {   
            throw new InvalidValidationException('This user must be valadate first');      //I use this exception for the moment
        }

        
    }

    public function checkPostAuth(UserInterface $user)
    {
        if (!$user instanceof UserPatient) {
            return;
        }

        /*
        $email = $user->getUsername();
        $token = self::fetchEmail($email);
        */
    }
}`


And this is my security YAML:

`  firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
       
        UserPatient_registration:
            pattern: ^/api/medics
            anonymous: true
            stateless: true
            methods: [POST]

        login:
            pattern:  ^/api/login
            provider: all_users
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            provider: all_users
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: lazy 
            user_checker: App\Controller\UserChecker`

**Comment by Sftaita** [comment]
I found something that works, even though I'm not a fan of the method. I used Login Event Listener. 

It works but I don't think it's great because first, you log the user, then you check the condition, then you log him out if the condition is not met.

**Comment by norkunas** [comment]
You should define on your `login` and `api` firewalls your user checker to make it work.

```
    login:
        pattern:  ^/api/login
        provider: all_users
        stateless: true
        anonymous: true
        user_checker: 'App\Controller\UserChecker'
        json_login:
            check_path:               /api/login_check
            success_handler:          lexik_jwt_authentication.handler.authentication_success
            failure_handler:          lexik_jwt_authentication.handler.authentication_failure
    api:
        pattern:   ^/api
        stateless: true
        anonymous: true
        provider: all_users
        user_checker: 'App\Controller\UserChecker'
        guard:
            authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator
```

**Comment by Sftaita** [comment]
Mmmm. No, it's not working. It's driving me crazy.

**Comment by fd6130** [comment]
It should work unless you have missed something. Have you tried add `dd('hello world')` to your user checker `checkPreAuth()` and `checkPostAuth()` method (put it before the if statement) to see if it will print out "hello world" or not?
