### ISSUE TITLE
Add auth route to generated documentation

### ISSUE THREAD

**Issue by McCrafterIV** [lexik/LexikJWTAuthenticationBundle#752]
I use nelmio/api-doc-bundle to document my API. Now I want to add the authentication route (in my case `security/login_check`) to the generated docs. The problem is (I think) that there is no controller for this route specified in the routes.yaml. Is there a way to add a controller to this route (in the routes.yaml) or create a new controller that "opens" the authenticator so that I can attatch the documentation to this function?

**Comment by fd6130** [comment]
> nelmio/api-doc-bundle

Hmmm maybe just create a new controller and inject `AuthenticationSuccessHandler` class to manually generate token.

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/7-manual-token-creation.md
