### ISSUE TITLE
Not setting the attribute "version" of the node "deprecated" is deprecated.

### ISSUE THREAD

**Issue by pdugas** [lexik/LexikJWTAuthenticationBundle#762]
Need to adjust `Resources/config/deprecated.xml` to add `version` attributes to the `<deprecated/>` tags to support Symfony 5.1.

**Comment by gmponos** [comment]
I think this is fixed on master.. I tried master and it seems to work.. 

@maintainers pls tag this.. this is the only thing that is blocking me as well to update to sf 5.1

**Comment by fd6130** [comment]
> I think this is fixed on master.. I tried master and it seems to work..
> 
> @ maintainers pls tag this.. this is the only thing that is blocking me as well to update to sf 5.1

So we have to wait for the new release yeah?

**Comment by gmponos** [comment]
Not sure if maintainers are waiting for something else to be fixed.. 

if not.. then yes we have to wait.. unless if you have tag privileges. 😋

**Comment by chalasr** [comment]
I’ll tag before sunday.

**Comment by chalasr** [comment]
Just tagged v2.8.0 (minor only because we removed PHP 5.5 support meanwhile, upgrading should be easy).
