### ISSUE TITLE
Undefined class constant 'SAMESITE_NONE'

### ISSUE THREAD

**Issue by bmehdi** [lexik/LexikJWTAuthenticationBundle#765]
https://github.com/lexik/LexikJWTAuthenticationBundle/pull/753 evolution does not work with symfony version < 3.4.28 because SAMESITE_NONE constant has been added in https://github.com/symfony/http-foundation/commit/f9bb07318c806a7dbe246f196b8af941585ad8e7. We have error message 'Undefined class constant 'SAMESITE_NONE' in composer install.

**Comment by simoninkel** [comment]
Hi there! I got the same issue with my SF4.1 project.

"Undefined class constant 'SAMESITE_NONE' in /code/vendor/lexik/jwt-authentication-bundle/DependencyInjection/Configuration.php on line 91"

I can't seem to understand what the problem is here.

**Comment by chalasr** [comment]
The problem is that this constant was introduced in a patch release on Symfony. We need to hardcode the `none` value for fixing it.
But note that your Symfony installation is outdated, you should really upgrade :)

**Comment by bmehdi** [comment]
Can we put "^3.4.28|^4.1.x..." at symfony dependency in composer.json ?

**Comment by DaveKnifeman** [comment]
@chalasr Which Symfony version contains the constant?
