### ISSUE TITLE
Event Not Dispatch

### ISSUE THREAD

**Issue by ad3n** [lexik/LexikJWTAuthenticationBundle#768]
![Screenshot from 2020-07-15 17-57-07](https://user-images.githubusercontent.com/7464920/87537409-c210ec00-c6c4-11ea-9c8f-65c598977826.png)

I use Symfony 5.1.2 and recently the event is fired but i am not remember when the event is not fired any more

**Comment by fd6130** [comment]
What do you mean? Can you explain it more?
