### ISSUE TITLE
Refresh token as cookie

### ISSUE THREAD

**Issue by greenkey-m** [lexik/LexikJWTAuthenticationBundle#773]
I can use config for set token to cookie:
  set_cookies:
    BEARER: ~

But, when i adding refresh cookie from
https://github.com/markitosgv/JWTRefreshTokenBundle

this token added to response body, is it possible to move refresh token to cookie, with special path?

**Comment by chalasr** [comment]
We would need someone to contribute that feature to https://github.com/markitosgv/JWTRefreshTokenBundle :)

**Comment by chalasr** [comment]
Now available since  https://github.com/markitosgv/JWTRefreshTokenBundle v1.0
