### ISSUE TITLE
Inestable performance of the bundle

### ISSUE THREAD

**Issue by acabrerac** [lexik/LexikJWTAuthenticationBundle#776]
I'm getting this error:

`Unable to verify the given JWT through the given configuration. If the \u0022lexik_jwt_authentication.encoder\u0022 encryption options have been changed since your last authentication, please renew the token. If the problem persists, verify that the configured keys\/passphrase are valid.`

It happens sometimes, others not. It is the same code, same credentials, same user. 

After run the command `bin/console lexik:jwt:check-config` I got

The configuration seems correct. 

I'm using the latest version (2.8)

**Comment by fd6130** [comment]
Not sure what causing the issue, this issue still persist?
