### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by TiS** [lexik/LexikJWTAuthenticationBundle#78]
Recently Ive come up with action to issue new, refreshed token without providing username / password. This may be used to decrease token TTL (which increases security).

```php
  public function refreshAction(Request $request)
    {
        /* @var $token JWTUserToken */
        $token = $this->get('security.context')->getToken();
        
        //Code to issue new, refreshed JWT token
        /* @var $jwtAuthenticationSuccess AuthenticationSuccessHandler */
        $jwtAuthenticationSuccess = $this->get('lexik_jwt_authentication.handler.authentication_success');
        return $jwtAuthenticationSuccess->onAuthenticationSuccess($request, $token);
    }
```

You may be interested in adding this to documentation examples.

**Comment by slashfan** [comment]
Hi, why not ! Do you think you could write a small example / use case ?

**Comment by TiS** [comment]
Certainly, in a few days.

**Comment by hiniesta** [comment]
Hello. I have an issue. I can't find a method to logout and destroy token and session. Any idea?

regards!
