### ISSUE TITLE
Create command for rsa generator

### ISSUE THREAD

**Issue by AdGARAY** [lexik/LexikJWTAuthenticationBundle#784]
Hi!

I'm using LexikJWTAuthentication, I wrote some code to generate the rsa for functional testing in automated CI/CD I use the Process Component of Symfony and the SymfonyCommands, what do you think about add this to the bundle

**Comment by rayenhidri27** [comment]
im using this library and this command, but when it asks me do enter the pass phrase, i cant type anything
i tried to type it in windows terminal, in VS Code terminal and even in git bash, it stills not working
is it a known issue ?
if so, is there a solution ?

even i wanna note that on git bash it stills bloqued in +++++++ and it dont ask for pass phrase

**Comment by rayenhidri27** [comment]
note that im on win 10, symfony 4.4.15, API Platform 2.5

**Comment by AdGARAY** [comment]
@rayenhidri27 that is not related to the issue if the issue is related with openssl is not related to this library and maybe you need to install it, I never tri it in windows https://www.openssl.org/

**Comment by rayenhidri27** [comment]
openssl is installed on my PC and the openssl command is working well

**Comment by fd6130** [comment]
@AdGARAY  That's a great idea, so we don't have to always refer to this docs, copy paste the command and execute it.

**Comment by fd6130** [comment]
> openssl is installed on my PC and the openssl command is working well

The pass phrase doesn't comes up anything after typing it is not an issue. After finish typing just press enter it will proceed to next stage.

**Comment by whizsid** [comment]
@AdGARAY  Can you post your script. I am stuck on configuring my CI.

**Comment by whizsid** [comment]
@AdGARAY I think this will work.
`openssl genpkey --help`:-
```
-pass val          Output file pass phrase source
```

`openssl pkey --help`:-
```
-passin val       Input file pass phrase source
```

To generate rsa files without any password prompt.

```
$ mkdir -p config/jwt
$ openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 --pass pass:mypassword
$ openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout --passin pass:mypassword
```

**Comment by fd6130** [comment]
We can generate keypair using `php bin/console lexik:jwt:generate-keypair`.
