### ISSUE TITLE
Problème login_check

### ISSUE THREAD

**Issue by aymericl** [lexik/LexikJWTAuthenticationBundle#79]
Bonjour,
J'ai installé LexikJWTAuthenticationBundle en suivant la documentation.

Cependant j'arrive pas à accéder à l'url "api/login_check".

j'ai cette erreur là : 
Unable to find the controller for path "/api/login_check". The route is wrongly configured.

C'est là première fois que je met en place un système de token.

security.yml : 
firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY } 

Routing.yml : 

#REST
rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api

api_login_check:
   path: /api/login_check

Pouvez-vous m'aider, merci.

**Comment by slashfan** [comment]
Salut, tu essaies d'accéder à l'url `/api/login_check` en GET ou en POST ?

**Comment by aymericl** [comment]
J'ai essayé en get et en post avec mon client angularJS qui me renvoi une erreur 404 aussi.

Merci de ton aide.

**Comment by aymericl** [comment]
Après avoir recommencer tout à 0, le message d'erreur à changé, c'est une erreur 401 (Unauthorized) quand je fais un post avec les données suivantes : {_username: "johndoe", _password: "test"}.

**Comment by aymericl** [comment]
Après de multiple essai, j'ai réussi. 

Je vous remercie :+1:

**Comment by aymericl** [comment]
J'ai recommencer à 0, j'ai persévéré et ça fonctionne à merveille.

Good job !
