### ISSUE TITLE
RegisteredClaimGiven exception raised with "iss" payload key

### ISSUE THREAD

**Issue by samijnih** [lexik/LexikJWTAuthenticationBundle#800]
Hey :wave: 

I've updating the bundle related to #793 but it still does not work.

I still have that exception
![image](https://user-images.githubusercontent.com/10528754/100521931-4ad98180-31a7-11eb-8752-6671a4fd8f3e.png)

I've been debugging and seems that it is not related to #793 about `OpenSSLAsymmetricKey` anymore.

It's now about `RegisteredClaims::ALL` from _lcobucci/jwt/src/Token/Builder.php:84_

I have a listener on JWT events which manually sets `iss` and `sub` keys.

![image](https://user-images.githubusercontent.com/10528754/100522775-b45b8f00-31ab-11eb-9691-6a5dcc0f9201.png)

But it's failing in the token builder because of _in_array_ check against `RegisteredClaims::ALL`.

![image](https://user-images.githubusercontent.com/10528754/100522183-3e562880-31a9-11eb-8d4e-7edfa474f8c5.png)

Is it possible to add a call to `Token\Builder::issuedBy` when the payload contains the `iss` key in _lexik/jwt-authentication-bundle/Services/JWSProvider/LcobucciJWSProvider.php_?
Actually you prevent any raised exception by looking on `sub` and `exp` keys.

I understand that I can define `iss` keys but the "setter" for `iss` is just missing.

Thanks :)

**Comment by samijnih** [comment]
Ok I think I had misunderstood your class behavior. I'm gonna edit this issue in few minutes because it is not like I've described above

**Comment by chalasr** [comment]
Hey @samijnih, thanks for the report.
#801 should fix this.

**Comment by samijnih** [comment]
@chalasr Hey

Just to tell you that my issue is fixed. It's working again, thanks :)
