### ISSUE TITLE
Using lcobucci/jwt v4.0 breaks jti claim

### ISSUE THREAD

**Issue by Warrows** [lexik/LexikJWTAuthenticationBundle#803]
I've been using this bundle for some time now. Trying to set it up on a new project I get everything fresh and copy some old code of mine.
Turns out using lcobucci/jwt v4.0 breaks the jti claim set through payload.
```
    public function onJWTCreated(JWTCreatedEvent $event)
    {
        $request = $this->requestStack->getCurrentRequest();
        $payload['token_type']     = 'access';
        $payload['jti']            = uniqid();
        $event->setData($payload);
    }
```
Gives
```
Lcobucci\JWT\Token\
RegisteredClaimGiven
Builder#withClaim() is meant to be used for non-registered claims, check the documentation on how to set claim "jti"
```
I haven't looked too far into it. But at first glance I think the best way to fix this would be either to:
- Check if a JTI claim is present and if yes to pass it to lcobucci/jwt through it's dedicated method `identifiedBy` as seen in https://github.com/lcobucci/jwt/blob/master/docs/issuing-tokens.md.
- Or use configuration to ask if we should automaticaly generate JTI and pass it correctly to the dependancy.

Other registered claims will certainly need the same kind of treatement. In the meantime, I'll avoid v2.10.1

**Comment by chalasr** [comment]
Just released v2.10.2 which ships a fix for this (#801). Can you please confirm it works for you?

**Comment by Warrows** [comment]
It doesn't seem to work.
Afforementionned error is still returned. 
Stack goes through 
`lcobucci\jwt\src\Token\Builder.php (line 85)`
`lexik\jwt-authentication-bundle\Services\JWSProvider\LcobucciJWSProvider.php (line 137)` : `$jws->{method_exists($jws,'with') ? 'with' : 'withClaim'}($name, $value);`

**Comment by chalasr** [comment]
Sorry, it should be ok with #804 (I used your test case), thanks for trying. 
I'm going to release v2.10.3 once the CI is green.

**Comment by Warrows** [comment]
Works like a charm. Thank you very much.
