### ISSUE TITLE
JWT Token combined simple_preauth

### ISSUE THREAD

**Issue by jankrueger** [lexik/LexikJWTAuthenticationBundle#81]
Hi, 

we are trying to combine LexikJWT authentication with a api key simple_preauth and are struggling with the configuration. 
Can you tell me if it is possible, to have a simple_preauth that is issuing a PreAuthToken in the same firewall as lexik_jwt?

**Comment by slashfan** [comment]
Hi, I haven't tested it with simple_preauth personnally but I guess it should be possible. What problem are you facing exactly ?

**Comment by jankrueger** [comment]
Hi @slashfan , 
thanks for your reply. I solved the problem by reviewing my code. 
The problem was that in my preauth handler i issued a `PreAuthenticatedToken` (which is fine) but added the role `IS_AUTHENTICATED_ANONYMOUSLY` explicitly. This made the `PreAuthenticatedToken` set its `authenticated` attribute to true and then ignores any firewall configuration afterwards.
