### ISSUE TITLE
Argument 1 passed to Lcobucci\JWT\Builder::sign()

### ISSUE THREAD

**Issue by PlamenPanayotov** [lexik/LexikJWTAuthenticationBundle#814]
Hello, I have a issue using the lexik/jwt-authentication-bundle v2.10.4, the message is "Argument 1 passed to Lcobucci\JWT\Builder::sign() must implement interface Lcobucci\JWT\Signer, instance of Lcobucci\JWT\Signer\Key given, called in /home/plamen/Projects/test/vendor/lexik/jwt-authentication-bundle/Services/JWSProvider/LcobucciJWSProvider.php on line 223", I believe that something is wrong with the LcobucciJWSProvider classs.

security.yaml
    

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

**Comment by chalasr** [comment]
Fixed in v2.10.5, thank you very much for the report @PlamenPanayotov.
