### ISSUE TITLE
Symfony 5.2 support

### ISSUE THREAD

**Issue by Eimantas123** [lexik/LexikJWTAuthenticationBundle#818]
When it will be supported for symfony 5.2?

**Comment by Eimantas123** [comment]
When it will be supported for symfony 5.2?

**Comment by fd6130** [comment]
Isn't it already support long time ago?

**Comment by chalasr** [comment]
Yes it does, the CI proves that.
Please tell us about the exact issue you have on 5.2 if you have one.
