### ISSUE TITLE
Consider switching underlying library from namshi/jose to lcobucci/jwt

### ISSUE THREAD

**Issue by guilhermeblanco** [lexik/LexikJWTAuthenticationBundle#82]
Reference: https://github.com/lcobucci/jwt

It does provide better support than namshi/jose. Check http://jwt.io/ for tests.

**Comment by slashfan** [comment]
Hi, library adapters are planned for the v2 version. And indeed, it seems to be a very good library. Thanks for sharing.

**Comment by javierseixas** [comment]
@slashfan that adapters features you talk about sounds really interesting. Is there any planning about when it is going to be released?

**Comment by chalasr** [comment]
@guilhermeblanco For the record, an encoder based on `lcobucci/jwt` has been added in the recently released V2. I hope we can totally switch from `namshi/jose` to this one in a near future, some help from people experienced with the library would be really appreciated.
