### ISSUE TITLE
Proper way to add verifications at login

### ISSUE THREAD

**Issue by nicolaskern** [lexik/LexikJWTAuthenticationBundle#83]
Hi,

I'm using your bundle in a new project, it works perfectly well, but I'm facing a problem :
What's the best way to put additional verifications at login?
I'd like to check if my user has some properties matching a right value before authenticating him.

I think I have to do it before JWT creation, so I tried to extend the JWTProvider and override authenticate method, without success.
Have I to listen to SecurityInteractiveLogin event and add my check logic here ?

I'm quite lost here...

Thanks a lot for your help,
Nicolas

**Comment by slashfan** [comment]
Hi, have a look at this part of the documentation https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md. There are examples on how to do that  without having to override the provider but by using events.

Tell me if it helps.

**Comment by nicolaskern** [comment]
Hi,

I guess this would be the right solution, but I think the events are dispatched too "far" in the authentication process :
Events::JWT_CREATED is dispatched after the JWT is created, but I don't want it to be created (or maybe I need to remove it, but that's not nice...)
Events::JWT_DECODED, Events::JWT_AUTHENTICATED, Events::AUTHENTICATION_SUCCESS and Events::JWT_ENCODED already has a JWT.

I guess it lacks an event dispatched before the JWT is created, what do you think?

Best,
Nicolas

**Comment by slashfan** [comment]
Hi, sorry I didn't have the time to work on it but feel free to make a PR or an entry in the documentation if you think it can be useful to others.

**Comment by nicolaskern** [comment]
Well actually, I don't have a clue about how I an do it.
Maybe someone can give a hand?

Best,
Nicolas

**Comment by slashfan** [comment]
Do you want to add checks before the user logs in the first time (using its credentials) to get a JWT or every time he uses the JWT as authentication mecanism ?

**Comment by nicolaskern** [comment]
I'd like to be able to check the first time he requests a JWT, using his _username and _password.
The idea is to check, for example, if my user has a boolean with the right value ;)

**Comment by slashfan** [comment]
Then I guess it's up to your userprovider to do this check. Creating and sending the JWT only happens after form login success. What do you tihink ?
