### ISSUE TITLE
Help on how to provide a new KeyLoader

### ISSUE THREAD

**Issue by drupol** [lexik/LexikJWTAuthenticationBundle#831]
Hello,

I'm working on a custom bundle that I will most probably release soon.

Basically the idea of this bundle is to provide a new type of [KeyLoader](https://github.com/lexik/LexikJWTAuthenticationBundle/tree/dc472dd55d6a7bc374306e3df8e6202bc95f76e9/Services/KeyLoader).
That new `KeyLoader` would make a request to fetch a public key and I also need to implements a "failsafe" mechanism when HTTP calls fails. The failsafe mechanism would then retrieve a local version of the key when the HTTP call fails.

This bundle will let you use a key defined remotely in a `jwks.json` file, eg:

```
lexik_jwt_authentication:
    secret_key: null
    public_key: 'http://something.com/jwks.json'
    pass_phrase: null
```

In order to do that, I created a `JWKSKeyLoader.php` service which is registered as such in my bundle:

```php
    $container
        ->services()
        ->set('foo.jwks_keyloader', JWKSKeyLoader::class)
        ->decorate('lexik_jwt_authentication.key_loader.raw')
        ->args([
            null, // Placeholder for $signingKey
            null, // Placeholder for $publickKey
            null, // Placeholder for $passPhrase
            service('.inner'),
            service('http_client')
        ])
        ->autowire(true)
        ->autoconfigure(true);
```

Everything so far works great.
However, when I inspect the values in `JWKSKeyLoader::__construct()`, I noticed that the `$publicKey` is always empty.

I also noticed that those values are injected in [LexikJWTAuthenticationExtension.php](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/dc472dd55d6a7bc374306e3df8e6202bc95f76e9/DependencyInjection/LexikJWTAuthenticationExtension.php#L89):

```php
        $container
            ->findDefinition('lexik_jwt_authentication.key_loader')
            ->replaceArgument(0, $config['secret_key'])
            ->replaceArgument(1, $config['public_key']);
```

Then my question is, how do you create a working decorator when its arguments are replaced? What would be the proper way to do that? Is there maybe a better way to achieve what I'm trying to do?

Thanks!

**Comment by Spomky** [comment]
Hi @drupol ,

If you use the [Spomky-Labs/lexik-jose-bridge bundle](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#service), you can use JWKS, JWK and much more (token encryption) out of the box.

**Comment by drupol** [comment]
Hi @Spomky,

Thanks for replying.

I updated my original message to include an explanation:

> Basically the idea of this bundle is to provide a new type of [KeyLoader](https://github.com/lexik/LexikJWTAuthenticationBundle/tree/dc472dd55d6a7bc374306e3df8e6202bc95f76e9/Services/KeyLoader).
> That new `KeyLoader` would make a request to fetch a public key and I also need to implements a "failsafe" mechanism when HTTP calls fails. The failsafe mechanism would then retrieve a local version of the key when the HTTP call fails.

I checked the bundle you advised but I don't think that the failsafe mechanism is implemented, so, it's not a good option for me.

Thanks for proposing it.

**Comment by Spomky** [comment]
> > Basically the idea of this bundle is to provide a new type of [KeyLoader](https://github.com/lexik/LexikJWTAuthenticationBundle/tree/dc472dd55d6a7bc374306e3df8e6202bc95f76e9/Services/KeyLoader).
> > That new `KeyLoader` would make a request to fetch a public key and I also need to implements a "failsafe" mechanism when HTTP calls fails. The failsafe mechanism would then retrieve a local version of the key when the HTTP call fails.
> 
> I checked the bundle you advised but I don't think that the failsafe mechanism is implemented, so, it's not a good option for me.

Your fallback logic should be in the HTTP client in case of non-2xx response. This is not different from a caching system. 
As the bundle I mentioned uses interfaces and not concrete implementation, you can easily use any client you want that allows you to always return a JWKS, even if the request failed (e.g. the symfony Http client Component or Guzzle)

**Comment by chalasr** [comment]
Thanks for your inputs @Spomky, closing as resolved.

**Comment by drupol** [comment]
The outcome of this is now live at https://github.com/ecphp/api-gw-authentication-bundle !

Thank you all for your help.
