### ISSUE TITLE
Release 2.11 breaks execution of `bin/console`

### ISSUE THREAD

**Issue by gggeek** [lexik/LexikJWTAuthenticationBundle#837]
See the description of the problem at https://github.com/lexik/LexikJWTAuthenticationBundle/pull/817#pullrequestreview-589297637

Note that this breaks only running the console without any other command, because the new, faulty command service is lazy loaded by default. It gets loaded when running bin/console, I guess, to have its description line...

**Comment by chalasr** [comment]
Thank you for the report @gggeek, I'm on it

**Comment by DavG** [comment]
Looks like the 2.11 version forces having a secret key on the project. Seems strange to me and not in the spirit of previous versions.

(On my projects, only one have the secret key, others only have public key).

Thanks in advance !

**Comment by chalasr** [comment]
Fixed in #838 and released in v2.11.2.
