### ISSUE TITLE
server side secret key rotation

### ISSUE THREAD

**Issue by uy711591** [lexik/LexikJWTAuthenticationBundle#843]
I was looking for a way to automatically change the passphrase and generate a new one while time is elapsing.
Do I have to write a script in order to that or is there something I could use?

**Comment by chalasr** [comment]
You can use the [Spomky-Labs/lexik-jose-bridge's key rotation feature](https://github.com/Spomky-Labs/lexik-jose-bridge/blob/v3.0/Resources/doc/Configuration.md#rotation-of-the-keys).
