### ISSUE TITLE
Question about logout :)

### ISSUE THREAD

**Issue by Yoann-TYT** [lexik/LexikJWTAuthenticationBundle#85]
Hello !
Thank you for this awesome bundle ;)

Just a small question... I don't know how to implement api/logout ?

Thanks a lot !

**Comment by slashfan** [comment]
Hi, does [this](https://github.com/lexik/LexikJWTAuthenticationBundle/issues/58#issuecomment-89641970) help ? There is no logout concept in a stateless authentication mecanism, you have to invalidate the token so it can not be longer be used and the user has to authenticate again.
