### ISSUE TITLE
Jwt token for user not in database but get with webservice

### ISSUE THREAD

**Issue by kevin-schmitt** [lexik/LexikJWTAuthenticationBundle#853]
Hello,

I want to construct jwt token for user get from a soap webservice, i have to use custom authenticator or provider please?

Thanks

**Comment by chalasr** [comment]
You probably need a custom user provider that load users from your soap service.
We use github for tracking issues and feature requests only, so please consider using symfony [support channels](https://symfony.com/support) if you need more help.
