### ISSUE TITLE
UserInterface: no such service exists

### ISSUE THREAD

**Issue by thehatami** [lexik/LexikJWTAuthenticationBundle#854]
i follow all instruction in here and implemented via symfony 5.2. but in login_check i get this error:

`Cannot autowire argument $user of "App\Controller\UserController::getTokenUser()": it references interface "Symfony\Component\Security\Core\User\UserInterface" but no such service exists. Did you create a class that implements this interface?
`

**Comment by fd6130** [comment]
What is the usage of `App\Controller\UserController`? Is it a controller class that create by you?

**Comment by ThibaultVlacich** [comment]
You cannot autowire UserInterface. you need to access using `$this->getUser()` in Controllers

**Comment by chalasr** [comment]
Closing here due to the lack of feedback.
