### ISSUE TITLE
Is it possible to use without Doctrine and custom models?

### ISSUE THREAD

**Issue by bettinz** [lexik/LexikJWTAuthenticationBundle#856]
Hello, I'm building a simple project with DDD and hexagonal architecture.
What I'm trying to do is to keep library/vendor services from domain: in that case I'm using api-platform with data transformers and with data provider and persister.
I'm also using a Model (a simple PHP class) with doctrine and I'm manually persisting a retrieving a user; because of that my domain User class doesn't implement UserInterface or anything related to Symfony/Doctrine.
My question is: can I use LexikJWTAuthenticationBundle to create the token after I've manually checked that email and passwords are verified?
Thanks

**Comment by fd6130** [comment]
> Hello, I'm building a simple project with DDD and hexagonal architecture.
> What I'm trying to do is to keep library/vendor services from domain: in that case I'm using api-platform with data transformers and with data provider and persister.
> I'm also using a Model (a simple PHP class) with doctrine and I'm manually persisting a retrieving a user; because of that my domain User class doesn't implement UserInterface or anything related to Symfony/Doctrine.
> My question is: can I use LexikJWTAuthenticationBundle to create the token after I've manually checked that email and passwords are verified?
> Thanks

Hmmm... i think you may want to check their internal code inside like how they create JWT etc. Extract those useful method and apply to your project.

**Comment by chalasr** [comment]
Yes, you can. Please consider using our support platforms such as the symfony-devs slack or stackoverflow with the `lexikjwtauthbundle` tag, if looking at the documenntation and/or the codebase is not enough.
Thank you.
