### ISSUE TITLE
is it possible to secure the urls of my api in addition to jwt so that only my mobile application can access them?

### ISSUE THREAD

**Issue by emj1986** [lexik/LexikJWTAuthenticationBundle#861]
I am using symfony 5 and LexikJWTAuthenticationBundle to authenticate users. everything works fine but I would like to ensure that only my mobile application can access the API. is it possible to override login_check in order to accept only request coming from my mobile app? thank you.

**Comment by fd6130** [comment]
Perhaps you need to write your custom event subscriber or something to intercept your request.

**Comment by chalasr** [comment]
Please use Symfony docs or official support channels for this.
