### ISSUE TITLE
2.11.3 tag based on wrong commit?

### ISSUE THREAD

**Issue by mbabker** [lexik/LexikJWTAuthenticationBundle#863]
It looks like the 2.11.3 tag is based on commit 78e8ddda0a57de4f2eb40ab247922e33e0772bc2, which seems to be [several commits](https://github.com/Lexik/LexikJWTAuthenticationBundle/compare/78e8ddda0a57de4f2eb40ab247922e33e0772bc2...2.x) behind the 2.x branch, and doesn't look to include a175d6dab968d93e96a3e4f80c495435f71d5eb7 as noted on the release changelog.

**Comment by chalasr** [comment]
Thank you. I'm on it.

**Comment by chalasr** [comment]
Fixed, thanks again for the report!
