### ISSUE TITLE
Using Symfony\Component\Security\Guard\AbstractGuardAuthenticator is deprecated in Symfony 5.3

### ISSUE THREAD

**Issue by ThibaultVlacich** [lexik/LexikJWTAuthenticationBundle#866]
Symfony 5.3 triggers this deprecation warning:

> User Deprecated: The "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" class extends "Symfony\Component\Security\Guard\AbstractGuardAuthenticator" that is deprecated since Symfony 5.3, use the new authenticator system instead.

**Comment by ChristianVermeulen** [comment]
Check out #810.

**Comment by a2550559** [comment]
I am trying to configure, but I get the error: 

`Argument 1 passed to Symfony\Component\Security\Http\Authentication\AuthenticatorManager::executeAuthenticator() must implement interface Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface, instance of Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator given, called in /mypath/vendor/symfony/security-http/Authentication/AuthenticatorManager.php on line 152 `

**Comment by ChristianVermeulen** [comment]
@TristanPouliquen is working on #872 in order to support this.
