### ISSUE TITLE
Programmatically logging a user

### ISSUE THREAD

**Issue by nicolaskern** [lexik/LexikJWTAuthenticationBundle#87]
Hi,

When I register an user, I'd like to be able to get his JWT.
I can't manage to find a proper way to do it, can this be done?

Thanks,
Nicolas

**Comment by blt909** [comment]
Hi,

we have a similar use case here.
Some of our users can register through social networks apis, and so we don't ask them a password.

Thanks

**Comment by slashfan** [comment]
Hi, does [this](https://github.com/lexik/LexikJWTAuthenticationBundle/issues/61#issuecomment-93706866) help ?
