### ISSUE TITLE
Allow only users with verified email

### ISSUE THREAD

**Issue by lukepass** [lexik/LexikJWTAuthenticationBundle#870]
Hello,
I would like to allow login only for users with a verified email address. I looked into this documentation:

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/2-data-customization.md

But I couldn't find an event to use. I would like something like this:

```
{
    "code": 403,
    "message": "Email address not verified."
}
```

Is it possible to add this (and potentially others) custom validations on the user?

Thanks.

**Comment by ThibaultVlacich** [comment]
Yes, you need to create a UserChecker class. This is a Symfony level feature. 

https://symfony.com/doc/current/security/user_checkers.html

**Comment by lukepass** [comment]
Thank you, this is exactly what I was looking for!
