### ISSUE TITLE
No route found for \"POST /api/login_check%20%20\

### ISSUE THREAD

**Issue by salina33** [lexik/LexikJWTAuthenticationBundle#871]
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers

    encoders:
        App\Entity\User: bcrypt

    providers:
 #       users_in_memory: { memory: null }
        database:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            provider: database
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                    - App\Security\LoginFormAuthenticator
                entry_point: lexik_jwt_authentication.jwt_token_authenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

**Comment by fd6130** [comment]
You need to add a route in config/routes.yaml"

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.md#configuration

```
api_login_check:
    path: /api/login_check
```

**Comment by ahules** [comment]
@fd6130 I have the same issue. 
I defined settings as you describe, but I do not understand should I create any controller?

**Comment by fd6130** [comment]
> @fd6130 I have the same issue.
> I defined settings as you describe, but I do not understand should I create any controller?

You don't have to cause this bundle will handle the login authentication for you. You just have to call the api through axios or ajax.

**Comment by fd6130** [comment]
@ahules Any update on this issue?

**Comment by chalasr** [comment]
Closing due to the lack of feedback.

**Comment by illodev** [comment]
`php bin/console cache:clear`
