### ISSUE TITLE
401 Unauthorized | invalid credentials | loadUserByIdentifier

### ISSUE THREAD

**Issue by mdieudonne** [lexik/LexikJWTAuthenticationBundle#874]
Hi,

After upgrading to Sf 5.3, I get a 401 right after login.

In `vendor/lexik/jwt-authentication-bundle/Security/Guard/JWTTokenAuthenticator.php`

Replacing `return $userProvider->loadUserByUsername($identity);` with `return $userProvider->loadUserByIdentifier($identity);`
solves the problem.

Is there an update about to be published?

**Comment by mynameisbogdan** [comment]
If you're implementing `UserLoaderInterface` using this example doesn't fixes your issue?

```php
public function loadUserByUsername(string $username)
{
   return $this->loadUserByIdentifier($username);
}
```
