### ISSUE TITLE
Extract ttl to new service

### ISSUE THREAD

**Issue by michaelzangerle** [lexik/LexikJWTAuthenticationBundle#888]
Hi there! 

I am currently working on a headless Sylius project and as you probably know they use this bundle for authentication at their new API. Now our customer wants have a remember-me-cookie like behavior for themselves and the end users. Meaning they don't want to be logged out that often but also don't want to force all users to have a very long TTL for their tokens. So I thought I just have two TTLs and depending on the request one of those gets used. 

I was able to accomplish that, but I had to copy `Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\LcobucciJWSProvider` and `Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Cookie\JWTCookieProvider` as the ttl gets injected there via the constructor (+ the class is final and most of it private).

Would it make sense from your point of view, to extract the TTL into a separate class (e.g. a `TtlProvider`) which returns the TTL from the settings by default? If we add an interface and make it a service it would be really easy to replace with a custom logic and I wouldn't have to copy the files mentioned above. 

WDYT?

**Comment by chalasr** [comment]
Hey,

Thanks for this issue.
Because tokens cannot be revoked by design (self-contained), using short-lived tokens is more secure and is considered a best practice.

The best way to implement a rememberme-like feature with JWT is to use refresh tokens.
Relevant package: https://github.com/markitosgv/JWTRefreshTokenBundle.
Please consider having a look at this approach instead.

**Comment by michaelzangerle** [comment]
Hi @chalasr,

thank you for the quick response and the pointer to the other bundle :slightly_smiling_face:  I had a look at it and if I understood it correctly you will get a refresh token to request a new valid token and the big difference here is that this refresh token is stored in the DB and can be revoked / removed right?

I do generally agree that this would be a cleaner approach and especially if we would have machines as clients or very regular users which are guaranteed online in a certain time period. But in our case some users might be online every day, some just once a week and others just once a month etc. So either the refresh token is valid for quite a long time or the users would still have to login next time the visit the shop.
I am not sure the benefit of having this sophisticated refresh token logic (+ the additional complexity) outweights the approach with two ttls one for e.g. 3 days and one for 3 months.

If there is something strange going on with a user account we would need to disable the user with our approach.
With the refresh token approach the token and the refresh token would both be in a cookie (in our case) and if somebody has access to those we would again end up with disabling the user as they would be able to just regenerate new tokens.

Did I miss something?

**Comment by chalasr** [comment]
I get your point about the complexity it adds. 
Something that just came back to my mind: you can hook into the token creation process with an event listener and overwrite the ttl there, so you could increase it based on, say, the current Request' data. See https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/2-data-customization.md#example-over ride-token-expiration-date-calculation-to-be-more-flexible.
Would that be enough for your use case?

**Comment by michaelzangerle** [comment]
Sort of. With this event I can only adjust the TTL of the token but not of the cookie we use for the transport. The cookie TTL will still be the one from the configuration. But the `Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Cookie\JWTCookieProvider` service can be decorated and so I can adjust the cookie TTL and then it matches again and I don't have to copy classes. 

Thanks for your help @chalasr  :pray:
