### ISSUE TITLE
Stoping propagation of `AUTHENTICATION_SUCCESS` before dispatching it.

### ISSUE THREAD

**Issue by pawaclawczyk** [lexik/LexikJWTAuthenticationBundle#89]
Here https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Http/Authentication/AuthenticationSuccessHandler.php#L52 is called `setResponse` method which internally calls `Symfony\Component\HttpKernel\Event\GetResponseEvent::stopPropagation` then the event is dispatched and stopped on first listener it reaches.

Is this expected beahavior?

**Comment by slashfan** [comment]
Hello.

This is indeed not the way it should work and it is not the way it worked at the beginning of the project. 
I'll try to fix it, in the meantime feel free to make a PR.
