### ISSUE TITLE
Authentication request could not be processed due to a system problem

### ISSUE THREAD

**Issue by vincentagi** [lexik/LexikJWTAuthenticationBundle#893]
Hello,
I think I have followed the bundle documentation (version 2.12) but I always get a 401 error with the message "Authentication request could not be processed due to a system problem".
I don't understand why or how this happens.
With the symfony debugging server I found the database query: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? LIMIT 1
We can see here that the user's email is not filled in.
I would like to attach my configuration files and the POST request.
I am very grateful in advance for the help you will give me and I am available to answer your questions.
Thank you

security.yaml
`security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }`

lexik_jwt_authentication.yaml
`lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # token TTL in seconds, defaults to 1 hour
    user_identity_field: email  # key under which the user identity will be stored in the token payload
    clock_skew: 0

    # token encoding/decoding settings
    encoder:
        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
        service:            lexik_jwt_authentication.encoder.lcobucci

        # encryption algorithm used by the encoder service
        signature_algorithm: RS256

    # token extraction settings
    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization

        # check token in a cookie
        cookie:
            enabled: false
            name:    BEARER
            
        # check token in query string parameter
        query_parameter:
            enabled: false
            name:    bearer`
routes.yaml
`api_login_check:
    path: /api/login_check`

User.php
`namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}`
request was made in POST on http://localhost:8000/api/login_check
`{
	"email": "agi.v@hotmail.fr",
	"password": "azerty"
}`

response 
`{
  "code": 401,
  "message": "Authentication request could not be processed due to a system problem."
}`

traces web server
`ul 14 09:37:35 |WARN   | SERVER POST (401) /api/login_check host="127.0.0.1:8004" ip="127.0.0.1" scheme="https"
[PHP        ] [Wed Jul 14 09:37:35 2021] 127.0.0.1:59098 Accepted
[PHP        ] [Wed Jul 14 09:37:35 2021] [info] Matched route "api_login_check".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4 FROM user t0 WHERE t0.email = ? LIMIT 1
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [info] Authentication request failed.
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Nelmio\CorsBundle\EventListener\CorsListener::onKernelRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Bundle\FrameworkBundle\EventListener\ResolveControllerNameSubscriber::resolveControllerName".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::configureLogoutUrlGenerator".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::onKernelRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::onKernelRequest" stopped propagation of the event "kernel.request".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.response" to listener "Nelmio\CorsBundle\EventListener\CorsListener::onKernelResponse".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.response" to listener "Nelmio\CorsBundle\EventListener\CacheableResponseVaryListener::onResponse".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.response" to listener "Symfony\Component\Security\Http\RememberMe\ResponseListener::onKernelResponse".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\DisallowRobotsIndexingListener::onResponse".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelResponse".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\StreamedResponseListener::onKernelResponse".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelFinishRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onFinishRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.finish_request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelFinishRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] [debug] Notified event "kernel.finish_request" to listener "Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener::onKernelFinishRequest".
[PHP        ] 
[PHP        ] [Wed Jul 14 09:37:35 2021] 127.0.0.1:59098 [401]: POST /api/login_check
[PHP        ] [Wed Jul 14 09:37:35 2021] 127.0.0.1:59098 Closing
`

I use Symfony 4.4, PHP 7.4, MySQL 5.6,
Thanks for your help
Vincent

**Comment by chalasr** [comment]
Hey, thanks for reporting.
I'll try to reproduce the issue by the end of the week

**Comment by filoucrackeur** [comment]
i confirm exactly same problem 
symfony 5.3.3 
PHP 7.4
<img width="921" alt="Capture d’écran 2021-07-23 à 09 52 08" src="https://user-images.githubusercontent.com/2182548/126752584-5ff5afcc-4f4c-4258-8010-282ece03865b.png">

**Comment by filoucrackeur** [comment]
i tried to replace IS_AUTHENTICATED_ANONYMOUSLY by PUBLIC_ACCESS in symfony 5.3.3 but same problem

**Comment by vincentagi** [comment]
Hello,
After many days I finally deleted the vendor folder, pugged the cache, did a compose install and a php bin/console d:s:u --force
I don't know exactly why but now it works for me

**Comment by filoucrackeur** [comment]
------- > lol for me always the same after did your process

**Comment by fd6130** [comment]
> ------- > lol for me always the same after did your process

Lol is it because of incorrect database config or whatever related with database? I have no problem here and i'm already using it for my fresh project.

**Comment by fd6130** [comment]
> i confirm exactly same problem
> symfony 5.3.3
> PHP 7.4
> <img alt="Capture d’écran 2021-07-23 à 09 52 08" width="921" src="https://user-images.githubusercontent.com/2182548/126752584-5ff5afcc-4f4c-4258-8010-282ece03865b.png">

Mine have no problem at all. Is the issue still persist?

**Comment by chalasr** [comment]
Closing due to the lack of feedback. Feel free to comment if it's still an issue so we can consider to reopen.

**Comment by AzamatProgrammist** [comment]
![Screenshot from 2024-12-03 16-32-52](https://github.com/user-attachments/assets/291541b4-662c-48d8-9eaa-ebabfee359d2)
Hello, I also faced this problem.
{
    "code": 401,
    "message": "Authentication request could not be processed due to a system problem."
}
