### ISSUE TITLE
Missing Import in/since v2.12.5

### ISSUE THREAD

**Issue by haruka** [lexik/LexikJWTAuthenticationBundle#898]
In [commit 9f276015](https://github.com/lexik/LexikJWTAuthenticationBundle/commit/9f276015dccbcfa1731045bf0bb2a1ccd75029b9)  a check was added if BaseNode::getDeprecation() exists.

Plottwist: BaseNode was not included via "use". So this check is always false and the old deprecation params are always used.

**Comment by chalasr** [comment]
Thanks for the report!
Fixed in https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v2.12.6.
