### ISSUE TITLE
Add `access_control` example to the configuration reference

### ISSUE THREAD

**Issue by chalasr** [lexik/LexikJWTAuthenticationBundle#899]
Reflecting the `anonymous: ~` behavior from the old security system.

**Comment by fd6130** [comment]
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.md#configuration

Are the issue solved? I think the docs is good except `IS_AUTHENTICATED_ANONYMOUSLY`.  Should we use `PUBLIC_ACCESS` in new system or both are correct actually?

**Comment by chalasr** [comment]
We should use PUBLIC_ACCESS here

**Comment by fd6130** [comment]
> We should use PUBLIC_ACCESS here

Alright, i can make a PR for it.

**Comment by fd6130** [comment]
Since we are promoting new authentication system, perhaps this section need to update as well (like removing the guard authentication usage) ?

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/1-configuration-reference.md#security-configuration

**Comment by chalasr** [comment]
> Alright, i can make a PR for it.

That would be great!

> Since we are promoting new authentication system, perhaps this section need to update as well (like removing the guard authentication usage) ?

I think we should keep the guard reference until we bump Symfony to 5.3+. Makes sense?

**Comment by fd6130** [comment]
> > Since we are promoting new authentication system, perhaps this section need to update as well (like removing the guard authentication usage) ?
> 
> I think we should keep the guard reference until we bump Symfony to 5.3+. Makes sense?

Yeah it does make sense here. But i realize that i did make a mistake here, i replace the "extending jwt guard authenticator" with "extending jwt authenticator" doc in my last PR. So i will restore the previous one and make it become two section in a file on my next PR.

And last thing, the bundle require Symfony 4.4+ but the doc still having Symfony 3 usage at https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.md#prerequisites

Should we remove that one as well?

**Comment by chalasr** [comment]
Oh yes, indeed!

**Comment by fd6130** [comment]
> Oh yes, indeed!

Done making a PR. Waiting for review.
