### ISSUE TITLE
Symfony 5.3 compatibility

### ISSUE THREAD

**Issue by crashbtz** [lexik/LexikJWTAuthenticationBundle#900]
Hello,

I'm trying to update my symfony project to 5.3 but LexikJWTAuthenticationBundle is only compatible with symfony/security-bundle ^5.1

```
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.2.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - lexik/jwt-authentication-bundle v2.12.6 requires symfony/security-bundle ^4.4|^5.1 -> satisfiable by symfony/security-bundle[v5.3.0, v5.3.2, v5.3.3, v5.3.4].
```
Dis I miss something or is it a work in progress?

Thanks

**Comment by chalasr** [comment]
This is the problem:

> Restricting packages listed in "symfony/symfony" to "5.2.*"

In order to upgrade Symfony to a new minor version, you need to change the following part of your composer.json:
```json
"extra": {
    "symfony": {
        "allow-contrib": false,
        "require": "5.2.*"
    }
}
```

to 
```json
"extra": {
    "symfony": {
        "allow-contrib": false,
        "require": "5.3.*"
    }
}
```

**Comment by crashbtz** [comment]
Indeed, it works now.

Thank you very much
