### ISSUE TITLE
JWTManager invalid a token after dispatch the event created with the payload

### ISSUE THREAD

**Issue by Rafael-Martin** [lexik/LexikJWTAuthenticationBundle#907]
Hi

I have added some logs into JWTManager to verify why allways i have a  401 "Invalid JWT Token" 
The method "decode" retun false invalidating the token.
(the token and payload received have correct information to be valided) 
That occurs just after the "dispatcher" dispatch the event created with the payload:

public function decode(TokenInterface $token)
    {
        error_log("\n >  decode TokenInterface <". get_class($token).">" );
       
        if (!($payload = $this->jwtEncoder->decode($token->getCredentials()))) {
            error_log("\n >  RETURN 1 FALSE" );
            return false;
        }
        
    //    dd($payload);
        
        $event = new JWTDecodedEvent($payload);
        
        error_log("\n >  event->isValid: A " ."<".$event->isValid().">" );
        
        $this->dispatcher->dispatch($event, Events::JWT_DECODED);
        
        error_log("\n >  event->isValid: B " ."<".$event->isValid().">" );
        
        if (!$event->isValid()) {
            error_log("\n >  RETURN 2 FALSE " );
            return false;
        }

        error_log("\n >  RETURN EVT PAYLOAD  ". $event->getPayload() );
        
        return $event->getPayload();
    }

and here is the output:

 >  decode TokenInterface <Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserToken>PHP message: 
 >  event->isValid: A <1>PHP message: 
 >  event->isValid: B <>PHP message: 
 >  RETURN 2 FALSE PHP message: 
 >1 InvalidTokenException A

**Comment by Rafael-Martin** [comment]
ok , i found .. 
JWTCreatedListener nor added the IP to the payload
JWTDecodedListener marked As Invalid if no IP was present

**Comment by chalasr** [comment]
Congratz for the successful debug :)
