### ISSUE TITLE
Deprecated error at authentication updating symfony 5.2.5 to 5.3.6 

### ISSUE THREAD

**Issue by gopikrish19** [lexik/LexikJWTAuthenticationBundle#908]
Hi ,
     I have updated my symfony project from 5.2.5 to 5.3.6 and I used LexikJWTAuthenticationBundle (* v2.12.6) with api-platform (* v2.6.3) after updating symfony version I received the below warning messages 

"[info] User Deprecated: The "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" class implements "Symfony\Component\Security\Guard\AuthenticatorInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead."

"[info] User Deprecated: The "Gesdinet\JWTRefreshTokenBundle\Security\Authenticator\RefreshTokenAuthenticator" class extends "Symfony\Component\Security\Guard\AbstractGuardAuthenticator" that is deprecated since Symfony 5.3, use the new authenticator system instead"

**Comment by fd6130** [comment]
I think that's fine? Start from Symfony 5, you may use the new authenticator as mentioned in https://symfony.com/doc/current/security/authenticator_manager.html

Those deprecated message occurs because you are using latest version of this bundle which is ready to use symfony new authenticator.

**Comment by chalasr** [comment]
Indeed, it's expected. Check https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/UPGRADE-2.12.md for instructions about how to get rid of the notices.

**Comment by chalasr** [comment]
Thanks again for your help @fd6130

**Comment by gopikrish19** [comment]
Thanks guys
