### ISSUE TITLE
API and Cookie Authentication in the same Application

### ISSUE THREAD

**Issue by naitsirch** [lexik/LexikJWTAuthenticationBundle#909]
If one want to use the bundle in an application where user can authenticate per API (responding with a JSON body containing the token) and per form login (sending token as Cookie) the `Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler` cannot be used.

The reason is that the token is removed from the JSON response if there are any cookie providers configured (see [here](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/06bd43f8aed787186e598aeb89be4c0dc2727650/Security/Http/Authentication/AuthenticationSuccessHandler.php#L66)).

It would be nice if this could be changed.

**Comment by chalasr** [comment]
I think adding a boolean parameter to the `AuthenticationSuccessHandler` constructor would do the trick, so that one is able to modify/decorate/extend/replace the service definition and use it.
Would you be interested to work on this?

**Comment by naitsirch** [comment]
But the class is marked as `@final`.

**Comment by naitsirch** [comment]
@chalasr I have created a PR ;-)
