### ISSUE TITLE
Refresh Token over LexikJWTAuthenticationBundle (new Bundle)

### ISSUE THREAD

**Issue by markitosgv** [lexik/LexikJWTAuthenticationBundle#91]
Hi everyone!

Im developing a bundle that Implements a Refresh Token system over Json Web Tokens in Symfony. This bundle depends of LexikJWTAuthenticationBundle.

This is the link:

https://github.com/gesdinet/JWTRefreshTokenBundle

Do you think we can make a doc chapter for this?

**Comment by mRoca** [comment]
Hello markitosgv, I'm working on the same subject, and I think your bundle has a bad dependency : imo the FosUserBundle should'nt be required.

I'm currently using the `Doctrine\Common\Cache\CacheProvider` interface as tokens storage, but the final solution must support custom storage layers.

**Comment by markitosgv** [comment]
Hi @mRoca,

Maybe is a good next step to work for avoid dependency from FOSUserBundle. Are you working on a open source git repo?

PS. PR on JWTRefreshTokenBundle are more than welcome! :D

**Comment by mRoca** [comment]
I will push my code soon. If I can add it to your repo, I will.

**Comment by markitosgv** [comment]
@mRoca perfect we can see it then

**Comment by mRoca** [comment]
Hi, I've created an example project implementing the refresh token. It's an example, and should be refactored to create a true auth listener : https://github.com/mRoca/sf2-jwt-refresh-token .

**Comment by markitosgv** [comment]
Now https://github.com/gesdinet/JWTRefreshTokenBundle no depends of FOSUserBundle

**Comment by slashfan** [comment]
Hi, about the initial subject, please feel free to make a PR for a link and a short use case description in the documentation. The best place would be in the https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#notes section, right after the token expiration note.

**Comment by GreGosPhaTos** [comment]
Hi guys! Question : is there a bundle / feature for invalidate the jwt ?

**Comment by markitosgv** [comment]
Answer to @slashfan:

Nice! I'm going to prepare a little text to add to documentation notes.

To @GreGosPhaTos:

A JWT token can't be revoked cause itself is autovalidating until date expires. The only way you can invalidate (all) tokens is resetting your private key.

You can set a low ttl for JWT but then you need to ask to your client his credentials many times. 

This is the main cause we release a [JWTRefreshToken bundle](https://github.com/gesdinet/JWTRefreshTokenBundle), to refresh JWT tokens by a refresh_token instead of ask every time credentials to a user.

**Comment by GreGosPhaTos** [comment]
Ok thanks for your answer @markitosgv , I know that's the invalidation is not a part of the jwt spec, but I am wondering if there's a bundle that can provide a way to blacklist (or whitelist) the tokens for example. 

I already implemented the refresh on my API, and I didn't read all the jwt specs but nothing in the spec telling that we cannot implemented a way to blacklist or whitelist the token right ?

Thanks for your answers guys.

**Comment by markitosgv** [comment]
You can implement some whitelist or blacklist to check JWT, but then you need to search on every query if JWT is valid, you lose the advantage to no depends on db.

With refresh token you only hit a DB when you need to refresh a JWT.

But maybe do a blacklist system with redis is a good way to revoke tokens.

**Comment by slashfan** [comment]
@GreGosPhaTos see https://github.com/lexik/LexikJWTAuthenticationBundle/issues/58#issuecomment-89641970

**Comment by GreGosPhaTos** [comment]
Thanks @markitosgv and @slashfan I ll do that, maybe I could create a bundle for that ... I ll let you know about this .
