### ISSUE TITLE
code (Lexik) vs. status (Symfony)

### ISSUE THREAD

**Issue by deezaster** [lexik/LexikJWTAuthenticationBundle#910]
The return code name in the response is '**code**' (JWTAuthenticationFailureResponse) and Symfony uses the name '**status**' (JsonResponse). Is it possible to use 'status' as well?

Examples

![code](https://user-images.githubusercontent.com/1539838/130283760-aa6c3a9e-781e-420a-9f1b-ba64b6dd2300.png)
![status](https://user-images.githubusercontent.com/1539838/130283798-425726d1-3c56-4a07-a662-44ba056947a7.png)

**Comment by fd6130** [comment]
Not sure about this but how about you try create your own exception class and set the response?

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/2-data-customization.md#eventsjwt_invalid---customizing-the-invalid-token-response

**Comment by deezaster** [comment]
I customize my exception class
