### ISSUE TITLE
Authorize without User entity?

### ISSUE THREAD

**Issue by arosiek** [lexik/LexikJWTAuthenticationBundle#911]
Hi!
I have 2 microservices:
- account (with User entity) + Api platform
- template (without User entity) + Api platform

my case is:
1. authenticate via account, get jwt token - this part works great
2. use jwt token to access some resources in template microservice. perhaps user ROLE would be in use.

is it possible to get resource without User entity and without authenticate with DB (only expire date should be checked here)?

**Comment by chalasr** [comment]
Hey,

Yes it is: Resources/doc/8-jwt-user-provider.md
