### ISSUE TITLE
JWTUserToken implements GuardTokenInterface that is deprecated since Symfony 5.3

### ISSUE THREAD

**Issue by lobodol** [lexik/LexikJWTAuthenticationBundle#913]
Hi there,

I'm using this bundle with Symfony 5.3, and I got some deprecation warnings when executing unit tests:

```
The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken" class implements "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
```

Do you plan to update `Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken` soon?

Regards,

**Comment by lunaticusz** [comment]
Hi, I have the same problem
```
The "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" class implements "Symfony\Component\Security\Guard\AuthenticatorInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserTokenInterface" interface extends "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserToken" class extends "Symfony\Component\Security\Guard\Token\PreAuthenticationGuardToken" that is deprecated since Symfony 5.3, use the new authenticator system instead.
The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken" class implements "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
```

**Comment by fd6130** [comment]
> Hi, I have the same problem
> 
> ```
> The "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" class implements "Symfony\Component\Security\Guard\AuthenticatorInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserTokenInterface" interface extends "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserToken" class extends "Symfony\Component\Security\Guard\Token\PreAuthenticationGuardToken" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken" class implements "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> ```

See #908

**Comment by lobodol** [comment]
> > Hi, I have the same problem
> > ```
> > The "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" class implements "Symfony\Component\Security\Guard\AuthenticatorInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> > The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserTokenInterface" interface extends "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> > The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserToken" class extends "Symfony\Component\Security\Guard\Token\PreAuthenticationGuardToken" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> > The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken" class implements "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> > ```
> 
> See #908

Oh, great! Thanks

**Comment by lunaticusz** [comment]
> > Hi, I have the same problem
> > ```
> > The "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" class implements "Symfony\Component\Security\Guard\AuthenticatorInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> > The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserTokenInterface" interface extends "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> > The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\PreAuthenticationJWTUserToken" class extends "Symfony\Component\Security\Guard\Token\PreAuthenticationGuardToken" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> > The "Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken" class implements "Symfony\Component\Security\Guard\Token\GuardTokenInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.
> > ```
> 
> See #908

Thanks!
