### ISSUE TITLE
How to get access to JWTUser with db-less user provider

### ISSUE THREAD

**Issue by arosiek** [lexik/LexikJWTAuthenticationBundle#919]
Hi!
I would like to get JWTUser from DataPersister (using api-platform).
I'm already using https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/8-jwt-user-provider.md to authenticate request. But I would like to extract/get some data from the token.

I am storing user roles and some user data which I would like to use in my microservice but I don't want to create user table in it. 

OK. Let me say I have some entity (Post) with user_id column/field. 
I don't want to have user table in my db. 
I would like to use PostDataPersister to set user_id from JWToken. How to get user_id from the request header token in that case? 

Am I doing something wrong/stupid? I didn't get an answer anywhere else :/

Kind regards,
amr

**Comment by fd6130** [comment]
Not sure about this but hope inside this authenticator class might help you some.

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Security/Authenticator/JWTAuthenticator.php


The Token Extractor and JWT Manager class.

**Comment by arosiek** [comment]
NVM. it missed the fact that JWTUser obj is set to Security service from symfony. It is possible to get user by injecting Symfony\Component\Security\Core\Security $security, and then $this->security->getUser();
