### ISSUE TITLE
Remove return type declaration from `JWTAuthenticator::start()`

### ISSUE THREAD

**Issue by raphahardt** [lexik/LexikJWTAuthenticationBundle#927]
The actual method declaration forces us to return a `JWTAuthenticationFailureResponse` instance.
On one hand it is convenient, but in terms of extend-ability of our own authenticators (or via event listeners to the `JWTNotFoundEvent` event) we are limited to only send responses in JSON format.

Use case: I may intercept or extend the entrypoint to return a RedirectResponse to redirect the user to another path instead.

Thanks in advance

**Comment by raphahardt** [comment]
Actual code:
```php
public function start(Request $request, AuthenticationException $authException = null): JWTAuthenticationFailureResponse
{
    $exception = new MissingTokenException('JWT Token not found', 0, $authException);
    $event = new JWTNotFoundEvent($exception, new JWTAuthenticationFailureResponse($exception->getMessageKey()));

    $this->eventDispatcher->dispatch($event, Events::JWT_NOT_FOUND);

    return $event->getResponse();
}
```

Proposal:
```php
public function start(Request $request, AuthenticationException $authException = null)
{
    $exception = new MissingTokenException('JWT Token not found', 0, $authException);
    $event = new JWTNotFoundEvent($exception, new JWTAuthenticationFailureResponse($exception->getMessageKey()));

    $this->eventDispatcher->dispatch($event, Events::JWT_NOT_FOUND);

    return $event->getResponse();
}
```

This matches the declaration from the original `Symfony\Component\Security\Http\EntryPoint\AuthenticationEntryPointInterface::start()` method, and gives us room to extend the method to return any type of response instead

**Comment by fd6130** [comment]
> The actual method declaration forces us to return a JWTAuthenticationFailureResponse instance

See #905 

> Use case: I may intercept or extend the entrypoint to return a RedirectResponse to redirect the user to another path instead.

How about write a custom authenticator for your use case? I think you can override all of the methods? https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/6-extending-jwt-authenticator.md

**Comment by raphahardt** [comment]
> See #905

Oh, I'm so sorry! I thought I was up to date but I was using v2.12.6, I should just upgrade to 2.13. Thanks!

> How about write a custom authenticator for your use case? I think you can override all of the methods? https://github.com/lexik
/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/6-extending-jwt-authenticator.md

Thats what I did for the meanwhile: I but a custom authenticator with the entrypoint redirecting, with "supports" method always returning false to bypass it and execute the JWTAuthenticator. But upgrading now I can return directly. Thanks!

**Comment by fd6130** [comment]
> > See #905
> 
> Oh, I'm so sorry! I thought I was up to date but I was using v2.12.6, I should just upgrade to 2.13. Thanks!
> 
> > How about write a custom authenticator for your use case? I think you can override all of the methods? https://github.com/lexik
> > /LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/6-extending-jwt-authenticator.md
> 
> Thats what I did for the meanwhile: I but a custom authenticator with the entrypoint redirecting, with "supports" method always returning false to bypass it and execute the JWTAuthenticator. But upgrading now I can return directly. Thanks!

It is because version v2.12.6 doesn't support custom authenticator until 2.13. 

Anyways, Glad that you have solve the issue.
