### ISSUE TITLE
syntax error, unexpected 'DataSet' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) (500 Internal Server Error)

### ISSUE THREAD

**Issue by andrey-grach** [lexik/LexikJWTAuthenticationBundle#929]
the problem appears every time with `IS_AUTHENTICATED_FULLY`

firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: lazy
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/admin, roles: ROLE_ADMIN }
    

lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

**Comment by andrey-grach** [comment]
okay with version 2.12 works fine

**Comment by fd6130** [comment]
> okay with version 2.12 works fine

Go with latest version is 2.13 if you are using Symfony 5.3 .

**Comment by andrey-grach** [comment]
> > okay with version 2.12 works fine
> 
> Go with latest version is 2.13 if you are using Symfony 5.3 .

I'm using 5.1.

**Comment by fd6130** [comment]
> > > okay with version 2.12 works fine
> > 
> > 
> > Go with latest version is 2.13 if you are using Symfony 5.3 .
> 
> I'm using 5.1.

Consider upgrade soon.

**Comment by Makapashev** [comment]
This issue comes up because of package `lcobucci/jwt` it supports version of php 7.4 and higher.
Which version of jwt_auth can i download to handle this problem in php 7.3?

**Comment by fd6130** [comment]
Just use version  <= 2.12 and i think it will be fine.

> This issue comes up because of package `lcobucci/jwt` it supports version of php 7.4 and higher. Which version of jwt_auth can i download to handle this problem in php 7.3?

**Comment by Makapashev** [comment]
@fd6130 same problem on version 2.12, I’ll try to install 2.11 later. Best decision would be to rollback version of lcobucci/jwt that supports php 7.3 and lower

**Comment by fd6130** [comment]
> @fd6130 same problem on version 2.12, I’ll try to install 2.11 later. Best decision would be to rollback version of lcobucci/jwt that supports php 7.3 and lower

How about try manual install `lcobucci/jwt` manually? Cause in the composer.json it is support ^3.4|^4.0. But i think it will affect other classes that required php7.4 or higher feature, sticking to the version which is before support Symfony 5.3 might be a better choice for you.

**Comment by Makapashev** [comment]
@fd6130 Last version that supports PHP 7.3 and lower is 2.11.3.
Install package using command below
`composer require "lexik/jwt-authentication-bundle: 2.11.*"`
