### ISSUE TITLE
Recommended way to integrate with Symfony Messenger

### ISSUE THREAD

**Issue by mvriel** [lexik/LexikJWTAuthenticationBundle#933]
In our product we want to generate a JWT and pass it as a stamp to Symfony Messenger to use the same authorization in the Messenger workers as used in the dispatcher. As far as I read the code, it is tightly coupled with HTTP / Symfony Security but Messenger cannot use this (as there is no Request).

What is the recommended way to generate a Security Token from a JWT string, and to create a JWT string from a Security Token / User?

**Comment by fd6130** [comment]
How about give it a try using JWTManager class, just pass your jwt string to `parse()` method.

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/3f30e12920d38fb00bd2720677cbfc2464911caa/Services/JWTManager.php#L123

**Comment by fd6130** [comment]
> What is the recommended way to generate a Security Token from a JWT string, and to create a JWT string from a Security Token / User?

I don't quite get it. You want to generate a Symfony Security Token in Messenger? Or you want to protect your messenger from unauthenticated users?

**Comment by chalasr** [comment]
You can use the `JWTTokenManagerInterface` service:
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/3f30e12920d38fb00bd2720677cbfc2464911caa/Services/JWTTokenManagerInterface.php#L21-L30
