### ISSUE TITLE
In ArrayNode.php line 314: Unrecognized option "jwt"

### ISSUE THREAD

**Issue by MindDesign** [lexik/LexikJWTAuthenticationBundle#934]
I just updated my Symfony application to Symfony 5.3 after installing Lexik JWT.

Process went as follows:

`php composer.phar require "lexik/jwt-authentication-bundle"`

`php bin/console lexik:jwt:generate-keypair`

`php composer.phar update "symfony/*" --with-all-dependencies`

Then following the setup/configuration process described here: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.md#getting-started

My composer.json looks like this:

```
{
    "type": "project",
    "license": "none",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=7.4",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "composer/package-versions-deprecated": "1.11.99.1",
        "doctrine/annotations": "^1.0",
        "doctrine/doctrine-bundle": "^2.3",
        "doctrine/doctrine-migrations-bundle": "^3.0",
        "doctrine/orm": "^2.8",
        "lexik/jwt-authentication-bundle": "2.x-dev",
        "nelmio/cors-bundle": "^2.1",
        "phpdocumentor/reflection-docblock": "^5.2",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "^5.3",
        "symfony/console": "^5.3",
        "symfony/dotenv": "^5.3",
        "symfony/expression-language": "^5.3",
        "symfony/flex": "^1.3.1",
        "symfony/form": "^5.3",
        "symfony/framework-bundle": "^5.3",
        "symfony/http-client": "^5.3",
        "symfony/intl": "^5.3",
        "symfony/mailer": "^5.3",
        "symfony/mime": "^5.3",
        "symfony/monolog-bundle": "^3.1",
        "symfony/notifier": "^5.3",
        "symfony/process": "^5.3",
        "symfony/property-access": "^5.3",
        "symfony/property-info": "^5.3",
        "symfony/proxy-manager-bridge": "^5.3",
        "symfony/security-bundle": "^5.3",
        "symfony/sendgrid-mailer": "^5.3",
        "symfony/serializer": "^5.3",
        "symfony/string": "^5.3",
        "symfony/translation": "^5.3",
        "symfony/twig-bundle": "^5.3",
        "symfony/validator": "^5.3",
        "symfony/web-link": "^5.3",
        "symfony/webpack-encore-bundle": "^1.11",
        "symfony/yaml": "^5.3",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
    "require-dev": {
        "symfony/browser-kit": "^5.3",
        "symfony/css-selector": "^5.3",
        "symfony/debug-bundle": "^5.3",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^5.3",
        "symfony/stopwatch": "^5.3",
        "symfony/var-dumper": "^5.3",
        "symfony/web-profiler-bundle": "^5.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "^5.3"
        }
    }
}
```

And my security.yaml is this:

```
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    enable_authenticator_manager: true

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/api/retailer, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['GET'] }
        #- { path: ^/api/webhook, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['GET'] }
        #- { path: ^/api/customer, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['GET'] }
        - { path: ^/webhook, role: IS_AUTHENTICATED_ANONYMOUSLY, methods: ['POST'] }
        - { path: ^/, role: ROLE_USER }
```

As mentioned in the title, when clearing cache after update and installation, I get an error telling me that `In ArrayNode.php line 314: Unrecognized option "jwt"`

Can anyone point me in any directions?

**Comment by fd6130** [comment]
Seems like  you install the incorrect version  of this bundle.

I saw this in your composer.json:

`"lexik/jwt-authentication-bundle": "2.x-dev",`

Change to `"lexik/jwt-authentication-bundle": "^2.13"`  and `composer update` it.

**Comment by MindDesign** [comment]
That pointed me directly to the solution. In fact it was the solution. Thank you for your help.

**Comment by Anand-q21** [comment]
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
   "require": {
        "php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "api-platform/doctrine-orm": "^4.2",
        "api-platform/symfony": "^4.2",
        "doctrine/dbal": "^3",
        "doctrine/doctrine-bundle": "^2.18",
        "doctrine/doctrine-migrations-bundle": "^3.7",
        "doctrine/orm": "^3.5",
        "lexik/jwt-authentication-bundle": "^2.18",
        "nelmio/cors-bundle": "^2.6",
        "phpdocumentor/reflection-docblock": "^5.6",
        "phpstan/phpdoc-parser": "^2.3",
        "symfony/asset": "^6.4",
        "symfony/asset-mapper": "^6.4",
        "symfony/console": "^6.4",
        "symfony/doctrine-messenger": "^6.4",
        "symfony/dotenv": "^6.4",
        "symfony/expression-language": "^6.4",
        "symfony/flex": "^2",
        "symfony/form": "^6.4",
        "symfony/framework-bundle": "^6.4",
        "symfony/http-client": "^6.4",
        "symfony/intl": "^6.4",
        "symfony/mailer": "^6.4",
        "symfony/mime": "^6.4",
        "symfony/monolog-bundle": "^3.0",
        "symfony/notifier": "^6.4",
        "symfony/process": "^6.4",
        "symfony/property-access": "^6.4",
        "symfony/property-info": "^6.4",
        "symfony/runtime": "^6.4",
        "symfony/security-bundle": "^6.4",
        "symfony/serializer": "^6.4",
        "symfony/stimulus-bundle": "^2.31",
        "symfony/string": "^6.4",
        "symfony/translation": "^6.4",
        "symfony/twig-bundle": "^6.4",
        "symfony/ux-turbo": "^2.31",
        "symfony/validator": "^6.4",
        "symfony/web-link": "^6.4",
        "symfony/yaml": "^6.4",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^11.5",
        "symfony/browser-kit": "^6.4",
        "symfony/css-selector": "^6.4",
        "symfony/debug-bundle": "^6.4",
        "symfony/maker-bundle": "^1.0",
        "symfony/stopwatch": "^6.4",
        "symfony/web-profiler-bundle": "^6.4"
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd",
            "importmap:install": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
   "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "^6.4"
        }
    }
}
This is my composer.json file and I am facing this  php bin/console lexik:jwt:generate-keypair

In ArrayNode.php line 327:

  Unrecognized option "enabled" under "lexik_jwt_authentication.api_platform". Available options are "check_path", "password_path", "user
  name_path".


2025-11-16T09:27:36+01:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
2025-11-16T09:27:36+01:00 [info] User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::registerCommands()" might add "void" as a native return type declaration in the future. Do the same in child class "Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle" now to avoid errors or add an explicit @return annotation to suppress this message. error how do I fix it.
