### ISSUE TITLE
user_identity_field can't be integer with Badge System

### ISSUE THREAD

**Issue by ComteZeroVD** [lexik/LexikJWTAuthenticationBundle#935]
Hi !

I was following the guide for database-less user provider and needed to define an IRI.
I wanted to define the attribute "id" (which is an integer) from my class User as the user_identity_field.
Looks like it leads to an error in 
Security/Authenticator/JWTAuthenticator.php line 113

```
$passport = new SelfValidatingPassport(
            new UserBadge($payload[$idClaim],
            function ($userIdentifier) use($payload) {
                return $this->loadUser($payload, $userIdentifier);
            })
        );
```

and more particulary this line

```
new UserBadge($payload[$idClaim],
```

because the constructor of UserBadge require a string.

**Comment by fd6130** [comment]
For temporarily solution, you can use custom authenticator and cast your id to string in UserBadge.

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/6-extending-jwt-authenticator.md

**Comment by NotionCommotion** [comment]
Hi,  Wish I read your post before figuring out the same on trial and error.  It doesn't seem to be really a JWTAuthenticatorBundle issue but a Symfony issue.  Thanks!

https://github.com/lexik/LexikJWTAuthenticationBundle/issues/376#issuecomment-965063709

**Comment by fd6130** [comment]
Related with #976 .
