### ISSUE TITLE
Security: getting other logged in users data

### ISSUE THREAD

**Issue by thgross** [lexik/LexikJWTAuthenticationBundle#936]
since updating to the newest version (and to symfony 5.3.9), whenever another user is logging in, i immediately get this other users userdata (with my own unique token):

`$this->getUser();`

How can that be and how can I avoid this? This seems like a major security hole. Is there some configuration that could be wrong?

**Comment by thgross** [comment]
this only happens in prod-environment, not in dev!

**Comment by fd6130** [comment]
I'm not quite understand this issue. Is that mean `$this->getUser()` will obtain other user(s) data instead of your own logged in one?

**Comment by thgross** [comment]
Yes that's the case. I assumed it was a problem with server side token handling, but finally found the problem in caching, which has nothing to do with the Authentication Bundle.
I couldn't just delete the issue unfortunately, so I just closed it.
Sorry for that!
