### ISSUE TITLE
Issue with Symfony 5.3.x

### ISSUE THREAD

**Issue by tarlepp** [lexik/LexikJWTAuthenticationBundle#941]
Looks like new `2.14.0` release is not supporting Symfony `5.3.x` anymore - but it requires Symfony `5.4.x` and Symfony `5.4.x` is not yet released...

https://github.com/lexik/LexikJWTAuthenticationBundle/compare/v2.13.0...v2.14.0#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R44-R53

**Comment by chalasr** [comment]
Thanks. I'm on it.

**Comment by chalasr** [comment]
Fixed in #942 and released in [v2.14.1](https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v2.14.1)
