### ISSUE TITLE
Compatibility with symfony 5.3/5.4

### ISSUE THREAD

**Issue by sargitcom** [lexik/LexikJWTAuthenticationBundle#943]
Looks like auth guards were changed in symfony 5.3/5.4. Method getGuardAuthenticator does not exists anymore, so package fails. Could you fix it?

[2021-11-02T13:21:16.620368+01:00] php.CRITICAL: Uncaught Error: Call to undefined method Symfony\Component\Security\Guard\Authenticator\GuardBridgeAuthenticator::getGuardAuthenticator() {"exception":"[object] (Error(code: 0): Call to undefined method Symfony\\Component\\Security\\Guard\\Authenticator\\GuardBridgeAuthenticator::getGuardAuthenticator() at /var/www/html/przypomnijmi/backend/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticator.php:45)"} []
[2021-11-02T13:21:16.649272+01:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "getGuardAuthenticator" of class "Symfony\Component\Security\Guard\Authenticator\GuardBridgeAuthenticator"." at /var/www/html/przypomnijmi/backend/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticator.php line 45 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"getGuardAuthenticator\" of class \"Symfony\\Component\\Security\\Guard\\Authenticator\\GuardBridgeAuthenticator\". at /var/www/html/przypomnijmi/backend/vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticator.php:45)"} []

**Comment by chalasr** [comment]
Hey, your error seems unrelated to this bundle. Can you paste the output of `composer show`?

**Comment by sargitcom** [comment]
brick/math                           0.9.3             Arbitrary-precision arithmetic library
composer/package-versions-deprecated 1.11.99.4         Composer plugin that provides efficient querying for installed package versions (no runtime IO)
doctrine/annotations                 1.13.2            Docblock Annotations Parser
doctrine/cache                       2.1.1             PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongod...
doctrine/collections                 1.6.8             PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                      3.2.0             PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better ...
doctrine/dbal                        3.1.3             Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/deprecations                v0.5.3            A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3 logging with options to disable all deprecations or selectively for ...
doctrine/doctrine-bundle             2.4.3             Symfony DoctrineBundle
doctrine/doctrine-migrations-bundle  3.2.0             Symfony DoctrineMigrationsBundle
doctrine/event-manager               1.1.1             The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.
doctrine/inflector                   2.0.4             PHP Doctrine Inflector is a small library that can perform string manipulations with regard to upper/lowercase and singular/plural for...
doctrine/instantiator                1.4.0             A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                       1.2.1             PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                  3.3.0             PHP Doctrine Migrations project offer additional functionality on top of the database abstraction layer (DBAL) for versioning your dat...
doctrine/orm                         2.10.2            Object-Relational-Mapper for PHP
doctrine/persistence                 2.2.3             The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/sql-formatter               1.1.1             a PHP SQL highlighting library
egulias/email-validator              3.1.2             A library for validating emails against several RFCs
friendsofphp/proxy-manager-lts       v1.0.5            Adding support for a wider range of PHP versions to ocramius/proxy-manager
laminas/laminas-code                 4.4.3             Extensions to the PHP Reflection API, static code scanning, and code generation
lcobucci/clock                       2.1.0             Yet another clock abstraction
lcobucci/jwt                         4.1.5             A simple library to work with JSON Web Token and JSON Web Signature
lexik/jwt-authentication-bundle      v2.14.1           This bundle provides JWT authentication for your Symfony REST API
monolog/monolog                      2.3.5             Sends your logs to files, sockets, inboxes, databases and various web services
myclabs/deep-copy                    1.10.2            Create deep copies (clones) of your objects
namshi/jose                          7.2.3             JSON Object Signing and Encryption library for PHP.
nikic/php-parser                     v4.13.0           A PHP parser written in PHP
phar-io/manifest                     2.0.3             Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                      3.1.0             Library for handling version information and constraints
phpdocumentor/reflection-common      2.2.0             Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock    5.3.0             With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in...
phpdocumentor/type-resolver          1.5.1             A PSR-5 based resolver of Class names, Types and Structural Element Names
phpspec/prophecy                     1.14.0            Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage            9.2.8             Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator            3.0.5             FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-invoker                  3.1.1             Invoke callables with a timeout
phpunit/php-text-template            2.0.4             Simple template engine.
phpunit/php-timer                    5.0.3             Utility class for timing
phpunit/phpunit                      9.5.10            The PHP Unit Testing framework.
psr/cache                            2.0.0             Common interface for caching libraries
psr/container                        1.1.1             Common Container Interface (PHP FIG PSR-11)
psr/event-dispatcher                 1.0.0             Standard interfaces for event handling.
psr/link                             1.1.1             Common interfaces for HTTP links
psr/log                              2.0.0             Common interface for logging libraries
ramsey/collection                    1.2.2             A PHP library for representing and manipulating collections.
ramsey/uuid                          4.2.3             A PHP library for generating and working with universally unique identifiers (UUIDs).
sebastian/cli-parser                 1.0.1             Library for parsing CLI options
sebastian/code-unit                  1.0.8             Collection of value objects that represent the PHP code units
sebastian/code-unit-reverse-lookup   2.0.3             Looks up which function or method a line of code belongs to
sebastian/comparator                 4.0.6             Provides the functionality to compare PHP values for equality
sebastian/complexity                 2.0.2             Library for calculating the complexity of PHP code units
sebastian/diff                       4.0.4             Diff implementation
sebastian/environment                5.1.3             Provides functionality to handle HHVM/PHP environments
sebastian/exporter                   4.0.3             Provides the functionality to export PHP variables for visualization
sebastian/global-state               5.0.3             Snapshotting of global state
sebastian/lines-of-code              1.0.3             Library for counting the lines of code in PHP source code
sebastian/object-enumerator          4.0.4             Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector           2.0.4             Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context          4.0.4             Provides functionality to recursively process PHP variables
sebastian/resource-operations        3.0.3             Provides a list of PHP built-in functions that operate on resources
sebastian/type                       2.3.4             Collection of value objects that represent the types of the PHP type system
sebastian/version                    3.0.2             Library that helps with managing the version number of Git-hosted PHP projects
sensio/framework-extra-bundle        v6.2.1            This bundle provides a way to configure your controllers with annotations
symfony/asset                        5.4.x-dev 1a482ad Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                  5.4.x-dev d250db3 Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                        v5.3.10           Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts              v2.4.0            Generic abstractions related to caching
symfony/config                       5.4.x-dev f8148c2 Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                      5.4.x-dev 4fe16b2 Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                 5.4.x-dev 44b933f Converts CSS selectors to XPath expressions
symfony/debug-bundle                 5.4.x-dev 71c299d Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/dependency-injection         v5.3.10           Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts        v2.4.0            A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge              v5.3.8            Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                  v5.3.7            Eases DOM navigation for HTML and XML documents
symfony/dotenv                       5.4.x-dev 0c5d051 Registers environment variables from a .env file
symfony/error-handler                v5.3.7            Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher             v5.3.7            Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts   v2.4.0            Generic abstractions related to dispatching event
symfony/expression-language          5.4.x-dev 8e47a1a Provides an engine that can compile and evaluate expressions
symfony/filesystem                   v5.3.4            Provides basic utilities for the filesystem
symfony/finder                       v5.3.7            Finds files and directories via an intuitive fluent interface
symfony/flex                         v1.17.2           Composer plugin for Symfony
symfony/form                         5.4.x-dev f39a253 Allows to easily create, process and reuse HTML forms
symfony/framework-bundle             5.4.x-dev b5e1939 Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                  5.4.x-dev 714059c Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts        v2.4.0            Generic abstractions related to HTTP clients
symfony/http-foundation              v5.3.10           Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                  5.4.x-dev a9f8989 Provides a structured process for converting a Request into a Response
symfony/intl                         5.4.x-dev 68e5c6f Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                       5.4.x-dev fd3581f Helps sending emails
symfony/maker-bundle                 v1.34.1           Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate c...
symfony/mime                         5.4.x-dev 17f3a3d Allows manipulating MIME messages
symfony/monolog-bridge               v5.3.7            Provides integration for Monolog with various Symfony components
symfony/monolog-bundle               v3.7.0            Symfony MonologBundle
symfony/notifier                     5.4.x-dev aa8ef2e Sends notifications via one or more channels (email, SMS, ...)
symfony/options-resolver             v5.3.7            Provides an improved replacement for the array_replace PHP function
symfony/password-hasher              v5.3.8            Provides password hashing utilities
symfony/phpunit-bridge               v5.3.10           Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme       v1.23.1           Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu            v1.23.0           Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn            v1.23.0           Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer     v1.23.0           Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring            v1.23.1           Symfony polyfill for the Mbstring extension
symfony/polyfill-php56               v1.20.0           Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php73               v1.23.0           Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80               v1.23.1           Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81               v1.23.0           Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/polyfill-uuid                v1.23.0           Symfony polyfill for uuid functions
symfony/process                      5.4.x-dev b076aa9 Executes commands in sub-processes
symfony/property-access              5.4.x-dev bd3efa2 Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info                5.4.x-dev bc3255e Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge         5.4.x-dev 497e278 Provides integration for ProxyManager with various Symfony components
symfony/routing                      v5.3.7            Maps an HTTP request to a set of configuration variables
symfony/runtime                      5.4.x-dev 2590032 Enables decoupling PHP applications from global state
symfony/security-bundle              5.4.x-dev 67a5aff Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core                5.4.x-dev dd2f0d0 Symfony Security Component - Core Library
symfony/security-csrf                v5.3.4            Symfony Security Component - CSRF Library
symfony/security-guard               v5.3.7            Symfony Security Component - Guard
symfony/security-http                5.4.x-dev 7b37c75 Symfony Security Component - HTTP Integration
symfony/serializer                   5.4.x-dev e1f4f55 Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts            v2.4.0            Generic abstractions related to writing services
symfony/stopwatch                    5.4.x-dev 68e61ec Provides a way to profile code
symfony/string                       5.4.x-dev dad92b1 Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                  5.4.x-dev 1bbbed9 Provides tools to internationalize your application
symfony/translation-contracts        v2.4.0            Generic abstractions related to translation
symfony/twig-bridge                  v5.3.7            Provides integration for Twig with various Symfony components
symfony/twig-bundle                  5.4.x-dev 717ad99 Provides a tight integration of Twig into the Symfony full-stack framework
symfony/uid                          5.4.x-dev 44788f8 Provides an object-oriented API to generate and represent UIDs
symfony/validator                    5.4.x-dev 3293c70 Provides tools to validate values
symfony/var-dumper                   v5.3.10           Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                 v5.3.8            Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                     5.4.x-dev de535b4 Manages links between resources
symfony/web-profiler-bundle          5.4.x-dev 9eeefab Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                         5.4.x-dev c55bc64 Loads and dumps YAML files
theseer/tokenizer                    1.2.1             A small library for converting tokenized PHP source code into XML and potentially other formats
twig/extra-bundle                    v3.3.3            A Symfony bundle for extra Twig extensions
twig/twig                            v3.3.3            Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                     1.10.0            Assertions to validate method input/output with nice error messages.

**Comment by sargitcom** [comment]
File that failes is vendor/symfony/security-http/Authenticator/Debug/TraceableAuthenticator.php
For unknown to me reason, there's no GuardBridgeAuthenticator:

$class = \get_class($this->authenticator instanceof GuardBridgeAuthenticator ? $this->authenticator->getGuardAuthenticator() : $this->authenticator);

**Comment by chalasr** [comment]
That's because you are installing a mix of 5.3, 5.4 and 6.0 components and bundles. Try updating them all to the same version at once (`composer update symfony/*`), that should work.

**Comment by sargitcom** [comment]
Thx for the help. I did downgrade everything to symfony 5.3.x and works like a charm :)

**Comment by chalasr** [comment]
Cool :)
