### ISSUE TITLE
PHP 7 Compatibility

### ISSUE THREAD

**Issue by dangaffey** [lexik/LexikJWTAuthenticationBundle#947]
It seems like the latest version dependencies ultimately resolve a sub-dependency in the lcobucci library to a version that requires PHP 8.

What I am seeing when checking out v2.14.1, is that the sub-dependency lcobucci/clock resolves to 2.1.0 which requires PHP 8.0.  

"name": "lcobucci/clock",
            "version": "2.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/lcobucci/clock.git",
                "reference": "903513d28e85376a33385ebc601afd2ee69e5653"
            },

I am using Composer version 2.1.9 2021-10-05 09:47:38

**Comment by chalasr** [comment]
Sorry but I can't reproduce. Our CI runs fine on PHP 7, and I managed to install the bundle locally on php 7.4 with the same composer version and no issue (composer rightly picked `lcobucci/clock:2.0.0`).

**Comment by dangaffey** [comment]
User error
