### ISSUE TITLE
Adding additional conditions before generating JWT token

### ISSUE THREAD

**Issue by geoffroyp** [lexik/LexikJWTAuthenticationBundle#949]
Greetings,

I have read the doc but there is an information I haven't found yet: How can I add additional logic to the token creation?

At the moment, it only checks for the username/password pair to validate the authentication and create a token. But what if, for instance, I want to check is the user has not been deactivated in DB, or if it has the right to connect at this particular time of the day, or any other condition?

**Comment by fd6130** [comment]
Perhaps you mean this? https://symfony.com/doc/current/security/user_checkers.html

**Comment by geoffroyp** [comment]
Yes indeed, that did the trick. Thanks a lot!

However, since it LexikJWTAuthenticationBundle is acting (or seems to be acting) like a checker as well, it might be a good idea to add the link to the doc, just to make sure people know they have to use the default symfony one rrather than looking for something like that in this bundle.
