### ISSUE TITLE
Why is SelfValidatingPassport imposed in JWTAuthenticator?

### ISSUE THREAD

**Issue by TristanPouliquen** [lexik/LexikJWTAuthenticationBundle#950]
Hello,

Still trying to extend the new `JWTAuthenticator` in my system.

In my JWT, I have additional data referencing a `Session` object we have and I need to check whether this session is still active when trying to login (this allows forced logout in case of security breaches). 

I migrated this logic into the new Authenticator system by providing a `CustomCredentials` to a simple `Passport` in my `::authenticate()` method.

But I'm then faced with the fact that `JWTAuthenticator::createAuthenticatedToken` checks that the passport receives is a `SelfValidatingPassport` and not simply a `Passport` or `PassportInterface`.

This forces me to override the method, and add the `EventDispatcher` as a property of my authenticator to be able to dispatch manually the `JWTAuthenticatedEvent`.

This seems really restrictive, as it prevents us from using custom credentials with the default `JWTAuthenticator::createAuthenticatedToken` method.

Is there a specific reason to be so restrictive that I'm not aware of?

`AbstractAuthenticator::createAuthenticatedToken` already checks that the `$passport` is a `UserPassportInterface`.

**Comment by chalasr** [comment]
👍 It's a mistake, the check should be about `Passport` instead of `SelfValidatingPassport` (`*PassportInterface` are deprecated in Symfony 5.4). Would you mind sending a PR?

**Comment by TristanPouliquen** [comment]
Here it is! https://github.com/lexik/LexikJWTAuthenticationBundle/pull/951/files
