### ISSUE TITLE
Composer `branch-alias` prevents installing 2.x branch

### ISSUE THREAD

**Issue by mbabker** [lexik/LexikJWTAuthenticationBundle#952]
With the `branch-alias` config aliasing the 2.x version to the master branch, when trying to install `^2@dev`, we end up installing the master branch.  The master branch is in a massively different state than the 2.x branch.  Can this be addressed?

**Comment by chalasr** [comment]
Thanks. The branch-alias has been removed removed in https://github.com/lexik/LexikJWTAuthenticationBundle/commit/52c9cc77f600fa0c3da99649e49e5d2a8808254d and cleaned up on packagist. Can you confirm it's ok?

**Comment by mbabker** [comment]
Yep, just did a `composer update` and got `Downgrading lexik/jwt-authentication-bundle (dev-master ae90ae2 => 2.x-dev 52c9cc7)`, so we're good here.  Thanks!
