### ISSUE TITLE
AuthenticationFailureEvent not providing token since Symfony 5.3

### ISSUE THREAD

**Issue by Tchekda** [lexik/LexikJWTAuthenticationBundle#957]
I just upgraded to Symfony 5.3 and my handler for `lexik_jwt_authentication.on_authentication_failure` stopped working.

After some digging, turns out `AuthenticationFailureEvent` contains a `BadCredentialsException` without the field `token` which used to have the submitted credentials.

**Comment by chalasr** [comment]
Hey @Tchekda, can you show me what your failure handler looks like so I can better understand the issue?
Thanks

**Comment by Tchekda** [comment]
Hi @chalasr, thx for answering, here is my code : 
```php

<?php

namespace App\EventSubscriber;

use Exception;
use Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationFailureEvent;
use Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationFailureResponse;
use Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;

class JWTAuthenticationFailureResponseSubscriber implements EventSubscriberInterface {

    public function __construct(private TokenStorageInterface $tokenStorage, private JWTTokenManagerInterface $JWTManager, private RequestStack $requestStack) {
    }

    public function onLexikJwtAuthenticationOnAuthenticationFailure(AuthenticationFailureEvent $event): void {
        /** @var JWTAuthenticationFailureResponse $response */
        $response = $event->getResponse();
        // My own processing where I used to have $event->getException()->getToken()
        $response->setMessage("ERROR MESSAGE");
        }
    }

    public static function getSubscribedEvents(): array {
        return [
            'lexik_jwt_authentication.on_authentication_failure' => 'onLexikJwtAuthenticationOnAuthenticationFailure',
        ];
    }
}
```

**Comment by fd6130** [comment]
I think this is somehow related with #977 ?

**Comment by fd6130** [comment]
I think "AuthenticationFailureEvent" does not contain "token" field is quite normal to me because it indicate that authentication has failed (since it failed, should have no token provided in the response).

**Comment by Tchekda** [comment]
> I think "AuthenticationFailureEvent" does not contain "token" field is quite normal to me because it indicate that authentication has failed (since it failed, should have no token provided in the response).

I do agree with you on that point, so why was it sent before ? It used to contain submitted credentials which failed the authentication process

**Comment by fd6130** [comment]
> > I think "AuthenticationFailureEvent" does not contain "token" field is quite normal to me because it indicate that authentication has failed (since it failed, should have no token provided in the response).
> 
> I do agree with you on that point, so why was it sent before ? It used to contain submitted credentials which failed the authentication process

That's strange, I do not recall that the response contains "token" field before. Or am I missing some information here?

**Comment by Tchekda** [comment]
I was using it in my process to try to identify why someone couldn't connect. I understand this isn't the best practice but at least it worked

**Comment by fd6130** [comment]
Try this in your `JWTAuthenticationFailureResponseSubscriber`:
```
    public function __construct(private RequestStack $requestStack, private TokenExtractorInterface $tokenExtractor) {}

    public function onLexikJwtAuthenticationOnAuthenticationFailure(AuthenticationFailureEvent $event): void {
        $request = $this->requestStack->getCurrentRequest();
        $token = $this->tokenExtractor->extract($request);

        /** @var JWTAuthenticationFailureResponse $response */
        $response = $event->getResponse();
        $response->setMessage("ERROR MESSAGE");
        $response->setData(['token' => $token]);;
    }
```

**Comment by Tchekda** [comment]
Thank you, I got it working with :
```php
json_decode($this->requestStack->getCurrentRequest()->getContent())
```

**Comment by amici** [comment]
> That's strange, I do not recall that the response contains "token" field before. Or am I missing some information here?

The `AuthenticationFailureEvent` did not contain the token, but it does still contain the `exception` property of the `AuthenticationException` type, injected in constructor. 
That `AuthenticationException` still contains the token, but only injected by its setter injection - which apparently doesn't happen any more (at least not in Symfony v5.4), not with the new authenticator.

Apparently, in v4, now deprecated `AuthenticationProviderManager.authenticate(TokenInterface $token)` was used, which in the end was setting the token, even on failed auth.
In v5.4, with the new `AuthenticatorManager` and its `executeAuthenticator()`, token is not set nor present anymore. It works just with the current $request.
