### ISSUE TITLE
Deprecated GuardBridgeAuthenticator

### ISSUE THREAD

**Issue by benblub** [lexik/LexikJWTAuthenticationBundle#960]
lexik/jwt-authentication-bundle 2.14.1

Since symfony/security-guard 5.3: The "Symfony\Component\Security\Guard\Authenticator\GuardBridgeAuthenticator" class is deprecated, use the new authenticator system instead.

When does lexik support Symfony 6.0 ?

**Comment by mbabker** [comment]
> When does lexik support Symfony 6.0 ?

It's supported as of 2.14.  You'll need to update your application configuration to use the newer authentication system, see https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.md#configuration for an example.

**Comment by benblub** [comment]
to let that here for others

remove
```
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```

add
````
jwt: ~
````
