### ISSUE TITLE
ChainTokenExtractor::getIterator() should either be compatible with IteratorAggregate::getIterator()

### ISSUE THREAD

**Issue by eerison** [lexik/LexikJWTAuthenticationBundle#965]
I'm trying to use php 8.1 but I'm getting this error

```
  During inheritance of IteratorAggregate: Uncaught Whoops\Exception\ErrorException: Return type of Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\ChainTokenExtractor::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/lexik/jwt-authentication-bundle/TokenExtractor/ChainTokenExtractor.php:91
Stack trace:
```

**Comment by Ocramius** [comment]
@chalasr I see this landed in mainline: is a release possible? :thinking: 

EDIT: this was solved in https://github.com/lexik/LexikJWTAuthenticationBundle/pull/966

**Comment by chalasr** [comment]
@Ocramius Here you go https://github.com/lexik/LexikJWTAuthenticationBundle/releases/tag/v2.14.3 
(should be a new minor because it adds some features, but no deprecation)

**Comment by Ocramius** [comment]
Oh, that was fast, thank you! :muscle: 

EDIT: aaaaand verified against my test suite, awesome! :rocket:
