### ISSUE TITLE
Symfony 6 Compatibility(security-guard)

### ISSUE THREAD

**Issue by jeka-corvus** [lexik/LexikJWTAuthenticationBundle#967]
I updated my project from Symfony 5.4 to Symfony 6.0. And now I have following error:

Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#188
    #message: """
      Attempted to load interface "AuthenticatorInterface" from namespace "Symfony\Component\Security\Guard".\n
      Did you forget a "use" statement for "Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface"?
      """
    #code: 0
    #file: "./vendor/lexik/jwt-authentication-bundle/Security/Guard/JWTTokenAuthenticator.php"
    #line: 43
    trace: {
      ./vendor/lexik/jwt-authentication-bundle/Security/Guard/JWTTokenAuthenticator.php:43 { …}
      ./vendor/symfony/error-handler/DebugClassLoader.php:287 { …}
      Symfony\Component\ErrorHandler\DebugClassLoader->loadClass() {}
      ./vendor/symfony/security-bundle/DependencyInjection/Compiler/RegisterEntryPointPass.php:53 { …}
      ./vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
      ./vendor/symfony/dependency-injection/ContainerBuilder.php:716 { …}
      ./vendor/symfony/http-kernel/Kernel.php:540 { …}
      ./vendor/symfony/http-kernel/Kernel.php:769 { …}
      ./vendor/symfony/http-kernel/Kernel.php:128 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:166 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:72 { …}
      ./vendor/symfony/console/Application.php:171 { …}
      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:54 { …}
      ./vendor/autoload_runtime.php:29 { …}
      ./bin/console:11 {
        › 
        › require_once dirname(__DIR__).'/vendor/autoload_runtime.php';
        › 
        arguments: {
          "/srv/api/vendor/autoload_runtime.php"
        }
      }
    }
  }
 [critical] Uncaught Error: Interface "Symfony\Component\Security\Guard\AuthenticatorInterface" not found

Package symfony/security-guard conflicts with Symfony 6.0.

**Comment by chalasr** [comment]
On Symfony 5.4+, you need to stop using the guard authenticator by migrating to the new authenticator. See https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/UPGRADE-2.12.md

**Comment by jeka-corvus** [comment]
Thank you!!!
