### ISSUE TITLE
Unauthorized when I use an entity provider

### ISSUE THREAD

**Issue by letal1609** [lexik/LexikJWTAuthenticationBundle#97]
First of all thank you for your bundle .
Now I'm stack with this problem : when I use the in_memory provider everything is working fine , but when I change the provider to use a Doctrine entity which implements UserInterface ,  I get 401 Unauthorized. 

{
"code": 401,
"message": "Bad credentials"
}

This is my security.yml

security:
    # encoders:
    #     Symfony\Component\Security\Core\User\User: plaintext
        

    encoders:
        Utb\MobileApiBundle\Entity\Abonne: 
            algorithm: md5
    # #     Symfony\Component\Security\Core\User\User: 
    # #         algorithm: md5

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    # providers:
    #     in_memory:
    #         memory:
    #             users:
    #                 jeremie: { password: ace3i, roles: [ 'ROLE_USER' ] }
    #                 admin: { password: password, roles: [ 'ROLE_ADMIN' ] }

    providers:
        user_provider:
            entity:
                class: UtbMobileApiBundle:Abonne
                property: username

    firewalls:
        dev:
            pattern:  ^/api-mobile/(_(profiler|wdt|doc))/
            security: false
            provider: user_provider

        login:
            pattern:  ^/api-mobile/login
            stateless: true
            anonymous: true
            provider: user_provider
            form_login:
                check_path: /api-mobile/login_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api-mobile
            stateless: true
            provider: user_provider
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

    access_control:
        - { path: ^/api-mobile/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api-mobile, roles: IS_AUTHENTICATED_FULLY }

**Comment by letal1609** [comment]
i don't know if i a missing anything

**Comment by dairdr** [comment]
I have the same issue

**Comment by letal1609** [comment]
dairdr, i resolved that issue by adding some parameters to my encoders

security:
    encoders:
        MobileApiBundle\Entity\Abonne: 
            algorithm: md5
            encode-as-base64: false
            iterations: 1

**Comment by letal1609** [comment]
Now i have another problem, i can login correctly but all i get 401 error when i try to access my secured api routes. What can be the cause of that ?

**Comment by dairdr** [comment]
letal1609, now it works, this is my config.yml:

# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
            
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN]

    providers:
        mysql_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~
            
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

Everything it's working fine, i can get 401 and 200 HTTP status codes.

**Comment by slashfan** [comment]
Thanks for sharing @dairdr. @letal1609 does it help ?

**Comment by patie** [comment]
i have the same problem, when using plaintext encoder or memory provider there is no problem, when i switch to bcrypt 401 Bad credentials
