### ISSUE TITLE
Attempted to call an undefined method named "loadUserByUsernameAndPayload" of class "Symfony\Component\Security\Core\User\ChainUserProvider"

### ISSUE THREAD

**Issue by v-matsuk** [lexik/LexikJWTAuthenticationBundle#971]
JWTAuthenticator throws an error when ChainUserProvider is used. When you iterate through `$this->userProvider->getProviders()` you call `loadUserByUsernameAndPayload` on `$this->userProvider` rather then on specific `$provider` in chain.

**Comment by mmarchois** [comment]
I also have the same problem and #972 solves the problem :+1:

**Comment by silverbackdan** [comment]
Not sure about the solution. It has not solved it for me.

Firstly, I get `method_exists(PayloadAwareUserProviderInterface::class, 'loadUserByIdentifierAndPayload')` as `false`

`$this->userProvider` is the `ChainUserProvider` as is being iterated over, so will not have the method `loadUserByIdentifierAndPayload` or `loadUserByUsernameAndPayload` - the chain is being looped over, I don't know why we would then use the chain `$this->userProvider` and not the provider within `$provider`

The solution that works for me is changing to

```
if ($provider instanceof PayloadAwareUserProviderInterface) {
                        if (method_exists($provider, 'loadUserByIdentifierAndPayload')) {
                            return $provider->loadUserByIdentifierAndPayload($identity, $payload);
                        } else {
                            return $provider->loadUserByUsernameAndPayload($identity, $payload);
                        }
                    }
```
