### ISSUE TITLE
Misspell: "JWT Token"

### ISSUE THREAD

**Issue by Gregoire-M** [lexik/LexikJWTAuthenticationBundle#983]
JWT is an acronym for "JSON Web Token". So it doesn't make sense to say "JWT Token".

It should be replaced by just "JWT", or "JSON Web Token" in messages such as "[Invalid JWT Token](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Exception/InvalidTokenException.php#L21)".

I can propose a PR if you agree.

**Comment by BigWil** [comment]
Right?!  Makes as much sense as PHP Hypertext Processor

**Comment by chalasr** [comment]
Short answer: this is due to backward compatibility that needs to be preserved. I hope we'll avoid the extra `Token` at some point. Closing as not planed yet.
