### ISSUE TITLE
This method is implemented for BC purpose and should never be called.

### ISSUE THREAD

**Issue by bluemoonljb** [lexik/LexikJWTAuthenticationBundle#987]
Lexik version 2.14.4
Symfony 5.4.2

I follow the example at following URL to create a custom authenticator.
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/6-extending-jwt-authenticator.md

But now I get the error message "This method is implemented for BC purpose and should never be called." when createAuthenticationListners, it seems the "create" method in JWTAuthenticatorFactoryTrait.php shold not be called, but I am not sure why it is still called. 

Anyone has idea how to fix this issue? 
Thanks.

**Comment by bluemoonljb** [comment]
I see we have to put. "enable_authenticator_manager: true" in security.yaml, this is not show in the example.

**Comment by cs-alok-agarwal** [comment]
@bluemoonljb Does the above solve your issue.
After making the necessary changes I am getting.

Cannot configure AuthenticatorManager as "basic" authentication does not support it, set "security.enable_authenticator_manager"  to `false`.

**Comment by fd6130** [comment]
> @bluemoonljb Does the above solve your issue. After making the necessary changes I am getting.
> 
> Cannot configure AuthenticatorManager as "basic" authentication does not support it, set "security.enable_authenticator_manager" to `false`.

Can you post your `security.yaml` here?

**Comment by cs-alok-agarwal** [comment]
@fd6130 
```
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Actors
                property: userId
        jwt:
            lexik_jwt: ~
    firewalls:
        api:
            pattern: ^/api/
            jwt:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            stateless: true
            provider: app_user_provider

        main:
            anonymous: lazy
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }```

**Comment by fd6130** [comment]
> ```
>     firewalls:
>         api:
>             pattern: ^/api/
>             jwt:
>                 authenticators:
>                     - lexik_jwt_authentication.jwt_token_authenticator
>             stateless: true
>             provider: app_user_provider
> 
>         main:
>             anonymous: lazy
> ```
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/index.rst#configuration

You are using new authenticator instead of guard because `enable_authenticator_manager: true` , just replace your `jwt` key in `api:` to `jwt: ~`

**Comment by cs-alok-agarwal** [comment]
@fd6130  Thanks that worked.

```
firewalls:
        pattern:
            pattern: ^/api/pattern/
            basic: ~
            jwt: ~
            stateless: true
            provider: app_user_provider
        api:
            pattern: ^/api/
            cs_hmac: ~
            jwt: ~
            stateless: true
            provider: app_user_provider
```

Although am getting issues when adding multiple patterns.
Not sure is something wrong with my implementation or its an issue, this used to work with 2.13.0


Just an update. When adding additional self-authentication apart from JWT its creates an issue, like in above case cs hamc

Thanks for the pointers.

**Comment by fd6130** [comment]
@cs-alok-agarwal Do you mean route not found or authentication is not working in multiple patterns?

>  When adding additional self-authentication apart from JWT its creates an issue, like in above case cs hamc

Can you further explain more about this?
